### ISSUE TITLE
Remove button margin

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#100]
Bug report
Probably need to remove default margin buttons

Example
https://monosnap.com/file/3h0mtn4zBwHumtkEtT7XDPO6cKtzhw

Example broken case in va-collapse
![button_2](https://user-images.githubusercontent.com/13301570/67476459-bf66f600-f660-11e9-937a-78143582e2ba.gif)

**Comment by jean-moldovan** [comment]
Completely agree, no default margin, should be handled in the user land.

**Comment by asvae** [comment]
Done in develop
