### ISSUE TITLE
Translations for examples

### ISSUE THREAD

**Issue by mxmvshnvsk** [epicmaxco/vuestic-ui#1000]
I have [prepared logic](https://github.com/epicmaxco/vuestic-ui/pull/999) for using reactive translations in code examples. We need to make translations for these examples =)

For example code template with translation:

```javascript
const iconsInstall = `
yarn add material-design-icons-iconfont -D
// $t('all.code.or')
npm install material-design-icons-iconfont -D
`
```

In sfc templates typical using:

```html
<template>
  <va-button>
    {{ $t('all.examplesTexts.button') }}
  </va-button>
</template>
```

**Comment by asvae** [comment]
@alygee can we close this one?

**Comment by aluarius** [comment]
@asvae everything checked - there're no untranslated examples, can close.
