### ISSUE TITLE
Validation system

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#102]
This issue is intended for discussion and laying out validation.

## Parts
* input components support (#104)
![image](https://user-images.githubusercontent.com/5394573/67609451-795f7e80-f795-11e9-8e03-2542fa4c4de4.png)
* form component (#103)
* library support (#112).

**Comment by asvae** [comment]
@xx13 I have an issue with current validation state we employ for components.

Normally, there are only 2 states: default and error.
We use 3 states instead: default, success and error.

So why this is a problem? Because of the way validation rules have only 2 states: valid and invalid.

Here's the way I can see this being handled properly:
* We make success optional (and not default). So normal states for input will be default and error, and user would have to set success state manually.
* Another option would be to get rid of it, which is probably not optimal as I can definitely see some value (not too much though, so if you have cases to throw at me - please do).

## Some other things for us to think of
* Which components should that success state affect? If we keep it, it probably should be implemented in all form components (checkboxes, radio buttons, sliders).

**Comment by jean-moldovan** [comment]
`success` is definitely should be controlled by the user `<va-input :success="true" ...`
success / error can be available as part of `va-field` component which would be built into 
 input/select by default, and can be applied to other form controls optionally (checkbox, sliders, etc).

**Comment by xx13** [comment]
@asvae validation can be useful when creating new accounts and checking for available usernames, checking the complexity of user's password, setting custom links, etc. and I totally agree that success validation should be optional.

**Comment by asvae** [comment]
Moved to #159
