### ISSUE TITLE
Incorrect UUID dependency in ESM bundle

### ISSUE THREAD

**Issue by nVitius** [epicmaxco/vuestic-ui#1021]
I'm building a project using vuestic-ui with webpack5 (vue-cli@5).
Got this error when trying to build my project:
![image](https://user-images.githubusercontent.com/3804041/129286532-b1656cc7-0e03-4980-818d-e25efed617a0.png)

The uuidjs/uuid project has an esm bundle that is built for browsers and does not use the `crypto` node module.

However, there's no reference to a dependency on uuid in the ui project's package.json. From what I can tell, we're using rollup's node-resolve and bundling them with the npm package instead. Is there a reason to do it this way? Shouldn't uuid be a dependency of the ui instead?

I can confirm that making this change locally seems to work.

**Comment by nVitius** [comment]
We're also bundling lodash, style-inject, and vue-class-component with the esm builds.

**Comment by asvae** [comment]
@m0ksem would you like to handle this on your own, or we can ask @VasylHryha ?

**Comment by m0ksem** [comment]
> @m0ksem would you like to handle this on your own, or we can ask @VasylHryha 

@VasylHryha, please replace uuid module with own implementation and remove node-buildins plugin from rollup config.

**Comment by VasylHryha** [comment]
> 
> 
> > @m0ksem would you like to handle this on your own, or we can ask @VasylHryha
> 
> @VasylHryha, please replace uuid module with own implementation and remove node-buildins plugin from rollup config.

Got it
