### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#103]
## Docs
- [x] Do after docs boilerplate (#17) is done.

## Props
- [x] `autofocus: Boolean` - focus on first element on render

## Slots
- [x] `default` - form components. For now we support only one level deep.

## Events
- [ ] `focus: () => void` - triggered when some form element is triggered. Might be useful for multi-tab forms. 
*- can use `focusin` native event*
- [x] `validation: (valid: Boolean) => void` - triggered on validation update

## Notes
* See validetable trait #104. It's a prerequisite for form.
- [ ] It should be possible to use one form inside of another form. The way it should work is that external form should trigger relevant method on internal form. (medium priority: if it's too hard - leave)

## Methods
- [x] `validate(): boolean` - performs validation and updates error state for each form component.
- [x] `focus(): void` - focus on first **focusable** element in the form.
- [x] `focusInvalid(): void` - focus on first invalid **focusable** component in the form. If there are none - should default to `focus()`.
- [x] `resetValidation(): void` - reset validation for all **validateable** form elements
- [x] `reset(): void` - reset value + validation stater for all form elements.

# Refs
* [Vuetify](https://vuetifyjs.com)
* [Quasar](https://quasar.dev)
* [Ant Design](https://ant.design)
* [iView](http://iview.talkingdata.com)
* [Element UI](https://element.eleme.io)

**Comment by Kreezag** [comment]
The `validation` event does not currently work with form elements. There may be errors in console for va-input.
It fixed in #104
