### ISSUE TITLE
TS type errors

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1046]
* **What is the expected behavior?**
Demo and docs should run correctly without errors.
* **What is the current behavior?**
Right now we have a few TypeScript errors after running `yarn serve:book` or `yarn serve:docs`
* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
1. Run  `yarn serve:book` or `yarn serve:docs` using dev branch of our project.
![TSErrors](https://user-images.githubusercontent.com/7745899/130469576-9f66f34d-934f-48d4-a844-1e344af166d1.png)

**Comment by alygee** [comment]
this issue relate to https://github.com/epicmaxco/vuestic-ui/pull/1045 and just fixed. Please check if there are any errors.

**Comment by Derranion** [comment]
@alygee Yeah, looks like we created the issue at the same minute :)

**Comment by Derranion** [comment]
Just checked #1045

 I've left some comments there are some types flaws.

Will fix it soon.
