### ISSUE TITLE
VaSelect : Error when dropdown

### ISSUE THREAD

**Issue by muzaman** [epicmaxco/vuestic-ui#1048]
**When dropdown VaSelect,  I get this error:**

Uncaught (in promise) TypeError: Cannot read property 'length' of null

<va-select
          :options="options"
          text-by="name"
          value-by="id"
          track-by="id"
          searchable
          v-model="currentOption"
          @update:modelValue="valueChanged"
        >

**options  are:**
this.options = [
      { id: "1", name: "First" },
      { id: "2", name: "Second" },
      { id: "3", name: "Third" },
      { id: "4", name: "Fourth" },
    ];
**methods:**
 valueChanged() {
      console.log("New Value=", this.currentOption);
    },

**Vue 3, Vuestic 1.0**
![ConsoleLog](https://user-images.githubusercontent.com/44603362/130570108-56f37d8e-8ceb-456f-ba69-ded79fee116c.jpg)

**Comment by alygee** [comment]
Hello @muzaman. Thanks for the issue.
Is the variable `currentOption` declared during the initialization of your component?

**Comment by muzaman** [comment]
> Hello @muzaman. Thanks for the issue.
> Is the variable `currentOption` declared during the initialization of your component?

Yes, of course,
```

export default {
  data() {
    return {
      options: [],
      currentOption: null,
      value:null,
    };
  },
```
or specify in `mounted`?

**Comment by muzaman** [comment]
> Hello @muzaman. Thanks for the issue.
> Is the variable `currentOption` declared during the initialization of your component?

Thanks, I solve this :
`data() {
    return {
     ...
     currentOption: {}, // <---- this
     ..
    };
  },` 

and

`mounted() {
....
      this.currentOption = {}; // <---------
  },`
**Thanks-спасибо!**
