### ISSUE TITLE
Select autocomplete example

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1051]
Select needs an example with autocomplete.

The case is where select has too much data (thousands), but we need to make it operable nonetheless.

Pretty sure we can handle it via `update-search`, but if you have better way to handle it - also good.

Implementing autocomplete right now is not a priority, we're mostly looking for non-too-pleasant solution with existing component, that solves the particular case.

**Comment by aluarius** [comment]
Duplicates https://github.com/epicmaxco/vuestic-ui/issues/2228
