### ISSUE TITLE
Docs compile warnings

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1056]
Can we get rid of scss deprecations warnings on docs compilation?

![image](https://user-images.githubusercontent.com/5394573/131136522-53c375aa-8617-41cc-8b1e-badeabb90c37.png)

**Comment by alygee** [comment]
I corrected vuestic's warnings about the deprecated functionality in this PR https://github.com/epicmaxco/vuestic-ui/pull/1077
But there are still warnings from the `font-awesome@4.7.0`.
