### ISSUE TITLE
if text-by points to number - searchable select breaks

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1057]
![image](https://user-images.githubusercontent.com/5394573/131351447-6ef28c10-1057-4371-892c-f217d3603361.png)

**Comment by Derranion** [comment]
@asvae 
We only support `String ` or `Function `as a `text-by`,` track-by` or `value-by` property value, we have this in docs description as well.
But I could implement Numbers if this will improve user experience.

**Comment by Derranion** [comment]
Looks like search didn't work for numbers at all.
