### ISSUE TITLE
Collapse when mounted with v-model true is still closed

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1063]
Go to `VaCollapse.demo.vue` and set

```
collapseValue: true,
```

Collapses are closed even though icon points upward. They should be open.
![image](https://user-images.githubusercontent.com/5394573/131576595-d87e5d59-b7bc-4317-ad2a-561892959820.png)

**Comment by m0ksem** [comment]
Also, found an issue with heigh calculation here.
![EOQOSLGYWv](https://user-images.githubusercontent.com/23530004/132847362-8a2226c7-bbff-4042-90d1-1dbdbf7eec5d.gif)
