### ISSUE TITLE
Investigate textBy, valueBy, trackBy usage

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1074]
Investigate **textBy**, **valueBy**, **trackBy** props inside " **useSelectableList** " to make sure that they are used correctly  - there could be more bugs like this one:

-  [if text-by points to number - searchable select breaks](https://github.com/epicmaxco/vuestic-ui/issues/1057)

Some dependencies and names are pretty questionable as well.

Update documentation if something will be changed.

**Comment by asvae** [comment]
Would add that we also want to restore tests, as these are fully covered, if I remember correctly.
