### ISSUE TITLE
Missed styles block in code examples

### ISSUE THREAD

**Issue by alygee** [epicmaxco/vuestic-ui#1079]
is expected that example of code will render the entire vue-component.

At now code example are missing a block with styles. This can make the example incomplete and create ambiguity.

![Screenshot from 2021-09-08 16-02-45](https://user-images.githubusercontent.com/60774386/132516157-287c8a25-5247-446b-8b67-17b2ca006026.png)

**Comment by asvae** [comment]
@alygee do you have a case where you need style block?

**Comment by alygee** [comment]
I only have one case, to show import styles in the example with ag-grid table.
If it still too minor feature, then issue can be closed.
