### ISSUE TITLE
No visual style for focused (not active, but focused) button in VaButtonGroup

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1086]
I mean the focused button using tab. Need to press them or show borders

![image](https://user-images.githubusercontent.com/23530004/132844106-d4cb4d41-02e9-4130-b1d7-d6b8828b193b.png)

Default focused style:
![image](https://user-images.githubusercontent.com/23530004/132844279-eb49d60a-1988-4446-9f4a-077ac2e20dd3.png)
Unfocused:
![image](https://user-images.githubusercontent.com/23530004/132844291-adbb35ce-5c7e-4ca8-86e9-ce011c800c09.png)

**Comment by kushich** [comment]
The shadow-type focus looks weird for a button group component.

<img width="423" alt="Screenshot 2021-09-15 at 11 12 51" src="https://user-images.githubusercontent.com/45711229/133402907-609ba5cd-72e0-40fc-b174-df5a8f789db5.png">
<img width="485" alt="Screenshot 2021-09-15 at 11 12 56" src="https://user-images.githubusercontent.com/45711229/133402912-e70bf0b9-de61-45f2-8cfb-60e1c91a85dc.png">
<img width="473" alt="Screenshot 2021-09-15 at 11 13 00" src="https://user-images.githubusercontent.com/45711229/133402913-77058837-de09-485d-bd24-3af0eb9555a4.png">

**Comment by asvae** [comment]
@xx13 ?

**Comment by xx13** [comment]
@asvae @kushich I think we decided to go with hover or pressed style on focus instead or adding a shadow. I'll review focus status for other elements too.

**Comment by asvae** [comment]
@xx13 can you check and close this issue if things are looking good for you?

Here's demos - http://vuestic-ui-demo.sub.asva.by/#/demo/va-button-group/VaButtonGroup.demo.vue
and here's docs - https://vuestic.dev/en/ui-elements/button-group

**Comment by xx13** [comment]
@asvae I'm not really sure how can I check focused style :D btw we don't have hover styles (and I assume for focused styles) for gradient button groups.

**Comment by m0ksem** [comment]
Looks like fixed. It becomes brighter on focus!
