### ISSUE TITLE
Button icons double in size during prod build

### ISSUE THREAD

**Issue by tlhunter** [epicmaxco/vuestic-ui#1087]
* **What is the expected behavior?**

The build/prod behavior would perfectly match the dev behavior.

* **What is the current behavior?**

In dev,  buttons with an icon have a font size of 24px. After running a build the buttons have an icon font size of 48px. Specifically the inline font-size of the `button.va-button > div.va-button__content > i.va-icon` element has this font size issue.

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**

I'm running `npm run serve` for the dev version and `npm run build && npx serve dist` to access the prod version. I'm using a random port with the prod version to make sure nothing is getting cached. In either dev and prod there are no console/network failures.

Prod:
![2021-09-10_11-26-32](https://user-images.githubusercontent.com/551402/132916710-a67e85b0-2a92-4907-82c5-847ac868fb86.png)
Local:
![2021-09-10_11-26-39](https://user-images.githubusercontent.com/551402/132916712-0dfaf593-79e8-4b10-8cbe-479395833e38.png)

* **Other information**

This is with the most recent 1.2.7 version of Vuestic.

Additionally, I'm seeing that modifications to the Vuestic configuration made in the entrypoint of the application are not honored either. The following config results in square buttons in dev and the default rounded buttons for prod:

```javascript
import { createApp } from 'vue';
import App from './app.vue';
import './registerServiceWorker.js';
import router from './router.js';
import { VuesticPlugin } from 'vuestic-ui';
import 'vuestic-ui/dist/vuestic-ui.css';

createApp(App)
  .use(router)
  .use(VuesticPlugin, {
    components: {
      VaButton: {
        rounded: false,
        size: 'medium',
      }
    }
  })
  .mount('main#app');
```

**Comment by tlhunter** [comment]
And here's the styles with that config applied:

Dev:
![2021-09-10_14-09-35](https://user-images.githubusercontent.com/551402/132918094-cb684fa3-3bcb-43f1-b102-560fdc0b10ef.png)

Prod:
![2021-09-10_14-09-44](https://user-images.githubusercontent.com/551402/132918097-a28bd3f1-8c82-47c4-9973-18777658127e.png)

**Comment by Derranion** [comment]
@tlhunter Thanks a lot, we are working on it, here are multiple related already opened issues:

- [Differences in Build and Dev versions #1054](https://github.com/epicmaxco/vuestic-ui/issues/1054)
- [Components arent following global config in build. #1042](https://github.com/epicmaxco/vuestic-ui/issues/1042)

That's why I will close this one to not duplicate them.

**Comment by Derranion** [comment]
@tlhunter Sizes should be fixed now, looking into fixing the rest.

**Comment by tlhunter** [comment]
@Derranion looking forward to the next release (-:
