### ISSUE TITLE
Sync labels between projects

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1098]
in `\packages\docs\conventions.md` we have all labels defined,

we want to 
- [ ] Sync it with current state
- [ ] Do the same for vuestic-admin (we assume it uses the same set of labels)

Bonus points
- [ ] automate the ordeal - https://github.com/Financial-Times/github-label-sync
- [ ] analyze, which additional labels we need, and which ones we can remove

**Comment by m0ksem** [comment]
Not relevant. Looks like we simply do not need it. At least for now.
