### ISSUE TITLE
Documentation analysis

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#11]
The idea is to provide platform for page by page investigation. The result of the task should be a list of pages extracted from the following frameworks docs. You can also provide small description if page name is ubiquitous or provide a link to specific doc. There should be no duplicates in the list.

Example:
```
Getting started:
* Playground - link to codesandbox etc [quasar](https://quasar.dev/start/playground)
...
Components:
* Chip
* Circular progress
...
```

Frameworks to check:

* Quasar
* Vuetify
* Element UI
* iView
* Ant Design

- [x] Add links to "Frameworks to check" list
- [x] Check documentation of frameworks from the list.

**Comment by AlexanderBoriskin** [comment]
This document contains list of possible documentation pages:
https://docs.google.com/spreadsheets/d/1QafcmgEe2c0uQIsA9GJVinaBq-P6bvgimG1skxu7OeM/edit#gid=0
