### ISSUE TITLE
Optimize loops

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1102]
Currently we have a lot of **overhead** in some of our loops like this one:

```
return Object.entries(propsOptions).reduce((computed, [name, definition]) => {
  return {
    ...computed,
    [name]: getValue(name, definition.default),
  }
}, {})
```
It is exponentially slower with every element - we could **make it a lot faster**.

Check for similar patterns in the project and enhance it.

**Comment by m0ksem** [comment]
I suggest ignore optimizations right now, but prefer code readability. We have a lot of more important tasks.
