### ISSUE TITLE
Unable to unfold an accordion collapse inside a card to show its internal form

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1105]
See https://github.com/epicmaxco/vuestic-admin/issues/819

**Comment by kushich** [comment]
@asvae works fine for me. Just some code errors in the provided example. 
https://github.com/epicmaxco/vuestic-admin/issues/819#issuecomment-923699528
![1111111](https://user-images.githubusercontent.com/45711229/134127683-3c4207c5-5016-4915-b506-9e84a08c18ca.gif)
