### ISSUE TITLE
Focus style for va-collapse

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#1114]
Focus with shadow style looks weird (screenshot). Let's use colored background instead. (Like in buttons on hover and on focus)
<img width="464" alt="Screenshot 2021-09-21 at 12 59 43" src="https://user-images.githubusercontent.com/45711229/134152463-a4b2ec09-f49e-4464-9dce-d8338ce3847a.png">

**Comment by kushich** [comment]
I think we should restyle the collapse component at all (https://github.com/epicmaxco/vuestic-ui/issues/719) to make it more customizable according to the parts where it is used (navbar and etc.)
My suggestion:

<img width="441" alt="Screenshot 2021-09-21 at 16 03 01" src="https://user-images.githubusercontent.com/45711229/134176117-e79606ce-5fc1-493a-a674-298ced4b1110.png">

**Comment by aluarius** [comment]
Implemented.
