### ISSUE TITLE
No focus state in Show Code button

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1118]
![ZkJLRj81Bk](https://user-images.githubusercontent.com/23530004/134326831-43939a71-0710-4247-845b-8c3b67aec46c.gif)

**Comment by kushich** [comment]
@m0ksem the problem is that we have to fit this button to the left, but now we have weird focus styles when we try to fit it. Look
<img width="351" alt="Screenshot 2021-09-22 at 15 33 31" src="https://user-images.githubusercontent.com/45711229/134344728-680419c9-9688-4502-b2c0-f3b216f42be2.png">

**Comment by kushich** [comment]
@asvae
