### ISSUE TITLE
Add BEM guide to Contribution guide

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1123]
I found that we have different types of modificator declarations.

`.va-input_readonly` or `.va-input--readonly`

Which one should we use? I would like to have this specified in contributions docs.

For me, `.va-input--readonly` looks much easier to understand.

Also, this issue requires changing everything to one style.

**Comment by asvae** [comment]
Convention was `.element__block--modifier`.

**Comment by m0ksem** [comment]
So we need to change the wrong code style in some components in this issue.
