### ISSUE TITLE
Card goes atop of modal from 1.2.8

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1135]
https://discord.com/channels/457593300799717377/771405157527191585/890924647632232488

**Comment by Derranion** [comment]
I was not able to reproduce it in dev or build version of our project, tried in new project using vite as well.

Asked Gossip Dolphin if his project is public to check it there.

Looks like nested issue related to the [last VaModal commit](https://github.com/epicmaxco/vuestic-ui/pull/965/files).
