### ISSUE TITLE
Show CSS variables in DOCS.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1150]
Now user don't know about CSS variables from docs.

- [ ] Docs page for core level css variables.
- [ ] Variables for particular components.

**Comment by ishpartko** [comment]
@m0ksem could you clarify which variables need to be printed to the documentation and where exactly?

**Comment by m0ksem** [comment]
> @m0ksem could you clarify which variables need to show in the documentation? From which file?
> 
> And where exactly to show it? Do you mean in the page https://vuestic.dev/en/styles/css-variables?

There are a lot of CSS variables in Vuestic components. 

For example, let's look at VaInput. There are variables like: text-color, scroll-color, min-height, disabled-opacity etc. They all declared here: `packages/ui/src/components/va-input/_variables.scss`. They exist to easily change some of component parameters, simply changing one CSS variable. The problem is no one know about these CSS variables — for now, user should go to our source code and look on CSS variables list there.

So, what I propose is to show these CSS variables on component's docs pages in some dropdown or smth like that.
