### ISSUE TITLE
Dropdown docs

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1154]
Need docs about VaDropdown component with references to PopperJS

---

In nuxt we remove poperjs, so need more details for this issue from me

**Comment by wossig** [comment]
Is there missing Dropdown doc on [https://vuestic.dev/en/ui-elements](url)?  I only see `Button Dropdown`.

**Comment by otatar** [comment]
Really need docs about VaDropdown...
