### ISSUE TITLE
Document styles usage

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1160]
* Specify you can use scoped styles only in demos or examples.
* Specify css variables usage

extracted from @nastassiadanilova feedback

**Comment by asvae** [comment]
* Add the page to onboarding process

Should have strategy described on:
* Where use root variables, where component scoped.
* Where to not use css variables.

**Comment by m0ksem** [comment]
Added here: https://github.com/epicmaxco/vuestic-ui/issues/1907#issuecomment-1195712961
