### ISSUE TITLE
In contribution docs split repo state and actions sequence for developers

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1161]
* State section should describe clearly, which branches do we have, tags, commit size, what do we think about history, naming, force pushing.

* Step sequence section should in detail describe steps developer should take to contribute to vuestic. There could be some overlap with state section (but point of view should be that of developer).

extracted from feedback by @zvenigorodskaia

**Comment by m0ksem** [comment]
I think contribution docs are pretty now. Clear and simple. Importantly, they're not boring.
