### ISSUE TITLE
Wrong preview image for repo link

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1162]
Preview for link is using wrong image 

![image](https://user-images.githubusercontent.com/5394573/137710713-eb20f834-13c9-4410-a1ee-4c502979c414.png)

Should use this one instead

https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/assets/vuestic-ui-image.jpg

**Comment by aluarius** [comment]
Seems to be already fixed.

![](http://dl3.joxi.net/drive/2022/04/01/0045/3830/2965238/38/4af5892255.jpg)
