### ISSUE TITLE
Vuestic Environment

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#1169]
I suggest expanding vuestic environment.

- [x] Move additional stuff to extensions (docs section already created in this PR #1077)
- [x] Create npmjs scope ([npmjs docs](https://docs.npmjs.com/cli/v7/using-npm/scope))
- [x] Create CLI for easier vuestic extensions installation and configuration

**Comment by asvae** [comment]
@kushich 

> Create CLI for easier vuestic extensions installation and configuration

Can you elaborate on this?

**Comment by m0ksem** [comment]
Closed here https://github.com/epicmaxco/vuestic-ui/pull/2861
