### ISSUE TITLE
Rich CSS helpers

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1174]
* [ ] Add `discussion` label after research is done.

Of interest is:
* What css helper chasses we have now.
* What helper classes we could ideally have. (check other frameworks, i.e. tailwind, bulma, vuetify).

- [x] #1288
- [x] #1287
- [ ] #1425
- [x] #774
- [x] #1194
- [x] #1222
- [x] #27

Also see this technical demo on what we can do with css variables: https://jsfiddle.net/Asva/n682expa/4/

**Comment by asvae** [comment]
See https://github.com/epicmaxco/vuestic-ui/issues/1288

**Comment by m0ksem** [comment]
Closing this, to have only https://github.com/epicmaxco/vuestic-ui/issues/1425 task.
