### ISSUE TITLE
Bundlers tests should execute on any OS

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1178]
* **What is the expected behavior?**
Bundlers tests should execute on any OS.

* **What is the current behavior?**
Bundlers tests `package.json` commands work only for Linux, for example:
`"build": "rm -rf ./dist && yarn build:vite && yarn build:vue-cli"`

Looks like the best way to resolve this is by writing new node.js script that will handle it ( import `os` and `exec` ).

**Comment by m0ksem** [comment]
Looks like we can rewrite some bash scripts to zx after this PR https://github.com/epicmaxco/vuestic-ui/pull/1801

https://github.com/epicmaxco/vuestic-ui/blob/59b98067be9e3cb61c1192d78fee82f46b0db262/packages/ui/package.json#L57
