### ISSUE TITLE
Update mixins props and methods

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#118]
I suppose to update mixins props and methods up to Vue styleguide
* **What is the motivation**
https://vuejs.org/v2/style-guide/#Private-property-names-essential

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

**Comment by asvae** [comment]
I don't see a whole lot of point.
