### ISSUE TITLE
Table examples error codesandbox

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1182]
* **What is the expected behavior?**
Table examples inside the [codesandbox](https://codesandbox.io/s/5z55v?file=/src/App.vue) should work without errors.

* **What is the current behavior?**
Codesandbox examples throw an error:
![image](https://user-images.githubusercontent.com/7745899/139437277-57f27e3c-c11d-4c72-844d-9a8687462493.png)

We didn't not get examples objects from this import.

Update:
Could be easily fixed by doing something like this: [solution example](https://codesandbox.io/s/mxe8f?file=/src/App.vue).

**Comment by damirJa** [comment]
New error still exist
https://github.com/epicmaxco/vuestic-ui/issues/2152
