### ISSUE TITLE
Refused to apply style from <URL>~normalize.css

### ISSUE THREAD

**Issue by amar-ox** [epicmaxco/vuestic-ui#1184]
I got this error with normalize.css after updating to vuestic-ui 1.3.0
And va-date/time input are not rendered correctly

<img width="305" alt="vuestic-issue" src="https://user-images.githubusercontent.com/24830847/139522666-e00efc70-a75e-4958-980e-8c202c533853.PNG">

With Vue3 and @vue/cli 5.0.0-beta.4

Current package-lock.json: 
"vuestic-ui": {
      "version": "1.3.0",
      "resolved": "https://registry.npmjs.org/vuestic-ui/-/vuestic-ui-1.3.0.tgz",
      "integrity": "sha512-FMwt9vZsmxhuVBiXuOSViFWwDzUBmbzvoSSldwyvmlktq9ig/beHIAIWSVGZ5cDFLI7bNrdK7c5DSR4cPGhK7Q==",
      "requires": {
        "@popperjs/core": "^2.9.2",
        "asva-executors": "^0.1.26",
        "cleave.js": "^1.6.0",
        "colortranslator": "^1.7.1",
        "detect-browser": "^5.2.0",
        "element-resize-detector": "^1.2.1",
        "flatpickr": "4.6.9",
        "lodash-es": "^4.17.21",
        "normalize.css": "^8.0.1",
        "tslib": "^2.2.0",
        "vue-flatpickr-component": "^9.0.3"
      }
    }

**Comment by m0ksem** [comment]
Hi, @amar-ox. 

Add following code to your vite config to resolve this issue. 
```js
  resolve: {
    alias: [
      { find: '~normalize.css', replacement: 'normalize.css'}
    ]
  }
```

**Comment by amar-ox** [comment]
@m0ksem  this does not seem to work. Is this the right way to add the code?

`module.exports = {
  lintOnSave: true,
  configureWebpack: {
    resolve: {
      alias: [
        { find: '~normalize.css', replacement: 'normalize.css'}
      ]
    },  
    resolve: {
      alias: {
        'vue-i18n': 'vue-i18n/dist/vue-i18n.cjs.js',
      },
    },
  },`

**Comment by m0ksem** [comment]
```js
  configureWebpack: {
    resolve: {
      alias: {
        'vue-i18n': 'vue-i18n/dist/vue-i18n.cjs.js',
        '~normalize.css': 'normalize.css'
      },
    },
  },
```

This could do the trick for you. Sorry, I'm not able to reproduce this issue with Webpack. This PR must fix this issue https://github.com/epicmaxco/vuestic-ui/pull/1187.

**Comment by amar-ox** [comment]
Still not working!

**Comment by amar-ox** [comment]
It does not event replace the url, is this normal?
Same when I modify files inside node_modules just to check. No change!
