### ISSUE TITLE
Components customization not working after build

### ISSUE THREAD

**Issue by JohnniePeixoto** [epicmaxco/vuestic-ui#1188]
* **What is the expected behavior?**
In development phase the custom changes of components works 
`components: {
            VaToast: {
                offsetY: 65,
                customClass: 'toast-zindex'
            },
            VaSwitch: {
                trueInnerLabel: "Sim",
                falseInnerLabel: "Não",
                size: "small"
            }
        }
`
* **What is the current behavior?**
After run npm build they dont work.

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
npm run build

**Comment by m0ksem** [comment]
Hi, @JohnniePeixoto. I can not reproduce this issue :(

Building with vite and vue-cli (webpack) works fine for me in production and development:
![image](https://user-images.githubusercontent.com/23530004/139578758-27d84d94-648c-480e-9d86-6f59bb1dee32.png)


Can you provide a bit more information about your setup? For example:
- What bundler do you use? Can you show it's config?
- Do you use treeshaking (esm build) or not default cjs).

**Comment by Derranion** [comment]
@JohnniePeixoto Hey, this issue was [resolved already](https://github.com/epicmaxco/vuestic-ui/issues/1042).

Maybe be you are using outdated version of vuestic that does not have this fix?

**Comment by JohnniePeixoto** [comment]
@Derranion Yess, i've updated the package version and now its working fine. Thank you guys!
