### ISSUE TITLE
Check for styles duplicates

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1190]
We want to check two things:
1. That [this closed issue](https://github.com/epicmaxco/vuestic-ui/issues/1163) related to styles duplicates is still resolved.
( just double check because it worked before - test production version of the project: `yarn serve: production` )
2. For the most part it should be fixed already - look for other styles duplicates and create new issue if you will find one.

Also care about #869 and #950

**Comment by aluarius** [comment]
Closed due to https://github.com/epicmaxco/vuestic-ui/pull/1724
