### ISSUE TITLE
Select in modal z-index issue

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1192]
Original report:

With the release of version 1.3.0, va-select dropdown placed inside va-modal will appear behind the modal. I think this is due to the teleportation logic used.
![image](https://user-images.githubusercontent.com/5394573/139688360-1a9970a4-5e20-4d73-a079-34f44ae4c2be.png)

**Comment by m0ksem** [comment]
You can implement this issue https://github.com/epicmaxco/vuestic-ui/issues/1136 as well here.
