### ISSUE TITLE
CSS classes documentation

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#1194]
We use some styles system but we don't have instruction for all styles in docs like paddings, display, position etc.

What classes do we need?

* [Link colors](https://getbootstrap.com/docs/5.2/helpers/colored-links/) - doesn't look appropriate for vuestic
* [**Display**](https://tailwindcss.com/docs/display) - easy to do, doesn't rely on anything, so definitely useful
* [Floats](https://tailwindcss.com/docs/float) - looks too advanced for vuestic, but also easy to implement
* [**Position**](https://tailwindcss.com/docs/position) - easy to do and pretty useful
* [Top / Right / Bottom / Left](https://tailwindcss.com/docs/top-right-bottom-left) - Doesn't seem that useful
* [**Visibility**](https://getbootstrap.com/docs/5.2/utilities/visibility/) - yep!
* Z-Index - probably not, not seeing a point
* Flex - not really sure, sounds like a lot of work. Maybe we can rely on tailwind more instead (first class tailwind support or something?). I'm also thinking of a smart flex-grid solution of sorts. I also have an idea on grid implementation that could be unique and interesting.
* Table - we already have and it's documented :>
Padding
Margin
Width
Min-Width
Max-Width
Height
Min-Height
Max-Height
etc

**Comment by m0ksem** [comment]
This issue should also close https://github.com/epicmaxco/vuestic-ui/issues/1175

**Comment by asvae** [comment]
Closed as we decided to move to tailwind.
