### ISSUE TITLE
TimePicker update design

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1198]
I have a few suggestions on how to improve `TimePicker`:

- Move user selection to the center.
 (because it's commonly used like this in a lot of widgets and just feels right)

Currently we focus second element from the top after clicking on time, [example](https://vuestic.dev/en/ui-elements/time-picker):
![TimePickerFocus2nd](https://user-images.githubusercontent.com/7745899/139848230-3f598bc9-0205-4067-8eab-5b3f0bc99448.jpg)

- User selection should stay centered and fixed all the time.
(this way users will select time even just by scrolling, faster and smoother - one less click is needed)

Right now it gets centered only after selecting a number and you can not see the selection at all sometimes, for example:
![TimePickerMakeItFixedAndCentered](https://user-images.githubusercontent.com/7745899/139850321-7e571ce1-9a2f-4c12-85ab-8b43a936eebb.jpg)
:

Here is the [common example](https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/) of suggested behavior:

![TimePickerAlwaysCenteredFixed](https://user-images.githubusercontent.com/7745899/139852378-e7d76376-6999-450a-b571-291755ceedc6.png)

**Comment by Derranion** [comment]
@xx13
Please remove current tags and add `ready for implementation` when you will approve.

Thank you.

**Comment by asvae** [comment]
Here's another piece of feedback from [reddit](https://www.reddit.com/r/vuejs/comments/qlskjb/comment/hj76866/?utm_source=share&utm_medium=web2x&context=3):
> ime pickers aren't very good UX. Scrolling to find a minute/hour or multiple needless clicks for date picking. Just way too clunky/clicky to justify use vs direct typing

**Comment by untael** [comment]
IMHO the selected hour/time should be tied to the center of the container, not to the top, and the numbers should be looped to avoid empty space.

**Comment by xx13** [comment]
@asvae @untael @Derranion surely, we'll allow direct input. other options would be (1) dropdown selects and (2) scroll controls.

- alignment might be an option, like centered, top or bottom
- looped valued might be an option, as having an looped list of `am pm am pm am pm` for 10 value dropdown would be quite a meh :D

**Comment by Derranion** [comment]
I've created new tasks to summarize our goals:
- [ ] [TimePicker centered and auto selected time #1549](https://github.com/epicmaxco/vuestic-ui/issues/1549)
- [ ] [TimePicker add infinite loop option #1550](https://github.com/epicmaxco/vuestic-ui/issues/1550)

Feel free to add anything or close this when they will be done.

Thanks a lot.

**Comment by asvae** [comment]
@Derranion assuming we can close this issue? It served its purpose as a discussion platform of sorts from what I see.

**Comment by Derranion** [comment]
Yeah thanks.
