### ISSUE TITLE
Vuestic.dev should have better image for sharing

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1199]
Here's current one on vk.
![image](https://user-images.githubusercontent.com/5394573/139858183-6008a229-aad6-4954-9d15-da4e455272c9.png)

**Comment by kushich** [comment]
Linked issue: #658

**Comment by xx13** [comment]
![social_thumbnail](https://user-images.githubusercontent.com/22664941/140653371-656aa3cf-74c9-4c24-b258-dead293a9edb.png)
pls check the updated social preview

**Comment by m0ksem** [comment]
This is fixed in at least telegram and discord. We can close this old issue. Feel free to reopen.
