### ISSUE TITLE
Data Tables: jumping "no-data" slot

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#1202]
![jumping](https://user-images.githubusercontent.com/9782236/140057799-28b5f4ed-965e-4bac-b8f7-834d6c15d419.gif)

This slot should also be enwrapped in transition-group so that it slowly appears/disappears.

**Comment by LighthouseKeeperYN** [comment]
Fixed in #956

**Comment by BrandanKing** [comment]
This issue still appears to exist in the latest version
