### ISSUE TITLE
SMALL THING

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1207]
> One small thing (and I mean like holy shit what's wrong with this guy?) is on the button examples, the spacing from the top of the button to the I in "Info" is 13 pixels while the bottom spacing is 11 so "at a glance" everything looks like it's sitting low. At 12x12, it would all center.
> That's viewing it on FF93.

**Comment by ishpartko** [comment]
Couldn't quickly figure out how to fix it, a similar problem is not solved in frameworks such as Bootstrap and Vuetify.

It has been decided to close the issue for now.
