### ISSUE TITLE
Allow easy bug reporting from documentation page

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1208]
![image](https://user-images.githubusercontent.com/5394573/140314183-2d4af216-7b24-4660-bbbe-0250a1a5b109.png)

Clicking on icon should open github issue dialog with component name filled and proper template selected.

**Comment by asvae** [comment]
@xx13 your thoughts on design?

I'm thinking this button could appear on hove or something?

**Comment by asvae** [comment]
We decided on the following

<img width="858" alt="image" src="https://user-images.githubusercontent.com/5394573/181480965-f6563764-3564-40a9-b514-2b2b581e9d12.png">

Let's add "Bug" button. Other titles we can shorten to one word. I.e. "Show code" -> "Show"

**Comment by rustem-nasyrov** [comment]
> We decided on the following
> 
> <img alt="image" width="858" src="https://user-images.githubusercontent.com/5394573/181480965-f6563764-3564-40a9-b514-2b2b581e9d12.png">
> 
> Let's add "Bug" button. Other titles we can shorten to one word. I.e. "Show code" -> "Show"

Also looks fine this variation (on mouse over appears tooltip), [source](https://element-plus.org/en-US/): 
![image](https://user-images.githubusercontent.com/29167241/181510068-f3de80a8-f7a9-4728-9d08-93376321b541.png)

**Comment by m0ksem** [comment]
I don't like this idea. It looks like we expect each demo to be bugged. Let's defer it.
