### ISSUE TITLE
Color accessibility improvement

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1210]
@xx13 any idea on that?

https://www.reddit.com/r/vuejs/comments/qlskjb/comment/hj9tsob/?utm_source=share&utm_medium=web2x&context=3

**Comment by kushich** [comment]
Useful [tool](https://webaim.org/resources/contrastchecker/)

@asvae  
And how about the dark theme for the docs? I'm a big fan of dark themes because they don't strain your eyes when reading.

**Comment by asvae** [comment]
Check if it could be a breaking change for some users and include in major release if so.

**Comment by asvae** [comment]
@xx13 up to you :)

**Comment by xx13** [comment]
I like the idea of having a dark theme. We even discussed that back in the days ^^ I'll create a ticket with colour contrast fixes, and we can discuss the dark theme during the call.

**Comment by m0ksem** [comment]
I've checked lighthouse and we don't have this issues anymore.
