### ISSUE TITLE
Component idea - stepper

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1212]
Not ready for implementation, just an idea.

![image](https://user-images.githubusercontent.com/5394573/140373560-877bf4d7-c4f1-45fe-b219-addc12f40bc7.png)

https://framework7.io/docs/stepper.html

**Comment by asvae** [comment]
Would be interesting if we don't have tasks for admin-ui.

This components still needs investigation.

**Comment by asvae** [comment]
Should go throungh following steps:
* investigation
* pass to Vasily
* estimate (next grooming) and assignment
* implementation.

We want to get this component up to next release.

**Comment by xx13** [comment]
[Design](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=1214%3A3135)

Types:
- input with actions
- input + 2 icon buttons

Features:
- min and max values (then corresponding controls turn disabled)
- number only input
- change values with up and down arrows

Customise:
- 3 built-in input styles: default, outlined, bordered
- width
- icons
- marings (for input with 2 buttons variant only)
- button style ( (for input with 2 buttons variant only)

Related:
- we need an input style with centred value, no label

@asvae
