### ISSUE TITLE
Modal not Fullscreen in Mobile

### ISSUE THREAD

**Issue by JohnniePeixoto** [epicmaxco/vuestic-ui#1215]
* **What is the expected behavior?**
Modal should be fullscreen in mobile

* **What is the current behavior?**
Even forced with the prop 'fullscreen' modal is not full on mobile (see image of the oficial docs, the same happens in my project)

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
![image](https://user-images.githubusercontent.com/26947545/140569519-a2caf08a-eae3-47fb-a1f0-ae43d87f6d58.png)

* **Other information** 
https://vuestic.dev/en/ui-elements/modal#base-layout

**Comment by tlhunter** [comment]
Are you setting the `:mobile-fullscreen="false"` flag?

**Comment by vserdobintsev** [comment]
Тоже обнаружил у себя. Временным решением будет у класса .va-modal--mobile-fullscreen отменить position: fixed.

**Comment by JohnniePeixoto** [comment]
> Are you setting the `:mobile-fullscreen="false"` flag? 

No. The only prop i've set was 'hide-default-actions'

> Тоже обнаружил у себя. Временным решением будет у класса **.va-modal--mobile-fullscreen** отменить `position: fixed`. 

Please could you describe a little more of your solution?

**Comment by vserdobintsev** [comment]
> Please could you describe a little more of your solution?

In your CSS styles, you can write like this:
```
.va-modal--mobile-fullscreen {
   position: static !important;
}
```
