### ISSUE TITLE
Requesting modal without manual HTML tags, like toast

### ISSUE THREAD

**Issue by tlhunter** [epicmaxco/vuestic-ui#1216]
In the application I'm building I've had several situations where I've needed to use a modal but that it wasn't convenient to throw in a `<va-modal />` element. Ideally, I'd love a solution like the toast component which doesn't require adding tags. The main issue is that it's easy to lose the 'context' of the current interaction; when using `<va-modal />`, I need to store any context information as additional props in the component. Instead, by allowing an inline call, all the necessary context will be close by.

Following the toast pattern:

```js
this.$vaToast.init({
  message: err.message,
  position: 'bottom-right',
  color: 'warning'
});
```

I would hope for something maybe like this:

```js
const foo_id = 12;
this.$vaModal.init({
  message: `Are you sure you would like to delete foo ${foo_id}?`,
  title: `Delete Foo ${foo_id}`,
  mobileFullscreen: false,
  okText 'KILL IT!',
  ok: async () => { await del(foo_id); },
  cancel: myCancelHandler
});
```

In this regard it's almost like an asynchronous version of the `confirm()` function.

I understand that only a subset of functionality would work with this approach since additional DOM elements can't be added to the component. Choosing where to attach it to the DOM also loses granularity but at least in my case it should be fine attaching it to the root element.

**Comment by asvae** [comment]
See https://bootstrap-vue.org/docs/components/modal#modal-message-boxes

**Comment by asvae** [comment]
I think this could be implemented as a function of modal itself (not as an optional plugin of sorts). I.e. you should be able to use modal as before + new way. Documentation should be posted on the same page.

**Comment by xiongmao86** [comment]
If no one is trying, I'll take a stab of this.
