### ISSUE TITLE
Vuestic css helpers

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1222]
Vuestic CSS helpers are intended for users who looking to get basic functionality.
If they need something more advanced - we recommend them getting separate CSS solution such as tailwind. We expect it to not conflict with components in any way.

We currently have some CSS helpers, but they're not too well documented. We also need to add some more css helpers

* [ ] Investigate what helpers we need to provide and add said list to the issue or PR.
* [ ] Helpers have to be modular/tree-shakeable (could be included or excluded from application, components should work as per usual).
* [ ] Add docs.
* [ ] We also need a list/recommendation of what to use if you need more functionality from css classes (i.e. tailwind). Provide an example for codesandbox where vuestic is being used with tailwind helpers. And add it to documentation page.

**Comment by RVitaly1978** [comment]
This issue should also close #1194

**Comment by zvenigorodskaia** [comment]
Please, care about #1288

**Comment by asvae** [comment]
We probably need
