### ISSUE TITLE
Autoloading Styles

### ISSUE THREAD

**Issue by aaronflorey** [epicmaxco/vuestic-ui#1227]
Is it possible to turn off the styles from being autoloaded?

I'm using Tailwind for my site CSS, and Vuestic is causing things to break by loading normalize and other helper classes. 

If possible, I'd like to only load the component CSS and not normalize/helpers

**Comment by m0ksem** [comment]
@aaronflorey, hey. You can use CLI plugin and select here tree shaking option — the easiest way. You can uncheck Grid and Normalize here. 

```
vue add vuestic-ui
```

Anyway, you are able to import styles from `vuestic-ui/dist/styles/essential.css` instead of `vuestic-ui/dist/styles/vuestic-styles.css`.

**Comment by m0ksem** [comment]
And maaaaaybe..... I'm not sure, let me know if components CSS load correctly. 


If there will be problems with components, you will need to turn on tree shaking for your bundler and use ESM bundle. Vite uses ESM automatically, for webpack you need to add:
```
    optimization: {
      usedExports: true,
    },
```

**Comment by aaronflorey** [comment]
hey @m0ksem 

Thank you for the reply. I'm using the Vue-CLI plugin currently, and pulling in each component separately, but for some reason, it still loads the main CSS file with normalization and reset.

I don't load any Vuestic CSS anywhere, so it must be coming from the components somewhere? I'm not sure, but it's strange.

```
import {App, Plugin} from 'vue'
import {VaInnerLoading, VaImage, VaButtonDropdown, VaButton} from "vuestic-ui";

import { mergeGlobalConfig } from 'vuestic-ui'

mergeGlobalConfig({
  colors: {
    primary: '#27272a',
    light: '#f4f4f5'
  },
})

const vuestic: Plugin = {
  install: (Vue: App) => {
    Vue.component('VaOverlay', VaInnerLoading)
    Vue.component('VaImage', VaImage)
    Vue.component('VaDropdownButton', VaButtonDropdown)
    Vue.component('VaButton', VaButton)
  }
}

export default vuestic
```

**Comment by m0ksem** [comment]
@aaronflorey 

I tested for myself. Works fine with your plugin code. 

Please, check if you are using the latest vuestic-ui version. 
Consider to use esm build of vuestic-ui.  You can try to set mode: 'production' in webpack config.

**Comment by aaronflorey** [comment]
Interesting. Were there any settings I have to put somewhere to configure the vue-cli plugin?

**Comment by m0ksem** [comment]
You can find example configuration in our packages/bundlers-tests.

**Comment by aaronflorey** [comment]
Hey @m0ksem,

My mistake, i didn't get the options for tree-shaking originally when adding the vuestic cli plugin, I must have either missed it or been running an old version. Thanks!
