### ISSUE TITLE
Input autosize widens input, but doesn't narrow it down

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1230]
See ant-design behavior, we need something similar:
https://www.antdv.com/components/input/

**Comment by ishpartko** [comment]
@asvae  Did I get it right that the text box should change its height when we reduce the number of characters?  
![1](https://user-images.githubusercontent.com/27618114/144240365-28aef836-9072-4406-8d0f-3fc85dc6b82e.gif)

**Comment by RVitaly1978** [comment]
The behavior of `VaInput` component (with `type="textarea"`) is now

![chrome-capture (1)](https://user-images.githubusercontent.com/55198465/164429286-4ee4084a-8134-4bf8-95d9-e5d8ff830d06.gif)

This issue was resolved in PR #1348
