### ISSUE TITLE
Sidebar gives Error

### ISSUE THREAD

**Issue by mezozawahra** [epicmaxco/vuestic-ui#1231]
Sidebar gives error: **(destructured parameter) is undefined** and doesn't render at all
but after adding app.use(router) the error disappears.
is it a bug ? or Vuestic requires router?

**Comment by smellyshovel** [comment]
@mezozawahra Taking a glance over the VaSidebarItem source code it's obvious that it *does* actually depend on Vue Router. But it definitely shouldn't be so, shoult it, @asvae?

![Screenshot_20211112_201547](https://user-images.githubusercontent.com/9782236/141507602-185cda4f-8523-43ba-adaf-7fc2959a6b2d.png)

**Comment by m0ksem** [comment]
@smellyshovel, @asvae. Exactly, I forget that user can use framework without router.
