### ISSUE TITLE
main.js generated by vue-cli plugin contains wrong path to essential.css

### ISSUE THREAD

**Issue by smheidrich** [epicmaxco/vuestic-ui#1235]
* **What is the expected behavior?**
The default `main.js` generated by the vuestic-ui vue-cli plugin should work out of the box.

* **What is the current behavior?**
The path in the generated `main.js` currently refers to `essentials.css`, when the file is called [`essential.css`](https://github.com/epicmaxco/vuestic-ui/blob/26ced5dc8769efd44373eb5815e26e9ea19e1b58/packages/ui/src/styles/essential.scss), leading to an error when trying to serve the app with `npm run serve`:

```
$ npm run serve --reload

> example@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 2 errors

This dependency was not found:

* vuestic-ui/dist/styles/essentials.css in ./src/main.js

To install it, you can run: npm install --save vuestic-ui/dist/styles/essentials.css

[... another unrelated error ...]
```

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**

1. Create empty Vue 3 project with vue-cli: `vue create --preset '__default_vue_3__' example && cd example`
2. Add vuestic-ui plugin via vue-cli: `vue add vuestic-ui` (just accept defaults for all prompts)
3. Try to serve the app generated by default using `npm run serve`

* **Other information**

Suggested fix (probably?): Change `essentials.css` to `essential.css` in https://github.com/epicmaxco/vuestic-ui/blob/26ced5dc8769efd44373eb5815e26e9ea19e1b58/packages/vue-cli-plugin/generator/configs/treeshaking.js#L5

**Comment by Sweetchuck** [comment]
I can confirm this bug.

**Comment by m0ksem** [comment]
Fix for this issue already merged in develop. @asvae, can I ask you to make release?
