### ISSUE TITLE
TS errors

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1244]
* **What is the expected behavior?**
Project scripts should work and execute without errors.
* **What is the current behavior?**
There are multiple TS errors currently when running `yarn serve` \ `yarn serve:book` etc.
* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**

1. Run `npx npkill` command to delete existing node modules.
2. Run `yarn` command to install fresh node modules.
3. Run `yarn serve` from `dev` branch

![TSerrors2](https://user-images.githubusercontent.com/7745899/142408193-c483d426-d371-4449-adca-df8d9b671a9f.png)

**Comment by asvae** [comment]
Doesn't reproduce on develop branch.
Reopen if still a problem.

**Comment by Derranion** [comment]
@asvae You didn't close it :)

But the issue still exists - just checked it.

Also exactly the same thing @ishpartko experienced and described in our epicmax channel 2 days ago (16:18 23 November).

Looks like you disabled `ESLint` check somehow or using its previous version.

If we will just manually run `yarn: lint` we will these errors.

**Comment by ishpartko** [comment]
@Derranion I can solve it by **deleting full project** and cloning it's again, but deleting node_modules **can't help**.

Please try to delete full project and clone it again.

Our assumption that this is a bug in the new version of the framework. When I configured the environment -- version in project was rolled back to a previous one and maybe this helped fix errors.

**Comment by asvae** [comment]
Looks very hard to figure. So closing as it seems not relevant.

**Comment by Derranion** [comment]
Pretty weird.

@ishpartko @asvae If you run `yarn: lint` it does not trigger any errors in the console?
