### ISSUE TITLE
Vertical tab slider broken

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1245]
![aJAcsQpr3C](https://user-images.githubusercontent.com/23530004/142408301-2f83079b-484f-440a-b257-54ec27ad3ab8.gif)

**Comment by asvae** [comment]
@m0ksem how do you reproduce this?

**Comment by ishpartko** [comment]
I can't reproduce :(

**Comment by m0ksem** [comment]
@asvae, @ishpartko This issue can be reproduced in Firefox. In Chrome, it works fine for me too.

**Comment by Derranion** [comment]
Was not able to reproduce - do not see this issue on vuestic.dev as well:
https://vuestic.dev/en/ui-elements/tabs#vertical-alignment

That's why I'll close this one.

But we have another vertical tab issue (looks like it may be related to `Vite`) going to create it soon.
