### ISSUE TITLE
Move some folders around

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1251]
Only for `packages/docs`.

* move `iconset` to `components`. There is too few icons to justify a separate folder.
* move `utilities/markdown-view` to `components`
* move `utils` to `helpers/` and name in a way that makes sense, or include in existing helpers file.

Doesn't have to be strictly as I wrote, but we want to move these out of root `src/`

**Comment by asvae** [comment]
@kushich can you check if what I wrote makes sense from your perspective?

**Comment by kushich** [comment]
@asvae m
aybe we should keep a components folder just for components that we export to our main file?
