### ISSUE TITLE
Navigating through sections within a docs page

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#1257]
It's a cool feature that helps users to find specific information on the page and check their position.

- [ ] create a design
- [ ] create a sidebar with a list of links related to sections on the page (I suggest using tabs component)
- [ ] push section's id to the URL according to the current position on the page
- [ ] add active style for the related link according to the current position on the page

Example: [vuetify](https://vuetifyjs.com/en/getting-started/installation/#webpack-install).

**Comment by asvae** [comment]
@xx13 your thoughts?

**Comment by asvae** [comment]
Looks pretty interesting!

**Comment by m0ksem** [comment]
Move this issue to https://github.com/epicmaxco/vuestic-ui/issues/2114
