### ISSUE TITLE
TS circular imports

### ISSUE THREAD

**Issue by ishpartko** [epicmaxco/vuestic-ui#1266]
* **What is the expected behavior?**
IDE process imports without errors.

* **What is the current behavior?**
![image](https://user-images.githubusercontent.com/27618114/143486629-371a25eb-3316-42ae-b314-dc69a0ac6b72.png)

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
This happened because our vue file has cyclic dependencies, and the typescript doesn't know how to handle them properly. My solution is to put the code into files to have only unidirectional imports in the project.  

Now(circular imports way):
```ts
// ./packages/docs/src/components/DocsTable/DocsTableTypes.ts
export type TableData = string[][];
export type TableColumn = string | { title: string, type?: 'strong' | 'markdown' | 'code' | 'pre' | 'plain' | 'translationString' }

export type { TableColumn, TableData }

// ./packages/docs/src/components/DocsTable/DocsTable.vue
import { TableData, TableColumn } from './DocsTable'
```

Could be(one way imports):
```ts
// ./packages/docs/src/components/DocsTable/DocsTableTypes.ts
export type { TableColumn, TableData }

// ./packages/docs/src/components/DocsTable/DocsTable.vue
import { TableData, TableColumn } from './DocsTable'

// ./packages/docs/src/components/DocsTable/DocsTableTypes.ts
export type TableData = string[][];
export type TableColumn = string | { title: string, type?: 'strong' | 'markdown' | 'code' | 'pre' | 'plain' | 'translationString' }
```
* **Other information** 

About this issue: https://stackoverflow.com/questions/24444436/circular-type-references-in-typescript

**Comment by ishpartko** [comment]
@asvae maybe it's about #1244

**Comment by asvae** [comment]
We could spend some time on this. But not too much.
