### ISSUE TITLE
swap font when it's loading in docs

### ISSUE THREAD

**Issue by ishpartko** [epicmaxco/vuestic-ui#1267]
* **What is the expected behavior?**
A spare, system font is displayed while the designer font is loaded.
```css
font-display: swap;
/*or*/
font-display: fallback;
```
Could we display a replacement font until the main font is loaded for the documentation? IMHO it is important for the developer to get the documentation content as quickly as possible and the font is not so important.

* **What is the current behavior?**
There is no replacement font now, the user is waiting for the font files download and all its variants to be downloaded in order to read the documentation. 
![image](https://user-images.githubusercontent.com/27618114/143492153-3d1b7830-be07-4bec-bc38-9e98b70728c5.png)

* **Other information** 
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by asvae** [comment]
Can you elaborate on this a bit?

Can't we just specify extended font-family i.e. 
```
font-family: "Source Code Pro", sans-serif;
```
