### ISSUE TITLE
Can't find Grid page in Docs

### ISSUE THREAD

**Issue by 10cheon00** [epicmaxco/vuestic-ui#1269]
Couple of days ago, grid page wasn't disabled. But today, I cannot access [grid page](https://vuestic.dev/en/styles/grid).
What happened? I saw grid page in style category a few days ago. But doesn't exists now.
![image](https://user-images.githubusercontent.com/13350111/143570042-67d1caa3-88fe-4f09-add7-9dcd7ef9d396.png)

**Comment by asvae** [comment]
Thanks for noticing.
Should be fine now :).
