### ISSUE TITLE
Paginator jumping when size of page number changing

### ISSUE THREAD

**Issue by ishpartko** [epicmaxco/vuestic-ui#1275]
* **What is the expected behavior?**
Paginator component not jumping when size of page number changing

* **What is the current behavior?**
![Анимация](https://user-images.githubusercontent.com/27618114/143616405-bdb9bdef-74c5-483f-a261-efae49987d83.gif)

**Comment by asvae** [comment]
Would be great to investigate if fix is needed even.

**Comment by asvae** [comment]
We can fix by hardcoding min width to 2 or 3 symbols
