### ISSUE TITLE
Auto form

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1284]
The idea is creating a form values object, that will contain all inputs values.

Example:

```html
<va-form v-model="myFrom">
  <va-input name="name" />
  
  <va-date-picker name="brithday" />
  
  <va-button @click="sendRequest('google.com', myForm)"></va-button>
</va-form>
```

```ts
myFrom: {
   name: '',
   birthday: new Date(),
}
```

---

For now, we need to create refs for each inputs....

**Comment by asvae** [comment]
We can use modelValue as an indication that ""

{ child: {name: 'value'} }

**Comment by asvae** [comment]
Let's try to create prototype and readd this to discussion.

**Comment by m0ksem** [comment]
Named fields are available in `useForm` composable.
