### ISSUE TITLE
Strange grid logic

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1287]
We have two classes:

d-flex
flex

md6 or sm12 classes don't work without flex class. 

flex class makes nothing by it self. 

It can be confused and also break some frameworks like tailwind.

**Comment by asvae** [comment]
Tailwind shouldn't be an issue, as if you use tailwind helpers you won'd use vuestic helpers.

**Comment by m0ksem** [comment]
> Tailwind shouldn't be an issue, as if you use tailwind helpers you won'd use vuestic helpers.

Yes, since we have tree-shakable CSS user can remove our grid from bundle. Anyway, these two classes can make smby confused.

**Comment by asvae** [comment]
Moved to another issue - we plan to rework CSS helpers

**Comment by asvae** [comment]
Let's handle this after investigation is done in scope of #1222
