### ISSUE TITLE
Optimize VaList, VaSelect long list etc.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1290]
![xMCqPDxciw](https://user-images.githubusercontent.com/23530004/144199878-c1b0bfb2-7291-46e7-9637-ed3b139da73b.gif)

I have ~400 options in this select, and it takes a long time to render.

It can be also solved if we add slot for `va-select-options-list`, so user can change this list and optimize it by himself.

----

Changing `v-if` to `v-show`  in va-dropdown here can be helpful...

**Comment by m0ksem** [comment]
Also, additional slots here can be helpful. In my example, I would like to add additional “Search Filed” with custom search logic.

**Comment by asvae** [comment]
Discussed:
* We can document existing approach (see http://vuestic-ui-demo.sub.asva.by/#/demo/va-select/VaSelect.demo.vue scroll-bottom event).

Potentially we might want to implement virtual scroll, but not right now.

**Comment by aluarius** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/2290
