### ISSUE TITLE
VaHover slot based access not working

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1292]
https://vuestic.dev/en/ui-elements/hover#slot-based-access

This works only if prop stateful set to true.

Question: Do we really need to provide stateful prop? Can we just look for `modelValue` to be undefined? That would be mean that component should be stateful by default.

**Comment by asvae** [comment]
> modelValue to be undefined
No, undefined is a valid state, that could be passed down from parent.

We can use stateful true as default if you think that covers more cases.

**Comment by m0ksem** [comment]
closed in https://github.com/epicmaxco/vuestic-ui/pull/1432
