### ISSUE TITLE
Ability for button-like components to adapt text color in accordance to background

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1295]
* Bonus points for manual assignment.

**Comment by kushich** [comment]
@asvae Maybe we should also keep text-color prop to override text-color even though we will use computed text color to handle edge cases. How do you think?

**Comment by asvae** [comment]
We want to support this for simplest cases:
* I.e. when text-color is not set - we set it based on background. But in all other cases - we're not being too smart.
* And it would choose between black and white color.

**Comment by Derranion** [comment]
Here are some recursive algorithms to implement this by checking parents background:
https://stackoverflow.com/questions/12576084/getting-the-real-background-color-of-an-element

**Comment by m0ksem** [comment]
I think it has been fixed here: https://github.com/epicmaxco/vuestic-ui/issues/1729
