### ISSUE TITLE
Fix withTransportConfig setup expose

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1297]
Expose function expose component properties only to instance, so there is no way to check exposed keys before component is rendered. 

Because of that, `withTransportConfig` can not determinate which methods are should be proxied from setup function.

There are few options that I can see:
- ✔ We should remove this proxy component and create some `transportConfig` hook. (This will require us to refactor all the components.)
- ✔ We should add `expose` component as option (like `emits`), so in `withTransportConfig` we can see exactly which methods should be proxied.  
- 🤔 Maybe we can see exposed methods after component is rendered and update methods on runtime.
- 🤔 Maybe we can modify props or propsData in withTransportConfig and use mixins here.

**Comment by asvae** [comment]
Personally, not a big fan of the whole component wrapper idea.
So would prefer to have config-based magical prop handling somehow hidden inside of component.

Would be great to have some sort of prototype (that covers expose function problem). We can have a bigger discussion on top of said prototype. That would also allow us to measure, how time consuming the whole thing would be.
