### ISSUE TITLE
Vuestic-ui book not work in ie11

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#131]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

*Vuestic-ui book does not work in ie11*

**Comment by asvae** [comment]
It does for me.
