### ISSUE TITLE
Build warning for asva-executors: "export '__spreadArray' was not found in 'tslib'

### ISSUE THREAD

**Issue by 4000degrees** [epicmaxco/vuestic-ui#1312]
**Vuestic-ui version:** 1.3.1

**Steps to reproduce**
1. Install Vuestic: `vue add vuestic-ui`
2. Run `npm run dev` or `npm run build`

**What is the expected behavior?**
Build without warnings.

**What is the current behavior?**
Get build warning:
```
 WARNING  Compiled with 1 warning

 warning  in ./node_modules/asva-executors/dist/src/index.esm.js

"export '__spreadArray' was not found in 'tslib'
```
**Other information**
Vue 3, @vue/cli 4.5.15

**Comment by asvae** [comment]
Pretty sure that's fixed. Executors have been moved out of project.
