### ISSUE TITLE
Add accents to the docs

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1314]
I believe we could add some **basic accents** to our docs in the style of **EpicMax** - some kind of **purple gradient**.

It is pretty easy to implement and will make docs look a bit more entertaining and appealing.

We can see something similar in the [npm docs](https://docs.npmjs.com/getting-started):
![addEpicMaxAccentsToTheDocs](https://user-images.githubusercontent.com/7745899/144940358-f66bbaa5-7130-4bb4-9127-0705e192245d.png)

**Comment by Derranion** [comment]
@xx13 Hello, would be great if you could share your thoughts as well.

**Comment by asvae** [comment]
@xx13 any updates on that?

**Comment by xx13** [comment]
@asvae added to my todo list

**Comment by m0ksem** [comment]
Let's focus on important stuff :)
