### ISSUE TITLE
Vite plugin

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1317]
Based on this discord discussion: https://discord.com/channels/457593300799717377/771405157527191585/916725337751179315

We already have vue-cli plugin, but we don't have [vite plugin](https://vitejs.dev/guide/api-plugin.html#plugins-config), which is starting to be dominant way of vue usage.

**Comment by m0ksem** [comment]
You meant vite community template:

https://github.com/vitejs/awesome-vite#templates

**Comment by asvae** [comment]
Oppsie!
