### ISSUE TITLE
Integrity check failed for "colortranslator" when installing

### ISSUE THREAD

**Issue by JJLee9527** [epicmaxco/vuestic-ui#1318]
I encountered this issue today. I've tried pnpm and yarn installation for vuesitc-ui, and both package manager showed similar answers telling the same thing : sha512 not matching caused the package fetching failed.

Really hope someone could help me with this 🙏

**Vuestic-ui version:** 1.3.1

**Steps to reproduce**

1.  shell: yarn add vuestic-ui
2. Error popped up
`yarn add v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/colortranslator/-/colortranslator-1.9.0.tgz: Integrity check failed for "colortranslator" (computed integrity doesn't match our records, got "sha512-6X1ilN5STXAyRosO3bEUq40oTTOJzzJE6xynkGAHKqOEXFJ6FZWx3SnE6BDBowoF5OOynUgXs8vnkC1OzVA2GQ== sha1-PTobSprMGPS/PdDzqOFRsq0xNaY=")
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**What is the current behavior?**
Can't use vuestic-ui in project
 
**Other information**
none

**Comment by asvae** [comment]
Thanks. We'll take a look.
Maybe updating colortranslator dep on our side would help.

@JJLee9527 could you check if `npm install vuestic-ui` work for you?
Curious if it's a yarn issue, as sometimes they handle deps differently.

**Comment by tomkys144** [comment]
@asvae npm does the same. When looking in repo it looks, like version 1.9.0 is broken, since CI/CD failed on this release...

**Comment by tomkys144** [comment]
for the time being workaround with specifying previous version of colortranslate is working OK... (wouldn't recommend for production but you can at least develop your app until author of the external package fixes the problem...)

```shell
npm i colortranslator@1.8.0
npm i vuestic-ui
```

**Comment by tomkys144** [comment]
elchininet/ColorTranslator#60 solved this. Version 1.9.1 is published, which should be working...

**Comment by asvae** [comment]
Assuming this is fixed. Thanks.
