### ISSUE TITLE
Timepicker update

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#1326]
Timepicker update includes visual changes along with new features, making this component more powerful and easier to use.

- [x] #1327
- [ ] #1328
- [x] #1329
- [x] #1330

**Comment by patrikhv** [comment]
Hi, I would like to contribute. Could you assign it to me, please?

**Comment by patrikhv** [comment]
` INFO  Starting development server...
[1%] setup (initialize)
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'disableHostCheck'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, static?, 
watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'disableHostCheck'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
    at validate (C:\Users\hvozd\OneDrive\Počítač\ess\vuestic-ui\packages\ui\node_modules\webpack-dev-server\node_modules\schema-utils\dist\validate.js:115:11)
    at new Server (C:\Users\hvozd\OneDrive\Počítač\ess\vuestic-ui\packages\ui\node_modules\webpack-dev-server\lib\Server.js:31:5)
    at serve (C:\Users\hvozd\OneDrive\Počítač\ess\vuestic-ui\packages\ui\node_modules\@vue\cli-service\lib\commands\serve.js:183:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.`I am having issues getting the development server to run. Any idea what going on?

**Comment by m0ksem** [comment]
> Hi, I would like to contribute. Could you assign it to me, please?

Woops. Sorry, missed that comment! It's better to make contribution in issues with "good first issue" label for newcomers.

**Comment by m0ksem** [comment]
Closing this issue, but waiting on https://github.com/epicmaxco/vuestic-ui/issues/1328
