### ISSUE TITLE
Timepicker visual update

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#1327]
[Design](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=707%3A2023)

- [ ] The selected values are vertically centered, instead of taking the 2nd slot from the top. If the amount of lines is even, the selected values sit closer to the top. _(Can we customize the position of the selected values? If so, please create a related issue in [the parent ticket](https://github.com/epicmaxco/vuestic-ui/issues/1326))._
- [ ] Selected text colour is changed to `primary`.
- [ ] On hover, the background should be added, but no changes to the font colour.

<img width="299" alt="timepicker-visual-update" src="https://user-images.githubusercontent.com/22664941/145542028-2fc76cd2-7a11-4b6d-a923-71ca2fbe724a.png">

**Comment by asvae** [comment]
Work in progress for @xx13 :)
After #1328

**Comment by xx13** [comment]
@asvae this issue can be closed as we have [Set values by scrolling (alternative input type)](https://github.com/epicmaxco/vuestic-ui/issues/1328) which is more up-to-date

**Comment by m0ksem** [comment]
Looks like fixed in 1.4.7.
