### ISSUE TITLE
Set values by scrolling (alternative input type)

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#1328]
- [x] Let's introduce an alternative type of data input. Instead of selecting a value by clicking, we'll set the value by scrolling, so that the highlighted value in the center is being treated as the clicked value in the current implementation.
- [ ] `Looped` attribute stands for having endless scroll of values in every section of the timepicker control, no empty values. It makes sense to have it for `scroll` type of control only.

**Comment by asvae** [comment]
@xx13 let's discuss this with you.
We decided it's ok to keep both click and scroll (as for mouse users scroll alone is not sensitive enough).

For looped we're generally positive, but could take a while to implement, so we maybe can move it to separate issue.

**Comment by asvae** [comment]
Discussed with @xx13, decided to fix dropdown style, create a different scroller.

https://demo.mobiscroll.com/jquery/datetime/mobile-desktop-usage#

**Comment by m0ksem** [comment]
Looped prop will require a lot of effort. Do we really need it?

**Comment by m0ksem** [comment]
Let's track loop prop in https://github.com/epicmaxco/vuestic-ui/issues/1550
