### ISSUE TITLE
VaDropdown has 100% width, but Select not

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1331]
![5vlYTjaAw5](https://user-images.githubusercontent.com/23530004/145541456-910b5c7f-f7b1-4bb8-aad6-49688c472f64.gif)

If you click on VaDropdown on the right side into space, select will be opened.

**Comment by RVitaly1978** [comment]
Fixed on PR https://github.com/epicmaxco/vuestic-ui/pull/1346
