### ISSUE TITLE
Junk card css

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1334]
My code: 
 ```

<va-card class="card" outlined>
....
</va-card>

```

![image](https://user-images.githubusercontent.com/23530004/145660890-e43245bb-ebad-4160-8e01-73974ec23734.png)

![image](https://user-images.githubusercontent.com/23530004/145660893-9f1d2ae5-1997-4669-8884-033ac298ee67.png)

Expected: Take a look at shadows.

![image](https://user-images.githubusercontent.com/23530004/145660956-e313c785-e5a1-4f66-8bc8-31b023576bc6.png)

**Comment by asvae** [comment]
@m0ksem can you clarify?
There should be no shadow?

**Comment by asvae** [comment]
I assume we just have to delete `.card`, also check similar problems.
