### ISSUE TITLE
VaListLabel should has default color

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1335]
![image](https://user-images.githubusercontent.com/23530004/145661188-83448400-1f00-42e7-9650-83a76434594d.png)

![image](https://user-images.githubusercontent.com/23530004/145661192-43d2ef8f-cae7-468f-834d-82c152317742.png)

**Comment by patrikhv** [comment]
Hi, could you assign that to me?

**Comment by patrikhv** [comment]
Which color should I set as default?

**Comment by asvae** [comment]
Awesome, thanks!

primary is probably the right call :).
