### ISSUE TITLE
Elvis strikes back

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1336]
**Vuestic-ui version:** 1.3.2 (I removed problem point in 1.3.3, but inherent problem still remains)

If you use elvis operator (`?.`) in **template** - it's not getting transpiled in the build.

If you use elvis operator in other places - it's getting transpiled fine.

So `@click="input?.focus()"` would be transpiled to `click: this.input?.focus()` which corrupts the build on user side.

That's really problematic, and we can't spot the issue in development phase.

Two ways we can deal with that:
1) Specify different es version for package so it's getting transpiled on user side (elvis is part of the spec).
2) Ensure template transpiles consistently with scripts.

**Comment by sergey-kravcov** [comment]
The error is only in `build`. No conversion occurs in the final file.
I created an empty `vue-cli` project with babel and everything works in it. So the problem is most likely in `rollup`.

**Comment by m0ksem** [comment]
cosed in #1443
