### ISSUE TITLE
VaModal anchor slot

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1337]
**Describe the solution you'd like**
```vue
<va-modal>
 <template #anchor="{ open, close }">
    <va-button @click="open"> Open settings  </va-button>
  </template>
  <UserSettingsComponent />
</va-modal>
```
**Describe alternatives you've considered**
Now we have to:

```vue
<va-button @click="showModal = !showModal">
  Open settings 
</va-button>
<va-modal v-model="showModal">
  <UserSettingsComponent />
</va-modal>
```

**Additional context**

Similar to VaPopopver

**Comment by asvae** [comment]
We can keep original approach as well.

We also have actions approach (where you can `$refs.modal.show()`), just make sure this works.
