### ISSUE TITLE
Typography code font

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1339]
.code-snipper uses `Source Code Pro` font and there is no information about it

![image](https://user-images.githubusercontent.com/23530004/145692607-ad93650f-92e6-48e2-89ff-3ce8e7ea4f8f.png)

Add this snippet somewhere 
```
<link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet"> 
```

**Comment by asvae** [comment]
If that's a helper, we can probably revisit this issue in scope of helpers overhaul.

**Comment by xiongmao86** [comment]
Hi, @m0ksem, I have search `.code-snippet` and don't know why we need information about the font used to render it?

**Comment by xiongmao86** [comment]
Has it already added over [here](https://github.com/epicmaxco/vuestic-ui/blob/d79cdfe784d361921935180a9a475d17012649d5/packages/docs/public/index.html#L29-L30) ?
