### ISSUE TITLE
In select it's very hard to deselect selected items

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1345]
Once I selected couple of items in select - there is no way for me to deselect them quickly.

![image](https://user-images.githubusercontent.com/5394573/145786392-021bc85e-c1c9-4173-af7a-e67617c26daa.png)

**Comment by RVitaly1978** [comment]
`va-select` has a `clearable` prop to clear all selected items. Do you think we need any else?

**Comment by m0ksem** [comment]
You could do something like this...

```vue
    <va-select v-model="value" :options="options" multiple>
      <template #content="{ value }">
        <span v-for="o in value" :key="o">
          {{ o }} <va-button @click="removeItem(o)" icon="delete" size="small" />
        </span>
      </template>
    </va-select >
```

...if you want to be able to remove a specific option from input.

----
But, here is a bug.

We should remove extra content slot 
in `packages/ui/src/components/va-input/components/VaInputField.vue`

![image](https://user-images.githubusercontent.com/23530004/145818983-f813b67e-9b65-437d-8a00-8bc5848503fd.png)

**Comment by m0ksem** [comment]
Already fixed. 
We even have a docs [demo](http://localhost:8080/en/ui-elements/select#slots).
