### ISSUE TITLE
Missing titles and component names.

### ISSUE THREAD

**Issue by Sadnessa** [epicmaxco/vuestic-ui#1350]
![изображение](https://user-images.githubusercontent.com/67637329/146661151-a0ed8e28-9010-4158-9823-cfd1ca418ff6.png)
https://vuestic.dev/ru/ui-elements/time-input

![изображение](https://user-images.githubusercontent.com/67637329/146661158-2f18062e-e625-46d7-8cc5-754c048ec35a.png)
https://vuestic.dev/ru/ui-elements/time-picker

**Comment by kushich** [comment]
Fixed
