### ISSUE TITLE
VaTimeInput manual input

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1351]
Broken VaTimeInput manual-input prop.

![iDMRaoCfjn](https://user-images.githubusercontent.com/23530004/147273949-b818b28d-7b87-4f7a-b05c-3e91ce271b5b.gif)

![image](https://user-images.githubusercontent.com/23530004/146662157-db399447-0c63-447b-9a63-c539d4a0173e.png)

---

Works fine on `vuestic-ui@1.3.1`

**Comment by asvae** [comment]
@VasylHryha you can close this if the issue is indeed no repro.
