### ISSUE TITLE
VaTimeInput opens dropdown after text input

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1352]
**Vuestic-ui version:** 1.3.3

I don't use here mouse clicks.
![Pme5XBhRfv](https://user-images.githubusercontent.com/23530004/146662294-ee817a2a-7ade-46ca-b477-a2512d48de90.gif)

**Comment by VasylHryha** [comment]
@m0ksem proposed the next changes in `VaDropdown` behavior:
 - disable dropdown close on `Enter`
 - add ability to close dropdown on `ESC`
 
 changes to `VaTimeInput`: 
 - when `manual-input` is enabled, open dropdown on `focus`
 
 @asvae are you ok with these changes ?
