### ISSUE TITLE
VaSelect inner label can be selected by user

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1353]
**Vuestic-ui version:** 1.3.3

For now, it is unusable if user want to copy this text and looks ugly after click.
![Q7YznemN3b](https://user-images.githubusercontent.com/23530004/146662355-952580af-151d-446f-a81d-76b5a64e45f8.gif)

**Comment by zvenigorodskaia** [comment]
@m0ksem You think we need to disable text highlighting here?

**Comment by m0ksem** [comment]
Yap. Would be nice to remove text highlighting on double click if it is possible. Or remove text highlighting completely.
