### ISSUE TITLE
Incorrect badge on readme

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1359]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**
https://github.com/epicmaxco/vuestic-ui
![image](https://user-images.githubusercontent.com/5394573/147472056-87157ea4-28e8-4aea-97be-aff86ac10d6f.png)

**What is the expected behavior?**
Should have version from `packages/ui`.

**What is the current behavior?**
1.0.0

**Other information**
Allegedly fixed in #1234 >.>. Also see the discussion there.

**Comment by kushich** [comment]
It's already fixed, but we decided to investigate a way for setting it per release version instead of the latest one
