### ISSUE TITLE
Vertical tabs Vite issue

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1362]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**
1. Create new project using `Vite` and `Vuestic 1.3.3`
2. Add this code to the template:
```
<va-tabs v-model="tabsModel" vertical>
    <va-tab>TabValue</va-tab>
    <va-tab>TabValue 2</va-tab>
    <va-tab>TabValue 3</va-tab>
  </va-tabs>
```
3. Select any tab

**What is the expected behavior?**
Selected tab should be correctly highlighted - the same way as it is showed in [our docs](https://vuestic.dev/en/ui-elements/tabs#vertical-alignment).

**What is the current behavior?**
This works correctly only when using local server.
And does not have vertical highlight on a new project using `Vite`.
![VerticalTabsBugViteNewProject](https://user-images.githubusercontent.com/7745899/147491033-067f8d94-0aaf-4602-9a0e-59fc6a9480c4.jpg)

**Comment by ralpheichelberger** [comment]
sorry, but this is still not working for me:
I am using:
    "vue": "^3.2.26",
    "vue-class-component": "^8.0.0-rc.1",
    "vue-router": "^4.0.12",
    "vue3-charts": "^1.1.27",
    "vuestic-ui": "^1.3.4"

using pug
`
const tabs = ["Produkte", "Produktgruppen", "Verkäufe", "Bons", "Steuern"]
        va-tabs(v-if="auth" v-model="currentTab" vertical)
            va-tab(v-for="title in tabs" :name="title" :key="title") {{ title }}

`
![Peek 2022-01-28 14-52](https://user-images.githubusercontent.com/34127607/151559731-56d7e361-fc74-4e2f-8cfe-fe5c3fc0eba9.gif)

**Comment by m0ksem** [comment]
> sorry, but this is still not working for me: I am using: "vue": "^3.2.26", "vue-class-component": "^8.0.0-rc.1", "vue-router": "^4.0.12", "vue3-charts": "^1.1.27", "vuestic-ui": "^1.3.4"
> 
> using pug ` const tabs = ["Produkte", "Produktgruppen", "Verkäufe", "Bons", "Steuern"] va-tabs(v-if="auth" v-model="currentTab" vertical) va-tab(v-for="title in tabs" :name="title" :key="title") {{ title }}
> 
> ` ![Peek 2022-01-28 14-52](https://user-images.githubusercontent.com/34127607/151559731-56d7e361-fc74-4e2f-8cfe-fe5c3fc0eba9.gif)


Consider to use #tabs slot. [Take a look at examples we have](https://vuestic.dev/en/ui-elements/tabs#vertical-alignment)

**Comment by ralpheichelberger** [comment]
You are right! using the slot "tabs" works!
Thank you! I did't see that.
