### ISSUE TITLE
optgroup in va-select

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1373]
### Discussed in https://github.com/epicmaxco/vuestic-ui/discussions/1240

<div type='discussions-op-text'>

<sup>Originally posted by **gitguidev** November 16, 2021</sup>
How can I use optgroup in va-select?</div>

Present in html select, https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup.
We might want to have something similar for vuestic select.
Implementation could be different though, as long as it solves the same problem.

**Comment by m0ksem** [comment]
We have this in design files, but not implemented.

https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=123%3A483
