### ISSUE TITLE
Ensure release is stable

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1375]
- [x] Go through [bug issues](https://github.com/epicmaxco/vuestic-ui/issues?q=is%3Aissue+is%3Aopen+label%3ABUG) and ensure nothing important is broken.
- [x] Ensure project works in vue-cli, vite, nuxt.

**Comment by ralpheichelberger** [comment]
I would propose introducing some testing framework, at least something like cypress.

**Comment by m0ksem** [comment]
> I would propose introducing some testing framework, at least something like cypress.

Hey. It is actually in [progress](https://github.com/epicmaxco/vuestic-ui/pull/1599). Currently, working on nuxt integration, so tests moved to second plan (I know how sad it sounds ☹).

**Comment by ralpheichelberger** [comment]
Ey, thats good! I know,  you guys are working on it. Its just I like the TDD method, where you start with the test. I am aware that thats also a lot of overhead but it really pays later in the project. I know  I am doing it for years now. And imho it is a requirement for a project to mature.
