### ISSUE TITLE
Add ESlint rule that will require developers to provide component name

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1378]
**Vuestic-ui version:** 1.3.3

For now, our component don't have a name in component options. That causes a problem in DOCS api. We use component name to get translation strings.

Current state:
![image](https://user-images.githubusercontent.com/23530004/147740534-01940db4-e750-4bf6-bd1f-81854a257279.png)

If name is set.

![image](https://user-images.githubusercontent.com/23530004/147740554-7b4632b5-3d18-4c57-8ea5-7cb1493185ad.png)

Would be nice to have ESLint rule that will require us to provide componen name.

**Comment by asvae** [comment]
Could a script of sorts as well, but linter rule is ideal, sure.
