### ISSUE TITLE
Select load on scroll

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1380]
**Is your feature request related to a problem? Please describe.**

Throw an event when select is scrolled to the bottom. This is needed to load additional options.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Alternative would be more involved loading. I.e. select could take a closure and handle loader and pagination internally.

**Additional context**

Requested by @untael

**Comment by patrikhv** [comment]
Hi, can you assign this for me?
