### ISSUE TITLE
Discuss tab behavior

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1388]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**

1. Open `Select`
2. Press `Tab`

**What is the current behavior?**
First `Tab` press focuses current Select. Only second `Tab` press selects next element.

**What is the expected behavior?**
From my perspective `Tab` should select next element after the first click.
I've made it work like this before because we treated it like a bug with @asvae not sure why it [was changed](https://github.com/epicmaxco/vuestic-ui/pull/1344).

**Other information**
If we will decide to move back just change this line inside the `Select va-dropdown-content`:

`@keydown.tab.prevent="hideDropdown"` to this `@keydown.tab="hideDropdown"`

**Comment by m0ksem** [comment]
Looks like fixed.
