### ISSUE TITLE
Discuss border style changes

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1389]
Currently we have barely visible border of the chosen `Select`, not sure if this is intended:

![barelyVisibleBorder](https://user-images.githubusercontent.com/7745899/147964985-e940b49f-7da8-4ccb-9916-8cabf8690a69.png)

Previously it was something like this:
![selectBorder](https://user-images.githubusercontent.com/7745899/147965369-e1ca4183-e09c-43d5-b19b-5129126a528a.png)

**Comment by asvae** [comment]
@xx13 can you check if that's relevant?

**Comment by xx13** [comment]
@Derranion nice catch. the focused border colour should be `primary`, not grey.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/22664941/163851708-e55e7bee-7795-4d8a-bedb-8bbe3355381f.png">

**Comment by Derranion** [comment]
It is fixed in dev branch.
