### ISSUE TITLE
Form problems

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#139]
## Bugs
- [x] `focusInvalidFormRef` -> `focusInvalidForm` everywhere.
- [x] validation doesn't trigger until I press "validate". It should be though.
![image](https://user-images.githubusercontent.com/5394573/70144143-5d150280-16ae-11ea-9d00-97510a62f09c.png)
- [x] `focusInvalid` focus invalid should not validate. Just focus.
- [x] validation should trigger on blur as well as on change.
- [x] If rule returns `false` - input should be considered invalid. Currently `true` or `false` are considered valid.
- [x] If rule returns empty string - input should be considered invalid. Currently '' means valid.
- [x] if rule returns anything that is not string or boolean - it should be considered invalid.

## Changes
- [x] add `start-validating-on-blur: boolean` prop to validateable component

If true, form component should validate according to rules only on blur.
Otherwise it should validate according to rules on blur and external value change.

**Comment by asvae** [comment]
@misterpekert can you check all points one by one?
I started from the top, and already the first one is not done.

**Comment by misterpekert** [comment]
@asvae it seems that for some reason I've missed this renaming in my changes. I've done and verified all points, so everything should be working right now.
