### ISSUE TITLE
VaTimeInput don't pass lable to VaInput

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1392]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/23530004/148130963-7aa4e324-2b2c-482b-aa85-af7bf372efdd.png)

**Comment by RVitaly1978** [comment]
Fixed it in PR https://github.com/epicmaxco/vuestic-ui/pull/1394
