### ISSUE TITLE
Create a list of components we need to convert to composition API

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1397]
closes #567 after all components refactored.

**Comment by LighthouseKeeperYN** [comment]
- [ ] packages\docs\src\components\DocsAlert.vue
- [ ] packages\docs\src\components\DocsAnchor.vue
- [ ] packages\docs\src\components\DocsApi\ApiDocs.vue
- [ ] packages\docs\src\components\DocsApi\ApiDocsPropsRow.vue
- [ ] packages\docs\src\components\DocsCode.vue
- [ ] packages\docs\src\components\DocsComponent.vue
- [ ] packages\docs\src\components\DocsContent.vue
- [ ] packages\docs\src\components\DocsExample.vue
- [ ] packages\docs\src\components\DocsHeadline.vue
- [ ] packages\docs\src\components\DocsLink.vue
- [ ] packages\docs\src\components\DocsNavigation.vue
- [ ] packages\docs\src\components\DocsSubtitle.vue
- [ ] packages\docs\src\components\DocsTable\DocsTable.vue
- [ ] packages\docs\src\components\header\components\ColorDropdown.vue
- [ ] packages\docs\src\components\header\components\HeaderSelector.vue
- [ ] packages\docs\src\components\header\components\LanguageDropdown.vue
- [ ] packages\docs\src\components\header\components\VersionDropdown.vue
- [ ] packages\docs\src\components\header\components\VuesticDocsLogo.vue
- [ ] packages\docs\src\components\header\components\VuesticLogo.vue
- [ ] packages\docs\src\components\header\Header.vue
- [ ] packages\docs\src\components\landing\Admin.vue
- [ ] packages\docs\src\components\landing\ColorTab.vue
- [ ] packages\docs\src\components\landing\Customize.vue
- [ ] packages\docs\src\components\landing\Footer.vue
- [ ] packages\docs\src\components\landing\Header.vue
- [ ] packages\docs\src\components\landing\icons\IconAdmin.vue
- [ ] packages\docs\src\components\landing\icons\IconEpicmax.vue
- [ ] packages\docs\src\components\landing\icons\IconSpinners.vue
- [ ] packages\docs\src\components\landing\OpenSource.vue
- [ ] packages\docs\src\components\landing\SeamlessIntegration\SeamlessIntegration.vue
- [ ] packages\docs\src\components\landing\StarsButton.vue
- [ ] packages\docs\src\components\markdown-view\MarkdownView.vue
- [ ] packages\docs\src\components\PrismWrapper.vue
- [ ] packages\docs\src\components\sidebar\algolia-search\AlgoliaSearch.vue
- [ ] packages\docs\src\components\sidebar\Sidebar.vue
- [ ] packages\docs\src\components\sidebar\SidebarLink.vue
- [ ] packages\docs\src\layouts\default.vue
- [ ] packages\docs\src\page-configs\getting-started\installation\components\OpenCodeSandbox.vue
- [ ] packages\docs\src\page-configs\services\colors-config\examples\change-colors.vue
- [ ] packages\docs\src\page-configs\services\colors-config\examples\components\colors-editor.vue
- [ ] packages\docs\src\page-configs\services\colors-config\examples\css-variable.vue
- [ ] packages\docs\src\page-configs\services\components-config\examples\button.vue
- [ ] packages\docs\src\page-configs\services\icons-config\examples\font.vue
- [ ] packages\docs\src\page-configs\ui-elements\backtop\examples\Default.vue
- [ ] packages\docs\src\page-configs\ui-elements\button-dropdown\examples\Events.vue
- [ ] packages\docs\src\page-configs\ui-elements\chip\examples\Closeable.vue
- [ ] packages\docs\src\page-configs\ui-elements\data-table\examples\Filtering.vue
- [ ] packages\docs\src\page-configs\ui-elements\data-table\examples\Pagination.vue
- [ ] packages\docs\src\page-configs\ui-elements\data-table\examples\Selection.vue
- [ ] packages\docs\src\page-configs\ui-elements\data-table\examples\Sorting.vue
- [ ] packages\docs\src\page-configs\ui-elements\date-input\examples\advancedFormatting.vue
- [ ] packages\docs\src\page-configs\ui-elements\date-input\examples\formatting.vue
- [ ] packages\docs\src\page-configs\ui-elements\date-input\examples\input.vue
- [ ] packages\docs\src\page-configs\ui-elements\date-input\examples\resetOnClose.vue
- [ ] packages\docs\src\page-configs\ui-elements\divider\examples\Inset.vue
- [ ] packages\docs\src\page-configs\ui-elements\divider\examples\WithList.vue
- [ ] packages\docs\src\page-configs\ui-elements\form\examples\Submit.vue
- [ ] packages\docs\src\page-configs\ui-elements\hover\examples\Slot.vue
- [ ] packages\docs\src\page-configs\ui-elements\image\examples\DefaultSlot.vue
- [ ] packages\docs\src\page-configs\ui-elements\image\examples\LoaderSlot.vue
- [ ] packages\docs\src\page-configs\ui-elements\infinite-scroll\examples\CustomTarget.vue
- [ ] packages\docs\src\page-configs\ui-elements\infinite-scroll\examples\Default.vue
- [ ] packages\docs\src\page-configs\ui-elements\infinite-scroll\examples\Disabled.vue
- [ ] packages\docs\src\page-configs\ui-elements\infinite-scroll\examples\Reverse.vue
- [ ] packages\docs\src\page-configs\ui-elements\select\examples\AllowCreate.vue
- [ ] packages\docs\src\page-configs\ui-elements\select\examples\Chips.vue
- [ ] packages\docs\src\page-configs\ui-elements\sidebar-item\examples\Active.vue
- [ ] packages\docs\src\page-configs\ui-elements\sidebar-item\examples\Components.vue
- [ ] packages\docs\src\page-configs\ui-elements\toast\examples\Click.vue
- [ ] packages\docs\src\page-configs\ui-elements\toast\examples\Close.vue
- [ ] packages\docs\src\pages\contribution\documentation-page.vue
- [ ] packages\docs\src\pages\contribution\guide.vue
- [ ] packages\docs\src\pages\contribution\index.vue
- [ ] packages\docs\src\pages\contribution\translation.vue
- [ ] packages\docs\src\pages\contribution\tree-shaking-requirements.vue
- [ ] packages\docs\src\pages\contribution\ui-element-guide.vue
- [ ] packages\docs\src\pages\extensions\ag-grid.vue
- [ ] packages\docs\src\pages\getting-started\accessibility-guide.vue
- [ ] packages\docs\src\pages\getting-started\configuration-guide.vue
- [ ] packages\docs\src\pages\getting-started\index.vue
- [ ] packages\docs\src\pages\getting-started\installation.vue
- [ ] packages\docs\src\pages\index.vue
- [ ] packages\docs\src\pages\introduction\browser-support.vue
- [ ] packages\docs\src\pages\introduction\index.vue
- [ ] packages\docs\src\pages\introduction\overview.vue
- [ ] packages\docs\src\pages\introduction\roadmap.vue
- [ ] packages\docs\src\pages\MarkdownTest.vue
- [ ] packages\docs\src\pages\services\advanced-icons-config.vue
- [ ] packages\docs\src\pages\services\colors-config.vue
- [ ] packages\docs\src\pages\services\components-config.vue
- [ ] packages\docs\src\pages\services\global-config.vue
- [ ] packages\docs\src\pages\services\icons-config.vue
- [ ] packages\docs\src\pages\services\index.vue
- [ ] packages\docs\src\pages\styles\colors.vue
- [ ] packages\docs\src\pages\styles\css-variables.vue
- [ ] packages\docs\src\pages\styles\grid.vue
- [ ] packages\docs\src\pages\styles\index.vue
- [ ] packages\docs\src\pages\styles\reset.vue
- [ ] packages\docs\src\pages\styles\typography.vue
- [ ] packages\docs\src\pages\ui-elements\accordion.vue
- [ ] packages\docs\src\pages\ui-elements\affix.vue
- [ ] packages\docs\src\pages\ui-elements\alert.vue
- [ ] packages\docs\src\pages\ui-elements\app-bar.vue
- [ ] packages\docs\src\pages\ui-elements\avatar.vue
- [ ] packages\docs\src\pages\ui-elements\backtop.vue
- [ ] packages\docs\src\pages\ui-elements\badge.vue
- [ ] packages\docs\src\pages\ui-elements\breadcrumbs.vue
- [ ] packages\docs\src\pages\ui-elements\button-dropdown.vue
- [ ] packages\docs\src\pages\ui-elements\button-group.vue
- [ ] packages\docs\src\pages\ui-elements\button-toggle.vue
- [ ] packages\docs\src\pages\ui-elements\button.vue
- [ ] packages\docs\src\pages\ui-elements\card.vue
- [ ] packages\docs\src\pages\ui-elements\checkbox.vue
- [ ] packages\docs\src\pages\ui-elements\chip.vue
- [ ] packages\docs\src\pages\ui-elements\collapse.vue
- [ ] packages\docs\src\pages\ui-elements\color-input.vue
- [ ] packages\docs\src\pages\ui-elements\color-palette.vue
- [ ] packages\docs\src\pages\ui-elements\color-picker.vue
- [ ] packages\docs\src\pages\ui-elements\data-table.vue
- [ ] packages\docs\src\pages\ui-elements\date-input.vue
- [ ] packages\docs\src\pages\ui-elements\date-picker.vue
- [ ] packages\docs\src\pages\ui-elements\divider.vue
- [ ] packages\docs\src\pages\ui-elements\file-upload.vue
- [ ] packages\docs\src\pages\ui-elements\form.vue
- [ ] packages\docs\src\pages\ui-elements\hover.vue
- [ ] packages\docs\src\pages\ui-elements\icon.vue
- [ ] packages\docs\src\pages\ui-elements\image.vue
- [ ] packages\docs\src\pages\ui-elements\index.vue
- [ ] packages\docs\src\pages\ui-elements\infinite-scroll.vue
- [ ] packages\docs\src\pages\ui-elements\inner-loading.vue
- [ ] packages\docs\src\pages\ui-elements\input.vue
- [ ] packages\docs\src\pages\ui-elements\list.vue
- [ ] packages\docs\src\pages\ui-elements\modal.vue
- [ ] packages\docs\src\pages\ui-elements\navbar.vue
- [ ] packages\docs\src\pages\ui-elements\option-list.vue
- [ ] packages\docs\src\pages\ui-elements\pagination.vue
- [ ] packages\docs\src\pages\ui-elements\parallax.vue
- [ ] packages\docs\src\pages\ui-elements\popover.vue
- [ ] packages\docs\src\pages\ui-elements\progress-bar.vue
- [ ] packages\docs\src\pages\ui-elements\progress-circle.vue
- [ ] packages\docs\src\pages\ui-elements\radio.vue
- [ ] packages\docs\src\pages\ui-elements\rating.vue
- [ ] packages\docs\src\pages\ui-elements\select.vue
- [ ] packages\docs\src\pages\ui-elements\sidebar-item.vue
- [ ] packages\docs\src\pages\ui-elements\sidebar.vue
- [ ] packages\docs\src\pages\ui-elements\slider.vue
- [ ] packages\docs\src\pages\ui-elements\switch.vue
- [ ] packages\docs\src\pages\ui-elements\table.vue
- [ ] packages\docs\src\pages\ui-elements\tabs.vue
- [ ] packages\docs\src\pages\ui-elements\time-input.vue
- [ ] packages\docs\src\pages\ui-elements\time-picker.vue
- [ ] packages\docs\src\pages\ui-elements\toast.vue
- [ ] packages\docs\src\router\RouterLayout.vue
- [ ] packages\ui\src\components\va-accordion\VaAccordion.demo.vue
- [ ] packages\ui\src\components\va-affix\VaAffix.demo.vue
- [ ] packages\ui\src\components\va-affix\VaAffix.vue
- [ ] packages\ui\src\components\va-alert\VaAlert.vue
- [ ] packages\ui\src\components\va-app-bar\VaAppBar.vue
- [ ] packages\ui\src\components\va-avatar\VaAvatar.vue
- [ ] packages\ui\src\components\va-backtop\VaBacktop.demo.vue
- [ ] packages\ui\src\components\va-backtop\VaBacktop.vue
- [ ] packages\ui\src\components\va-badge\VaBadge.vue
- [ ] packages\ui\src\components\va-breadcrumbs\VaBreadcrumbs.vue
- [ ] packages\ui\src\components\va-breadcrumbs\VaBreadcrumbsItem\VaBreadcrumbsItem.vue
- [ ] packages\ui\src\components\va-button-dropdown\VaButtonDropdown.demo.vue
- [ ] packages\ui\src\components\va-button-dropdown\VaButtonDropdown.vue
- [ ] packages\ui\src\components\va-button-group\VaButtonGroup.vue
- [ ] packages\ui\src\components\va-button-toggle\VaButtonToggle.vue
- [ ] packages\ui\src\components\va-button\VaButton.demo.vue
- [ ] packages\ui\src\components\va-button\VaButton.vue
- [ ] packages\ui\src\components\va-card\VaCard.vue
- [ ] packages\ui\src\components\va-card\VaCardContent.vue
- [ ] packages\ui\src\components\va-card\VaCardTitle.vue
- [ ] packages\ui\src\components\va-checkbox\VaCheckbox-validation.vue
- [ ] packages\ui\src\components\va-checkbox\VaCheckbox.vue
- [ ] packages\ui\src\components\va-chip\VaChip.vue
- [ ] packages\ui\src\components\va-collapse\VaCollapse.vue
- [ ] packages\ui\src\components\va-color-indicator\VaColorIndicator.vue
- [ ] packages\ui\src\components\va-color-input\VaColorInput.vue
- [ ] packages\ui\src\components\va-color-palette\VaColorPalette.vue
- [ ] packages\ui\src\components\va-config\ConfigUsageTest.vue
- [ ] packages\ui\src\components\va-config\VaConfig.demo.vue
- [ ] packages\ui\src\components\va-data-table\VaDataTable.demo.vue
- [ ] packages\ui\src\components\va-data-table\VaDataTable.new.demo.vue
- [ ] packages\ui\src\components\va-data-table\VaDataTable.vue
- [ ] packages\ui\src\components\va-date-input\VaDateInput.demo.vue
- [ ] packages\ui\src\components\va-date-input\VaDateInput.vue
- [ ] packages\ui\src\components\va-date-picker\components\VaDayPicker\VaDayPicker.vue
- [ ] packages\ui\src\components\va-date-picker\components\VaMonthPicker\VaMonthPicker.vue
- [ ] packages\ui\src\components\va-date-picker\components\VaYearPicker\VaYearPicker.vue
- [ ] packages\ui\src\components\va-date-picker\VaDatePicker.vue
- [ ] packages\ui\src\components\va-divider\DividerWithList.vue
- [ ] packages\ui\src\components\va-divider\VaDivider.demo.vue
- [ ] packages\ui\src\components\va-divider\VaDivider.vue
- [ ] packages\ui\src\components\va-dropdown\VaDropdown.vue
- [ ] packages\ui\src\components\va-file-upload\VaFileUpload.vue
- [ ] packages\ui\src\components\va-file-upload\VaFileUploadGalleryItem\VaFileUploadGalleryItem.vue
- [ ] packages\ui\src\components\va-file-upload\VaFileUploadList\VaFileUploadList.vue
- [ ] packages\ui\src\components\va-file-upload\VaFileUploadListItem\VaFileUploadListItem.vue
- [ ] packages\ui\src\components\va-file-upload\VaFileUploadSingleItem\VaFileUploadSingleItem.vue
- [ ] packages\ui\src\components\va-file-upload\VaFileUploadUndo\VaFileUploadUndo.vue
- [ ] packages\ui\src\components\va-form\VaForm-reset.vue
- [ ] packages\ui\src\components\va-form\VaForm.demo.vue
- [ ] packages\ui\src\components\va-form\VaForm.vue
- [ ] packages\ui\src\components\va-hover\VaHover.vue
- [ ] packages\ui\src\components\va-icon\VaIcon.vue
- [ ] packages\ui\src\components\va-image\VaImage.demo.vue
- [ ] packages\ui\src\components\va-image\VaImage.vue
- [ ] packages\ui\src\components\va-infinite-scroll\VaInfiniteScroll.demo.vue
- [ ] packages\ui\src\components\va-infinite-scroll\VaInfiniteScroll.vue
- [ ] packages\ui\src\components\va-inner-loading\VaInnerLoading.vue
- [ ] packages\ui\src\components\va-input\components\VaInputWrapper.vue
- [ ] packages\ui\src\components\va-input\components\VaMessageList\VaMessageList.vue
- [ ] packages\ui\src\components\va-input\components\VaMessageListWrapper.vue
- [ ] packages\ui\src\components\va-input\components\VaTextarea\VaTextarea.vue
- [ ] packages\ui\src\components\va-input\VaInput-validation.vue
- [ ] packages\ui\src\components\va-input\VaInput.vue
- [ ] packages\ui\src\components\va-list\VaList.vue
- [ ] packages\ui\src\components\va-list\VaListItem.vue
- [ ] packages\ui\src\components\va-list\VaListItemLabel.vue
- [ ] packages\ui\src\components\va-list\VaListItemSection.vue
- [ ] packages\ui\src\components\va-list\VaListLabel.vue
- [ ] packages\ui\src\components\va-list\VaListSeparator.vue
- [ ] packages\ui\src\components\va-modal\VaModal.demo.vue
- [ ] packages\ui\src\components\va-modal\VaModal.vue
- [ ] packages\ui\src\components\va-navbar\VaNavbar.vue
- [ ] packages\ui\src\components\va-option-list\VaOptionList.vue
- [ ] packages\ui\src\components\va-pagination\VaPagination.vue
- [ ] packages\ui\src\components\va-parallax\VaParallax.vue
- [ ] packages\ui\src\components\va-popover\VaPopover.vue
- [ ] packages\ui\src\components\va-popup\popup\VaPopup.vue
- [ ] packages\ui\src\components\va-progress-bar\progress-types\VaProgressBar.vue
- [ ] packages\ui\src\components\va-progress-bar\progress-types\VaProgressCircle.vue
- [ ] packages\ui\src\components\va-progress-bar\VaProgressBar.vue
- [ ] packages\ui\src\components\va-progress-bar\VaProgressCircle.vue
- [ ] packages\ui\src\components\va-radio\VaRadio.vue
- [ ] packages\ui\src\components\va-rating\VaRating.vue
- [ ] packages\ui\src\components\va-rating\VaRatingItem\VaRatingItem.demo.vue
- [ ] packages\ui\src\components\va-rating\VaRatingItem\VaRatingItem.vue
- [ ] packages\ui\src\components\va-scrollbar\VaScrollbar.vue
- [ ] packages\ui\src\components\va-select\VaSelect.demo.vue
- [ ] packages\ui\src\components\va-select\VaSelect.vue
- [ ] packages\ui\src\components\va-select\VaSelectOptionList\VaSelectOptionList.vue
- [ ] packages\ui\src\components\va-separator\VaSeparator.vue
- [ ] packages\ui\src\components\va-sidebar\VaSidebar.vue
- [ ] packages\ui\src\components\va-sidebar\VaSidebarItem\VaSidebarItem.vue
- [ ] packages\ui\src\components\va-slider\VaSlider.vue
- [ ] packages\ui\src\components\va-spacer\VaSpacer.vue
- [ ] packages\ui\src\components\va-switch\VaSwitch.vue
- [ ] packages\ui\src\components\va-tabs\VaTab\VaTab.vue
- [ ] packages\ui\src\components\va-tabs\VaTabs.vue
- [ ] packages\ui\src\components\va-time-input\VaTimeInput.vue
- [ ] packages\ui\src\components\va-time-picker\VaTimePicker.vue
- [ ] packages\ui\src\components\va-timeline\VaTimeline.demo.vue
- [ ] packages\ui\src\components\va-toast\VaToast.demo.vue
- [ ] packages\ui\src\components\va-toast\VaToast.vue
- [ ] packages\ui\src\components\va-tree-view\SquareWithIcon\SquareWithIcon.vue
- [ ] packages\ui\src\components\va-tree-view\VaTreeCategory\VaTreeCategory.vue
- [ ] packages\ui\src\components\va-tree-view\VaTreeNode\VaTreeNode.vue
- [ ] packages\ui\src\components\va-tree-view\VaTreeRoot.vue
- [ ] packages\ui\src\services\color-config\ColorCSSVariablesUpdater.demo.vue
- [ ] packages\ui\src\styles\global\color-themes.demo.vue
- [ ] packages\ui\src\styles\grid\SpacingPlaygroud.vue

**Comment by asvae** [comment]
We also need to remove all deprecated mixins after composition api conversion is done.

**Comment by m0ksem** [comment]
Update on this issue:

- [ ] VaChip https://github.com/epicmaxco/vuestic-ui/pull/1668
- [ ] VaTreeView https://github.com/epicmaxco/vuestic-ui/pull/1568 

So after merging this two PRs we can finally remove `vue-class-component`.

**Comment by m0ksem** [comment]
> * [ ]  `VaCollapse`
> 
> 
> Looks like we mistakenly moved to composition API `VaCollapse` in the `docs` instead of the actual component :) [packages/docs/src/pages/ui-elements/collapse.vue](https://github.com/epicmaxco/vuestic-ui/pull/1476/files)
> 
> Also some other components are marked as resolved though they are still using `VueClassComponent`:
> 
>     * [ ]  `VaDropdown`
> 
>     * [ ]  `VaFormReset` (not if we need this one)
> 
>     * [ ]  `VaPopover`

These components are in docs/nuxt-rework :( Sorry.
