### ISSUE TITLE
Test composables

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1399]
That's the most important thing to test as composables have very high reuse value.

We want to test global composables:
- [x] useAlign.ts
- [ ] useArrayRefs.ts - not used anywhere, seems to be outdated.
- [x] useBem.ts
- [x] useClearable.ts
- [x] useColor.ts
- [x] useEmitProxy.ts
- [x] useFocus.ts
- [x] useForm.ts
- [x] useHover.ts
- [x] useKeyboardOnlyFocus.ts
- [ ] useLoading.ts - the only exported function useLoading isn't used anywhere (but useLoadingProps).
- [x] useMaxSelections.ts
- [ ] useResizeObzerver.ts
- [ ] useRouterLink.ts
- [ ] useSelectable.ts
- [x] useSelectableList.ts
- [x] useSize.ts
- [x] useStateful.ts
- [ ] useSyncProp.ts
- [ ] useTimer.ts
- [ ] useValidation.ts

I suggest creating an issue for each hook. + you can split this whole task into multiple mrs for convenience.

**Comment by aluarius** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/1399
