### ISSUE TITLE
Form input control can close  autaomatic validation, so that we can validate form when required

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1400]
**Is your feature request related to a problem? Please describe.**

I checked vuestic doc [https://vuestic.dev/](url),  and didn't found way to disable automatcic validation on form control,  but under some requirement, we don't want to trigger validation automactilly,  and we cannot specify control to trigger validation with specific event.

By currently desgin,   I only found  way to specify  validation state [https://vuestic.dev/en/ui-elements/input#validation-and-error-success-state](url)  manualy,  but with this way we must put validation logic on seperate part which out input control self, not very well.

So sugguest have following ways to control validation with accurately:
- Have way to specify when to trigger validation, like `click` `change`
- Have a property like `automaticValidate`  wiht defualt value `true`

**Comment by asvae** [comment]
Thanks for your report. We'll take a look :).

**Comment by m0ksem** [comment]
Here is immediate prop on VaFrom now https://ui.vuestic.dev/ui-elements/form#named-fields
