### ISSUE TITLE
Form validation doesn't work

### ISSUE THREAD

**Issue by 4000degrees** [epicmaxco/vuestic-ui#1404]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**
1. Add va-form with an input
2. Try formRef.value.validate()
3. Validation is always false, even if inputs don't have rules

**What is the expected behavior?**
Validation works.

**What is the current behavior?**
Form validate() is always false, even if fields are actually valid, or if there are no rules.
Even example copied from the [docs](https://vuestic.dev/en/ui-elements/form#trigger-validation) doesn't work.

**Other information**
Works in vuestic-ui 1.3.1

**Comment by RVitaly1978** [comment]
Fixed in commit https://github.com/epicmaxco/vuestic-ui/commit/8f2b1d7cdaa71c8566a9cf748b4963724f72e901

**Comment by asvae** [comment]
Thanks!
This will be fixed in next release :).
