### ISSUE TITLE
Green banner on the landing page

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#1406]
**Vuestic-ui version:** 1.3.3

On the landing page we have a green banner for stars, how we can improve this?

![image](https://user-images.githubusercontent.com/35342240/148915381-d2b75bae-f026-4077-8781-09c466014e4f.png)

**Comment by asvae** [comment]
Checked stats for date when this was implemented. And I wouldn't call it very significant (star growth rate stays pretty much constant).

Additionally, we had a small release at 12th October (change is 11th october).

![image](https://user-images.githubusercontent.com/5394573/148933704-69bf8b1f-039b-461a-9f5f-83b9b563d912.png)

**Comment by m0ksem** [comment]
Removed
