### ISSUE TITLE
New component: Menu

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#1417]
We have select component and navbar, but don't have menu component.
![image](https://user-images.githubusercontent.com/35342240/149531908-f01ff8df-bf59-4cf5-a1ec-fb66574a53ff.png)

![image](https://user-images.githubusercontent.com/35342240/149531991-90724fab-a876-44a7-a634-366db41f7546.png)

![image](https://user-images.githubusercontent.com/35342240/149532963-37eed34d-9c57-4441-b114-c23cad4fb6ae.png)

**Examples:** 

https://vuetifyjs.com/en/api/v-menu/
https://material.io/components/menus
https://www.primefaces.org/primevue/showcase/#/menu

Acceptance Criteria: 
- [ ] Menu component should have double wrapping functionality

![image](https://user-images.githubusercontent.com/35342240/149532675-80ad13cf-da1c-49dc-8739-05ad596fc91b.png)

- [ ] Component should include button with icon

- [ ] Menu Item should include left and right icons 

![image](https://user-images.githubusercontent.com/35342240/151320788-1bf4c549-778b-49d7-bc4a-ed6d6c707032.png)

- [ ] we need props for: disabled, position, activator slot, alighment, close delay, close on click outside, close on content click, content-class, disable keybord, render on mounted, max and min sizes, offset-overflow, open on click / on focus / on hover, transition, z-index, value, rounded

- [ ] input event

- [ ] activator and default slot

**Comment by pogrib0k** [comment]
I can try it.
