### ISSUE TITLE
TimeInput ampm changes format only in input filed, but picker use 24h format

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1419]
**Vuestic-ui version:** 1.3.3

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/23530004/149541614-b822747c-e1f3-4d97-a33c-be1757bef73b.png)
![image](https://user-images.githubusercontent.com/23530004/149541660-3817a882-734b-4650-bd30-97cd7473e667.png)

**Other information**

Probably fixed here: https://github.com/epicmaxco/vuestic-ui/pull/1383

**Comment by asvae** [comment]
We can check this after the merge.
