### ISSUE TITLE
Optional services

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1426]
We need a way to separate Core services from Optional services.

Requiremets:
* Core services have to be included if you use vuestic-ui. So they stay as they are now (globally imported).
* For optional services we should have a way to disable them.

The way I see it is:
* We provide `VuesticPlugin` import, that inludes all services (if user doesn't care and wants all features).
* We give user a way to have partial imports for whatever they need.

We can steamline Optional services handling in context of this issue

- [ ] Documentation should be updated to showcase which services are optional, and which are not.
- [ ] Installation docs should be also updated to showcase 2 ways of import + have a list of services.

**Comment by m0ksem** [comment]
I think it closed in https://github.com/epicmaxco/vuestic-ui/pull/1530
