### ISSUE TITLE
New Component: Page layout

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#1430]
# Layout components

General requirements:

- [ ] Mobile first.
- [ ] Adaptivity and responsivity.
- [ ] Independent nested components.
- [ ] Themeable.
- [ ] Customizability.
- [ ] Semantic markup, by default need to use the `header`, `main`, `aside` and `footer` HTML tags.
- [ ] Keep in mind that web also have the RTL and LTR reading and writing directions.
- [ ] CLI to generate ready layouts for the views.
- [ ] Documentation
- [ ] Tests
- [ ] Implement wireframes, ready to use examples (auth forms, simple admin panel).

## Features
- [ ] Layout builder (constructor), [example](https://quasar.dev/layout-builder).

### VaApp (VaLayout)

Component wrapper for the placing child components: `VaHeader`, [`VaSidebar`](https://vuestic.dev/en/ui-elements/sidebar) (implemented), `VaMain` и `VaFooter`).

### VaHeader
App header, can be used for the navigation.

Requirements:
- [ ] Should be placed on the top.
- [ ] Sticky on the scroll.
- [ ] Collapsible.
- [ ] Hide/show on the scroll.

### VaMain

For the router view.

### VaFooter

App footer, can be used for the navigation.

Requirements:
- [ ] Should be placed on the bottom.
- [ ] Sticky on the scroll.
- [ ] Collapsible.
- [ ] Hide/show on the scroll.

**Comment by asvae** [comment]
Found an article regarding modern layouts: https://ishadeed.com/article/rebuild-featured-news-modern-css/

**Comment by zvenigorodskaia** [comment]
![Image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/1ea75caf-2953-49ea-aa02-189e4458aed0)

**Comment by asvae** [comment]
We have a very small issues:


![Image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/b7a939b1-81c8-4abc-90aa-cb253f5a06dd)
