### ISSUE TITLE
bug on web site doc

### ISSUE THREAD

**Issue by musashiM82** [epicmaxco/vuestic-ui#1433]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**
* go to https://vuestic.dev/en/ui-elements/modal
* click on "show code"
* error in console: TypeError: Cannot read properties of undefined (reading '$t')

**What is the expected behavior?**
example code is shown

**What is the current behavior?**
example code is not shown

**Other information**

**Comment by wyhfrank** [comment]
I wonder whether there is a temporary solution to this bug? 
E.g., Is there a github repo that stores the example code? where we can view the source code directly.

**Comment by CheIIau** [comment]
It's not only Modal section actually. It's every 'show code' button on the site

**Comment by m0ksem** [comment]
> I wonder whether there is a temporary solution to this bug? E.g., Is there a github repo that stores the example code? where we can view the source code directly.

All examples are stored in docs package.

[Source code on Github](https://github.com/epicmaxco/vuestic-ui/tree/develop/packages/docs/src/page-configs/ui-elements/modal/examples)
[Github.dev](https://github.dev/epicmaxco/vuestic-ui/tree/develop/packages/docs/src/page-configs/ui-elements/modal/examples/Overview.vue)
