### ISSUE TITLE
It should have a way to  use toast component in specific method, service easier under Typescript

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1436]
**Vuestic-ui version:** 1.3.3

**Steps to reproduce**
I'm trying to use taost component after some async operation (request api) did success, but from the document, it seems have no simple way to simply use global variable `$vaToast` under typescript, i checked existing issue regarding toast component, there's no regarding's.

**What is the expected behavior? **
Add global variable which other Vue ui framwork did like 
[https://element-plus.org/en-US/component/notification.html#with-types](url)
```javascript
import { ElNotification } from 'element-plus'

ElNotification({
  title: 'Success',
  message: 'This is a success message',
  type: 'success',
})
```

**What is the current behavior?**

Currently i used toast like this in my code, but not good style for typescript:
```javascript
function toast(config: any) {
      if (app) {
        const vaToast = app.appContext.config.globalProperties.$vaToast
        vaToast.init(config)
      }
    }
```

**Other information**

**Comment by asvae** [comment]
@m0ksem can you elaborate on this? Not sure if it's up for implementation.
