### ISSUE TITLE
`next` documentation

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1439]
Currently production documentation is generated from `master`. That's not ideal, as we sometimes want to seed docs for recent version.

Here's a vue bootstrap implementation, and it looks like something we need.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/5394573/174547279-3333277a-93c5-4e7a-83bf-31a51822d8a0.png">

-----

* Could be implemented via circleci or/and github actions.
* Idea is to keep docs synced with current version. Then have next for early adopters.
* Syncs nicely with #1444 (maybe you could work on both at the same time)

Discussed in [this](https://www.notion.so/epicmax/Vuestic-1912bb453cee4ae1a2071dd03e291160?p=5b80098279fe419a8bb548c423ad63f1) meeting.

Also see https://github.com/epicmaxco/vuestic-ui/issues/767

**Comment by m0ksem** [comment]
develop.vuestic.dev solves it
