### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#145]
#68  Docs
- [ ] Do after docs boilerplate (#17) is done.

## Props
- [ ] `open-delay: Boolean`

## Slots
- [ ] `key` - some text

## Events
- [ ] `key` - some text

## Transitions
- [ ] 

## Design
- [ ]

## Notes
- [ ] 

# Refs
* [Vuetify](https://vuetifyjs.com)
* [Quasar](https://quasar.dev)
* [Ant Design](https://ant.design)
* [iView](http://iview.talkingdata.com)
* [Element UI](https://element.eleme.io)

**Comment by Kushich** [comment]
@asvae We have a [va-popover](http://vuestic-ui-demo.sub.asva.by/#/demo/vuestic-components/va-popover/VaPopover.demo.vue) component that does the same
