### ISSUE TITLE
Create useRouterLink hook to replace RouterLinkMixin

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [epicmaxco/vuestic-ui#1461]
We need to create useRouterLink hook to be used instead of existing RouterLinkMixin, however current RouterLinkMixin depends on options API to detect vue-router and nuxt plugins (it checks if plugin property exists in global context). Also both of those libs can be used with hooks instead of being setup as plugin so we need some other way to detect them instead of checking for plugin property in global context.

**Comment by m0ksem** [comment]
You could try to use `getCurrentInstance` from 'vue' and try to find nuxt plugin in global properties. same as we have ugly solutions for VaToast plugin. https://github.com/epicmaxco/vuestic-ui/issues/825#issuecomment-852888700


If that does not work, you could try to safely resolve nuxt package using `require.resolve` [(Example)](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-jest/presets/typescript/jest-preset.js). But I don't know how it would work with UMD, IFFE modules.
