### ISSUE TITLE
Tabs docs don't have a content slot usage example

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1466]
https://vuestic.dev/en/ui-elements/tabs

Usually, I and other people look at examples first. It's hard to notice that we actually have a slot for content.

Also, looks like the `va-tab-content` component is missing. (https://github.com/epicmaxco/vuestic-ui/issues/285)

Looks like users need to handle current tab content manually. https://github.com/epicmaxco/vuestic-ui/issues/1362#issuecomment-1024251042

**Comment by rustem-nasyrov** [comment]
> Also, looks like the va-tab-content component is missing. (https://github.com/epicmaxco/vuestic-ui/issues/285)

I think this won't fit with the current issue and it needs to be separated to the new issue.
