### ISSUE TITLE
Vuestic UI website tweks

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#1478]
- [x]  increase the default `p` font size to 1.2rem (not 1.1 rem)
- [x]  `seamless__subtitle` margin-top: 1 rem (not 3 rem)
- [x]  `seamless__subtitle` font-size: 1.2 rem (not 1.1 rem)
- [x]  `customize__subtitle` padding-top: 1 rem (not 3 rem)
- [x]  `customize__subtitle` font-size: 1.2 rem (not 1.1 rem)
- [x] `opensource__text` font-size: 1.2 rem (not 1.1 rem)
- [x]  `opensource__text` line-height: 1.5 (not 1.5 rem)
- [x]  `opensource__title` padding-bottom: 1 rem (not 1.7 rem)
- [x] `admin__subtitle` font-size: 1.2 rem (not 1.1 rem)
- [x]  `admin__subtitle` padding-top: 1 rem (not 1.5 rem)
- [x]  `admin__subtitle` line-height: 1.5 
- [x]  `item__title` font-size: 1.2 rem (not 1.1 rem)
- [x]  `item__title` line-height: 1.5 (not 1.8 rem)
- [x]  `footer__subtitle` font-size: 1.2 rem (not 1.1 rem)
- [x]  `footer__subtitle` line-height: 1.5
- [x]  set primary colour to #2550C0 (not #4382D9)
- [x]  navbar: `overview` should be `black` on the landing page
- [ ]  navbar: language dropdown label font-weight: 600 (not 700)
- [x]  navbar: fix language dropdown select position (close to the parent menu item)
- [x]  navbar: `Docs` menu items should lead to Introduction > Overview (https://vuestic.dev/en/introduction/overview) (not to the roadmap)

**Comment by Derranion** [comment]
Thanks @xx13

Could you tell are we sure that we want this?:

- [ ] navbar: language dropdown label font-weight: 600 (not 700)

Because it will look this way:

![600languageFont](https://user-images.githubusercontent.com/7745899/161278640-7e9c2893-4c9c-4e04-a1ad-34dc2ddb3f57.jpg)

Language text will be lower in size than the `version number` (from the left).

**Comment by Derranion** [comment]
Our current primary color is #2C82E0 which is close to #4382D9

Do we want to change it?

`- [ ]  set primary colour to #2550C0 (not #4382D9)`

**Comment by xx13** [comment]
@Derranion 
- navbar font weight should be `600` for every item: the ones with icons and for dropdown selects. now it's `700` and it should be fixed for **both navigations:** Vuestic Home and Vuestic Docs.
- primary colour should be `#2550C0` in any case ^^
