### ISSUE TITLE
color helpers

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#148]
Initial idea is to add some color helpers, like `text-danger`, `text-primary`. But we can probably add some other things as we go. I.e. background color.

- [x] Check other framework solutions in regards to naming. We want standard approach. Replace naming sсheme if you think something else works better.
- [x] `color-[color]` for all theme colors - example: `color-danger`
- [x] `bacground-[color]` for all theme colors - example: `background-danger`.
- [x] Implementation should be similar to what is done for [epic-spinners](https://github.com/epicmaxco/epic-spinners) colors. There style block is injected in body initially, then dynamically overriden each time we have a change.
- [x] color helpers should be independent of components (separate system/plugin).

**Comment by Mikkou** [comment]
https://github.com/epicmaxco/vuestic-ui/pull/169
