### ISSUE TITLE
Date picker could support actions

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1480]
As a framework user for range date picker, I want to easily select ranges. I.e.:
* next month/week
* previous month/week
* maybe some other ways?

Unclear how we want to do this and what's the priority.

**Comment by asvae** [comment]
Needs examples and investigation.

**Comment by aluarius** [comment]
Examles of usage in popular services:

- Partner Yandex
![](http://joxi.ru/v29elwsZvDEE2G.jpg)

- Luckyads.pro
![](http://joxi.ru/bmoQVNS38eNQAy.jpg)

- Leads.su
![](http://joxi.ru/krDeDKsKlqMzmp.jpg)

Exmaples from other UI Frameworks:

- https://element.eleme.io/#/en-US/component/date-picker
![](http://joxi.ru/Y2LL0xh7lzw426.jpg)
Implemented by props -> user options array (close to the variant with slots).
![](http://joxi.ru/eAOa1yF9zVw3mo.jpg)

- https://bootstrap-vue.org/docs/components/calendar#default-slot
![](http://joxi.ru/bmoQVNS38eMQAy.jpg)
![](http://joxi.ru/V2VkKMTdQR0NAv.jpg)
Implemented by named slots.

**Comment by asvae** [comment]
@xx13 can you check if we can have design for that?

**Comment by aluarius** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/2148
