### ISSUE TITLE
Codesandbox doesn't work too well

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1481]
![image](https://user-images.githubusercontent.com/5394573/152420093-7956cdef-a4b4-442d-aa35-b25f46945e3f.png)

![image](https://user-images.githubusercontent.com/5394573/152420262-0c71ea5b-380f-4192-88c6-94310c0daada.png)

When you open codesandbox - things seem to work well, but after any change - it throws an error.

Reported by genius programmer @Lemonka93 🥇 .

**Comment by asvae** [comment]
Seems to be fixes

**Comment by m0ksem** [comment]
Can be closed, I think.
