### ISSUE TITLE
Normalize.css -styles should be better scoped

### ISSUE THREAD

**Issue by anttimateria** [epicmaxco/vuestic-ui#1489]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
Add any Vuestic component to a page or register library globally, and you see `normalize.css`-styles applied globally, which is not desired:

![Screenshot 2022-02-07 at 12 54 01](https://user-images.githubusercontent.com/18732832/152934018-522fc3c3-da78-4600-9a9f-feba88cdb075.png)

**What is the expected behavior?**

The normalized styles should apply only to Vuestic-components i.e. they should be **scoped**. 

**What is the current behavior?**
`normalize.css`-styles are applied globally, which might override/conflict some other page styles.

**Other information**

**Comment by m0ksem** [comment]
Changing 
```ts
import 'vuestic-ui/dist/vuestic-ui.css'
```

to

```ts
import 'vuestic-ui/dist/styles/essentials.css'
import 'vuestic-ui/dist/styles/grid/grid.css'
import 'vuestic-ui/dist/styles/resources/typography.css'
```
should make a trick. 



For new project, you can use `vue add vuestic`, use treeshaking and unselect `Normalize CSS` option in prompts.

**Comment by asvae** [comment]
We have do document this, as far as I see users won't have a way to know we have that functionality in place already.

Further development on optional/core is [here](https://github.com/epicmaxco/vuestic-ui/issues/1426), we plan to tackle it next milestone.
