### ISSUE TITLE
[va-datatable] should support fixed header which AG grid supported

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1492]
**Vuestic-ui version:** 1.3.4

**Comment by asvae** [comment]
Thank you.
We have [AG Grid wrapper](https://vuestic.dev/en/extensions/ag-grid) if you need BIG POWER from your data table. :)

@smellyshovel is it possible to do so, or that's too much for our data-table?

**Comment by smellyshovel** [comment]
@asvae isn't that achievable with plain CSS? If we don't consider cases when the horizontal scrolling is needed.
