### ISSUE TITLE
va-data-tabel loose selected items on filtering, when those are not in the result

### ISSUE THREAD

**Issue by ralpheichelberger** [epicmaxco/vuestic-ui#1493]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
go to https://vuestic.dev/en/ui-elements/data-table#pagination

Pagination example has selection and filter too:

at the example for pagination select on and filter for a different line (e.g. select Antonette and  type "Sam" in the filter field)
you will loose the selection BUT you wont loose selection if you type "Ant" - so the behaviour isn't really be intended, or is it?

**What is the expected behavior?**
selected items is a v-model array and should be manipulated via script only 

on filtering, selected item should stay selected, please!

**What is the current behavior?**
selection of item, that are not in the filtered result are lost

**Other information**
![Peek 2022-02-09 10-32](https://user-images.githubusercontent.com/34127607/153167169-ce28b8b4-cbe7-4e23-8d92-66514672e677.gif)
![Peek 2022-02-09 10-33](https://user-images.githubusercontent.com/34127607/153167172-503876c7-1c44-4017-b9ab-2dd623307fbc.gif)

**Comment by asvae** [comment]
Thanks. You're absolutely right and that's not intended!

**Comment by asvae** [comment]
- [ ] Would be nice to have some explanation in notion in context of this task implementation.
