### ISSUE TITLE
contextual popover on right click

### ISSUE THREAD

**Issue by ralpheichelberger** [epicmaxco/vuestic-ui#1494]
**Is your feature request related to a problem? Please describe.**
I like to provide a simple context popover in e.g. my va-data-tabel that shows more info, options with buttons, etc.

**Describe the solution you'd like**
Similar to the default context menu of e.g. chrome, it would open a popover starting at the postion of the mouse, or where it is in the viewport.
This could be done in the same way va-popover is designed by wraping the content of that "context-popover".

I imagine this component like this:

```vue
<template>
  <va-context-popover
    color="primary" 
    text-color="white"
    title="Product options"
  >
    <va-button>
        @click="doOption1">
            Option 1
    </va-button>
    <va-button>
        @click="doOption1">
            Option 1
    </va-button>    
  </va-context-popover>
</template>
```

So it is basically a popover but positioned where you right click the mouse and is space on the viewport.

**Comment by asvae** [comment]
Thanks. Interesting.

Thinking if we can reuse existing popover, while adding `anchor="cursor"` slot or something similar.

**Comment by ralpheichelberger** [comment]
Hey! How are you guys! Are you considering to add this feature some time soon?

**Comment by asvae** [comment]
Would be great for mini release after we're done with current one.
