### ISSUE TITLE
Could we add asterisk after label for form control if we want controls be required.

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1497]
**Is your feature request related to a problem? Please describe.**

With the current version, if we want to mark the specific control required, we can add prop `message` to achieve it, but let us think about that, in most scenarios, we just want to let user know the specific control is required without hint message. 

**Describe the solution you'd like**
We should let control have ability add asterisk after label if we want the control to be required.
![image](https://user-images.githubusercontent.com/22833218/153319372-d50443d1-62e4-4445-b969-fa584801e6f1.png)

**Comment by asvae** [comment]
As a minimum we can do asterisk of label color. Not sure about red asterisk.

@xx13 your thoughts?

**Comment by asvae** [comment]
We decided to go with red asterisk. Should use danger css -> required-asterisk local for input variable, not prop.
- [ ] We need to check other components with similar behavior
- [ ] Probably docs should be fine, but we can double check.
