### ISSUE TITLE
Add exports to package.json

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1503]
Example
```json
  "exports": {
    ".": "./dist/index.mjs",
    "./styles": "./dist/styles/"
  },
```

It's annoying to import `vuestic-ui/dist/styles/essential.css`

should be `vuestic-ui/styles/essential.css`

**Comment by xiongmao86** [comment]
Hi, @m0ksem, I have `yarn build` and find dist I built is inside `package/ui/` should I change the path accordingly?

I also have question: is this exports used for developer or consumer of vuestic-ui?

**Comment by m0ksem** [comment]
> Hi, @m0ksem, I have `yarn build` and find dist I built is inside `package/ui/` should I change the path accordingly?
> 
> I also have question: is this exports used for developer or consumer of vuestic-ui?

Hi. This is exports for consumer of vuestic-ui.

If you take a look at vuejs/core [package.json](https://github.com/vuejs/core/blob/main/packages/vue/package.json) you will se, that you can easily import server-renderer
Because of
```json
    "./server-renderer": {
      "import": "./server-renderer/index.mjs",
      "require": "./server-renderer/index.js"
    },
```

so import will be

```ts
import { SSRContext } from 'vue/server-renderer'
```

While actual file is under 'vue/server-renderer/index.mjs'
