### ISSUE TITLE
"Form.Validate" stopped validation after first invalid control detected.

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1504]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
the demo between docs and codesandbox have different behaviors: 
[https://vuestic.dev/en/ui-elements/form#trigger-validation](https://vuestic.dev/en/ui-elements/form#trigger-validation)
[https://codesandbox.io/s/7ru9i?file=/src/App.vue](https://codesandbox.io/s/7ru9i?file=/src/App.vue)

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

**Comment by RVitaly1978** [comment]
Was fixed in [PR1472](https://github.com/epicmaxco/vuestic-ui/pull/1472)
