### ISSUE TITLE
VaAffix element is null

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1521]
In vue book (demos) after changing the page from VaAffix to some other page have error 
![image](https://user-images.githubusercontent.com/23530004/154865876-61f88d55-0524-4634-bbc7-cf048657da20.png)

**Comment by syahrizalxs** [comment]
I do some debugging for this issue, and I found this bug caused by the onBeforeUnmount lifecycle
![image](https://user-images.githubusercontent.com/47208687/154912203-0443597a-5d63-48a3-b981-f6d9ae6d023f.png)
