### ISSUE TITLE
VaConfig prop for most of the components

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1527]
We want our components to have `va-config`  or `config` or `components-config` props, that will work as `va-config` component. This must be made using some composition hook.

For example we want to have date-picker for blind person. 👓
```vue
<va-date-picker components-config="{ VaIcon: { size: 'large' }  }" />
```

As we discussed:
We can conditionally wrap in VaConfig component for now. Then we can improve this solution as prototype becomes more mature.

**Comment by asvae** [comment]
@m0ksem interesting, but also looks not really important right now. Do you have cases where this functionality is mandatory?

**Comment by m0ksem** [comment]
This could be helpful in VaCounter. For example, instead of using slots user can just provide config for VaButton and VaInput. This would be great to see after we move from withTransportConfig.

**Comment by Derranion** [comment]
`va-config` wrapper could be easy solution, check it

**Comment by asvae** [comment]
We probably don't need this for components without internal components.

But probably easier for us to implement for all components indiscriminately.

**Comment by m0ksem** [comment]
I think headless VaConfig component solves this issue now.
