### ISSUE TITLE
"Rules" not works for va-data-input

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1529]
**Vuestic-ui version:** 1.3.4
Sandbox for reproduce: 
[https://codesandbox.io/s/dank-https-ew2p9f](https://codesandbox.io/s/dank-https-ew2p9f)

BTW,  Should we add some unit testing to ensure the basic feature works always? I very much appreciate your great efforts.  but we need a stable version to release to our PROD environment with Vuestic UI,  and that will give us the confidence to use Vuestic UI in other projects.  and also I want to ask how's the plan to release the next version?

**Comment by m0ksem** [comment]
VaDateInput has never supported rules prop. We have only validation for VaTimeInput. It's actually not a basic feature, but would be nice to become. So we need to support rules prop in VaDateInput, VaSelect, and any other inputs as well.

We have milestones that determine release dates. I believe we will release a new version periodically in near future. We working on it.

**Comment by wossig** [comment]
> VaDateInput has never supported rules prop. We have only validation for VaTimeInput. It's actually not a basic feature, but would be nice to become. So we need to support rules prop in VaDateInput, VaSelect, and any other inputs as well.
> 
> We have milestones that determine release dates. I believe we will release a new version periodically in near future. We working on it.

Thanks for your response, I have a question, will VaDateInput support rules in future, from my requirement, I just want to make the date field required, is there other alternate solution for it? 

From my understanding, it should be basic feature, it will be good to explain your though on it.

**Comment by m0ksem** [comment]
> > VaDateInput has never supported rules prop. We have only validation for VaTimeInput. It's actually not a basic feature, but would be nice to become. So we need to support rules prop in VaDateInput, VaSelect, and any other inputs as well.
> > We have milestones that determine release dates. I believe we will release a new version periodically in near future. We working on it.
> 
> Thanks for your response, I have a question, will VaDateInput support rules in future, from my requirement, I just want to make the date field required, is there other alternate solution for it?
> 
> From my understanding, it should be basic feature, it will be good to explain your though on it.

Yep. This must be easy to implement feature. We will try to implement it in next release. (this week)

**Comment by asvae** [comment]
We can handle this with priority after release.
