### ISSUE TITLE
Remove target props from va-parallax demo

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1532]
Let's change the DOCS page layout and make the body a scrollable container.

![image](https://user-images.githubusercontent.com/23530004/155356155-e0787253-6cb0-4bd8-8d6a-4b226faea2e8.png)

**Comment by asvae** [comment]
What's the point of making body scrollable? (apart from these selectors being a tad clearer)

**Comment by m0ksem** [comment]
For now, we have .base-layout__content our scroll container. Because of that, we need to specify target for all VaParallax components.

We could actually use a global config for that! The it will make Parallax demo cleaner.

**Comment by m0ksem** [comment]
Simply set target prop globally via GlobalConfig

**Comment by m0ksem** [comment]
Fixed somewhere.
