### ISSUE TITLE
Move from rollup to vite

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1545]
Since [rollup-plugin-vue](https://github.com/vuejs/rollup-plugin-vue#archived) is no more maintainable, let's move to vite and [@vite/plugin-vue](https://github.com/vitejs/vite/tree/main/packages/plugin-vue).

Should be easy to change bundler after v1.4.0 - this release makes vuestic work with nuxt's vite. Also would be nice to move demos to vite too and remove webpack from source code,

Remember we have bundlers-test package that test project for both vite and webpack. After this FR is complete, we can also remove vite from tests, because it will be used in demos and docs.

**Comment by Derranion** [comment]
Yeah and we can also use the same `demo` inside our `bundlers tests`.
