### ISSUE TITLE
should not use !important style in va-sidebar to set content-wrap margin-left value

### ISSUE THREAD

**Issue by SgtDaJim** [epicmaxco/vuestic-ui#155]
* **I'm submitting a ...**
  - [ ] bug report

> https://github.com/epicmaxco/vuestic-ui/blob/7314d580cdf4ae5930b0cb4662fd32eb2b382bee/src/components/vuestic-components/va-sidebar/VaSidebar.vue#L81

In my opinion, !important style is unreasonable in the above code. The user cannot override it when they need to. For example, I want to make the sidebar fully hidden on mobile device, so i override the minimized style. But the margin-left of content-wrap is unchangable and it is nonsense.

**Comment by SgtDaJim** [comment]
And additionally, I think the sidebar should be fully hidden on mobile device instead of minimized.

**Comment by asvae** [comment]
Makes sense. Thanks.
