### ISSUE TITLE
Nuxt plugin (nuxt module?)

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1553]
VuesticNuxtModule must:
- [ ] Register required CSS, fonts etc.
- [ ] Be customizalbe (e.g. user can remove typography, grid etc.)
- [ ] Register globally composables
- [ ] Have basic app.vue template.

**Comment by aluarius** [comment]
Closed due to https://github.com/epicmaxco/vuestic-ui/pull/1716
