### ISSUE TITLE
Button dropdown content overlaps button

### ISSUE THREAD

**Issue by misterpekert** [epicmaxco/vuestic-ui#156]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Content of the button dropdown component is incorrectly positioned when button is positioned at the bottom of a container
* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
![screenshot](https://user-images.githubusercontent.com/11361743/72334243-0a2b6380-36ce-11ea-9752-31b01970c5a1.png)
* **What is the expected behavior?**
Dropdown content should be overlap a button
* **What is the motivation / use case for changing the behavior?**
Current behavior prevents user of seeing the button he has clicked

**Comment by Derranion** [comment]
Was not able to reproduce, looks like this issue was resolved already in the recent patches.
