### ISSUE TITLE
`<va-date-input />` shouldn't expect `va-icon` to be registered globally.

### ISSUE THREAD

**Issue by scythianfeather** [epicmaxco/vuestic-ui#1560]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
Load a simple app, with an entry point that looks like this:
```
import { VuesticPluginsWithoutComponents } from 'vuestic-ui';
//import { VaIcon } from 'vuestic-ui';
import 'vuestic-ui/dist/styles/essential.css';

createApp(App)
    //.component('va-icon', VaIcon)
    .use(VuesticPluginsWithoutComponents)
    .mount('#app');
```
And an App.vue like this:
```
<template>
  <va-date-input />
</template>

<script>
import { VaDateInput } from 'vuestic-ui';

export default {
  name: 'MyComponent',
  components: {
    VaDateInput,
  }
}
</script>
```

**What is the expected behavior?**
`<va-date-input />` shouldn't expect `va-icon` component to be registered globally.

**What is the current behavior?**
Console message, `[Vue warn]: Failed to resolve component: va-icon`

**Other information**

**Comment by m0ksem** [comment]
Thanks! This issue likely have been fixed in develop branch. Will close this issue on release.
