### ISSUE TITLE
`left-icon` prop has no effect on `<va-date-input>`

### ISSUE THREAD

**Issue by scythianfeather** [epicmaxco/vuestic-ui#1561]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**
`<va-date-input left-icon>`

**What is the expected behavior?**
Calendar icon is displayed on left side of input instead of right.

**What is the current behavior?**
Calendar icon remains on the right, which is the default behavior.

**Other information**

**Comment by aluarius** [comment]
Can't reproduce problem, seems it's already fixed.
