### ISSUE TITLE
Cannot apply other icons except material-icons

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1563]
**Vuestic-ui version:** 1.3.4
![image](https://user-images.githubusercontent.com/22833218/158377384-975372bb-f0ea-4fc2-9752-1a98122f2856.png)

[https://codesandbox.io/s/9msnz?file=/src/App.vue:87-101](https://codesandbox.io/s/9msnz?file=/src/App.vue:87-101)

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

**Comment by asvae** [comment]
@wossig is that only for codesandbox demo or did you encounter this in your app as well?
