### ISSUE TITLE
Modal exit animation is gone :<

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1570]
**Vuestic-ui version:** 1.3.4

**Steps to reproduce**

Go to https://vuestic.dev/en/ui-elements/modal#base-layout

**What is the expected behavior?**

Seeing closing animation

**What is the current behavior?**

Not seeing closing animation

**Other information**

Closing animation was there before, I'm pretty sure.

**Comment by xiongmao86** [comment]
After d6fe093b35c4eeab044b66a89ff25248cecca8c3, closing animation disappear.

**Comment by xiongmao86** [comment]
`@before-close` and `@close` doesn't emit.
`@before-open`, `@open`, `@update:model-value`, `@ok`, `@cancel` callbacks is call when emit.
