### ISSUE TITLE
VaParallax target prop must be undefined 

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1572]
By default, its emtpy string, is used in querySelector. So querySelector by '' throws error. If there is no string, let's use document.body. 

Think about ssr, if there is no document component must work.

**Comment by Sync271** [comment]
Can I work on this?

**Comment by m0ksem** [comment]
> Can I work on this?

Sure, thanks for your effort 😊

**Comment by m0ksem** [comment]
Closed in https://github.com/epicmaxco/vuestic-ui/pull/1621. Thanks!
