### ISSUE TITLE
Fix nuxt-docs issues

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1577]
I updated https://github.com/epicmaxco/vuestic-ui/tree/docs/nuxt-rework so now it should show all of our docs demos. Please, have a look and help me find issues with vuestic-ui components (docs we can discuss later).

# Issues related to nuxt (high priority)
1. [x]  vue-class-component computed do not react on state changes
For example. VaParallax has opacity: 0 when image is not loaded. State changes isLoaded === true, but computed still the same.
Moving ALL components to composition api could save us: https://github.com/epicmaxco/vuestic-ui/issues/1397
1. [x] Investigate landing bugs:
    - [x] VaInput gets focus when you click anywhere.
1. [x] VaToast instance is not creating in docs demo @m0ksem 
1. [x] VaSlider broken transition.
1. [x] VaTabs - no default value and clicks doing nothing @rustem-nasyrov 

Search for more bugs and add them to this list! 
Also, tell me about memory leaks - is them exists or it just me?

# Issues related to new docs (can be done later after release)
1. [ ] Look on page-configs - especially on comments. I probably commented something to get it work.
1. [ ] Think again about manul api, @m0ksem child components manual api property?
1. [ ] Fix ag-grid page-config @m0ksem 
1. [ ] Remove temporal TODO page-configs, use components from old docs.
1. [ ] Create a beautiful loader for examples! (steal from here https://epic-spinners.epicmax.co/ hehehe)

**Comment by Derranion** [comment]
- [ ] Doesn't launch on windows - commands are made for Linux

**Comment by Derranion** [comment]
- [ ] Examples code font is harder to read and not formatted. (low priority)

![codeFontAndAlignment](https://user-images.githubusercontent.com/7745899/159477577-0c286ee3-e101-4807-8ac4-28800909a217.jpg)

**Comment by m0ksem** [comment]
> - [ ] Some of the `default` values are now missing in the `Api` -> `Props`
> 
> ![someDefaultValuesAreMissing](https://user-images.githubusercontent.com/7745899/159490953-1981e1c3-ee92-4461-9e9d-0e1d77217e12.jpg)
> 
> 

Can confirm that. This props should been inherited from VaInput, but I skipped this for now.

**Comment by Derranion** [comment]
- [ ]  Some of the `Event types` are now missing in the `Api` -> `Events` table

 
![someEventTypesAreMissing](https://user-images.githubusercontent.com/7745899/159492324-543e3a50-4f9e-4100-9694-108d275564c4.jpg)

**Comment by Derranion** [comment]
- [ ] Icons are smaller in size than before

![iconsSmallerInSize](https://user-images.githubusercontent.com/7745899/159591550-a0a33f29-0b21-4d03-aa9a-d5c6c3906eb0.jpg)

**Comment by Derranion** [comment]
- [ ] Clicking on `Select` scrolls down and focuses different select, instead of the selected one.

Could be tested here ...`ui-elements/select`

**Comment by Derranion** [comment]
- [ ] Accordion on click behavior

Steps to reproduce:

1. Open basic usage of accordion
2. Click on first collapse
3. Click on second collapse

Result:
Second collapse will not be opened and will require second click to open it.

Expected behavior:
Clicking on second collapse should close the first one and open second one immediately.

![accordionBaseUsageOnClickBehavior](https://user-images.githubusercontent.com/7745899/159906081-08c75f88-3225-4f95-a949-c62f62315e08.jpg)

**Comment by asvae** [comment]
We probably want to check what is already done before hoping on that + mergin all ongoing works.

**Comment by asvae** [comment]
Connected to #650 and closing.
