### ISSUE TITLE
License pre 1.0.0

### ISSUE THREAD

**Issue by dschmidt** [epicmaxco/vuestic-ui#1583]
The LICENSE[.MD] file was only introduced in dc5221bf6b279759b53086ce45e6c2dd43c679c6 for version https://github.com/epicmaxco/vuestic-ui/tree/v1.0.0-rc.1.

Can older releases be considered to be released under that version as well?

**Comment by asvae** [comment]
Can you explain your case a bit? Not sure I follow. :)

**Comment by asvae** [comment]
Yes, you can consider all early version to be MIT licensed.

I hope my response in this issue is enough (given I'm a vuestic-ui lead 😁).

If it's not - please reopen this issue and we'll think of something (like `0.1.8-mit` version).

**Comment by dschmidt** [comment]
Thanks a lot, yes, I hope this is enough for now.

We will reevaluate upgrading asap anyhow, thanks again!
