### ISSUE TITLE
Composables refactoring

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1584]
Let's spend some time on composables improvements.

- [ ] Having tests and some readmes for complex composables.
- [ ] Move service composables to composables directory
- [ ] Move component specific composables to components folder if it used ones. (useSelections, useAlign e.g.)
- [ ] Rename hooks directories to composables.
- [ ] Move composables outside from mixins directory.
- [ ] Remove old mixin composables... Like useLoading or useColor.
- [ ] Composables that are located in services folder should be moved to composables folder.

**Comment by LighthouseKeeperYN** [comment]
> useSyncProp vs useStateful? This two makes the same thing in different ways.

useStateful seems to handle boilerplate of if statement for the most part. We'll have to move said boilerplate to either components, or useSyncProp, neither of which looks like a good idea.

**Comment by LighthouseKeeperYN** [comment]
> https://github.com/epicmaxco/vuestic-ui/issues/1576 🤔
Definitely not. Providing props manually comes with typechecking. I already lost count how many times I forgot include composable props and emits in component and typechecker warned me about this.

**Comment by m0ksem** [comment]
Most of these are done. If something not done, it means we don't need it. 😊
