### ISSUE TITLE
Calculate color for VaSidebarItem.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1590]
We have getTextColor, but it's unused in VaSidebarItem

---

The problem here with alpha. We are not able to calculate text color if we have alpha background...  We want this feature as service later.

**Comment by aluarius** [comment]
Already fixed.

**Comment by m0ksem** [comment]
Fixed here: https://github.com/epicmaxco/vuestic-ui/issues/2028
