### ISSUE TITLE
Autocomplete for components in IDEs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1594]
Currently ide autocomplete doesn't work for vuestic-ui.

Major IDEs we want to support are:
* Webstorm
* VS Code

- [ ] Check autocomplete works for component.
- [ ] Check autocomplete works for tags.
- [ ] Follow up our solution in Notion.

Probably related to #1581

**Comment by ghsgabriel** [comment]
That would be awesome.

I use PHPStorm, if it is possible to add to it I would love it.

As PHPStorm uses the same core as Webstorm, I believe it is very similar.

**Comment by m0ksem** [comment]
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/1490

**Comment by m0ksem** [comment]
closed in https://github.com/epicmaxco/vuestic-ui/pull/1634

![image](https://user-images.githubusercontent.com/23530004/166902593-f25d0f29-7dd2-4bcd-850a-fddb96b380b9.png)
