### ISSUE TITLE
Make composables as part of vuestic-ui, maybe we have some useful composables for end-user (not sure if we have...).

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1604]
Couple of points on this:

* We generally want to document only composables that are useful for end user, so service-like composables and heavily reused composables.
* It's ideal to link showcase composables for specific components. I.e. if select is using `stateful` composable, then all related props should mention it + link to `stateful` composable page, where in-depth explanation is held.
* We need pretty detailed documentation pages for our external composables.
* Intent is that user would use these high quality composables for their own components.
* We'd need test coverage for composables as well.

**Comment by m0ksem** [comment]
Checked it recently, I would prefer to use VueUse, we don't have a much composables to expose.
