### ISSUE TITLE
Font-awesome deprecation warning

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [epicmaxco/vuestic-ui#1605]
We have the following deprecation warning during project build

> DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

It comes from font-awesome v5. It's a known issue that was already fixed in version 6 but weren't (and probably won't be) fixed in v5.
https://github.com/FortAwesome/Font-Awesome/issues/18371

This warning plagues vuestic-admin as well.

**Comment by m0ksem** [comment]
It comes from v4.7

Must be fixed here: https://github.com/epicmaxco/vuestic-ui/pull/1899
