### ISSUE TITLE
Icons rotating in input field

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#1607]
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**
1. Build or run `serve` on current `develop` brunch
2. Open any input (input, forms)
4. Look for icons, they're rotating

**What is the expected behavior?**
Icons doesn't rotate.

**What is the current behavior?**
Icons rotate.

https://user-images.githubusercontent.com/29167241/161087854-34c38922-9c5a-4f06-838f-96b419e92c20.mp4

**Comment by Derranion** [comment]
This could be fixed by adding false check on this line inside of the `VaIcon`:
`      if (spin === undefined) { return }
`
