### ISSUE TITLE
Docs warning color

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1624]
Currently users are redirected to this [installation page](https://vuestic.dev/en/getting-started/installation) from our [landing](https://vuestic.dev/).

And the first thing they see is this big orange warning:

![installationWarning](https://user-images.githubusercontent.com/7745899/161631032-ba7da342-c9a7-444a-84ad-961c9ae5e364.jpg)

I would suggest changing it to something like this (`color` - `info`):

![installationInfo](https://user-images.githubusercontent.com/7745899/161631256-122c640e-40e2-4049-bb12-4b5f41f5a71a.png)

Because it will be more catchy, fit better with the main theme and less disruptive for an eye.

We can change `warning` `color` in our `docs` to something that will match blue theme as well.

**Comment by asvae** [comment]
I think it makes sense from semantics point to keep this a warn.

We have different styles though. See [docs](https://vuestic.dev/en/ui-elements/alert#different-styles). Outline or border might work great.

@xx13 maybe you have an idea on how we can make alerts less bright?

**Comment by xx13** [comment]
@Derranion we may have 2 options (let's also consider updating `alert` component:
- outlined style
- quote style

![image](https://user-images.githubusercontent.com/22664941/163856726-8c05ec95-8bf2-435d-85d7-1e808879d296.png)

**Comment by m0ksem** [comment]
> @Derranion we may have 2 options (let's also consider updating `alert` component:
> 
>     * outlined style
> 
>     * quote style
> 
> 
> ![image](https://user-images.githubusercontent.com/22664941/163856726-8c05ec95-8bf2-435d-85d7-1e808879d296.png)
> 
> [design wip](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=1436%3A4443)

Isn't these designs already implemented? 
![image](https://user-images.githubusercontent.com/23530004/163857659-9823538b-3fec-485d-ac71-46e8562482e6.png)
https://vuestic.dev/en/ui-elements/alert#different-styles

**Comment by xx13** [comment]
@m0ksem actually (1) looks like a flat version of an outlined alert, and (2) is closer to [quote](https://vuestic.dev/en/styles/typography#blockquote). btw we need to fix the secondary colour there, I'll add a task

**Comment by Derranion** [comment]
Thanks.

I'll apply `outline` style for now, though we could think about color mixes that match `Vuestic` theme better in the future.

> @m0ksem actually (1) looks like a flat version of an outlined alert, and (2) is closer to [quote](https://vuestic.dev/en/styles/typography#blockquote). btw we need to fix the secondary colour there, I'll add a task

Do you mean that `text color` inside of the [Blockquote](https://vuestic.dev/en/styles/typography#blockquote)[ #](https://vuestic.dev/en/styles/typography#blockquote) is gray.

Or which secondary color?
