### ISSUE TITLE
`va-checkbox` doesn't work after build

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1631]
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**
Create `data-table` with `selectable` `prop` set to `true`

**What is the current behavior?**
Selection will stop working after the build:

![dataTableSelectionBuildIssue](https://user-images.githubusercontent.com/7745899/161872424-6a9c27ad-86f6-40e1-9178-2446c7009850.png)

**Other information**
[Initial community report from discord](https://discord.com/channels/457593300799717377/771405157527191585/960237163532914759).

**Comment by Derranion** [comment]
This is related to `va-checkbox` overall.

**Comment by asvae** [comment]
@Derranion can you do a bit of follow up on this. I.e. how this happened in a first place (the fact that build and serve differ).

**Comment by m0ksem** [comment]
@Derranion check if https://github.com/epicmaxco/vuestic-ui/pull/1634 may fix it. 🙂

**Comment by Derranion** [comment]
In general any additional wrapper to components (`withConfigTransport` etc.) may lead to unexpected behavior because it is not a common use case for a bundlers.

I've checked both build versions (`vite` \ `vue-cli`) in the #1634 [Remove withTransportConfig wrapper](https://github.com/epicmaxco/vuestic-ui/pull/1634) and it now works as expected.

That's why I'm closing this one.
