### ISSUE TITLE
Nuxt alpha release

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1641]
Need to make a complete release, so we can test it with nuxt. (Maybe from release/v1.4.0 branch).
This task shouldn't be connected with nuxt-docs features.

- [x] Deal with withTransportConfig https://github.com/epicmaxco/vuestic-ui/pull/1634
- [x] Update colorTranslator to min 1.8 - allows esm build.
- [x] Compile tslib with rollup (or update it someway). Check if we even need to prebuild it with nuxt.
- [x] Check if all components are moved to composition api.
- [x] Check if all fixes from nuxt-docs branch are available in release/v1.4.0. 

@aluarius, feel free to grow this task list.

**Comment by aluarius** [comment]
- VaChip was moved to composition api (https://github.com/epicmaxco/vuestic-ui/pull/1568).
- VaTreeRoot the same (https://github.com/epicmaxco/vuestic-ui/pull/1568).
- VaPopup & VaScrollbar are not in composition api, but they are deprececated.
- There are some doubts about VaTimeLine.
- Others are in composition api.
