### ISSUE TITLE
Nuxt double style loading

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1642]
‼️ That should be done after nuxt docs are stable.

We want to check if nuxt doesn't load vuestic plugin twice in docs.

**Comment by asvae** [comment]
On hold until we go hard on nuxt again.

**Comment by asvae** [comment]
Maybe we can do some research on that and see if we can narrow down what is possible there.

(please don't spend a year on that 😬)

**Comment by m0ksem** [comment]
Looks fixed.
