### ISSUE TITLE
Plugins fabric

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1647]
We want to ensure what plugin is installed.

For example, we have css variables plugin, that should be used differently on SSR.

We want to ensure that user uses renderCSSVariables on SSR, if he use plugin. Just make a warning if not to prevent errors. This can be helpful also in ColorHelpers plugin.

**Comment by asvae** [comment]
Couple of ideas I can add:
* We need a way of linking plugin dependencies. That could take 2 forms: 
  * warning user if dependency is missed + explaining how to add one (we need at least that solution),
  * auto importing dependency plugins.
* That should work for both dev and build.

**Comment by m0ksem** [comment]
Closed in https://github.com/epicmaxco/vuestic-ui/pull/1530
