### ISSUE TITLE
Slider drag doesn't work for touch devices

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1665]
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**
<img width="386" alt="image" src="https://user-images.githubusercontent.com/5394573/163568698-18acf8b6-963d-49f4-bccf-4fa2d7f44503.png">
https://vuestic.dev/en/ui-elements/slider#base-layout
Reproduces in chrome on mobile mode.

**What is the expected behavior?**
Slider should allow drag change on mobile version.

**What is the current behavior?**
Only click works properly on mobile.

**Other information**
On desktop + mouse it's working just fine.

**Comment by m0ksem** [comment]
Works fine in Firefox mobile mode on desktop :)

Also, checked docs on Android Firefox and Android Chrome. Works well.

Looks like it Chrome mobile issue only.
