### ISSUE TITLE
Code examples with tabs

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1674]
Let's have some api to create code examples with tabs on top of it.

Here is a real example:
![image](https://user-images.githubusercontent.com/23530004/163853919-962eb54d-47a2-4613-9aa8-474cc443f872.png)

Let's change it to
```ts
block.code({
   'npm': 'npm install @vuestic/agGrid-theme',
   'yarn': 'yarn add @vuestic/agGrid-theme'
})
```
I'm talking about this kind of tabs:
![image](https://user-images.githubusercontent.com/23530004/163854272-a2ad7bba-0555-4ba2-99a8-1d6f70d8830e.png)

**Comment by xiongmao86** [comment]
If no one is assigned, I would like to take a stab of this.
