### ISSUE TITLE
GUI color picker to VaColorInput

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [epicmaxco/vuestic-ui#1681]
VaColorInput allows input only as text value. Would be nice to invoke native color input when clicking on color circle.

(the video is just a demo, it's not currently implemented)
https://user-images.githubusercontent.com/47790197/164025877-2387b9bc-008d-404c-b42b-0777fa178f63.mp4

**Comment by asvae** [comment]
Yeah, component looks super weird. As if something is broken.

As colors are clickable, but do nothing. Demos also look pretty broken.
