### ISSUE TITLE
Skeleton component implementation

### ISSUE THREAD

**Issue by NekoBlackCat** [epicmaxco/vuestic-ui#1682]
!!! Should be implemented after design is done.

* Design
* [Architecture](https://www.notion.so/epicmax/Skeleton-a4fec0ecb8864c5b93287d5a100464d7)

## Docs
- [ ] Do proper documentation page.
You can use information from architecture page. Not copy exactly, please modify (stolen text)

## Testing
- [ ] Demos for all cases.
- [ ] Couple of tests for core functionality.

### VaSkeleton

- [ ] `type`
- [ ] `active`
I recommend using  [`'wave'`](https://quasar.dev/vue-components/skeleton#animations) animation
- [ ] `round`
- [ ] `rounded`
- [ ] `size`
- [ ] `rows`

## Slots

[ ]

## Emits

[ ]

## Actions
[ ]

## Other 
- [ ] Demo skeleton components against skeletonable (button, avatar etc) components for all sizes.

**Comment by aluarius** [comment]
Implemented https://github.com/epicmaxco/vuestic-ui/pull/2918
