### ISSUE TITLE
Skeleton component

### ISSUE THREAD

**Issue by NekoBlackCat** [epicmaxco/vuestic-ui#1684]
**Design after implementation**

Need design for Skeleton component

[Implementation ](https://github.com/epicmaxco/vuestic-ui/issues/1682)
[Architecture  ](https://www.notion.so/epicmax/Skeleton-a4fec0ecb8864c5b93287d5a100464d7)

To `@xx13` for inspiration:

See skeleton types [here](https://quasar.dev/vue-components/skeleton#example--qskeleton-types)

![1_cliigGKN7ktpBaMJiSvJYQ](https://user-images.githubusercontent.com/62652578/164033261-e5da3169-c593-4f57-b10f-69576687f8c8.gif)

![1_rrY0dyPqgZBMln_VVPx9Gg](https://user-images.githubusercontent.com/62652578/164033275-93bc9d47-3ea0-4f3e-817b-002281202676.gif)

![complex-gif](https://user-images.githubusercontent.com/62652578/164033291-8e771fbb-b8c3-4abc-990d-51d2938406c2.gif)
![jQuery-Grid-Skeleton-Screens-with-Dummy-Image-Placeholder](https://user-images.githubusercontent.com/62652578/164033294-0b98b16f-338f-4001-89ea-db9fac20de38.gif)

**Comment by aluarius** [comment]
Implemented https://github.com/epicmaxco/vuestic-ui/pull/2918
