### ISSUE TITLE
Can't unit test vuestic-ui components

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1685]
Is there any documentation on how to Unit test with Vuestic using jest in Vue3? I receive this error each time:

[Vue warn]: Failed to resolve component: va-icon
    If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

For any vuestic components. I've also tried creating a local vue:

const localVue = createLocalVue();
localVue.use(VusticPlugin);

const wrapper = mount(Component, { localVue });

But I'm still receiving the error.

**Comment by StephenBaione** [comment]
Is there no recommended setup for using vuestic with jest? What unit tests are used for vuestic internally? I've tried registering the VuesticPlugin as a global plugin in mount, and registering individual components when mounting, neither worked.

**Comment by m0ksem** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/2254
