### ISSUE TITLE
Select validation shows error without clicking on it

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1688]
![image](https://user-images.githubusercontent.com/23530004/164266069-574445c6-de28-4b07-9a97-8bcf44700016.png)

https://m0ksem.github.io/clocks/ (Click add button)

It uses `1.4.0-alpha1`.

**Comment by Derranion** [comment]
It looks like `error` `prop` is set to `true` for this field.

Here is an example of validation rules that do not trigger without clicking on select.
https://vuestic.dev/en/ui-elements/select#validation-rules
