### ISSUE TITLE
`VaDatePicker` with range mode don't ignore not allowed dates

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1698]
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**
  - go to [vuebook](http://vuestic-ui-demo.sub.asva.by/#/demo/va-date-picker/VaDatePicker.demo.vue) (see last example with range mode and allowed dates)

**What is the expected behavior?**
  - `modelValue` must ignore not allowed dates
  - these dates must not be selected
 
**What is the current behavior?**

<img width="282" alt="image" src="https://user-images.githubusercontent.com/55198465/164725969-46325c2a-85f3-406a-8172-4be844d02903.png">

**Other information**

**Comment by m0ksem** [comment]
Let's have some function that creates array-dates from range using disable-fn.

v-model:array-range=""

**Comment by m0ksem** [comment]
Nvm, it is fixed.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/23530004/221447994-ad499c68-9a78-4a6a-aabf-b34f7c3c4078.png">
