### ISSUE TITLE
Release 1.4.0a known bugs

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [epicmaxco/vuestic-ui#1715]
Landing page, "Customize Everything" section: 
- [x] incorrect tab content
- [x] first tab content is broken

Docs:
- [x] Side bar items don't get selected upon navigation

UI:
- [x] #1699

**Comment by Derranion** [comment]
- [ ] Sidebar's selected category is not highlighted

**Comment by Derranion** [comment]
- [ ] `Sidebar` selected category is not highlighted (same in the `dev` branch)
