### ISSUE TITLE
Remove unused emits

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1733]
Some of the components have legacy \ irrelevant `events` listed in our docs and not used anymore in the component itself.

For example `VaFileUpload` has `input` `Event` described in the documentation but we don't have this `emit` in the component:

![unusedEmitsExample](https://user-images.githubusercontent.com/7745899/166954740-27a116f8-ff59-47f1-ae2c-0da791ac637a.jpg)

- [x] Find similar cases and remove them

**Comment by xiongmao86** [comment]
If no one is trying, I'll take a stab of this.
