### ISSUE TITLE
Add prop to make `VaFileUpload` undo action optional

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1735]
When deleting a file from `VaFileUpload` there is an `undo` action:
![fileUpload](https://user-images.githubusercontent.com/7745899/166959179-88a9c827-d1de-40e2-9f4f-5ebdd881f4a6.jpg)

- [ ] Add a `prop` to make this optional.

Additional info:
`Undo` action will show up only when `type` `prop` is set to `list` or `gallery`.
[Initial discord reply](https://discord.com/channels/457593300799717377/771405157527191585/971459220711034950).

**Comment by eyuelberga** [comment]
@Derranion I like to help out with this. What should be the name of the prop?

**Comment by Derranion** [comment]
Hey @eyuelberga thanks, I've assigned you.

Just `undo` should be fine :)
