### ISSUE TITLE
"Unknown html tag xxx" in WebStorm

### ISSUE THREAD

**Issue by Jycjmf** [epicmaxco/vuestic-ui#1737]
Hello guys , I  am trying to use this library in vue3+Typescript without Tree shaking . However , after installation , I try to code some component tag like `<va-button>` , WebStorm always prompt `Unknown html tag va-button `. Although the `va-button` works fine in browser , But it it really inconvenient to code without IntelliSense , How could I fix this problem ? Thanks a lot!
Here is my `main.ts`
```
import {createApp} from 'vue'
import App from './App.vue'
import {VaButton, VuesticPlugin} from 'vuestic-ui' //(✓)
import 'vuestic-ui/dist/vuestic-ui.css' //(✓)


createApp(App).use(VuesticPlugin)
    .component('va-button', VaButton)    //I try to register manually , But web storm also prompt 'unknown tag'
    .mount('#app')
```
Here is my `App.vue`
```
<template>
  <va-button>test</va-button>
</template>

<script lang="ts" setup>
</script>
```
WebStorm Prompt:
![image](https://user-images.githubusercontent.com/30173232/167054692-e21c8b70-0eb7-4351-b1dd-7111d87771e4.png)
It works fine in Broswer:
![image](https://user-images.githubusercontent.com/30173232/167054897-0d1729df-5e5b-48d9-b31c-41b038261eec.png)

**Comment by m0ksem** [comment]
@Jycjmf, hey. You can try `vuestic-ui@1.4.0-alpha2`. We added component types here.

**Comment by Jycjmf** [comment]
> @Jycjmf, hey. You can try `vuestic-ui@1.4.0-alpha2`. We added component types here.

Hi @m0ksem, I have changed to `vuestic-ui@1.4.0-alpha2`, but where is the docs for the latest version? The old document seems not work for the latest 1.4.0 version.
![image](https://user-images.githubusercontent.com/30173232/167234537-ddd79abb-98b3-4e25-ab48-90b8e12f3a06.png)

**Comment by m0ksem** [comment]
> > @Jycjmf, hey. You can try `vuestic-ui@1.4.0-alpha2`. We added component types here.
> 
> Hi @m0ksem, I have changed to `vuestic-ui@1.4.0-alpha2`, but where is the docs for the latest version? The old document seems not work for the latest 1.4.0 version.
> ![image](https://user-images.githubusercontent.com/30173232/167234537-ddd79abb-98b3-4e25-ab48-90b8e12f3a06.png)
> 

Sorry, no docs for now. Just released yesterday to see if my changes can help you with this issue. 

For css problem, now you need to change path to vuestic-ui.css to /css.

`import 'vuestic-ui/css'`

**Comment by Jycjmf** [comment]
> import 'vuestic-ui/css'

Ok, thanks bro, I'll still the `ver 1.3.5`  till the new document released. Anyways, Thanks for your amazing ui library!
