### ISSUE TITLE
VaOptionsList has strange internal logic

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1741]
VaCheckbxo, VaRadio, VaCheckbox must have only boolean prop type (or null  | string for VaCheckbox).

For some reason VaCheckbox can have Array type model-value and option prop which is confusing for user. 

It is very stange....
![image](https://user-images.githubusercontent.com/23530004/167188775-2b2ff9d2-9c3a-45e0-acb5-63f2ca76b274.png)

This type looks off
![image](https://user-images.githubusercontent.com/23530004/167189522-0f3cc31c-6fa4-49e2-b962-8decc91bdfbe.png)

**Comment by LighthouseKeeperYN** [comment]
Isn't that a documented feature?
https://vuestic.dev/en/ui-elements/checkbox#grouped-array

**Comment by m0ksem** [comment]
> Isn't that a documented feature? https://vuestic.dev/en/ui-elements/checkbox#grouped-array

Yes. We have options group for this feature. 
https://vuestic.dev/en/ui-elements/option-list

Why do we need it in checkbox? 
For me, checkbox value can be only Boolean or Boolean | null. That is what user expect from this component.
