### ISSUE TITLE
VaButton to prop doesn't work in Nuxt

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1748]

**Comment by asvae** [comment]
That's pretty important.

I would assume it's the same for other router-bound components?

**Comment by m0ksem** [comment]
VaSidebarItem works well, but https://github.com/epicmaxco/vuestic-ui/issues/1760

**Comment by m0ksem** [comment]
@aluarius. your massive button rework likely must fix this issue 👌

**Comment by ihorbond** [comment]
Just came across this issue and made a small repro
https://stackblitz.com/edit/nuxt-starter-y5dyb7?file=pages/index.vue

As workaround can wrap in <NuxtLink></NuxtLink> for the time being

**Comment by m0ksem** [comment]
> Just came across this issue and made a small repro https://stackblitz.com/edit/nuxt-starter-y5dyb7?file=pages/index.vue
> 
> As workaround can wrap in NuxtLink for the time being

Thanks! @aluarius already working on this issue. It looks like `component is="nuxt-link"` doesn't work in nuxt.

**Comment by m0ksem** [comment]
> VaSidebarItem works well, but #1760

@aluarius, investigate why VaSidebarItem works in nuxt, please 😄.

**Comment by aluarius** [comment]
Fixed for 1.5.0, soon (today) will make a fix for develop branch.
