### ISSUE TITLE
va table

### ISSUE THREAD

**Issue by Vikec** [epicmaxco/vuestic-ui#1750]
**Vuestic-ui version:** 1.3.5

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

va-data-table
    :items="items"
   striped
            

<template #cell(name)="{  rowData  }">
                {{rowData.name }}
              </template>

why i can't get the rowData

**Comment by RVitaly1978** [comment]
Could you show your `items`?

**Comment by Vikec** [comment]
> 

 const items = [{
      "id": "1",
      "name": "kks"
    }]

**Comment by RVitaly1978** [comment]
Sorry, but in the current release of vuestic-ui, in the `cell(...)` slot, you have access to the `value`, `source`, and a few other variables (but no access to `rowData` yet).
Now you can do it:
```
<template #cell(name)="{ value }">
  {{ value }}
</template>
```
In our next release, you will be able to access the rowData variable.

**Comment by Vikec** [comment]
> Sorry, but in the current release of vuestic-ui, in the `cell(...)` slot, you have access to the `value`, `source`, and a few other variables (but no access to `rowData` yet). Now you can do it:
> 
> ```
> <template #cell(name)="{ value }">
>   {{ value }}
> </template>
> ```
> 
> In our next release, you will be able to access the rowData variable.

I see. Thank you
