### ISSUE TITLE
Impossible to remove VaModal's padding

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1752]
![image](https://user-images.githubusercontent.com/23530004/167679646-1bf59370-80aa-472f-a3e5-5fde4ca44677.png)

Must be css varialbe.

**Comment by m0ksem** [comment]
@xx13

**Comment by asvae** [comment]
Prop would also be nice to have.

something like no-padding. But please don't trust me and investigate a best solution :).

**Comment by m0ksem** [comment]
We can make a slot, that will override whole modal content: actions, title, default slot.

**Comment by asvae** [comment]
@m0ksem 
> We can make a slot, that will override whole modal content: actions, title, default slot.

There are props to remove title and default actions. That allows you to achieve the same, no?

**Comment by m0ksem** [comment]
> @m0ksem 
> > We can make a slot, that will override whole modal content: actions, title, default slot.
> 
> There are props to remove title and default actions. That allows you to achieve the same, no?

For example, I want to add a image so it [fit full modal width](https://vuestic.dev/ru/ui-elements/card#image). How can I make it?

Or, instead of card, I simply want to show text on overlay, without any card background.
