### ISSUE TITLE
Release v1.4.0 check if all prop types are valid

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1753]
![image](https://user-images.githubusercontent.com/23530004/167677990-8b30b472-9ff6-41d9-819c-5c3e0df1fdfc.png)

VaInput validation rules

You can do this as you go: https://github.com/epicmaxco/vuestic-ui/issues/1761

**Comment by asvae** [comment]
Would be great to check both webstorm and vs code.
