### ISSUE TITLE
yarn 2.0 support

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#176]
## Why
* Better dependency resolution.
* Better monorepo support. (plan is to get there)
* Better console errors.

## Current progress
* #175 2/9/2020 - failed attempt. Suggest revisiting in ~2-3 months.

**Comment by asvae** [comment]
Curious - https://spin.atomicobject.com/2021/02/17/switch-yarn-2/
Might be worth it

**Comment by asvae** [comment]
Another article

https://psidium.github.io/lerna/monorepo/yarn/nodejs/pnp/zero-install/2021/08/23/migrating-a-monorepo-from-lerna-to-yarn-3.html

**Comment by m0ksem** [comment]
@asvae We probably need to move to pnpm, because it doesn't have issues with nuxt in monorepo.
