### ISSUE TITLE
Popover automatically makes background brighter

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1770]
For now, if `dark` passed as popover color, it will automatically make it brighter, converting to hoverColor.

@xx13, are you ok if we will just use color prop, without transforming it to hoverColor.
![image](https://user-images.githubusercontent.com/23530004/168280109-22c24497-e3d2-4df9-86c5-dabaecb6cb26.png)

#### Example
(Passed dark color as background)

![image](https://user-images.githubusercontent.com/23530004/168279525-d274afc1-f3ce-49d7-a30c-2f866a260b69.png)

**Comment by xx13** [comment]
@m0ksem 👍🏻 removing the lighten effect is a nice fix

**Comment by Sadnessa** [comment]
I can work on this issue, if you don't mind.

**Comment by xx13** [comment]
let's have the dark black default backgroud colour and white as the default text colour

**Comment by Sadnessa** [comment]
@xx13 Which is better in your opinion? 
![изображение](https://user-images.githubusercontent.com/67637329/168288486-80f287a3-6227-4870-a0a5-932df0e2509d.png)
![изображение](https://user-images.githubusercontent.com/67637329/168288611-7ee63509-c938-4570-b8c0-a63f79b8cde4.png)

**Comment by xx13** [comment]
@Sadnessa the black one with an optional title and an optional icon ^^
