### ISSUE TITLE
Correct VaSelect keyboard navigation

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1783]
Enter usually used for submit action in form. I would rather just use space to open select. Pressing enter on any component could submit my form.

Also, up and down buttons often used not for dropdown opening, but switching between options without opening dropdown.

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/pull/1778#discussion_r873627811_

**Comment by m0ksem** [comment]
Take a notice that VaTimePicker also must select option on space, instead of scroll.
http://localhost:8080/en/ui-elements/time-input#default

OR do we want to change space to enter? Not sure here...

**Comment by asvae** [comment]
> Enter usually used for submit action in form

Regarding enter/space usage I think best idea would be to stick to vanilla behavior, as that could be something that user expects.

For vanilla select:
* enter opens select and selects values
* space only opens select

> but switching between options without opening dropdown
Yeah. That's a good one, matter of convenience for selects with few options. We can definitely implement it.

> Take a notice that VaTimePicker also must select option on space, instead of scroll.
A matter of convention. It might make sense not to close picker on enter (select does close).

**Comment by m0ksem** [comment]
More information can be found here: https://www.w3.org/TR/wai-aria-practices/#combobox-keyboard-interaction

**Comment by Derranion** [comment]
I support this - `UP` and `Down` buttons to open dropdown seems a bit weird.

> Take a notice that VaTimePicker also must select option on space, instead of scroll. http://localhost:8080/en/ui-elements/time-input#default
> 
> OR do we want to change space to enter? Not sure here...

Or we could add `enter` there as well :)

> Enter usually used for submit action in form. I would rather just use space to open select. Pressing enter on any component could submit my form.
> 
> Also, up and down buttons often used not for dropdown opening, but switching between options without opening dropdown.
> 
> _Originally posted by @m0ksem in [#1778 (comment)](https://github.com/epicmaxco/vuestic-ui/pull/1778#discussion_r873627811)_

If depends on `focus` - if `Select` is focused `enter` will not submit form, not sure where this can cause issues.

> Let's use enter as select option action. Looks like selecting only with space, it is macOS only specific behavior.
> 
> More information can be found here: https://www.w3.org/TR/wai-aria-practices/#combobox-keyboard-interaction

Yeah on windows it opens by "Enter" press.

**Comment by m0ksem** [comment]
Since we support multiple select, it is suggested that UP and DOWN keys must open dropdown. So this issue probably need to be closed.
