### ISSUE TITLE
`VaDateInput` throw warning

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1789]
**Vuestic-ui version:** v1.4.0-alpha5

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/55198465/168651026-963b0286-374d-4e72-9064-099c748c5183.png">

**Comment by Derranion** [comment]
@m0ksem Hello hello, just an update

It throws some more warnings when you use it:
`Component emitted event "focus" but it is neither declared in the emits option nor as an "onFocus" prop.`
`Component emitted event "blur" but it is neither declared in the emits option nor as an "onBlur" prop.`
