### ISSUE TITLE
Release popup announcement

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1799]
![image](https://user-images.githubusercontent.com/23530004/168987130-3075f6f8-bd80-463d-966d-c578d97cba27.png)

Let's have some popup that will notify user about new version.

Make it able to hide, show first three days from release, show only one time, make a record in local storage.

We also don't have such component.

**Comment by asvae** [comment]
Looks like toast for me?

Looks questionable.
