### ISSUE TITLE
Component config variants

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1806]
# Useage example
```vue
<va-button variant="buy" />

<va-button variant="cancel" />
```

We want to make user be able to create component from some kind of presets.

User should be able to define varians in global config

```ts
createVuestic({
   config: {
      components: {
         VaButton: {
             variants: {
                buy: {
                   color: '#0fe',
                   icon: 'money',
                   gradient: true,
                   
                   class: 'buy-button'
                },
                cancel: {
                   color: 'secondary',
                   flat: true,
                }
             }
         }
      }
   }
})
```

https://www.notion.so/epicmax/b1b5f6118bde486fb72b88fa932249ea

See also https://github.com/epicmaxco/vuestic-ui/issues/1527
and https://github.com/epicmaxco/vuestic-ui/issues/1856

**Comment by Derranion** [comment]
Main logic is ready, refactoring it a bit, adding types, creating new documentation right now.

**Comment by Derranion** [comment]
This feature was implemented here:

[Feat #1806: Presets for all components & components config structure change ](https://github.com/epicmaxco/vuestic-ui/pull/1921)
