### ISSUE TITLE
Docs stopped working in Safari

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1828]
[Vuestic.dev](vuestic.dev) does not open in Safari browser.

![safariErrors](https://user-images.githubusercontent.com/7745899/169548363-a9c9f7c9-0cd0-4a3f-afbd-012b06396dee.png)

Check this out using a newer version of Safari and iOS.

**Comment by aluarius** [comment]
Can't reproduce promble with macOS 12.4 & Safari 15.4.

**Comment by m0ksem** [comment]
Doesn't work on Safari 12 / Mojave

**Comment by asvae** [comment]
Safari 12 is way below 1% usage. That's not something we want to support.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/5394573/171832133-a5730366-2ae6-427f-aac7-27b983287cb7.png">
