### ISSUE TITLE
VaButton focus on alt tab

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1834]
I also found the issue if you focus button, then alt+tab and focus another button - previous focus will stay.

Looks like issue in useKeyboardFocus...

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/issues/1833#issuecomment-1133462428_

**Comment by m0ksem** [comment]
Likely it was hot reload. Can somebody check it and close if not relevant?

**Comment by Derranion** [comment]
I've checked this:

1. Focused `button` gets `focus` back after `alt` + `tab`
2. Pressing `tab` correctly moves `focus` to the next element.
