### ISSUE TITLE
Font size regression

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1837]
Paragraph font size is too big. Please investigate the cause of regression.

![image](https://user-images.githubusercontent.com/5394573/169689843-ee54a890-e160-4e4b-aec0-050d2bd12645.png)

**Comment by aluarius** [comment]
It was increased to 1.2 rem via https://github.com/epicmaxco/vuestic-ui/issues/1479

**Comment by xx13** [comment]
I'll create a list of all related text style updates.
