### ISSUE TITLE
Content select doesn't show focus

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1839]
* Doesn't have any effect on click
* Doesn't show any effect on keyboard focus
* On Safari - first example can't be keyboard focused at all (that's not a big deal, if you don't have an idea as to why - ignore this point)
  ![image](https://user-images.githubusercontent.com/5394573/169691030-d1ecf05e-d152-4ca1-9416-c2f943f07559.png)

**Comment by Derranion** [comment]
This is most likely caused by `slot` content not having a `tabindex` or other `focusable` element.
