### ISSUE TITLE
`app._context` in `createVaModalPlugin` and `createVaToastPlugin`

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1853]
Isn't context set to VNode in `app.mount` method? Do we even need to handle context here?

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/pull/1713#discussion_r881558109_

**Comment by asvae** [comment]
Can you provide more info on this?

**Comment by m0ksem** [comment]
We don't want this
