### ISSUE TITLE
VaConfig improvements

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1856]
- [x] Remove div from VaConfig
- [ ] Try to make all components use with config transport. Also check if we can remove some boilerplate to support 2 soluitons (i.e. maybe we can have config support inside of component)

**Comment by Derranion** [comment]
Checked first point because `VaConfig` has only slot in the render function.
No additional `DOM` elements are made.
```
render () {
  return this.$slots.default ? this.$slots.default() : null
},
```
