### ISSUE TITLE
change theme not work

### ISSUE THREAD

**Issue by ginoking** [epicmaxco/vuestic-ui#1857]
**Vuestic-ui version:** 1.4.0

HI 

What do i do to make changing theme work after update to 1.4.0?

It always say "inject() can only be used inside setup() or functional components." and "Global config plugin is not registered"

thanks a lot!

**Comment by m0ksem** [comment]
You mustn't use `useColors` composable outside setup function.

[Here ](https://github.com/m0ksem/clocks/blob/master/src/hooks/useTheme.ts) you can find example how to implement theme switcher.

**Comment by ginoking** [comment]
@m0ksem 

Thanks a lot !!
I find the way!
