### ISSUE TITLE
VaDivider doesn't use va-divider color

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1858]
😶

**Comment by dnischeta** [comment]
Hello!
Do you mean, that content should has `va-divider-border-top-color` also? Because, as I understand, divider lines respect css-variable.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/55282960/171444616-b56418e5-5245-46b9-8162-c62b9dba757e.png">

**Comment by m0ksem** [comment]
> Hello!
> Do you mean, that content should has `va-divider-border-top-color` also? Because, as I understand, divider lines respect css-variable.
> <img width="973" alt="image" src="https://user-images.githubusercontent.com/55282960/171444616-b56418e5-5245-46b9-8162-c62b9dba757e.png">
> 

Hey. No it doesn't. It doesn't react on colors config changes. 

Forgot to mention, I'm working on it in scope of dark themes.

**Comment by m0ksem** [comment]
Merged in 1.5.0 with #1865
