### ISSUE TITLE
Small hack in develop

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1864]
In `range-model-value-guard.ts` I made a small change to make build work:

![image](https://user-images.githubusercontent.com/5394573/170736153-bd1cde6b-1d4e-4631-8732-e24ea3c8f758.png)

Please check what's wrong and fix it properly.

You can test build with `npm run build`. There should be no errors.

**Comment by m0ksem** [comment]
closed here: https://github.com/epicmaxco/vuestic-ui/pull/1935
