### ISSUE TITLE
Incorrect css rule

### ISSUE THREAD

**Issue by wossig** [epicmaxco/vuestic-ui#1867]
**Vuestic-ui version:** 1.4.1
**Steps to reproduce**

The active color should be white for `va-sidebar-item`
![image](https://user-images.githubusercontent.com/22833218/170863977-c23bc04c-1874-4886-9532-6f0e034b6033.png)

**What is the expected behavior?**
active color should be white.

**What is the current behavior?**
inline color overrided by othre css rules.

**Comment by m0ksem** [comment]
SidebarItem is a bit complicated. Will be fixed in scope of dark themes in 1.5.0.
https://github.com/epicmaxco/vuestic-ui/pull/1865

**Comment by m0ksem** [comment]
Fixed here: https://github.com/epicmaxco/vuestic-ui/issues/2028
