### ISSUE TITLE
Don't use the latest vuestic-ui version in nuxt module

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1909]
Let's update manually vuestic version in nuxt module to prevent issues like [this](https://github.com/epicmaxco/vuestic-ui/issues/1902).

Same as vue-cli-plugin.

**Comment by asvae** [comment]
Can't we instead focus on testing to prevent regression?

I.e. on tiny+ release run a script that would spin nuxt project with updated deps and see it doesn't break?
