### ISSUE TITLE
TS interface error

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1916]
**Vuestic-ui version:** 1.4.1
![TS Interface errors](https://user-images.githubusercontent.com/7745899/172185139-d615f49e-dbfb-466a-8e0c-8a0bac88737f.png)

**Steps to reproduce**
Trigger anything related to `GlobalComponents` interface

**Comment by m0ksem** [comment]
Works fine for me.

**Comment by Derranion** [comment]
Closing this while we don't see issues in `dev`.

**Comment by Derranion** [comment]
Closing this while we don't see issues in dev.
