### ISSUE TITLE
Button component acts weird when got clicked.

### ISSUE THREAD

**Issue by Sadnessa** [epicmaxco/vuestic-ui#1919]
**Vuestic-ui version:** 1.4.1

There are I have two states - ``isVisibleLogin`` and ``isVisibleSignup`` - which have to change when I click on the button.  
And they are changing, but when I off my mouse cursor from button after click. 

![firefox_CVHpHFnP4O](https://user-images.githubusercontent.com/67637329/172353574-5ce0451a-4305-4944-924c-2f70df84cb48.gif)

Also, as you can see, hover is still on button when my mouse is not on it. 

Here is my code: 
HTML
``<va-button outline @click="switchWindows"> Sign up</va-button>``
``<va-button outline @click="switchWindows"> Log in</va-button>``

Script
```let isVisibleLogin = ref(true);
let isVisibleSignup = ref(false);
const switchWindows = () => {
  isVisibleLogin.value = !isVisibleLogin.value;
  isVisibleSignup.value = !isVisibleSignup.value;
};

**Comment by aluarius** [comment]
It's a `Vue Devtools` lag. Try to render this var ({{ isVisibleLogin }}) and you'll see that it changes immediatly.

P.S. All the same for native `<button>` tag.
