### ISSUE TITLE
New design of VaButton implementation

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#1923]
New buttons ([figma](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=1538%3A7170)) have some new states, that will affect the list of component's props.

1. Add the `pressed` state. I can't see it anywhere at all. May be we should create new composable `usePressed`.
2. Delete the `outline` prop and state (no design for it, watch next option).
3. Add `borderColor` prop (undefined as default). In purpose to create old-like outline buttons based on `secondary` state of the new design (suggestion by Vasily).
4. Rename the `flat` prop to `plain`.
5. ~~Delete `type` prop. It's seems to be double of the `tag` prop. ~~
5.1. NEW: visual presets (`primary, secondary, plain, plain-opacity`) will be located in `Global Config` and connected with components via https://github.com/epicmaxco/vuestic-ui/pull/1921
5.2. NEW: opacity variables (e.g.: `opacity-hover, hover-opacity` etc.) will be located in `Color Config`.
7. ~~Add the `borderRadius` prop (`undefined` as default). To allow users to change default border radius (suggestion by Vasily).~~
8. CHANGED: `round` will serve as a helper for `border-radius: 50%`.
9. Delete the `rounded` prop (all new variants are square).
10. ~~Change default `color` prop value to `undefined` (by default appearance will depend on new `type`/`style` prop).~~
11. Add `iconColor` prop if we want different colors for text & icon (suggestion by Vasily).

**Comment by aluarius** [comment]
@RVitaly1978 @asvae @Derranion @rustem-nasyrov take a look, please.

**Comment by asvae** [comment]
@xx13 can you explain why we're getting rid of outline buttons?

**Comment by asvae** [comment]
3 - I don't see a point. If outline buttons are solution we don't want our users to employ - why give them tools? I suggest supporting outline preset or removing altogether.
5 - probably we want to use new preset system for that.
6 - that's not great, definitely not prop, css variable - yes.
7-8 - I strongly feel we need to have a way for button to be rounded/not rounded. There are cases like fab button, so even in same design solution - you can have semantically different buttons of varying roundedness.
9. Probably should still have some kind of default on button. You can think of presets as external layer. It adds goodness, but button should be perfectly functional without it.

Other points look reasonable. 👯

**Comment by asvae** [comment]
Let's discuss that in grooming :)

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/1945
