### ISSUE TITLE
Missing docs about input 'type' prop.

### ISSUE THREAD

**Issue by Sadnessa** [epicmaxco/vuestic-ui#1925]
Input docs contain information about 'type' prop, but there is no demo with it, and there is also no information about which kind of type input can be.

**Comment by m0ksem** [comment]
Details: Take a look on `type` prop TS types. It must be string or `'textarea' | StandardInputTypeAttribute`.
> StandardInputTypeAttribute - fictional type, find a better name.

Reason we have this task – it is confusing for user how to set VaInput to be password input.
