### ISSUE TITLE
Select not showing icons

### ISSUE THREAD

**Issue by scottmilla** [epicmaxco/vuestic-ui#1933]
I'm using the default select component with default icons (mdi). For some reason the only icons not loading are the select's. Screenshots attached below. 

<img width="455" alt="Screen Shot 2022-06-13 at 1 09 19 PM" src="https://user-images.githubusercontent.com/21327095/173407729-9f91baef-3ce5-4ee5-a8f5-152e2e8b1272.png">
<img width="459" alt="Screen Shot 2022-06-13 at 1 09 02 PM" src="https://user-images.githubusercontent.com/21327095/173407772-03ebf099-b7ad-40bb-8da8-6c06cf8ac78d.png">

**Comment by m0ksem** [comment]
@scottmilla, hey. Check if MaterialIcons font is installed in your app.
https://vuestic.dev/en/getting-started/installation#assets-installation

**Comment by scottmilla** [comment]
@m0ksem I have the outlined icons installed as follows:
@import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,200,0,0');

**Comment by m0ksem** [comment]
> @m0ksem I have the outlined icons installed as follows: @import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,200,0,0');

For outlined icons you need to configure outline font.

```
    config: {
      icons: createIconsConfig({
        fonts: [
          {
            // Any icon name
            name: '{code}',
            class: `material-symbols-outlined`,
            resolve: ({ code }) => ({ content: code }),
          },
        ]
      })
```

Learn more from docs: https://vuestic.dev/en/services/icons-config#fonts
