### ISSUE TITLE
Roadmap out of date

### ISSUE THREAD

**Issue by Leon0402** [epicmaxco/vuestic-ui#1944]
Version 1.4.0 was already released, but is still marked as "in development". 

![image](https://user-images.githubusercontent.com/33933142/173626741-5bf4eed4-d452-491a-8441-d98ea61adc94.png)

Would be nice to see what is planned for 1.5 additionally.

**Comment by asvae** [comment]
![image](https://user-images.githubusercontent.com/5394573/180246556-ceba434f-d822-4cff-a2e3-8be1392af135.png)

**Comment by asvae** [comment]
Would be great to handle this on high level of quality. We can show our plans similarly to what developer do in games.

On screenshot you can see some of the plans we're very committed for. So these could be easily shaped into timeline.
