### ISSUE TITLE
Vue-tsc errors

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1948]
**Vuestic-ui version:** 1.4.1

**Steps to reproduce**

1. Run `yarn build:types`
2. You can see TS error as the result

**What is the current behavior?**
![vueTSCErrors](https://user-images.githubusercontent.com/7745899/173851334-7d53f22e-c439-4658-b6c7-19fc4b08621f.png)

This info could be helpful:
[TS4082: Default export of the module has or is using private name](https://github.com/typed-ember/ember-cli-typescript/issues/133)

**Comment by m0ksem** [comment]
Fixed here. https://github.com/epicmaxco/vuestic-ui/pull/1949
