### ISSUE TITLE
`VaRating` disabled, readonly, hover behaviour

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1952]
**Vuestic-ui version:** 1.4.1

**Steps to reproduce**
  - http://vuestic-ui-demo.sub.asva.by/#/demo/va-rating/VaRating.demo.vue
  - http://vuestic-ui-demo.sub.asva.by/#/demo/va-rating/components/VaRatingItem/VaRatingItem.demo.vue

**What is the current behavior?**
  - `disabled` and `readonly` weird behaviour
![chrome-capture-2022-5-16](https://user-images.githubusercontent.com/55198465/174081644-65657b93-fc65-40d6-8edd-8c21456117d2.gif)

  - hover with `halves`
https://user-images.githubusercontent.com/55198465/174083141-30a98911-82d0-415e-86c4-b0d1e7982c89.mov

**Comment by smellyshovel** [comment]
> disabled and readonly weird behaviour

It behaves the way it does because the disabled and readonly variants are used with the `hover` prop:
```
<va-rating disabled hover v-model="value" />
<va-rating readonly hover v-model="value" />
```

Do we want to ignore the `hover` prop in cases when it's used alongside either of `disabled` or `readonly`? Or should the existing behavior be considered correct?

@m0ksem, @RVitaly1978, what do you think?

**Comment by m0ksem** [comment]
> > disabled and readonly weird behaviour
> 
> It behaves the way it does because the disabled and readonly variants are used with the `hover` prop:
> 
> ```
> <va-rating disabled hover v-model="value" />
> <va-rating readonly hover v-model="value" />
> ```
> 
> Do we want to ignore the `hover` prop in cases when it's used alongside either of `disabled` or `readonly`? Or should the existing behavior be considered correct?
> 
> If we remove the `hover` prop for the above cases there'd be no visual changes when the stars are hovered.
> 
> @m0ksem, @RVitaly1978, what do you think?

`disabled` and `readonly` must disable `hover` prop. Likely user want to set `hover` prop in global config and sometimes use `disabled` prop conditionally, so he would expect that `disable` prop disables `hover` as well.

**Comment by smellyshovel** [comment]
@RVitaly1978 Can't reproduce the 3d point:

https://user-images.githubusercontent.com/9782236/175049985-de079950-c262-4e24-b2fc-097f49af16b7.mp4

Could you please deploy the demo case or tell me how to reproduce?
