### ISSUE TITLE
Create a way to handle attributes in the configs

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1954]
- [ ] Create a way to manage attributes in the configs

**Describe the solution you'd like**

Currently we handle only `props` inside of the `components` `config`.

We think that adding a way to add `attributes` there could be helpful for components reuse.

Here is the new [Presets feature for all of the components](https://github.com/epicmaxco/vuestic-ui/pull/1921) - this could be one of the entry points to add attributes.

One of the possible structures may look this way:
```JS
components: {
   ...
   presets: {
     VaInput: {
       'prime': { attrs: { class: 'highlight-text' }, color: 'primary', },
   }
   ...
}
```

**Comment by asvae** [comment]
Couldn't this be handled same as props? Any downsides to that you can see?

**Comment by Derranion** [comment]
I can re-use part of the code but `attributes` are a different entity - most likely will patch `setup` function `context` to achieve this.

**Comment by Derranion** [comment]
We decided that this is not critical and could be done later.

That's why I'll finish this when I have time instead of assigning to someone else.
