### ISSUE TITLE
`VaTimeInput` selection animation

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1978]
**Vuestic-ui version:**
1.4.1

**Steps to reproduce**
1. Open `VaTimeInput` dropdown
2. Press and hold any navigation button - for example `Arrow Down`

**What is the current behavior?**
Selected time will not change until you depress `Arrow Down` \ `Arrow Up`
![holdArrowDown](https://user-images.githubusercontent.com/7745899/174855322-81df82e5-0841-4a63-b556-b54d8b1831ac.gif)

**What is the expected behavior?**
We should see what is currently selected

**Additional info**:
I believe it worked almost correctly previously - probably one of the recent changes affected this.

**Comment by rustem-nasyrov** [comment]
It's looks same for me, compared with 1.3.4 version. @RVitaly1978, @aluarius or @m0ksem can you guys check it too?
