### ISSUE TITLE
Add progress bar to the undo action in the file upload component

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#1982]
Would be nice to have a progress here.
![image](https://user-images.githubusercontent.com/23530004/174872467-2177ecba-f1d9-4432-8779-15913938647b.png)

So this line is slightly decreasing as undo time gone. Would be nice if you implement it with CSS variable and CSS keyframes :)

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/pull/1977#pullrequestreview-1014066775_

**Comment by rustem-nasyrov** [comment]
Also need to refactor partially child components, because in places is using the `va-card` component.

**Comment by m0ksem** [comment]
This also can be made using VaProgress.

**Comment by arkmadj** [comment]
@m0ksem Can I have a go at this issue?
