### ISSUE TITLE
Add bundler test to release pipeline

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1991]
## Why

So far we had multiple issues with getting broken for new users. That's far from ideal as we don't have a visibility on the thing of most importance for end user. If component breaks - that's sad, but not unnerving. If build doesn't work at all - that's a broken framework, no can do.

## How

Bundler tests should in total answer the question - does compiled vuestic-ui work in [insert environment].

### High prio

Project configuration:
Checking kitchensink page for errors in the console.

Environments:
- [x] vite spa
- [ ] vite spa + tree shake
- [x] nuxt spa + ssr
- [x] webpack spa
- [ ] webpack spa + tree shake

Additional requirement:
- [x] esm (default vite)
- [x] esm-node (default nuxt) 
- [ ] cjs (https://github.com/epicmaxco/vuestic-ui/issues/2313)
- [ ] iife (seems not to work too)

### Medium prio
- [ ] vitest
- [ ] codesandbox (kitchensink + full-build/modular-build)
- [ ] accessibility check
- [ ] integrations check (tailwind, ag-grid, inertia etc)

### Low prio:
- [ ] vite ssr
- [ ] webpack ssr
- [x] node 16
- [x] node 18 (lts)
- [x] yarn 
- [ ] npm
- [ ] pnpm

### Next step on this task
* We can probably have some optional tests, that would just hint users on which versions we support. I.e. if new version of vite is released - we can run tests to see if vuestic works with that version - then showcase that in the docs.

Probably do after #2204

**Comment by aluarius** [comment]
for more information about iife and cjs builds see https://github.com/epicmaxco/vuestic-ui/issues/2825

**Comment by asvae** [comment]
@aluarius can you handle this issue (extract remainders to different issues then close?)
