### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1994]
**Vuestic-ui version:**
1.5.0 (next release branch)

**Steps to reproduce**
Run `yarn build`

For some weird reason exactly the same route path as was used before for `import` \ `export` throws error during `yarn build`.

![buildError](https://user-images.githubusercontent.com/7745899/175291198-d7af8a1f-41c6-4e60-8577-1ceb1a871575.png)

Update:
Looks like this is caused by the usage of `.ts` `imports` inside of the `<script>`
`<script lang='ts'>` may resolve this but then we will have multiple `TS` errors in the related files and there are a lot of them.

Update:
We decided with @m0ksem that will fix this later, before `1.5.0` release.

**Comment by m0ksem** [comment]
Fixed in 1.5.0. 👌
