### ISSUE TITLE
Focus-state styling for the va-rating component.

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#1995]
Moved from #1952 

  - focus visualization (or focus-color outline?)
![chrome-capture-2022-5-16 (1)](https://user-images.githubusercontent.com/55198465/174082385-8203ce00-fe42-437e-b0b4-5e3cd2dbcccf.gif)

Not sure though how what it should look like in the end. @xx13's comments would be appreciated.

**Comment by xx13** [comment]
let's have it consistent with yellow stroke around the icon box
