### ISSUE TITLE
Make fixed prop for VaNavbar and VaAppBar

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2006]
https://github.com/aluarius/vuestic-ui/commit/286ea45b5be896c3b3cdbfe4ddb216ae8e2f47ed#r76929690

VaHeader and VaAppBar must be relative on default, but fixed on scroll, maybe? Also think about hide-on-scroll prop.

So yes, this two must be reworked.

let's have fixed prop.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2022
