### ISSUE TITLE
vuestic.dev doesn't open on firefox

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2012]
Seems like an issue with `www.` handling

<img width="772" alt="image" src="https://user-images.githubusercontent.com/5394573/175995327-c7de347e-7b47-4e72-8bdc-e9abad957320.png">

**Vuestic-ui version:** 1.4.4

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

**Comment by asvae** [comment]
Ok, and as soon as I add www, we got problem with ssh >.>.

**Comment by asvae** [comment]
Have to acknowledge that backend is our weakest spot so far. It kinda works, but it would be great to have something dokerized and more fool proof.

**Comment by misterpekert** [comment]
There is a slight edge case with Firefox autocomplete feature. Once you have a broken link (with `www` in our case) in history, it would suggest it even when you explicitly type the site without the `www` part. To fix this issue, we need to redirect from `www` to the URL without it and after it should work normally.

**Comment by asvae** [comment]
@misterpekert could you create another issue to handle this www -> nothing redirect?

Then close this one?

**Comment by misterpekert** [comment]
@asvae sure. #3411 it is.
