### ISSUE TITLE
Create Attributes merging logic in Configs

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#2014]
Task should be done after this one:
[Create a way to handle attributes in the configs #1954](https://github.com/epicmaxco/vuestic-ui/issues/1954)

**Description:**
We want to think about most likely usage of `Attributes` in the `Config` by our users.

To improve their experience.

Currently - after this task [#1954](https://github.com/epicmaxco/vuestic-ui/issues/1954),
`Attributes` that are set in `Global Config` will be completely overwritten by `Local Config` `Attributes` or `Preset` `Attributes`.

This could be fine in most cases but looks like merging them together would be more convenient.

For example:
```
// set Class for all Buttons
Global Config -> VaButton -> attrs: { class: 'vuesticButton' }

// set Class for local Buttons
Local Config -> VaButton -> attrs: { class: 'highlightButton' }
```

Merging all classes into one could be beneficial - `class: ['vuesticButton, 'highlightButton']`

Same thing can be relevant for other `Attributes`.

**Summary:**:
- [ ] Think about possible caveats and ways to improve `Attributes` usage.

**Comment by Derranion** [comment]
We decided that this is not critical and could be done later.

That's why I'll finish this when I have time instead of assigning to someone else.

Related to:
https://github.com/epicmaxco/vuestic-ui/issues/1954

**Comment by aluarius** [comment]
May be also we want to add something like `presets.all` config, that will set at least hover-pressed behaviour.
