### ISSUE TITLE
Missing padding for input's prepend slot

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#2015]
v. 1.2.x -> 1.4.2 migration bug: missing right padding for the input element's prepend slot:

Old:
![Screenshot_20220628_175034](https://user-images.githubusercontent.com/9782236/176210170-37fefc49-9590-4dbd-b78b-4bab3f5e4eb9.png)

New:
![Screenshot_20220628_175046](https://user-images.githubusercontent.com/9782236/176210233-dc265bb7-0ba4-43f0-bf7b-d93dbc280723.png)

**Comment by smellyshovel** [comment]
@aluarius
![Screenshot_20220630_135306](https://user-images.githubusercontent.com/9782236/176660113-375e22e9-8b8b-4503-b055-2e1b7fb93bd4.png)

Check please also this case.

**Comment by smellyshovel** [comment]
@aluarius It's when the append slot is used:

`                 <va-input v-model="withButton" placeholder="Input With Button">
                    <template #append>
                      <va-button style="margin-right: 0" small> UPLOAD </va-button>
                    </template>
                  </va-input>`

**Comment by aluarius** [comment]
> @aluarius ![Screenshot_20220630_135306](https://user-images.githubusercontent.com/9782236/176660113-375e22e9-8b8b-4503-b055-2e1b7fb93bd4.png)
> 
> Check please also this case.

Should be fine now.

![](http://dl3.joxi.net/drive/2022/06/30/0045/3830/2965238/38/bc64d6388e.jpg)
