### ISSUE TITLE
Cards with images on-image-text contrast

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#2017]
v1.2 -> v1.4.2. Consider contrast-ration changes. The green and red cards look OK to me, but the text on the image is IMHO unreadable.

Old:
![Screenshot_20220628_180639](https://user-images.githubusercontent.com/9782236/176214218-3fabf016-412e-4590-ad8c-942a3885000c.png)

New:
![Screenshot_20220628_180652](https://user-images.githubusercontent.com/9782236/176214276-c7e3a22a-0688-4606-aae8-969ba4e55908.png)

**Comment by smellyshovel** [comment]
See the "WITH TITLE ON IMAGE" text.

**Comment by smellyshovel** [comment]
Not 100% a bug. If it's intended so then I just need a confirmation of that.

**Comment by aluarius** [comment]
Solved while grooming.

**Comment by m0ksem** [comment]
Yes. We need color helpers. `class="text--white"`.
