### ISSUE TITLE
Strange border-radii for collapses

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#2021]
UI v 1.2.x -> 1.4.2 comparison. Strangely-looking and behaving border radii for the collapse elements.

Old
![old-radii](https://user-images.githubusercontent.com/9782236/176386804-7a394352-55af-41b2-b41c-e0d1f551db73.gif)

New
![new-radii](https://user-images.githubusercontent.com/9782236/176386961-d7ab2f0e-666a-44ee-98e0-a5c90a81ec6b.gif)

It feels to me like it would make much more sense if there would be no border-radius at the bottom when the collapse is opened and the same bottom radius as at the top when it's closed. I.e. vice-verse from what it's now.

**Comment by m0ksem** [comment]
@xx13, how we can deal with it? Do we even need colored background?

**Comment by smellyshovel** [comment]
@aluarius what about the radii? Will there be any fixes until the patch release?
