### ISSUE TITLE
Sidebar issues

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#2028]
1.2 -> 1.4

**Old**:
Correct cusor shape on collapsed:
![Screenshot_20220630_134250](https://user-images.githubusercontent.com/9782236/176658218-de293d66-8a22-4ce5-bffe-c58f2e051281.png)

Correct highlighting for selected:
![Screenshot_20220630_134314](https://user-images.githubusercontent.com/9782236/176658278-7947a911-c7cf-45f6-ad0e-415726666532.png)

Correct text color:
![Screenshot_20220630_134330](https://user-images.githubusercontent.com/9782236/176658335-f4ee2b62-f3dc-4bc5-b808-73c268e21399.png)

**New**:

No pointer cursor shape:
![Screenshot_20220630_134403](https://user-images.githubusercontent.com/9782236/176658422-57894f05-5d66-4d5c-84b0-e3c198f8d1fc.png)

Highlights selected item. Should not.
![Screenshot_20220630_134429](https://user-images.githubusercontent.com/9782236/176658491-fcebf27b-9ba8-4bac-8ca5-8fc84919f6c5.png)

Incorrect text color when highlighted (see screenshot above).

**Comment by smellyshovel** [comment]
Also the sizes. These rows have become larger than they used to be. Not sure that the issue comes from the UI package, but knowing that nithing's changed on the Admin side, it should be the UI's issue. Please, check.

**Comment by m0ksem** [comment]
This is fixed [here](https://github.com/epicmaxco/vuestic-ui/pull/1865), but we need to fix even before 1.5.0.

**Comment by smellyshovel** [comment]
@m0ksem, Not sure if the following thing is taken care of in the PR you've mentioned, but also need to resolve the wierd opacity 0 for minimized sidebar:
![Screenshot_20220704_194343](https://user-images.githubusercontent.com/9782236/177186651-197a5006-b57d-4d28-b166-e1c414c3ac55.png)

For some reason it's specified explicitly here

![Screenshot_20220704_194457](https://user-images.githubusercontent.com/9782236/177186737-6aed9b5f-1e6a-4c80-9532-1340f646123a.png)

And Git blames Vitaly for that. @RVitaly1978, would you please give it a look?
