### ISSUE TITLE
Missing fonts for popovers

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-ui#2033]
Popovers use some wierd fonts by default. My browser is configured to use sans- families for missing fonts by default, but it seems to me like popovers are configured for some reason to use serif- fonts by default. Please, check this one.
![Screenshot_20220630_182901](https://user-images.githubusercontent.com/9782236/176716801-e2e44d7d-401c-4c41-80f5-99ace0a45684.png)

**Comment by smellyshovel** [comment]
@aluarius would you please give it a look until the new version's coming?

**Comment by m0ksem** [comment]
Likely this issue exists in any dropdown.

**Comment by smellyshovel** [comment]
@m0ksem doesn't seem like so ti me. Maybe the fonts are redefined somewhere in admin locally, but anyway it seems to me that the issue only affects popovers.
