### ISSUE TITLE
`VaTimeInput` text field jumps after clearing

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#2054]
**Vuestic-ui version:** 1.4.5

- text field (without explicitly set width) jumps after clearing
![chrome-capture-2022-6-7](https://user-images.githubusercontent.com/55198465/177711279-d8a25572-fc4e-4730-a948-ac258ac0641f.gif)

**Comment by rustem-nasyrov** [comment]
It's look like a common problem with `VaInput` component.

**Comment by rustem-nasyrov** [comment]
@RVitaly1978, @m0ksem do we need to reserve space for the `icon` slot in the VaInpuWrapper component when the `icon` slot is used?

**Comment by m0ksem** [comment]
> @RVitaly1978, @m0ksem do we need to reserve space for the `icon` slot in the VaInpuWrapper component when the `icon` slot is used?

We can have two icons in text field. For example, clear icon and failed validation icon. The easiest solution is to set width: 100%; max-width: 400px;

**Comment by rustem-nasyrov** [comment]
@m0ksem I've tested it now, and it doesn't fix it.

**Comment by rustem-nasyrov** [comment]
Fixed here: https://github.com/epicmaxco/vuestic-ui/pull/2063
