### ISSUE TITLE
Doc `Sidebar` has weird border on active

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#2055]
**Vuestic-ui version:** 1.4.5

![chrome-capture-2022-6-7 (1)](https://user-images.githubusercontent.com/55198465/177712812-81c07b1c-0a8f-4db2-9a9c-22e70ca155a7.gif)

**Comment by m0ksem** [comment]
Simply removed this extra yellow outline, because we have background on the focused element.
