### ISSUE TITLE
Range slider is changeable even without v-model.

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2073]
**Vuestic-ui version:** 1.4.6

**Steps to reproduce**

* Use this syntax:

  ```html
  <va-slider :model-value="[20, 80]" range />
  ```

* Click on slider in range
* See:

  <img width="443" alt="image" src="https://user-images.githubusercontent.com/5394573/178250319-f4413d50-5087-47a9-8c72-ec54bcfd1d8d.png">

**What is the expected behavior?**

* Click shouldn't change anything visually.

**Comment by arkmadj** [comment]
@asvae I don't really understand. Can you explain a bit more?

**Comment by arkmadj** [comment]
Yeah. I can see the issue now. Thanks
