### ISSUE TITLE
VaSwitch `@input` event doesn't work

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2074]
**Vuestic-ui version:** 1.4.6
We have it stated in the docs
<img width="851" alt="image" src="https://user-images.githubusercontent.com/5394573/178253860-e585a741-5261-49af-80fe-94479e14b881.png">

but I tried in demo to 

```
<va-switch
        v-model="value"
        @update:model-value="$vb.log('@update:model-value', value)"
        @input="$vb.log('input', $event)"
      />
```
and `@input` event was never getting triggered. It should return native event btw.

## Bonus points
* Consider adding change event (is it useful?). Maybe we only need `@change`?
----
So this issues is about native events. If switch doesn't have input event or something - you don't have to use it.

**Comment by m0ksem** [comment]
Likely junk from vue2.
