### ISSUE TITLE
Remove root div from examples

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2080]
![image](https://user-images.githubusercontent.com/23530004/162320008-0f4035bb-bca2-4243-bc0c-361975f110f3.png)

Also, we don't need a root div anymore in vue3.

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/issues/698#issuecomment-1092214567_

**Comment by brunorabelo** [comment]
Thank you!
