### ISSUE TITLE
How can I pass Vuestic UI element in child component in slot

### ISSUE THREAD

**Issue by kamleshdarteweb** [epicmaxco/vuestic-ui#2083]
I am trying to write reusable code. I want to  pass Vuestic UI element in child component in slot so please share idea how can i do this

**Comment by m0ksem** [comment]
Sorry, I don't understand your question or issue you struggle with... 

There mustn't be any issue with passing Vuestic components into slots. 

If you need help, you can visit our [discord server](https://discord.com/invite/u7fQdqQt8c) and describe your problem in details with some examples.
