### ISSUE TITLE
Add missing props description

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#2095]
- [ ] Add missing description
- [ ] _Optional_: add missing examples

**Subject**:
Some `props` descriptions are missing - for example [Input date](https://vuestic.dev/en/ui-elements/date-input#api):
![missingPropsDescription](https://user-images.githubusercontent.com/7745899/178966489-8e34f376-a816-406f-b46d-20a31a2a1d0e.jpg)

Check other similar cases as well.

Would be great to have additional examples of less intuitive `props`, but this is optional.

**Comment by xiongmao86** [comment]
I am trying to solve this issue lately. @m0ksem, thanks.
