### ISSUE TITLE
Use vite for development build

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2099]
Currently we use vite for production build, but development build uses vue-cli.
We can use vite for both.

One issue is vue book. Here's how you can use it in vue 3 (consult @asvae if something is not clear):

```js
// vue-book doesn't support vite out of the box,
//  got to pretend we're webpack 😈.
const getRequireContext = () => {
  const glob = import.meta.globEager('../components/**/*.demo.vue')
  const requireContext: any = function (key: string) {
      console.log('glob[key]', glob[key])
      return glob[key]
    }
  ;(requireContext as any).keys = () => Object.keys(glob)
  return requireContext
}

const routes = [
  createRoute({
    requireContext: getRequireContext(),
    path: '/demo',
  }),
  {
    path: '/:pathMatch(.*)*',
    redirect: '/demo',
  },
]
```

- [ ] Replace `vue-cli` with `vite` for development
- [ ] Make sure `vue-book` works fine.
- [ ] Replace all commands in `package.json`s
- [ ] Remove `vue-cli` deps.

**Comment by m0ksem** [comment]
Let's migrate to Histoire instead :)
