### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by jean-moldovan** [epicmaxco/vuestic-ui#21]
# Docs

- [ ] Do after [docs boilerplate](#17) is done.

# Props

## List
- [x] `separator: Boolean`
- [x] `bordered: Boolean`

## List Item
- [x] `to: String/Object` support vue-router
- [x] `exact/append/replace: Boolean` support vue-router
- [x] `tag: String` use 'label' with checkbox/radio
- [x] `clickable: Boolean`

## List Item Section
- [x] `avatar: Boolean` reserve space for an avatar 48px
- [x] `side: Boolean` reserve space for an icon 24px

## List Item Label
- [x] `caption: Boolean` small text
- [x] `lines: String/Number` apply ellipsis based on the number of lines

# Design
- [ ] Present to @xx13 after finishing.

# Refs
* [Quasar](https://quasar.dev/vue-components/list-and-list-items)
* [Vuetify](https://vuetifyjs.com/en/components/lists)

**Comment by asvae** [comment]
Should include expansion list
