### ISSUE TITLE
Use ts or tsx for build scripts 

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2100]
We want to have one approach for script handling.

See https://github.com/epicmaxco/vuestic-ui/pull/2081#pullrequestreview-1039277152

- [ ] Do for `1.5.0`, then cherrypick to develop.

**Comment by m0ksem** [comment]
zx removed and we use tsx 👍

**Comment by aluarius** [comment]
> zx removed and we use tsx 👍

Wasn't here an idea to type deeply whole build script?

**Comment by m0ksem** [comment]
> > zx removed and we use tsx 👍
> 
> Wasn't here an idea to type deeply whole build script?

We have only vite config with `.js` ext. Ins't it okay?

**Comment by aluarius** [comment]
Asva has talked smthg about this, will ask tomorrow.
