### ISSUE TITLE
Analyse vuestic features in context of our competitors

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2111]
We want vuestic to be great. For that - it has to cover most users needs. Ideally do almost everything other solutions on the market do already. Right now we don't have a clear understanding of how much work would be needed to reach that state.

- [x] Create a component list, that are missing in vuestic, but present in competitor's solutions. Assign a priority for each of them from your perspective
- [x] Add existing vuestic components to the list and define their current state. Are there crucial features missing?

We kinda already have a [list](https://www.notion.so/epicmax/Vuestic-ui-10e698cacd5846688647e1d8482277c9#88519b644b054376b00421971bcfb2ed), so that seems like an ideal place to work on this issue, but up to you.

**Comment by aluarius** [comment]
Everything is in Notion now.
