### ISSUE TITLE
.md support for docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2112]
The idea is to have version of documentation, that doesn't support translations and is less powerful, but is very easy to work with as a developer. This documentation could be used for internal things, such as composables, tests, analytics etc. We could also move some things from notion.

For usage - it won't be that different from our current documentation. It would have a route on https://vuestic.dev/, maybe slightly hidden.

- [ ] Provide a way to use md documentation (maybe as a documentation block?)
- [ ] Connect existing md files to that documentation
- [ ] document this approach in contribution docs

**Comment by m0ksem** [comment]
We don't need to make user (us) able to write docs in Markdown. With Markdown, we're losing a lot of blocks and typescript support. It will make us lazy to write good docs.

```js
export default [
  block.markdown(`
  # Release notes
  
  ### v1.5.0 
  
  brrrrrrrrrrrrrrrrrrrrrr
  `)
]
```

or
```ts
import md from 'page.md?raw'

export default [
  block.markdown(md)
]
```

**Comment by asvae** [comment]
This looks pretty much as what I imagined 🤗
```
import md from 'page.md?raw'

export default [
  block.markdown(md)
]
```
