### ISSUE TITLE
Automated accessibility checks

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2121]
Run accessibility automated checks agains docs and demos.

The intention is to prevent regression as well as keeping consistent quality (accessibilty-wise) for new functionality.

- [ ] Integrate as part of release script.

**Comment by asvae** [comment]
@aluarius would you consider that to be useful, or majority of accessibility work requires manual tinkering?

**Comment by aluarius** [comment]
Only keyboard accessibility needs manual tinkering.

For aria-attributes checks we can use https://github.com/dequelabs/axe-core (refs: https://www.deque.com/blog/writing-automated-tests-accessibility/ , https://www.telerik.com/blogs/the-need-for-automated-accessibility-testing) or one of its child scripts: https://github.com/nickcolley/jest-axe , https://github.com/vue-a11y/vue-axe

**Comment by aluarius** [comment]
I don't think we need to integrate it as a part of release script because it just an another one type of code testing. We can join it with writing components tests.

**Comment by m0ksem** [comment]
We can write accessibility tests as well as unit tests. 
Let's make this task in scope of https://github.com/epicmaxco/vuestic-ui/issues/1685
