### ISSUE TITLE
Accessibility guide

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2122]
We can do this in docs after md support (#2112) is implemented. There is no need for translation as this is intended for developers.

- [x] Write accessibilty guide in docs.
- [x] Add a short checklist to [notion](https://www.notion.so/epicmax/Vuestic-ui-10e698cacd5846688647e1d8482277c9#f10c56baffde4b62826cb90aad02fe5a) + link a guide

* My idea is that we're mostly worried about new components. I.e. what kind of checks developer have to perform to ensure a component follows high accessibility standards.

**Comment by aluarius** [comment]
https://www.notion.so/epicmax/Vuestic-ui-10e698cacd5846688647e1d8482277c9#f10c56baffde4b62826cb90aad02fe5a
