### ISSUE TITLE
Recommended setup for using vuestic with jest

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2123]
Is there no recommended setup for using vuestic with jest? What unit tests are used for vuestic internally? I've tried registering the VuesticPlugin as a global plugin in mount, and registering individual components when mounting, neither worked.

_Originally posted by @StephenBaione in https://github.com/epicmaxco/vuestic-ui/issues/1685#issuecomment-1107529823_

Some users might want to unit test their components that use vuestic components internally. We want to check if that's possible to do and provide instruction in docs.

- [ ] Try to test vuestic components in fresh project.
- [ ] Document your process.

**Comment by adam-of-barot** [comment]
I started up a fresh project with `npm init vue@latest` with vitest support, installed vuestic-ui, and managed to get some _very_ basic tests running with the Vuestic components.

Setup documentation:
1. Create a project with `npm init vue@latest`. Add vitest support during the setup.
2. `npm install vuestic-ui`
3. Create a `vuestic` subfolder
4. Create an `index.js` in that folder.
```javascript
// vuestic/index.js
import { createVuestic } from "vuestic-ui";

const vuestic = createVuestic()
export default vuestic
```
5. Create the folowing `vitest.config.js` in your src folder.
```javascript
// vitest.config.js
import { defineConfig } from "vitest/config"
import Vue from "@vitejs/plugin-vue"

export default defineConfig({
  plugins: [Vue()],
  test: {
    environment: "jsdom",
  },
})
```
6. Install vuestic into the Vue app
```javascript
// main.js
import { createApp } from 'vue'
import App from './App.vue'
import vuestic from './vuestic'

import './assets/main.css'
import 'vuestic-ui/css'

createApp(App).use(vuestic).mount('#app')
```
7. Add a Vuestic component to the existing `components/HelloWord.vue` file. I used a `<va-button>Test button</va-button>`
8. Modify the existing `components/__tests__/HelloWorld.spec.js`
```javascript
// components/__tests__/HelloWorld.spec.js
import { describe, it, expect } from 'vitest'

import { mount } from '@vue/test-utils'
import HelloWorld from '../HelloWorld.vue'
import vuestic from '../../vuestic'

describe('HelloWorld', () => {
  it('renders properly', () => {
    const wrapper = mount(HelloWorld, {
      props: { msg: 'Hello Vitest' },
      global: {
        plugins: [vuestic]
      }
    })
    expect(wrapper.text()).toContain('Test button')
    expect(wrapper.text()).toContain('Hello Vitest')
  })
})
```

**Comment by m0ksem** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/2254
