### ISSUE TITLE
Select is doing paralax

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2125]
**Vuestic-ui version:** 1.4.6

**Steps to reproduce**
https://vuestic.dev/

<img width="365" alt="image" src="https://user-images.githubusercontent.com/5394573/180160130-a34eda7c-d116-4a26-85d0-310c0b2c231b.png">

**What is the expected behavior?**
No paralax for select dropdown

**What is the current behavior?**

**Other information**

**Comment by m0ksem** [comment]
Likely fixed here: https://github.com/epicmaxco/vuestic-ui/pull/2109

Need to double-check.
