### ISSUE TITLE
Allow us to change the CSS that's injected into Nuxt

### ISSUE THREAD

**Issue by Luffyyy** [epicmaxco/vuestic-ui#2130]
**Is your feature request related to a problem? Please describe.**
Version 1.4.7 introduced a way to choose which CSS file you'd like to include, this unfortunately hasn't been done for Nuxt yet.

**Describe the solution you'd like**
An option in VuesticOptions like 'css' that would override the default behavior.

**Describe alternatives you've considered**
Not including styles and forcing the developer to do so by themselves.

**Additional context**
https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/nuxt/src/module.ts#L38

**Comment by m0ksem** [comment]
Yeah. The same must be done with components, so user can select which components to use.
