### ISSUE TITLE
Actions for examples are taking too much space

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2160]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/5394573/181048520-fb983175-b1b4-4ea7-ad2e-29e810c04ee1.png">

I suggest we use only icons for smaller screen sizes, so that it stays on one line.

Also codesandbox icon seems to be missing, so would be great if you can fix that as well.

**Comment by m0ksem** [comment]
Codesandbox likely fixed here: https://github.com/epicmaxco/vuestic-ui/pull/2157

**Comment by asvae** [comment]
@m0ksem doesn't seem so, looking at pr.

**Comment by m0ksem** [comment]
> @m0ksem doesn't seem so, looking at pr.

We'll need to release it to work on codesanbox on Thursday :)

**Comment by m0ksem** [comment]
We can hide "Open in sandbox" and "Copy code" for mobile. It is useless on mobile anyway.
