### ISSUE TITLE
Make dropdown specs for developers

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2171]
Even I don't understand what's going on here.

**Comment by m0ksem** [comment]
![image](https://user-images.githubusercontent.com/23530004/181627128-4647cc5c-60ed-451f-b97f-323f3845174e.png)

I'm not sure, but looks like we have some strange formula... Because, we don't need to calculate root, actually.

**Comment by m0ksem** [comment]
I got it. We need `viewport` to react if content have overflow for auto-placement and stick-to-edges. But from `root` we calculate position.

- viewport - container with overflow hidden.
- root - relative container which content will be positioned. 

![image](https://user-images.githubusercontent.com/23530004/181629414-5e40211a-7a3c-4d3c-8e78-8808b956d98b.png)

**Comment by rustem-nasyrov** [comment]
@m0ksem, we need to decide where to place a markdown assets, i.e. images, gif, etc. Is it okay to place them in the same directory where is a md file under the `assets` directory?

**Comment by m0ksem** [comment]
> @m0ksem, we need to decide where to place a markdown assets, i.e. images, gif, etc. Is it okay to place them in the same directory where is a md file under the `assets` directory?

Yeah. If we have following structure it is okay:

page-config/va-component/ma
  - spec.md
  - assets
     - map.png
     - thing.svg
