### ISSUE TITLE
Docs header markup

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#2173]
**Vuestic-ui version:** 1.4.7
 
1. Bug in our docs header markup on mobile

https://user-images.githubusercontent.com/55198465/181690910-336ab7d8-249d-47a1-8525-81253cec6b54.mov

2. We want the search input collapsed by default and expanded (with absolute position and z-index) when focused.

**Comment by m0ksem** [comment]
We'll need to hide this input under search icon-button.
