### ISSUE TITLE
Use ellipses at the end in select placeholder

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2178]
![image](https://user-images.githubusercontent.com/23530004/181748581-ea39028c-112f-4289-80c5-144bde26958a.png)

We have va-ellispeses SCSS mixin. Find it somewhere...

**Comment by rustem-nasyrov** [comment]
I think it should depend on the max-value length or something.

**Comment by aluarius** [comment]
We need to discuss, what behaviour we want for `VaSelect` long placeholders, multi select text & chip content.

Now it's just growing (as vuetify and quasar do). Maxim suggested to add ellipsis-buttons for expanding (or scroll).

Should decide and/or ask Vasiliy.
