### ISSUE TITLE
Icon died 🪦

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2182]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/5394573/181855680-3ff17d0b-e3a1-4be9-ba0c-0ea1a3c6fda5.png">

<img width="258" alt="image" src="https://user-images.githubusercontent.com/5394573/185353530-cc9e1385-5eaf-4644-a5e3-75e9fa3386aa.png">

**Comment by m0ksem** [comment]
![image](https://user-images.githubusercontent.com/23530004/181859340-d519d627-3b5f-4318-ac3c-c729ad0084d0.png)
