### ISSUE TITLE
Tailwind transition overthinking

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2184]
We decided to have 1st class tailwind support, so we'd scrape some of our helpers, and just link tailwind solutions instead. That's not an easy process so let's think it over.

* Typography - there is a typography plugin for tailwind (https://play.tailwindcss.com/uj1vGACRJA?layout=preview), also typography doesn't go out of the box for tailwind. So we probably can keep our solution and it's overall a good fit
* [Colors](https://tailwindcss.com/docs/customizing-colors) - not exactly clear on implementation, but we're probably looking to integrate tailwind config with vuestic config.
* [Breakpoints](https://tailwindcss.com/docs/screens) - we're looking for some kind of integration with tailwind solution. As we can't rely completely on tailwind here.
* Grid - We should separate smart (vuestic) grid classes and tailwind. Both could be used at once though.
* [Dark theme](https://tailwindcss.com/docs/dark-mode) - again, would be nice to have a way to combine both, but not sure if that's possible.
* [Reset](https://tailwindcss.com/docs/preflight) could also become a bit of an issue. (maybe not - if we don't use it for vuestic components at all)

----

* Might make sense to introduce **vuestic-tailwind-plugin** to keep all tailwind integration in one place. Or maybe as an optional service?

### Relevant issues
These should ideally be handled in context of this issue.
* #665
* #731
* #764

**Comment by asvae** [comment]
We decided to use tailwind and not to use tailwind for vuestic component.

![image](https://user-images.githubusercontent.com/5394573/209569471-f94edf05-3a3c-4369-ab0e-8c0e30c81b9f.png)

**Comment by asvae** [comment]
![image](https://user-images.githubusercontent.com/5394573/209572522-7f0cb603-be36-4307-b669-7e0996e11a2a.png)

**Comment by m0ksem** [comment]
@asvae, @aluarius done?

**Comment by aluarius** [comment]
Imo yes, can't see anything else to do here.
