### ISSUE TITLE
Add eslint-plugin-vue-i18n

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2185]
https://eslint-plugin-vue-i18n.intlify.dev/rules/no-unused-keys.html#rule-details

**Comment by asvae** [comment]
Do we need this at all? Looks to me that some custom utility would be much more useful compared to external tool.

**Comment by m0ksem** [comment]
Yeah. Eslint plugin will not help us here.

**Comment by asvae** [comment]
Closing then 🤨
