### ISSUE TITLE
Issue with Nuxt build on production. 

### ISSUE THREAD

**Issue by scottmilla** [epicmaxco/vuestic-ui#2192]
**Vuestic-ui version:** 1.4.8

**Steps to reproduce**
Upgrading from Vuestic version 1.4.1 (had to lock here for Prod to work)
**What is the expected behavior?**
The vuestic styling to work as below.
<img width="1113" alt="Screen Shot 2022-08-01 at 12 16 50 PM" src="https://user-images.githubusercontent.com/21327095/182195305-61a8bfe3-cf64-491f-bd04-ad0fa8bd4688.png">

**What is the current behavior?**
Much of the styling is broken. Buttons full screen length, selects and inputs not full width in a full width form, etc..
![Screenshot 2022-08-01 at 08 09 15](https://user-images.githubusercontent.com/21327095/182195487-6cdd39a9-0ce8-471d-9cce-f751a18190e2.png)

**Other information**

**Comment by m0ksem** [comment]
Hey. Add following into nuxt.config.ts

```
vuestic: {
   css: ['reset', 'typography', 'grid']
}
```

This issue will be fixed in vuestic-ui@1.4.9.
