### ISSUE TITLE
VaButton semantics look weird

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2194]
![image](https://user-images.githubusercontent.com/5394573/182212682-20212282-65f3-4cad-ab69-dabec1783aa8.png)

- [ ] speaking of `href(unknown) target to`, `active-class`, `exact-active-class`
- [ ] Bonus points for checking other components for similar weirdness

**Comment by aluarius** [comment]
Anyway, all changes will be overwritten in 1.5.0 with new implementation.

P.S. Will check 1.5.0 branch buttons for this issues.

**Comment by m0ksem** [comment]
P.P.P.S I suggest closing it as not planned.
