### ISSUE TITLE
VaSplit drag is still hellish on mac

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2195]
That probably applies to other drag things on mac, so would be great to solve it here and maybe do quick information on how dragging is to be implemented on mac henceforth. (I noticed similar problem with other libraries)

https://user-images.githubusercontent.com/5394573/182220023-55451d97-b9f0-4576-90af-9b8e377ab70a.mov

**Comment by aluarius** [comment]
Solving in https://github.com/epicmaxco/vuestic-ui/pull/2068
