### ISSUE TITLE
Vue book upgrade

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2196]
I don's see a particular need to switch to storybook (there are upsides, but there are also downsides). I.e. storybook is very close to what we have in docs (and with introduction of playground it would be even more so). While vue-book is niche robust developer tool. But we need to give some love to vue-book as it didn't see any for a while.

* https://github.com/asvae/vue-book/milestone/1
* #701

**Comment by m0ksem** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/2924
