### ISSUE TITLE
Avatar component

### ISSUE THREAD

**Issue by jean-moldovan** [epicmaxco/vuestic-ui#22]
# Docs

- [ ] Do after [docs boilerplate](#17) is done.

# Props
- [ ] `size: String`
- [ ] `color: String` - use theme plugin
- [ ] `text-color: String` - use theme plugin
- [ ] `square: Boolean`
- [ ] `icon: String`
- [ ] `src: String`

# Slots
- [ ] `default` - intended to pass down symbol or string or or image url

# Design
- [ ] Present to @xx13 after finishing.

# Notes
- [ ] Check to work with badge (see iView)
- [ ] Text in avatar should be automatically scaled depending on size (see iView)
- [ ] Native events should be propagated.
- [ ] Test (in demo) `v-icon` and `img` via slot (this is needed for complex icons and img attributes, such as `alt`)

# Refs
* [Quasar](https://quasar.dev/vue-components/avatar)
* [Vuetify](https://vuetifyjs.com/en/components/avatars)
* [iView](http://iview.talkingdata.com/#/components/avatar-en)

**Comment by asvae** [comment]
@jean-moldovan 

Thanks for tickets. I did several additions.

I'm not sure which of two is better:
1 - add url prop and pass down img props,
2 - or just pass img via slot.

1 is obviously less to write. But do we have any reasons to work with img tag directly perhaps?
