### ISSUE TITLE
Service for auto keyboard focus outline style

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2200]
Idea is to make an optional service which will add `focus-outline` style to the every element with `tabindex >= 0` selected from keyboard (via `Tab`).

This will solve several problems:
- no more need to make sure every time that every interactive element has focused style state;
- we don't want elements to have `focus-outline` style via mouse/touchpad (it makes no sense).

**Comment by asvae** [comment]
Ideally we want to use composable and no service.

We also never need focus-outline without keyboard navigation, so it makes no point to make it a flag. We should only use this outline on keyboard navigation.

**Comment by asvae** [comment]
We want to get rid of highlight to next big release. It's incredibly annoying (played with file upload and tree view).

**Comment by aluarius** [comment]
> We want to get rid of highlight to next big release. It's incredibly annoying (played with file upload and tree view).

To get rid at all? This will ruin half of accessibility. I've suggested to apply `focus-outline` style only for items, selected via keyboard, not via mouse or touchpad, because i'm agree that focus state style via mouse makes no sense and annoying - isn't that enough?

**Comment by m0ksem** [comment]
> > We want to get rid of highlight to next big release. It's incredibly annoying (played with file upload and tree view).
> 
> To get rid at all? This will ruin half of accessibility. I've suggested to apply `focus-outline` style only for items, selected via keyboard, not via mouse or touchpad, because i'm agree that focus state style via mouse makes no sense and annoying - isn't that enough?

We need it as keyboard focus service. 
Speaking about file-upload we need to remove outline from file completely. 
![image](https://user-images.githubusercontent.com/23530004/183449926-ca07f417-77ed-4a42-876d-dbc98b1fc811.png)

**Comment by asvae** [comment]
We need a composable, that should be imported in each component and handle focus behavior.

**Comment by aluarius** [comment]
Close via https://github.com/epicmaxco/vuestic-ui/pull/2248
