### ISSUE TITLE
create-vuestic package

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2204]
The idea is to make users able to install vuestic with one command.

```bash
npx create-vuestic
```

This must ask user if he wants to use vuestic-admin or clean project.

- Use Vuestic Admin template? yes\no
- Use Nuxt3? yes/no
- Use tree-shaking?
  - Select CSS modules:
    - typography, grid, reset
  - Select plugins
    - breakpoints, css variables ???
    
see #1991

**Comment by asvae** [comment]
We have notion tasks for this. Maybe we can incorporate it here?
