### ISSUE TITLE
VaSelect remove key-by

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2207]
I hardly see any usage for that prop. Anything I can think of could be achieved by `track-by`, `text-by` and `value-by`.

**Comment by m0ksem** [comment]
We can make this instead https://github.com/epicmaxco/vuestic-ui/issues/2136.

**Comment by asvae** [comment]
VaOption list seems to use track-by as key-by, so beware 🤪.

**Comment by asvae** [comment]
We don't have key-by...
