### ISSUE TITLE
Update config documentation

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#2208]
- [ ] Update config docs for `components.all`
- [ ] Add `Presets` feature docs

**Description**:
We need to update config docs for `1.5.0` version because we made two big things there:
1. Added new feature - [Feat #1806: Presets for all components & components config structure change](https://github.com/epicmaxco/vuestic-ui/pull/1921).
2.  Made the breaking change by moving `componentsAll` feature to `components.all` and `componentsPresets` to `components.presets`.
(More info is here #1967)

To help you with that here is the **current config structure**:
```JS
{
  components: {
    all: { ... },
    presets: { ... },
  },
  colors: { ... },
  icons: { ... },
}
```

**Previous structure**:
```JS
{
  components: { ... },
  componentsAll: { ... },
  componentsPresets: { .. },
  colors: { ... },
  icons: { ... },
}
```

**Tips**:
To add `components.all` docs just rename \ correct this in the docs.

To add `Presets` docs you could use `VaConfig.demo` -> `Presets` as an example, in the `1.5.0` branch.
Also it is possible to use `Presets` with `VaConfig` component (local config).

**Side note**:
You could do this in the end of the `1.5.0` Milestone because there is a chance that I'll add this during free time.

**Comment by asvae** [comment]
Can we check if all requirements are met in current state and close this? @aluarius

**Comment by aluarius** [comment]
> Can we check if all requirements are met in current state and close this?

@asva Not, current state must be reworked. I'll deal with it today.
