### ISSUE TITLE
Scoped config code example

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#2209]
[Scoped config code example](https://vuestic.dev/en/services/components-config#scoped-config) has incorrect code alignment.
Looks weird, just fix tabs there.

![codeExampleScopedConfig](https://user-images.githubusercontent.com/7745899/183312344-77a90180-ba22-4ffe-84a2-83146d30d1a0.jpg)

**Comment by aluarius** [comment]
Already fixed:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/64714442/203515916-a7e0d97d-5a13-4137-ba29-f35483c0bfe5.png">
