### ISSUE TITLE
`VaDropdown` related components `disabled` state style

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2210]
From discussion with Vitaly related to https://github.com/epicmaxco/vuestic-ui/pull/2191 - who should apply disabled state:

dropdown via disabled prop (current implementation). Arguments for this option: simple implementation scheme. Disabled state for component using VaDropdown by default. Against: not flexible.
anchor component via disabled prop transfered from VaDropdown to anchor slot (VaDropdown applies disabled style no more at all): component -> dropdown -> anchor -> anchor component -> disabled style. Arguments for this option: flexibility. Against: it's very unlikely that different component will have different disabled style.

**Comment by asvae** [comment]
v-on v-bind would work nicely here.

**Comment by m0ksem** [comment]
I like how it works now.
