### ISSUE TITLE
Remove focus from VaFileUpload list item

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2212]
Speaking about file-upload we need to remove outline from file completely. 
![image](https://user-images.githubusercontent.com/23530004/183449926-ca07f417-77ed-4a42-876d-dbc98b1fc811.png)

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/issues/2200#issuecomment-1208249389_

Let's have it only for remove button. List doesn't need to be focused. Maybe we need to remove focus from VaListItem as well.

**Comment by asvae** [comment]
Non interactive elements shouldn't be focusable. Unless they're actionable/selectable (which could be a prop).

**Comment by aluarius** [comment]
Already changed.
