### ISSUE TITLE
VaSelect scrolls the page

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2213]
**Vuestic-ui version:** 1.4.9

**Steps to reproduce**
In [select docs](https://vuestic.dev/en/ui-elements/select#base-layout) click on "single select", then scroll down and click on "hide selected".

**What is the expected behavior?**
No scroll would happen.

**What is the current behavior?**
Scroll is forced to "single select". Page visually jumps.

**Other information**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/5394573/183582998-a874cf81-65de-4242-8528-b7572303c984.png">

**Comment by m0ksem** [comment]
@asvae, can I ask you to double-check this? Looks like fixed for me.

**Comment by aluarius** [comment]
Same for me, seems to be already fixed. Will reopen if the problem will appear again.
