### ISSUE TITLE
Aspect ratio wrapper

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2227]
Little but useful feature.

Refs: https://vuetifyjs.com/en/api/v-responsive/, https://v1.quasar.dev/vue-components/responsive

Also suitable for `VaImage`.

Mb option for `VaContent`?
Mb other responsive features for `VaContent` (https://vuetifyjs.com/en/api/v-responsive/#props)?

**Comment by asvae** [comment]
Let's do a bit of research on this.

It seems we need this functionality for at least 3 components: card, image, carousel. So it might make sense to extract it into a component.
