### ISSUE TITLE
`VaDataTable` popup cell edit feature

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2231]
Ref: https://quasar.dev/vue-components/popup-edit#persistent-and-with-buttons

**Comment by asvae** [comment]
I think we can make this as an example and not add any new props to table.

The way it should work:
* On click - throw event with ref with dom node
* Pass dom node to popover as anchor
* Modify data on button click.

**Comment by m0ksem** [comment]
We have example with VaValue component.
