### ISSUE TITLE
Virtual scroller

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2236]
Also mb we want to implement intersection component, base on virtual scroll.

Virtual scroll is also suitable for `VaSelect`, autocomplete, data table and other components with potentially long lists.

Refs: https://quasar.dev/vue-components/intersection & https://vuetifyjs.com/en/components/virtual-scroller/#usage

**Comment by asvae** [comment]
First priority should be virtual scroll component. - needs discuss

Then apply said component to other componens that might benefit from it.

Then intersection if we decide it makes sense. - needs discuss

**Comment by aluarius** [comment]
Moved to separate issues.
