### ISSUE TITLE
Add dropdown props to DateInput, TimeInput, Select

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2237]
- [ ] VaDateInput
- [ ] VaSelect
- [ ] VaTimeInput

**Comment by thetejasmagade** [comment]
Your issue is not that much clear. Can, you please ellaborate more on this?

**Comment by m0ksem** [comment]
> Your issue is not that much clear. Can, you please ellaborate more on this?

Hi. We have some functions to proxy component props from child to parent. It is called something like extractComponentProps.

For example, we already extract props from VaInput and pass it as VaDateInput props. This makes user able to modify input props. 

The same thing must be done with VaDropdown, which used in VaDateInput. This way user will be able to pass props like placement, prevent-overflow, etc. to dropdown.
```
<va-date-input placement="top" color="#f0f" />
```
