### ISSUE TITLE
Stepper component

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2245]
Looks close to timeline, mb fast to implment.

Refs: https://vuetifyjs.com/en/components/timelines/ & https://quasar.dev/vue-components/stepper & https://vuetifyjs.com/en/components/steppers/

**Comment by asvae** [comment]
We currently have timeline component, but it's broken and old.

We probably want to create separate issues for stepper and timeline, where we can continue our planning.

**Comment by LighthouseKeeperYN** [comment]
I propose only implementing the actual stepper part without the content at least for now and wait for the feedback.

Props:
```
modelValue: number
steps: string[] 
showStepNumber?: boolean
vertical?: boolean
```
Slots: 
```
<slot name="stepIcon" />
<slot name="step-[i]" v-bind="{ text: steps[i] }" />
<slot name="separator" />
```

Events:
```
update:modelValue: number
```

We can provide examples on how to cover common cases via slots in documentation.

**Comment by asvae** [comment]
Maybe we can reuse some logic from tabs.
