### ISSUE TITLE
Dropdown position is broken after SPA route change in nuxt

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2250]
Reproduction: https://codesandbox.io/s/loving-hoover-phqo6c?file=/pages/index.vue

**Comment by Luffyyy** [comment]
Been pretty annoying lately, hope it gets fixed soon enough

**Comment by m0ksem** [comment]
> Been pretty annoying lately, hope it gets fixed soon enough

Sorry for that! It is going to be fixed ASAP, since we haven't released anything this week. For now, as a workaround, you can turn off `prevent-overflow`  prop for now.
```
  vuestic: {
    config: {
      components: {
        VaDropdown: {
          preventOverflow: true,
        }
      }
    },
  },
```
