### ISSUE TITLE
VaProgress max prop

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2253]
For now, max is hardcoded to be 100.

**Comment by asvae** [comment]
@m0ksem why is that a problem?

**Comment by m0ksem** [comment]
> @m0ksem why is that a problem?

I have a list of 44 elements and want to show its progress. So instead of

```vue
<va-progress-bar :model-value="completedCount" :max="count" />
```

I need to make this kind of ugly:

```vue
<va-progress-bar :model-value="100 / count * completedCount" />
```
It just makes user to think.
