### ISSUE TITLE
Codesandbox examples doesn't work

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#2257]
1. Open any documentation of any component
2. Click any codesandbox example
3. After initizalisation facing issue given in the screenshot below.

![image](https://user-images.githubusercontent.com/29167241/185137847-05652e69-2b4e-4cef-bd40-8ae99730cf2d.png)

**Comment by rustem-nasyrov** [comment]
@asvae can we close this?

**Comment by m0ksem** [comment]
> @asvae can we close this?

Same as https://github.com/epicmaxco/vuestic-ui/issues/2313 now.
