### ISSUE TITLE
Margin either of these buttons is off

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2262]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/5394573/185366956-4f2f38c6-885f-47da-b4a2-b30fcac422e7.png">

**Comment by Akidane47** [comment]
I'd like to work on this, I'm guessing you only want one button displayed?

**Comment by m0ksem** [comment]
> I'd like to work on this, I'm guessing you only want one button displayed?

Hey, sorry for lack of description 😄.

Horror here cause by alignment. 

BTW, this demo can be improved, you can change "Click me" to "Hover" and auto-hide can be removed here.

**Comment by aluarius** [comment]
Already fixed: 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/64714442/203502148-10c595aa-0020-4167-9632-c3e1dc4b418c.png">
