### ISSUE TITLE
(1.5.0) Button text color doesn't change after preset changed

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2269]
![firefox_CQMsYpsgik](https://user-images.githubusercontent.com/23530004/185616257-ff1163f9-0708-4b06-a51b-454855300666.gif)

Repo code in nuxt:

```vue
<template>
  <va-button :preset="preset" @click="onClick">Aaa {{ preset }}</va-button>
</template>

<script setup lang="ts">
const preset = ref('text');

const onClick = () => {
  preset.value =  preset.value !== 'secondary' ? 'secondary' : 'text';
}
</script>
```

Problem can be related to presets, buttons or useTextColor.

**Comment by aluarius** [comment]
Guess it's a presets service problem - it must switch preset to `default` if non-existing preset was passed ( it's just setting it and nevermind if it doesn't exist).

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2283
