### ISSUE TITLE
Make more meaningful CSS variables for user, not developer

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2276]
![image](https://user-images.githubusercontent.com/23530004/185786535-9deea8d7-9bd8-465c-9024-6d15329a0f82.png)

Why do we have progress-wrapper css variables? I just want to make `va-progress-border-radius: 0`. 

BTW we don't have square prop, so this is useless:
```css
  /* Square */
  --va-progress-bar-square-border-radius: 0;
```

**Comment by asvae** [comment]
In a couple of places - we have `--[a-z-]+--something` css variables. We can use only `-` (no bem).

For progress bar - we can discard `wrapper` word as it doesn't make sense for end user.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/5394573/186643426-c61758ef-5fc7-48c9-acda-207308102792.png">

**Comment by m0ksem** [comment]
In scope of this task we need to handle if we have general css variables for components. For example, for border radius we need to create general css variable, so VaCard and VaAlert has the same border radius (see https://github.com/epicmaxco/vuestic-ui/pull/1134)
![image](https://user-images.githubusercontent.com/23530004/187030678-46e4286e-0030-4b01-88f9-9efbd15ee273.png)

Same to box-shadow, font and other.
