### ISSUE TITLE
VaButton mustn't have margin 0 by default

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2277]
![image](https://user-images.githubusercontent.com/23530004/185791699-72e8ad26-2f6f-4fa1-a336-0a123e300d17.png)

Unable to override.

**Comment by asvae** [comment]
That's tricky to safeguard from component side. As we have different margins and paddings across the components.

So I think it would be easier to handle from perspective of CSS ordering.
