### ISSUE TITLE
Rename bundlers-tests to sandbox

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2280]
Add CLI commands

Running different environments:
```
sandbox:serve:vite
sandbox:serve:nuxt
sandbox:serve:vue-cli
```
This will makes us able to play with different bundlers. For now, we edit demos or docs to play with vuestic.

**Comment by asvae** [comment]
I would suggest not shorten words and use less commands on root level (maybe only one with prompt)
