### ISSUE TITLE
On hover - "Open in Github" button is barely visible

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2282]
All other buttons are ok.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/5394573/185955026-336fbc25-3c0c-4d82-9594-d08ed0449c5b.png">

**Comment by m0ksem** [comment]
> From which file is this exactly from ?

Hey, @Pathholder1806. This issue is related to DocsExample component. You can find reproduction on any demo we have in docs: https://vuestic.dev/en/ui-elements/alert#default

**Comment by Pathholder1806** [comment]
The issue is persisting with all the 'a tags'

**Comment by Pathholder1806** [comment]
So the issue is in the following file:
https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/styles/typography/_mixins.scss
Line number - 183

The value of brightness filter on hover is too high.

**Comment by Pathholder1806** [comment]
@m0ksem 
**filter: brightness(100%)** should fix the issue.
File - https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/styles/typography/_mixins.scss
Line - 183

**Comment by asvae** [comment]
Might be related to #2260. Global typography is giving us issues.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2288
