### ISSUE TITLE
`pattern` prop as alias to `rules` in inputs

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2284]
Likely, it would be easier for user to write pattern (regex), instead of creating rules="[(x) > /puk/.test(x)]".
Similar to: https://www.w3schools.com/tags/att_input_pattern.asp

I would love if we will have validation docs: pattern -> rules -> async rules. This way we have easy validation and more advanced each layer.

**Comment by asvae** [comment]
Let's check if we pass native `pattern` to input.
