### ISSUE TITLE
Presets docs

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2287]
Let's add an example to documentation with presets for variety of components to the preset docs page (where that makes sense):
* Inputs (email, password, url)
* Selects
* etc

```vue
<va-input preset="email" rules="[(v) => v.endsWith('epicmax.co') || 'Must have specific domain']" />
```

**Comment by asvae** [comment]
Merging presets could be an issue. They look similar to vue mixins, which is not that scalable of an approach.

I would also hope to solidify our foundation (do decent test coverage) before we move with that idea.

**Comment by m0ksem** [comment]
It's done, but requires a tutorial, which will be handled in different task
