### ISSUE TITLE
CSS helpers modifiers via '-' not '--' separator

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2296]
can we use one dash instead of two: 
```suggestion
          "xs": "`.gutter-1` - Extra small gutter between cells",
```

_Originally posted by @RVitaly1978 in https://github.com/epicmaxco/vuestic-ui/pull/2189#discussion_r953814092_

**Comment by m0ksem** [comment]
@aluarius, let's mark this kind of issues with "breaking changes" label and 1.5.0 milestone, so we will be able to make a migration guide easily.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2341
