### ISSUE TITLE
Ag-grid extension should use peer dependencies instead of direct dependencies

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2301]
Users might want to use [modules or packages](https://www.ag-grid.com/javascript-data-grid/modules/), we ideally want to support both.

You may test this by using module and package build - both should work

**Comment by m0ksem** [comment]
We require ag-grid ^29 and vuestic ^1.3 I think this is okay. We don't need it to be peer deps, this will mean that ag-grid extension can work without vuestic-ui - that's not true, because we need CSS variables.
