### ISSUE TITLE
Types. VaRadio `option` prop type is missing

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2303]
Must be string or boolean and likely required.

packages/ui/src/components/va-radio/VaRadio.vue

**Comment by Udaay** [comment]
Also, what would be the default value for this ?

**Comment by m0ksem** [comment]
> Also, what would be the default value for this ?

@Udaay, I think this mustn't have a default value. I can't see any case where you might need a default value... It always must be passed. So this is looks like required prop without default value.

Usage example:
```vue
<va-radio option="yes" />
<va-radio option="no" />
```

**Comment by asvae** [comment]
Options is actually `any` :). You can pass whatever and `object`/`null` is pretty common case.

**Comment by m0ksem** [comment]
> Options is actually `any` :). You can pass whatever and `object`/`null` is pretty common case.

Hm. Make sense.

**Comment by Udaay** [comment]
I this PR related this is already merged , should i undo it ??

**Comment by m0ksem** [comment]
> I this PR related this is already merged , should i undo it ??

No need to undo, would be nice to create new one. Sorry for that.

**Comment by Udaay** [comment]
Yeah no problem I will do that
