### ISSUE TITLE
(1.5.0) buttons' colors are broken here (page: `/en/styles/css-variables`):

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2304]
Not for this PR, but buttons' colors are broken here (page: `/en/styles/css-variables`): 
![image](https://user-images.githubusercontent.com/29167241/186898511-4aa82535-c8b2-4f64-9721-eed0b7b87b04.png)

_Originally posted by @rustem-nasyrov in https://github.com/epicmaxco/vuestic-ui/issues/2189#issuecomment-1228402551_

**Comment by m0ksem** [comment]
@aluarius, please, mark it as 1.5.0 issue to prevent heart attack.

**Comment by aluarius** [comment]
Also will fix here this problem:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/64714442/187450854-7a1f58a3-370a-4d85-8c26-69089a711f61.png">

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2332
