### ISSUE TITLE
bundlers sandbox must use vitest

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2307]

**Comment by asvae** [comment]
Any point for that? Aren't the checks like "things are being built properly"?

**Comment by m0ksem** [comment]
> Any point for that? Aren't the checks like "things are being built properly"?

Exactly. I used to test different build for correct tree-shaking, so we have a few unit tests that ensures that there is no extra code in dist. 

It used jest for that with small ts issues and longstart.
