### ISSUE TITLE
Dropdown doesn't ignore overflow from parent

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2308]
![image](https://user-images.githubusercontent.com/5394573/186943173-f53f23e0-2122-4571-aa96-aa8a6af13789.png)

In [these demos](http://vuestic-ui-demo.sub.asva.by/#/demo/va-dropdown/VaDropdown.demo.vue) - dropdown should overflow container. 

The way I understand it - dropdown by default should be appended to `body`. This helps to avoid overflow issues (which is very tricky for users to deal with).

But we also have (had?) `DisableAttachment` flag, which allows to render dropdown inside a parent.

Ideally we want to support both ways (via a flag), but `body` should go by default.

@m0ksem your thoughts on this would be appreciated. 😼

**Comment by m0ksem** [comment]
Old demo. This can be resolved by adding `prevent-overflow` prop to dropdown.

**Comment by asvae** [comment]
I think we should fix demo then.
