### ISSUE TITLE
cjs build errors

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2313]
Reproduces from `1.4.7`. Slightly different error message though:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/5394573/186029749-b5ece192-752f-422f-b034-4a590092af0b.png">

_Originally posted by @asvae in https://github.com/epicmaxco/vuestic-ui/issues/2257#issuecomment-1223240018_

**Comment by asvae** [comment]
I think this should be irrelevant after updating codesandbox to vite.

**Comment by m0ksem** [comment]
> I think this should be irrelevant after updating codesandbox to vite.

cjs build might be used in vite-ssr.

**Comment by m0ksem** [comment]
Move to #2825
