### ISSUE TITLE
Datatable filter must be debounced

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2316]
> datatable filter should wait for user to finish typing or backspaceing (e.g. for 0.7 seconds) before re-initiating filtering -> makes filter unresponsive on big tables or slow devices

**Comment by asvae** [comment]
I'm not sure that's needed. Also not sure on implementation as we do.

**Comment by asvae** [comment]
Let's not add props for debounce, we can implement an example with debounce instead.

In example we can emulate api request with debounce.
