### ISSUE TITLE
Update contribution docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2334]
We didn't update contribution docs for a while.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/5394573/187738990-7f8f0a80-e78f-4a4f-bb66-2077490a10e2.png">

- [ ] Ideally we want a "human language" guide. I.e. what steps new contributor should take to start project, run demos locally etc.
- [ ] Let's use only english and `.md`, so that it's easier to update for us.
- [ ] Walk through contribution docs and ensure everything is relevant. If not - update that.

**Comment by m0ksem** [comment]
Docs are updated, but there is other stuff to add here in different tasks.
