### ISSUE TITLE
Data table sticky header adds strange background color

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2338]
![image](https://user-images.githubusercontent.com/23530004/187916369-6e73974c-f5db-44e1-97b8-91062171e394.png)

How about... var(--va-secondary) or var(--va-white)?

**Comment by Udaay** [comment]
I will look into this

**Comment by m0ksem** [comment]
> I will look into this, can you please let me know how to reproduce this bug.

Hey. Here is a reproduction in our docs demo.
https://vuestic.dev/en/ui-elements/data-table#sticky-header-and-footer

**Comment by m0ksem** [comment]
This issue is a part of quest:
- We need `var(--va-white)` or `va-secindary` (decide which looks better) to be a default color.
- We need to simplify demos, so it is clear how to change header color. (see https://github.com/epicmaxco/vuestic-ui/issues/2353)
- In additional, we might remove unnecessary text in demo (see https://github.com/epicmaxco/vuestic-ui/issues/2352)
