### ISSUE TITLE
Update info on accessibility in docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2343]
https://vuestic.dev/

![image](https://user-images.githubusercontent.com/5394573/188165270-4ef5696b-d4e0-4d67-a992-1f9c3b455dd4.png)

That was relevant when we didn't have accessibility support, only keyboard navigation. Right now we can mention "Accessibility" and maybe some standard we follow.

Link is also broken.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2355
