### ISSUE TITLE
select box trigger icon contains hard coded styles

### ISSUE THREAD

**Issue by TheDirigible** [epicmaxco/vuestic-ui#2359]
I'm trying to customize the select box trigger icon using CSS.  It doesn't appear to be possible, because this is using hard coded styles:
style="color: rgb(37, 80, 192); font-size: 24px; height: 24px; line-height: 24px;"

These styles should be applied in a class.

**Comment by m0ksem** [comment]
This styles usually comes from props. For example, if you want to change color, simply pass color prop. 

You are also able to use !important. 

We're still working on sizes config, so user can change these styles.
