### ISSUE TITLE
Select text-by broken if value-by isn't empty

### ISSUE THREAD

**Issue by Luffyyy** [epicmaxco/vuestic-ui#2362]
**Vuestic-ui version:** 1.4.10

Basically the select will show the value rather than text-by's text, possibly due to relying on the value-by.

**Steps to reproduce**
Same as before:
```vue
<template>
    {{test}}
    <div>
        <va-select v-model="test" :options="options" value-by="value" multiple/>
    </div>
</template>

<script setup>
const test = ref([]);
const options = [
    { 
        text: 'Hello',
        value: 1
    },
    { 
        text: 'World',
        value: 2
    },
    { 
        text: 'Test',
        value: 3
    }
];
</script>
```

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/11510099/188510781-bcb814c9-727d-4e57-af2c-c745126eb40c.png)

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/11510099/188510794-9c15782f-a4f5-413b-8b00-aaa40b213f48.png)

**Other information**
😅 hopefully last issue report regarding the select

**Comment by stuk88** [comment]
I get it too

**Comment by stuk88** [comment]
So for anyone struglling with that as myself.
when textBy is "number" or "boolean" it will act strange. 
change the name of the label to a different name, like `label` or `text` 
And than  valueBy="value" is must.

**Comment by m0ksem** [comment]
> So for anyone struglling with that as myself. when textBy is "number" or "boolean" it will act strange. change the name of the label to a different name, like `label` or `text` And than valueBy="value" is must. Oh and it acts wierd when the model is object

Hi, can you reproduce it in https://ui.vuestic.dev/play/ and share here?
