### ISSUE TITLE
Error in `useSelectable`

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2375]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/64714442/189149916-55ca6ff0-2b0e-4a8a-af88-4dcabda32d8a.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/64714442/189149951-22615719-9fc4-4915-b709-19a630f15ec3.png">

For, for example, `VaCheckbox` or `VaSwitch`.

**Comment by rustem-nasyrov** [comment]
Fixed here https://github.com/epicmaxco/vuestic-ui/commit/149b0f73dd94e7f5e942a00da8e7b25e25fb8ba5
