### ISSUE TITLE
Why do we need support arrayValue in checkbox?

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2378]
https://vuestic.dev/en/ui-elements/checkbox#grouped-array
https://vuestic.dev/en/ui-elements/option-list#default

Look at first demo, on second... First and then again second... Could you see the difference?

**Comment by asvae** [comment]
@Azgiliat can you help to figure out if they're exactly the same?

**Comment by Azgiliat** [comment]
They are really the same. So if we have special component (`VaOptionList`) to group form inputs, there is no point to handle array-value prop in `VaCheckbox`

**Comment by asvae** [comment]
We want to check if prop array-value is used in option list instead of separate implementation.

**Comment by asvae** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/2450
