### ISSUE TITLE
Facing issues with colors in the sources

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2380]
Facing issues with colors in the sources.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/29167241/189161417-6acd250b-1475-492b-bee6-0f4617d98b73.png">

_Originally posted by @rustem-nasyrov in https://github.com/epicmaxco/vuestic-ui/issues/2374#issuecomment-1240867347_

**Comment by m0ksem** [comment]
Closed with #2382
