### ISSUE TITLE
Icon font import doesn't work

### ISSUE THREAD

**Issue by TheDirigible** [epicmaxco/vuestic-ui#2387]
**Vuestic-ui version:** 1.4.10

**Steps to reproduce**
The docs say you can use <link or @import to use the material icon font.  The <link version works, but the @import does not:
```
    @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;1,700&display=swap');
    @import url('https://fonts.googleapis.com/icon?family=Material+Icons');

```
**What is the expected behavior?**
icons show up

**What is the current behavior?**
no icons, just placeholder text like expand_more

**Other information**
Another part of the docs says:
```
    By default Vuestic UI uses material icons, so make sure to install the package:
    npm install material-design-icons-iconfont -D

```
This would seem to conflict with the other method, and this also does not get them working.

**Comment by rustem-nasyrov** [comment]
@TheDirigible how do you use the `@import`? You imported it in the style tag of the App.vue or you've created main.css and imported it in the main.js file?
