### ISSUE TITLE
On dark theme sponsors are not very visible.

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2390]
![image](https://user-images.githubusercontent.com/5394573/189658286-93891f01-4674-4494-b308-26c40146ae24.png)

Probably just needs a half-transparent white background for problematic images, but you can investigate a bit.

Might be possible to do in context of markdown, github allowed some html before.

**Comment by Shinigami92** [comment]
We could try out using two different SVGs and then apply this CSS: https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/

If it works, we then could use a white border for the letters

**Comment by vjc22** [comment]
I have made the SVG files with white borders for the sponsors that are difficult to read and will update the HTML soon.

**Comment by rustem-nasyrov** [comment]
@asvae, as I know we decided to not apply a dark theme to the landing page. Maybe we should close this issue?
