### ISSUE TITLE
va-avatar shouldn't use color if src is provided and image exists

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2396]
**Vuestic-ui version:** 1.4.10
<img width="529" alt="image" src="https://user-images.githubusercontent.com/5394573/190127169-fb4cd593-78b2-4c8b-be7a-5ed502a6a8df.png">

Probably best would be to check refs on that. Not sure what's the perfect approach.
<img width="136" alt="image" src="https://user-images.githubusercontent.com/5394573/190372064-4e164f10-fd97-4db5-9f4b-e645aae5e44e.png">

**Comment by shatanov** [comment]
Hi, I would like to take this issues, could you describe it in a little more detail?)
