### ISSUE TITLE
Horizontal/Circle progress

### ISSUE THREAD

**Issue by ilearnjs** [epicmaxco/vuestic-ui#24]
# Docs
- [ ] Do after [docs boilerplate](#17) is done.

# HorizontalProgressBar
## Props
- [x] `value: Number` - percentage value for the progress
- [x] `buffer: Number` - percentage value for the buffer
- [x] `indeterminate: Boolean` - infinite animation when loading progress is unknown
- [x] `color: String` - use theme plugin (to rename `theme`)
- [x] `rounded: Boolean, default: true` - make the bar rounded
- [x] `size: Number | String` - height of the bar in pixels or height in css units.
- [x] 'reverse: Boolean' - should reverse progress bar direction (useful for RTL languages).
- [x] ~`small: Boolean` - called thin in zeplin~ - implemented in `size` prop
- [x] ~`large: Boolean` - called thick in zeplin~ - implemented in `size` prop
## Slots
- [x] `default` - default slot

# CircularProgressBar
## Props
- [x] `value: Number` -  percentage value for the progress
- [x] `color: String` - use theme plugin (to rename `theme`)
- [x] `indeterminate: Boolean` - infinite animation when loading progress is unknown
- [x] `size: Number | String` - bar size (diameter) in pixels or size in css units.
- [x] `thickness: Number` - circle border size in percent of component size
## Slots
- [x] `default` - default slot

# Design
* [Zeplin](https://app.zeplin.io/project/5bcd9657767a220982a4ab61/screen/5c2f424346bce344082ea8cd)
* 
- [ ] Present to @xx13 after finishing.

# Notes
- [x] ~Rename existing components: horizontal to linear and circle to circular~ Renamed to `VaProgressBar`, `VaProgressCircle`. Not exactly as planned, but sounds ok.

# Refs
Vuetify [linear](https://vuetifyjs.com/en/components/progress-linear) / [circular](https://vuetifyjs.com/en/components/progress-circular)
Quasar [linear](https://quasar.dev/vue-components/linear-progress) / [circular](https://quasar.dev/vue-components/circular-progress)
[Ant](https://vue.ant.design/components/progress/)

**Comment by asvae** [comment]
@ilearnjs 

> Rename horizontal to linear (to discuss)
I think it makes sense to make it consistent, ie:
* horizontal - cricular
* line - circle

LinearProgressBar, CircularProgressBar makes perfect sense to me.

**Comment by asvae** [comment]
@ilearnjs 

Interested in your opinion:
1) Default show hide transition as in vuetify.
2) Slot inside of horizontal bar.
3) Striped + animated striped options.
4) Reverse progress. (+ reverse indeterminate)
5) Size presets for height.
6) Buffer custom color.

**Comment by ilearnjs** [comment]
> @ilearnjs
> 
> > Rename horizontal to linear (to discuss)
> 
> I think it makes sense to make it consistent, ie:
> 
> * horizontal - cricular
> * line - circle
> 
> LinearProgressBar, CircularProgressBar makes perfect sense to me.

Updated

**Comment by ilearnjs** [comment]
> @ilearnjs
> 
> Interested in your opinion:
> 
> 1. Default show hide transition as in vuetify.
> 2. Slot inside of horizontal bar.
> 3. Striped + animated striped options.
> 4. Reverse progress. (+ reverse indeterminate)
> 5. Size presets for height.
> 6. Buffer custom color.

1. Not sure we need to build in animation into the component. As I remember vuetify has transition components and you can use them as a wrapper (with very important prop `hide-on-leave`).
2. We already have a slot inside implemented by design. If you are about the position of slot it is better to @xx13.
3. Not sure that is important feature. But I can add.
4. See p. 4
5. Added.
6. See p. 4

**Comment by asvae** [comment]
@ilearnjs regarding size presets - let's keep it out for now.
It's not a problem to implements later and I'm not completely sure how it should shape out. As for different components same size presets might mean different things.

**Comment by asvae** [comment]
@ilearnjs I discussed with @xx13 and added small, large and reverse to horizontal progress bar.

**Comment by asvae** [comment]
@xx13 please review

http://vuestic-ui-demo.sub.asva.by/#/demo/vuestic-components/va-progress-bar/progress-types/VaProgressBar.demo.vue
http://vuestic-ui-demo.sub.asva.by/#/demo/vuestic-components/va-progress-bar/progress-types/VaProgressCircle.demo.vue

PS There are small issues, marked with exclamation mark. They're safe to ignore and should not influence your reasoning.
