### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2400]
Default scrollbar is not sexy enough. Maybe we can improve it a bit.

* Ieally we want scrollbar to at least follow the theme (dark/light), so that it doesn't hurt eyes.
* Maybe different scrollbars? (fancy for main page, unfancy for everything else)

**Comment by arkmadj** [comment]
Hi @asvae Can I work on this issue?

**Comment by m0ksem** [comment]
We're not sure about this task yet. We might have complex solution like https://github.com/m0ksem/vue-custom-scrollbar/tree/master/packages/vue-custom-scrollbar or more performant with CSS only, like we have in VaScrollContainer.

**Comment by asvae** [comment]
Doesn't seem that useful
