### ISSUE TITLE
VaAccordion flat mode

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2404]
Looks like sidebar, but can be used anywhere across app.
![image](https://user-images.githubusercontent.com/23530004/190903374-35849d6b-8ee3-4f2a-ab4b-991765719f68.png)

**Comment by arkmadj** [comment]
Hi @m0ksem Can you give more explanation on this issue?

**Comment by asvae** [comment]
@xx13 any ideas from your side on this?

That's how current one looks. Maybe we can only keep flat?
<img width="462" alt="image" src="https://user-images.githubusercontent.com/5394573/193004632-e8405bcb-1e80-4793-a5bd-3230cd63ad47.png">

**Comment by xx13** [comment]
@asvae I'll share the fix this week

**Comment by xx13** [comment]
[default - screens](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=2101%3A11134)

[default - proto](https://www.figma.com/proto/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?page-id=0%3A1&node-id=2101%3A11133&viewport=-9588%2C4032%2C0.5&scaling=min-zoom&starting-point-node-id=2101%3A11133)

[flat - screens](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=2101%3A11196)

[flat - proto](https://www.figma.com/proto/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?page-id=0%3A1&node-id=2101%3A11179&viewport=-9588%2C4032%2C0.5&scaling=min-zoom&starting-point-node-id=2101%3A11179&show-proto-sidebar=1)

**Comment by xx13** [comment]
- it would be nice to have not only flat in terms of `no shadow` variant, but also without bg so it can be embedded into any view
- it is important to add dividers to the view

**Comment by m0ksem** [comment]
Done
