### ISSUE TITLE
Flashbang effect on docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2419]
**Vuestic-ui version:** 1.4.11

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/5394573/191276339-59600d06-80ae-40b9-a049-0fd5704241e2.png">

When you open docs on dark theme - it shows you white screen briefly, then goes to dark mode. That hurts.
Ideally there shouldn't be any brightness transition.

**Comment by m0ksem** [comment]
This is caused because of SPA. We're not able to make page dark before SPA is loaded. There will be a dark or white flash bang in any case. We might make some hacks here, but let's discuss it before.
