### ISSUE TITLE
VaDatePicker shouldn't have yellow outline on hover

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2420]
**Vuestic-ui version:** 1.4.11

<img width="356" alt="image" src="https://user-images.githubusercontent.com/5394573/191277072-38c35943-a9e0-4e0a-97b7-984fd1db422a.png">

**Comment by r-Dev03** [comment]
@asvae can I take on this issue?

**Comment by vrindavan** [comment]
This file?
https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue

**Comment by VBoudreau55** [comment]
Can I be assigned to this issue, I think it would be a great first issue for me

**Comment by rustem-nasyrov** [comment]
> This file? [VaDatePickerCell.vue](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue)

Yeah, this file.

**Comment by rustem-nasyrov** [comment]
> @r-Dev03, @vrindavan, @VBoudreau55 hi! Of course you can assign yourselves, but before you start, please read the [contribution guide](https://vuestic.dev/en/contribution/guide). :)

My bad, I'll assign someone.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2422
