### ISSUE TITLE
Unable to change placeholder text in select search input

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2430]
![image](https://user-images.githubusercontent.com/23530004/191795899-01a97d82-fe6c-40e2-b643-6f9f3936c761.png)

Need some prop, so user can be able to change this "Search" text.

**Comment by hannaPekert** [comment]
Hi! Can I take this one? :)

**Comment by m0ksem** [comment]
> Hi! Can I take this one? :)

Hey. Thank you for interest! Looks like it is already taken, sorry.
