### ISSUE TITLE
Nuxt RC.11 Errors with "Failed to load vuestic-ui/dist/styles/essential.css"

### ISSUE THREAD

**Issue by Luffyyy** [epicmaxco/vuestic-ui#2433]
**Vuestic-ui version:** 1.4.11

**Steps to reproduce**
https://stackblitz.com/edit/github-qegecq?file=nuxt.config.ts

**What is the expected behavior?**
The site works

**What is the current behavior?**
The site crashes 😐

**Other information**
From what I saw, vuestic doesn't actually ship with essential.css if you look in the node_modules folder.
![image](https://user-images.githubusercontent.com/11510099/191886404-f5c69e85-e731-48eb-bf81-dd9e99cfde70.png)

**Comment by m0ksem** [comment]
Must be fixed in 1.4.12.
