### ISSUE TITLE
VaCollapse does not dynamically adjust

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2448]
**Vuestic-ui version:** 1.4.13

> Hello, I've noticed that a bug that was fixed in a previous version is back in 1.4.13. When opening a va-collapse the height does not adjust dynamically based on the current content. So for example when you put a component inside a v-if and you open the collapse the content is cropped. This doesn't happen for example in the 1.4.9 version

from BrachyKnight#0155 in discord

**Comment by aluarius** [comment]
Can't reproduce, seems to be already fixed. However, it's unreal case in my opinion, because body block hasn't `height` (or `max-height`) attribute at all.
