### ISSUE TITLE
Can't use `vuestic-plugin` in `vuestic docs` because of the `va-date-picker` issue

### ISSUE THREAD

**Issue by raichev-dima** [epicmaxco/vuestic-ui#246]
* **What is the expected behavior?**
All components work properly once the plugin is imported and used 

* **What is the current behavior?**
When I'm trying to import and use the plugin in the vuestic docs folder, I've got the error: 
```
Module build failed (from ...vuestic-ui/node_modules/postcss-loader/src/index.js):
Error: Can't resolve '~flatpickr/dist/flatpickr.css' in '...vuestic-ui/packages/ui/src/components/vuestic-components/va-date-picker'
```

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
Import the plugin somewhere in the `docs` code:
```
import VuesticPlugin from '../../ui/src/components/vuestic-plugin'
```

**Comment by SergeiPleshkov** [comment]
Problem with imports also occurs in DataTable, NavLinkGroup, Popover.
