### ISSUE TITLE
Codeblock overflows on vuestic landing

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2463]
**Vuestic-ui version:** 1.4.11

Bug is on `develop` branch:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/5394573/194243209-21429e52-bc78-446d-8da0-466b48093224.png">

On [master docs](https://vuestic.dev/) it looks - fine:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/5394573/194243320-f1034a2f-c7ac-4db6-9f07-71cd613fa073.png">

**Comment by m0ksem** [comment]
fixed here: https://github.com/epicmaxco/vuestic-ui/pull/2466
