### ISSUE TITLE
Make hide-arrows prop in va-tabs

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2469]
@m0ksem, @asvae while I was working on this issue, and used the va-tabs component, I had thoughts about to add show/hide pagination property. Do we need it?

_Originally posted by @rustem-nasyrov in https://github.com/epicmaxco/vuestic-ui/issues/2466#issuecomment-1270197961_

**Comment by m0ksem** [comment]
![image](https://user-images.githubusercontent.com/23530004/194617120-ac6e1d87-74a8-425c-97f6-a28c550d3f2b.png)

**Comment by m0ksem** [comment]
How about making this buttons flat? 
![image](https://user-images.githubusercontent.com/23530004/195718126-8ecc9ef7-a261-4ab1-8cb5-6045e0e2f2d0.png)

**Comment by xiongmao86** [comment]
Does merging #2605 meaning this should be closed?

**Comment by rustem-nasyrov** [comment]
@xiongmao86 yes, it should. Thank you that you mentioned it. :)
