### ISSUE TITLE
VaImage doesn't show image on ssr

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2488]
**Vuestic-ui version:** 1.5.0

![image](https://user-images.githubusercontent.com/5394573/195140968-0e53db69-9e3f-4d9d-a609-1ed4177f5abf.png)

In component `loading` is set to `true` which sets `display: none`. `loading = false` is set on image load, but for some reason image load doesn't happen (on client)

**Comment by asvae** [comment]
I set loading to false by default, but error case still doesn't work on SSR.

**Comment by kilakewe** [comment]
I'm still seeing this same issue in nuxt using SSR for the va-image component. 

Versions: 
    "nuxt": "^3.2.0",
    "@vuestic/nuxt": "^1.0.10",
    "vuestic-ui": "0.0.0-experimental-5cff9945d-20230214"

**Comment by aluarius** [comment]
@kilakewe unfortunately, I can't reproduce this problem for mentioned stack. Can you provide more information - part of code with VaImage usage, for example.

**Comment by aluarius** [comment]
@rustem-nasyrov if you have time, test it too please, just to be sure.

**Comment by aluarius** [comment]
I will close it for now. Will reopen in case of new information.
