### ISSUE TITLE
Dropdown jumps on create

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2491]
**Vuestic-ui version:** 1.5.0

When you click on input - dropdown appears at the bottom, then jumps up
Should appear at the bottom from the beginning

Dropdown keeps position for 2nd and next openings

Reproduced on nuxt, but probably a problem for standard build

![image](https://user-images.githubusercontent.com/5394573/195179087-26d72efa-3cb8-4229-a6dc-948d5aac95f5.png)

**Comment by asvae** [comment]
Stopped reproducing for me 🤷🏼‍♀️

**Comment by rustem-nasyrov** [comment]
@asvae did you check if `prevent-overflow` props were enabled?
