### ISSUE TITLE
cursor pointer doesn't work on nuxt on pickers

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2492]
**Vuestic-ui version:** 1.5.0

![image](https://user-images.githubusercontent.com/5394573/195181701-9a3cba94-8922-49db-a906-8b1477c3932d.png)

**Comment by m0ksem** [comment]
This is caused because of `_ctx.readonly` returns vue `readonly` from auto-import. As solution we can use readonly from $props in template.

Can not reproduce it in clean project, likely problem in sandbox. Have you seen this outside of sandbox?
