### ISSUE TITLE
Divider is very hard to see

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2493]
**Vuestic-ui version:** 1.5.0

It's barely visible on my monitor, on some monitors it might be not visible at all.

![image](https://user-images.githubusercontent.com/5394573/195183073-e6c86209-333a-42f5-9dac-bf55adb1b6d4.png)

@xx13

**Comment by rustem-nasyrov** [comment]
@m0ksem, @asvae maybe we'll return the previous color back?
