### ISSUE TITLE
VaTreeView hydration mismatch on nuxt

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2498]
**Vuestic-ui version:** 1.5.0

I used docs examples

![image](https://user-images.githubusercontent.com/5394573/195198962-feda6c2f-4997-43e7-8104-595e9b72e251.png)

**Comment by m0ksem** [comment]
Reproduced this in sandbox. Set expanded: true to any node and see:
![image](https://user-images.githubusercontent.com/23530004/201389143-6a1ac773-107d-42aa-b13a-d19e57bdc3e0.png)

**Comment by m0ksem** [comment]
@rustem-nasyrov, fixed?

**Comment by asvae** [comment]
Seems to be fixed
