### ISSUE TITLE
va-chart wrong props

### ISSUE THREAD

**Issue by kenobikty** [epicmaxco/vuestic-ui#25]
- I'm submitting a ... bug report 

https://github.com/epicmaxco/vuestic-ui/blob/d81dd983289641a145c696dd97920278507353c6/src/components/vuestic-components/va-chart/VaChart.vue#L6

`:options` does not match the props name in `chartMixin`

should it be `chartOptions` ?

**Comment by asvae** [comment]
Thanks.

Seems to be fixed already.
