### ISSUE TITLE
Demo spacing

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2509]
## Checkbox

![image](https://user-images.githubusercontent.com/23530004/195716277-069451ef-7eb8-4e42-9ee3-1cc69e196cf6.png)

![image](https://user-images.githubusercontent.com/23530004/195716308-70e7be15-a8b2-48d3-946a-a5c1a29cf6db.png)

![image](https://user-images.githubusercontent.com/23530004/195716329-ff23d80b-3ee5-4102-8db6-4560027c5513.png)

## Select

![image](https://user-images.githubusercontent.com/23530004/195716683-51e5593f-c0ff-4f8a-9a52-0643a749c1bf.png)

## List
Lost spacing between items
![image](https://user-images.githubusercontent.com/23530004/195717293-912d52b0-23ad-45e5-b7ac-62f69e3fa980.png)

Strange padding in list
![image](https://user-images.githubusercontent.com/23530004/195717608-858bfa6e-d70c-4b3c-b332-de8dde3f2e00.png)

**Comment by Sadnessa** [comment]
Hi. I can fix this.
