### ISSUE TITLE
@vuestic/ag-grid-theme broken demo in docs

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2516]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/36926073/195808065-752b594e-57a4-4396-81b3-a79ceeea4454.png">

https://codesandbox.io/s/misty-feather-1cv0uh?file=/src/App.vue

**Comment by Valar103769** [comment]
because i need `pnpm add @ag-grid-community/core`

**Comment by m0ksem** [comment]
This demo must work without any changes from user. We should add @ag-grid-community/core to package json.

**Comment by m0ksem** [comment]
@rustem-nasyrov, this path also must be fixed.
![image](https://user-images.githubusercontent.com/23530004/195835088-0cbf970c-f602-471c-9cf9-e9ba3718a0d3.png)

Add resolve alias, same as we have for ui.

**Comment by Valar103769** [comment]
> @rustem-nasyrov, this path also must be fixed. ![image](https://user-images.githubusercontent.com/23530004/195835088-0cbf970c-f602-471c-9cf9-e9ba3718a0d3.png)
> 
> Add resolve alias, same as we have for ui.

it can work
```vue
<style lang="scss">
@import '@vuestic/ag-grid-theme/index.scss';
</style>
```
