### ISSUE TITLE
1.5.0 migration guide

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2527]
RAW: Must be moved to docs later
TODO: Fill other stuff. Most of component styles changed, like VaChip now is inline-block, etc.

### VaButton

Button has been changed visually and its API changed too.
`flat` props has been moved to `secondary` preset.
`rounded` renamed to `round` and now false by default

### Checkbox
Checkbox is now inline-element, not block.

### Colors
In 1.5.0 we must make a major changes to support dark themes. Color config is now extended with `variables` (where previous colors are stored). `dark`, `white`, `background`, `gray` colors have been removed. Text color in components is calculated automatically, but you can force text to be `textDark` or `textLight`. There are 4 types of background color now: `backgroundPrimary`, `backgroundSecondary`, `BackgroundTertiary`, `backgroundElement`. Read more: vuestic.dev/styles/colors

`useColors` has the same API, but we added `useTheme`, so if you have implemented `useTheme`, it is recommended to use `useTheme` from vuestic.
### Grid
We removed extra -- in clases, so now `justify--center` renmaed to `justify-center`

### Typography
All typography clases now have `va-` prefix and `--` removed.
`display-1` has been renamed to `va-h1`, similar with 2, 3, 4, 5, 6
`title` renmaed to `va-title`

**Comment by Azgiliat** [comment]
`link` -> `va-link`
`text--right|center` -> `va-text-right|center`

**Comment by asvae** [comment]
That's done
