### ISSUE TITLE
[va-modal] footer slot not showen

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2533]
**Vuestic-ui version:** 1.4.11

https://codesandbox.io/s/interesting-dawn-vv7v2c?file=/src/App.vue

the footer slot can't be rendered

**Comment by m0ksem** [comment]
@Valar103769, you'll need to use `#default`, `#header` and `#footer` slots.

`#content` slot disables `#header` and `#footer`. This is likely not a bug, but lack of documentation.
