### ISSUE TITLE
[DropDown]  without any css layout

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2544]
it is too simple, headerless is not beautiful, complete it please?

**Comment by m0ksem** [comment]
Hey @Valar103769. Can you explain a bit of this issue?

There is a VaDropdownContent or VaCard if you want some background.
Also notice that there is VaPopover for popovers.

**Comment by Valar103769** [comment]
> 

Usually paired with a drop-down list , like
1.  [flowbite](https://flowbite.com/docs/components/dropdowns/)
2. [elemnt-plus](https://element-plus.gitee.io/zh-CN/component/dropdown.html)
3. [antd](https://antdv.com/components/dropdown)
4. [primevue](https://www.primefaces.org/primevue/dropdown)

and please remove popovers   padding, the list item need to be clicked with the full width
