### ISSUE TITLE
Tree view suggestions

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#2545]
The `TreeNode` component must be not available to end users.
- [x] In the docs we need to unite slots from TreeNode to the TreeView component.
![image](https://user-images.githubusercontent.com/29167241/196886788-c04221c5-47d0-4e22-bd5f-35a740a610e5.png)
- [ ] Make public exportable TreeView and TreeNode types and private ones.
- [ ] Create TreeNodeType as generic.
- [x] Pass to the bindable slots whole TreeNode type (props).
- [x] We need to expose only Treeview here:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/29167241/196887998-16d6e9f1-07f6-4f43-9304-c042776aada3.png">

- [x] Separate colors and select (checkbox) demos:
![image](https://user-images.githubusercontent.com/29167241/196888713-5b48308f-b2fd-40db-b95a-d9eb149e7ae5.png)

**Comment by m0ksem** [comment]
VaTreeNode type can be generic.

```ts
type User = { name: 'Maksim', id: 'm0ksem' }

// ...

;(node as VaTreeNode<User>).id
```

**Comment by asvae** [comment]
Doesn't make much sense given we'll get [`satisfies` operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-rc/#the-satisfies-operator) pretty soon.

Then user can:
```typescript
const userNode = { name: 'Maksim', id: 'm0ksem' } satisfies TreeNode
```
