### ISSUE TITLE
Breakpoints are hardcoded in scss

### ISSUE THREAD

**Issue by Azgiliat** [epicmaxco/vuestic-ui#2560]
<img width="466" alt="Screenshot 2022-10-23 at 22 20 53" src="https://user-images.githubusercontent.com/46869767/197411908-d5ae7209-e775-4a67-83b5-c1a04c3d5089.png">
Right now breakpoints live in scss and not synchronized with breakpoints service. So this service is pretty useless right now

**Comment by bogdan0083** [comment]
Yeah, having the same issue actually. I've just copied a `grid` folder with `scss` files in my project for now until the issue is fixed.

**Comment by aluarius** [comment]
Grid helpers will be totally removed in 1.7.0 with these hardcoded breakpoints.
