### ISSUE TITLE
[Dropdown] placement can be changed by long content

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2567]
https://codesandbox.io/s/peaceful-chaplygin-p5ipbu?file=/src/App.vue

step: 
1. when  dropdown is showen
2.  change `va-dropdown-content`  's height too large 
3. the postion can by changed to placement:top,

I hope 
when  set `placement='bottom'` by direct , not change the placement 

https://user-images.githubusercontent.com/36926073/197748832-99c098c6-2b41-4049-a27a-9520baad4169.mov

**Comment by m0ksem** [comment]
Try to set `auto-placement` props to `false`

<va-select :auto-placement="false" />

**Comment by Valar103769** [comment]
> Try to set `auto-placement` props to `false`

thanks
