### ISSUE TITLE
Warn alert is not readable

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2578]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/5394573/198064403-383b940f-e6aa-43c9-8859-393b24081f01.png">

**Comment by rustem-nasyrov** [comment]
@xx13 can you take a look please, when we set the `outline` property, alerts doesn't look like an alert component. I suggest to make the border width bigger or use barely visible background color.

**Comment by m0ksem** [comment]
@rustem-nasyrov, can't we close it?
