### ISSUE TITLE
[va-popover]: support placement: bottom-[right]

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2597]

**Comment by m0ksem** [comment]
Hey @Valar103769, there is a bottom-end placement instead of bottom-right.

https://vuestic.dev/en/ui-elements/dropdown#placement-and-offset

We totally need to make some link from Popover to Dropdown placement example...

**Comment by Valar103769** [comment]
> Hey @Valar103769, there is a bottom-end placement instead of bottom-right.
> 
> https://vuestic.dev/en/ui-elements/dropdown#placement-and-offset
> 
> We totally need to make some link from Popover to Dropdown placement example...

thanks
