### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by jean-moldovan** [epicmaxco/vuestic-ui#26]
# Docs
- [ ] Do after [docs boilerplate](#17) is done.

# Props
Add to existing component:
- [ ] `loading: Boolean`
- [ ] `block: Boolean` - takes all awailable width
- [ ] `round: Boolean`

# Notes
* Button icons should work with material design icons

# Design
- [ ] Present to @xx13 after finishing.

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/buttons)

**Comment by ssemenkoff** [comment]
@jean-moldovan @asvae 
Seems like there is no way to use material icons inside the button component at the moment.

**Comment by asvae** [comment]
@ssemenkoff added to issue

**Comment by ssemenkoff** [comment]
Can I get more details on round button? Looks like all of the buttons in vuestic-ui are already rounded. What this prop should actually do?

**Comment by asvae** [comment]
@ssemenkoff it's `true` by default. So `false` should make them square.

**Comment by ssemenkoff** [comment]
Ok, got it
