### ISSUE TITLE
[dropdown]: auto-placement is invalid 

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2604]
**Vuestic-ui version:** 1.5.0

<img width="923" alt="image" src="https://user-images.githubusercontent.com/36926073/199193717-cfb2dda7-9b9c-4bba-8342-fd1c6799227a.png">

current positon is  bottom right of screen

```vue
 <va-dropdown trigger="click" :close-on-content-click="false" class="ml-2">
        <template #anchor>
          <va-button icon="settings" flat color="#1F2937" />
        </template>
</va-dropdown>
```

**Comment by m0ksem** [comment]
You can use `stick-to-edges` to prevent dropdown to be rendered outside of view-port.

**Comment by Valar103769** [comment]
It's not enough, it only adjusts the position in the horizontal direction, and the vertical direction is still overflowing

![image](https://user-images.githubusercontent.com/36926073/199195610-ffbf2756-d324-42d5-acd6-5e6b4bf9eced.png)

<img width="454" alt="image" src="https://user-images.githubusercontent.com/36926073/199195586-8b5d2f1a-f025-4083-a76f-059a03d5be37.png">

**Comment by Valar103769** [comment]
placement="bottom-right" meaning right:0 ?  , look like it is invalid
<img width="531" alt="image" src="https://user-images.githubusercontent.com/36926073/199449548-c64d9870-5674-4cce-878f-92b76324b7eb.png">


```vue
 <va-dropdown
        trigger="click"
        :close-on-content-click="false"
        placement="bottom-right"
        class="ml-2"
        stick-to-edges
      >
...
```


@m0ksem

**Comment by m0ksem** [comment]
> hi @m0ksem
> 
> `placement="bottom-right"` meaning `right:0` ? ,current look like it is invalid <img alt="image" width="531" src="https://user-images.githubusercontent.com/36926073/199449548-c64d9870-5674-4cce-878f-92b76324b7eb.png">
> 
> ```
>  <va-dropdown
>         trigger="click"
>         :close-on-content-click="false"
>         placement="bottom-right"
>         class="ml-2"
>         stick-to-edges
>       >
> ...
> ```
> 
> expect <img alt="image" width="497" src="https://user-images.githubusercontent.com/36926073/199449887-13bbf983-cc7c-49f6-870b-8a7866aa1643.png">

Hi @Valar103769.

You should have been using `bottom-end`, not `bottom-right`.

It might worth it to make aliases to make it more intuitive...
