### ISSUE TITLE
Make  position alises in dropdown

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2612]
> hi @m0ksem
> 
> `placement="bottom-right"` meaning `right:0` ? ,current look like it is invalid <img alt="image" width="531" src="https://user-images.githubusercontent.com/36926073/199449548-c64d9870-5674-4cce-878f-92b76324b7eb.png">
> 
> ```
>  <va-dropdown
>         trigger="click"
>         :close-on-content-click="false"
>         placement="bottom-right"
>         class="ml-2"
>         stick-to-edges
>       >
> ...
> ```
> 
> expect <img alt="image" width="497" src="https://user-images.githubusercontent.com/36926073/199449887-13bbf983-cc7c-49f6-870b-8a7866aa1643.png">

Hi @Valar103769.

You should have been using `bottom-end`, not `bottom-right`.

It might worth it to make aliases to make it more intuitive...

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/issues/2604#issuecomment-1299922714_
      

---

Bottom-right should be transformed to bottom-end, because it actually the same position always.

end-start was made to easily determinate offset with main&cross lines, similar to flexbox logic. But looks like people usually need simply set position without thinking about this complex logic of main&cross lines (and they need to remember this directions, which is hard lol)

Must be super easy to implement:

```ts
const aliases = {
  'bottom-right': 'bottom-end',
  'bottom-left': 'bottom-start',
  // ...
}

placement = aliases[placement] || placement
```

**Comment by Valar103769** [comment]
i think it is a good idea, link css rule
`margin-left` is same valid as `margin-inline-start`
