### ISSUE TITLE
[va-scroll-container] can eat error 

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2614]
repreduct

// eat error ❌
```vue
<va-scroll-container vertical style="max-height: 100px">
    <div height="200px">
      {{ new Error() }}
    </div>
  </va-scroll-container>

```

<img width="913" alt="image" src="https://user-images.githubusercontent.com/36926073/199482590-7b169d03-b65b-4bdb-837b-79a32f0584f7.png">

// throw error ✅
```vue
<div>{{ new Error() }}</div>
```

<img width="656" alt="image" src="https://user-images.githubusercontent.com/36926073/199482765-a1bca68d-5e69-4317-89b3-fb74ec16dbb5.png">

**Comment by m0ksem** [comment]
This might be more related to Vue, and you'll probably face this issue with any other component, since VaScrollContainer is a super-simple two-div component.

https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/va-scroll-container/VaScrollContainer.vue

Looks like `setVarsOnVNode` is Vue method for `v-bind` in css.

**Comment by Valar103769** [comment]
this is a simple reproduce ，today i meet same error message in runtime ，but i move error codes to va-dropdown-content the error is shown correctly，I first meet this issue

**Comment by Valar103769** [comment]
```vue
  <va-dropdown>
    <template #anchor>
      <va-button>va-dropdown</va-button>
    </template>
    <va-dropdown-content>
      {{ new Error('va-dropdown') }}
    </va-dropdown-content>
  </va-dropdown>
```
<img width="715" alt="image" src="https://user-images.githubusercontent.com/36926073/199638708-87c994c0-53bd-455e-bb84-e70311217ec5.png">


```vue
<va-dropdown>
    <template #anchor>
      <va-button>va-dropdown</va-button>
    </template>
    <va-dropdown-content>
      <va-scroll-container> // -> if va-scroll-container  exists ,the error changed
        {{ new Error() }}
      </va-scroll-container>
    </va-dropdown-content>
  </va-dropdown>
```

<img width="724" alt="image" src="https://user-images.githubusercontent.com/36926073/199638773-db9f178d-8c77-46a8-8752-2f2684d16323.png">

**Comment by Valar103769** [comment]
@m0ksem

**Comment by m0ksem** [comment]
@Valar103769, in case you think this is really important issue, and you need to be able to throw Error in template, you can continue the conversation here https://github.com/vuejs/core/issues/7015#issuecomment-1302021671.

Thanks!

**Comment by Valar103769** [comment]
speechless about their comprehension,
Obviously, what I want to express is that v-bind will engulf runtime errors, and use throw Error to reproduce, just because this is the most convenient way to reproduce. As for the computed in the demo, other things in the global api, It may be a little related, but not the point,

If you have to reproduce, you can also bind a deep object to v-model, and it may be undefined at runtime.

Anyway thank you

**Comment by Valar103769** [comment]
should add below
```js
app.config.errorHandler = (error: any, instance: any, info: string) => {
  console.error(error, instance, info)
}
```
