### ISSUE TITLE
Color Pick does not show native color selector on IOS Chrome or Safari

### ISSUE THREAD

**Issue by rlightner** [epicmaxco/vuestic-ui#2616]
**Vuestic-ui version:** 1.5.0

**Steps to reproduce**
Open https://vuestic.dev/en/ui-elements/color-input page in IOS Chrome or Safari

**What is the expected behavior?**
Clicking color dot should show native browser color selector

**What is the current behavior?**
Input traps focus and shows keyboard

**Comment by m0ksem** [comment]
I'll close this just because we're going to make a separated color picker component instead of using native one (see https://github.com/epicmaxco/vuestic-ui/issues/146) in the near future.

Thanks!
