### ISSUE TITLE
ButtonDropdown design is meh

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2619]
Looks too generic. Check other frameworks designs.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/5394573/199515399-e60b099b-78a9-461f-b58a-4de434897d1b.png">

Here's ant example:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/5394573/199685252-f6975958-da26-4114-8ce8-04ae43da35be.png">

What I think can be done:
* Use different shadow (so that top border of dropdown is visible)
* Improve examples (add options)
* Add animation
* Center button dropdown by button even if it has separate arrow
* Optional arrow (maybe a bit hard to do, so up to you)

Needs https://github.com/epicmaxco/vuestic-ui/issues/2935

**Comment by asvae** [comment]
@xx13 what do you think?

**Comment by tasiotas** [comment]
I agree, dropdown is the main reason why I need component library :)

[Example](https://www.inkline.io/docs/components/dropdown)
![image](https://user-images.githubusercontent.com/9046931/216709320-2be6a97b-be85-4539-8c0d-8afec49fb825.png)

Please consider adding:
1. Separator
2. Arrow (element at the top that connects to the originating anchor)
3. Dropdown elements with hover indicator
4. Animaton

thank you

**Comment by m0ksem** [comment]
How about making MenuComponent? I can propose this API:

```vue
<va-button-dropdown label="label" arrow>
  <va-menu>
     <va-menu-item>Action</va-menu-item>
     <va-menu-item>Another Action</va-menu-item>
     <va-menu-item disabled>No</va-menu-item>
     <va-divider />
     <va-menu-item>BEBEBE BUBUBU</va-menu-item>
  </va-menu>
</va-button-dropdown>
```

Something similar to `VaList`, but smaller with hover effect similar to `VaSelect`. We actually have `VaSelectOptionsList` which can be exposed as separated component. Maybe even name is `VaOptionsList` instead of `VaMenu`.

**Comment by m0ksem** [comment]
Moved to https://github.com/epicmaxco/vuestic-ui/issues/1417
