### ISSUE TITLE
Vuestic unplugin instead of vue-cli-plugin

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2625]
Looks like [create-vue](https://github.com/vuejs/create-vue) is recommended way to create vue project, so likely no one use vue-cli anymore. 

We might create unplugin for vite, webpack etc, which handle installation of vuestic. 
(example of installation process: https://github.com/m0ksem/unplugin-object-3d#install)

In plugin we also might handle automatic tree-shaking (scan for used components across app and install them with createVuesticEssential) - similar to what nuxt has built-in.

Might be more important than [create-vuestic](https://github.com/epicmaxco/vuestic-ui/issues/2204)

We need to make it easy to install vuestic, so user shouldn't even think about looking at manual installation docs.

**Comment by asvae** [comment]
Looks promising. 👍

**Comment by m0ksem** [comment]
Since we have nuxt integration and create-vuestic I think we don't need this issue.
