### ISSUE TITLE
Something went wrong with code formatting.

### ISSUE THREAD

**Issue by whitel1ght** [epicmaxco/vuestic-ui#2629]
<img width="868" alt="Screenshot 2022-11-03 at 17 14 37" src="https://user-images.githubusercontent.com/6572181/199744317-72473748-7bb4-4240-9de3-7653f9f45dd8.png">

**Comment by aluarius** [comment]
Seems to be already fixed:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/64714442/203500741-3d651c16-b249-4600-a66f-66966b6a9d34.png">
