### ISSUE TITLE
[va-avatar] show letter if image is undefined

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2635]
![image](https://user-images.githubusercontent.com/23530004/200107934-3ecee3f8-9dbf-4443-9967-49404da2473b.png)

Expected image to be shown.
![image](https://user-images.githubusercontent.com/23530004/200108054-a31d0fa5-173b-4803-8f16-b25021fb8009.png)
![image](https://user-images.githubusercontent.com/23530004/200108037-825f9f71-df89-4e0c-9906-ebe1469285d1.png)

It would be nice to pass name, so it shows MN if there is not image. Something like name prop

And also src can not be null in types which is sucks

**Comment by m0ksem** [comment]
For now we need to do something like this:

```vue
<va-avatar :src="user.photoURL">
  <template v-if="!user.photoURL">
     {{ convertNameToLetters(user.displayName) }}
  </template>
</va-avatar>
```

Also, user need to implement `convertNameToLetters` manually.

I think for AVATAR it is OK behavior to simply write:

```
<va-avatar :fallback-name="user.displayName" :src="user.photoURL" />
```

**Comment by rustem-nasyrov** [comment]
> Also, user need to implement convertNameToLetters manually.

It's not that big problem to take first chars from the string.

> I think for AVATAR it is OK behavior to simply write:

`<va-avatar :fallback-name="user.displayName" :src="user.photoURL" />`

It's not a problem to do like this:

```html
<template>
  <va-avatar :src="noAvatar">
    J.D.
  </va-avatar>
</template>

<script setup>
const noAvatar = new Promise((resolve) => {
  setTimeout(resolve, 3000);
});
</script>
```
In my opinion this is over-engineering. I think we don't need to add odd props for all common cases, that can be simply resolved by component' usual behavior.

**Comment by asvae** [comment]
Moved to #2663
