### ISSUE TITLE
useColors setHslaColor doesn't allow to set alpha to 0

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2636]

**Comment by rustem-nasyrov** [comment]
It's allows us to set to zero, but it will be transparent. Check example [here](https://www.w3.org/wiki/CSS/Properties/color/HSLA).
<img width="372" alt="image" src="https://user-images.githubusercontent.com/29167241/200577691-db6b188d-cbbc-4bac-91ee-c2a7a754c73b.png">
