### ISSUE TITLE
[va-button] can not  modify backgroundColor  for va-button

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2662]
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/36926073/201057049-27b2dcd3-c739-4cac-9b2d-714cb034c59a.png">

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/36926073/201057150-a86dadd0-f9f0-45d2-9a5f-7afe91ce03a7.png">

the  `::before`  fake element  is used for icon ?

**Comment by m0ksem** [comment]
Hey, @Valar103769. Why wouldn't you just use color prop?

**Comment by Valar103769** [comment]
> Hey, @Valar103769. Why wouldn't you just use color prop?

i dont know color prop means color or bgcolor or theme?

**Comment by m0ksem** [comment]
> > Hey, @Valar103769. Why wouldn't you just use color prop?
> 
> i dont know color prop means color or bgcolor or theme?

color prop means color of button, so it's bg. You can find example docs
