### ISSUE TITLE
Horizontal prop of the VaCard component

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#2669]
Find out interesting idea about making horizontal property of the VaCard component.

<details>
<summary>Screenshots</summary>
<img width="837" alt="image" src="https://user-images.githubusercontent.com/29167241/201184606-96099e5e-30bb-4328-81a8-e49423e6acbf.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/29167241/201184645-f743a24f-6a7e-48ea-96c2-340064135b65.png">
</details>

# Refs
- [Quasar](https://quasar.dev/vue-components/card#example--basic-horizontal)
- [Vuetify](https://vuetifyjs.com/en/components/cards/#horizontal-cards)

**Comment by asvae** [comment]
You can implement this change, and we can check this on review. :)

If you want to discuss:
Our solution: blah blah
Competitor solution: blah blah
Recommended solution: blah blah
