### ISSUE TITLE
[VaSelect]: maxTagCount

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2673]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/36926073/201573145-668fa550-77db-4514-b4cb-a1689ccfdc2d.png">
https://ant.design/components/select-cn/

**Comment by asvae** [comment]
I see this as 2 tasks:
* 1 - select should have `chips` prop
* 2 - select should support `visibleSelections`?

**Comment by aluarius** [comment]
We have already discussed this feature.

- vuefity - transfer to a new line by default, current feature is presented only in slot example (https://vuetifyjs.com/en/components/selects/#selection) and its pretty useless;
- quasar - transfer to a new line by default, current feature isn't presented;
- naiveui - transfer to a new line by default, current feature exists as `max-tag-count` prop (over limit items will be moved to `+N more items` cheap):

<img width="452" alt="image" src="https://user-images.githubusercontent.com/64714442/203002495-26368308-8287-41d1-a689-676d41910c21.png">

- antdesign - same as for naiveui.

We can implement this feature via several ways:
- `max-visible-options` prop. As naiveui and antdesign do. Easy to implement;
- `auto-visible-options` prop. We will force component to calc select wrapper/selected options width and then show some amount of them that can fill select wrapper width without transfering them to the next line. Medium difficulty, suitable if this case has value.
- implement both variants.

**Comment by rustem-nasyrov** [comment]
@aluarius, I'll go with:
> max-visible-options prop. As naiveui and antdesign do. Easy to implement;

**Comment by asvae** [comment]
Let's go with only `max-visible-options`. We probably also need a slot on how to display last items. 

We might have 2nd option if it's fast.

**Comment by asvae** [comment]
But needs more research to get an exact implementation, i.e. are we showing values on hover etc.

**Comment by aluarius** [comment]
- vuetify/antdesign - no additional logic for hidden options hover/click;
- naiveui - popover with all options for hidden options hover.

As was decided, we will implement simple `max-visible-options` prop. For the `+3`-like options we can:
- show all selected options with transfer to the new line (and additional icon to hide them again?);
- do nothing, it's also looks native - just open options list;
- show popover as naiveui does.
