### ISSUE TITLE
Button pressed state

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2674]
![image](https://user-images.githubusercontent.com/23530004/201747456-3f2fb1c7-85af-45ce-b8c8-3c30fa4f9e0d.png)

Want to be able to have pressed buttons like "active".

Solved lt with "secondary" presset.

![image](https://user-images.githubusercontent.com/23530004/201755202-47f92a23-0687-4467-be1a-62240e451360.png)

**Comment by aluarius** [comment]
Why don't use this props?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/64714442/202986042-8d154f8f-7876-4634-9189-7cf05afacf9b.png">
