### ISSUE TITLE
[site] color change is invalid

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2685]
**Does  va-select  can support  this feature  that  look like same as dropdown , such as border-none style** ?

 because hope use va-select  in header, and use this border-none style

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/36926073/202428372-b390bd33-60c9-49db-992b-eaeebf0bbeb0.png">

**Comment by aluarius** [comment]
Thank you for issue!

Seems here to be 2 separate tasks - problem with color switcher and design state request (will move to separate issue).
