### ISSUE TITLE
Dark Theme active by default

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#2690]
**Vuestic-ui version:** 1.5.1

**Steps to reproduce**
if you go from Landing page on any docs page for example
https://vuestic.dev/en/introduction/overview
you can see Dark theme

**What is the expected behavior?**
Dark theme inactive by default
**What is the current behavior?**
Dark theme active by default
**Other information**

**Comment by rustem-nasyrov** [comment]
Can't reproduce. Can you check `localStorage`? Usually we save selected theme to the `localStorage`.
