### ISSUE TITLE
[ag-table] 

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2698]
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/36926073/202988477-6b44fe5a-1e94-4557-87fd-851aa5947cb2.png">

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/36926073/202988526-c8e17005-c61a-4713-b006-01d46f7d8c54.png">

should see all headerName no `overflow: ellipsis`

**Comment by rustem-nasyrov** [comment]
Hello @Valar103769, thank you for your reporting, if it's not tough for you, can you share example on codesandbox or part of the code? Fast check resulted that we don't have any `overflow: ellipsis` in our styles.

**Comment by m0ksem** [comment]
`text-overflow: ellipsis;` comes from ag-grid. I suggest use less columns, paddings, etc. It is not related to Vuestic theme here. Thanks!
