### ISSUE TITLE
Breakpoints / screen service

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#27]
# Previous progress
* Check this [issue](https://github.com/epicmaxco/vuestic-admin/issues/308). We want to improve on existing solution.

# Docs
- [x] Do after [docs boilerplate](#17) is done.
- [ ] Provide some general information on flexbox in context of vuestic grid syntax. Intended for new user, who might be not proficient in flexbox.
- [ ] Playground.

# Introduction
* Breakpoints are used in 2 places: as a JS service and in css classes. We want both.
* For exact breakpoint number we use [material design](https://quasar.dev/layout/grid/introduction-to-flexbox#Responsive-Design) solution

# Breakpoint service

- [ ] Support breakpoints xs, sm, md ,lg, xl.
- [ ] Allow modifying thresholds on app initialization.
- [ ] Create getters for conditional breakpoints on app initialization (i.e. `mdAndUp`, see also https://github.com/epicmaxco/vuestic-ui/issues/1193)
- [ ] provide current breakpoint
- [ ] provide width and height
- [ ] expose thresholds as numbers. (i.e. `$va.screen.thresholds.xs`). There should be no threshold for highest breakpoint.

## Notes
* All exposed methods and properties should be reactive.
* We want implementation to be bound via inject/provide to be able to test specific breakpoints more easily.

# CSS implementation

------------------- [TODO] --------------------

# Notes
* The intention for thresholds declaration is to provide them separately for scss and js. But feel free to investigate/play around with universal declaration, i.e. json file. We want to understand trade-offs.
* See also https://github.com/epicmaxco/vuestic-ui/issues/774

# Refs
* [Vuetify](https://vuetifyjs.com/en/customization/breakpoints)

**Comment by luuuke** [comment]
A small suggestion: What about making breakpoints for the content section dependent on the sidebar state? I.e. if the sidebar is maximized, less space is available for the content, thus breakpoints should trigger earlier than when the sidebar is minimized.

**Comment by asvae** [comment]
Would be great to run another round of research before implementation here.

There are also several points to discuss here. I.e. do we want to bind css helpers to breakpoints implementation (tailwind style) or keep them separate.

**Comment by asvae** [comment]
Couple of ideas:

![image](https://user-images.githubusercontent.com/5394573/179629714-a109c108-c678-4228-91ec-3b7cb5495dd4.png)

Breakpoint service could somewhat overlap with sidebar and layout logic. On implementation side it's not clear how that would look, could be one service or multiple ones.

**Comment by m0ksem** [comment]
How about having two sidebars on both sides? This can be implemented with CSS variables. Change them programmatically if sidebar is opened. But it is a thing that user must do manually. We don't have components that rely on breakpoints. So it is an independent service for user to play with. 🤔

**Comment by asvae** [comment]
We might be able to do some trickstery with js: https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia.

CSS variables are sadly not an option for media queries.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2189
