### ISSUE TITLE
va-button with icon-right shifted

### ISSUE THREAD

**Issue by maximebakercssc** [epicmaxco/vuestic-ui#2704]
**Vuestic-ui version:** 1.5.1

**Steps to reproduce**
Add va-button with icon-right
**What is the expected behavior?**
va-button keeps same aspects.
**What is the current behavior?**
va-button with icon-right is shifted.
**Other information**
![image](https://user-images.githubusercontent.com/68647427/203131617-de66fba9-04ec-4d0b-9fc8-7c6695b28e2f.png)
![image](https://user-images.githubusercontent.com/68647427/203131661-ee2c10da-afbc-47d0-9471-e010f51bb8ac.png)

**Comment by rustem-nasyrov** [comment]
Thank you for your report, we'll fix.

**Comment by rustem-nasyrov** [comment]
@maximebakercssc Hi, for now I'll suggest you to use `display: flex` on the parent `div`. We're working on the issue.

**Comment by asvae** [comment]
I think we had similar issue in other places as wel.

**Comment by asvae** [comment]
We're not going to finish it in sprint. Will wait for @igorprodev1.

**Comment by asvae** [comment]
I'm on 1.8.0 and it's still meh

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/b6e4ed30-e28d-41ad-b318-7ed685984ff7)

**Comment by maximebakercssc** [comment]
> I'm on 1.8.0 and it's still meh
> 
> ![image](https://user-images.githubusercontent.com/5394573/269387679-b6e4ed30-e28d-41ad-b318-7ed685984ff7.png)

Yeah me too, it cames back.
