### ISSUE TITLE
[Menu] Vertical Menu with sub-menus.

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2714]
look like https://element-plus.org/en-US/component/menu.html#side-bar

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/36926073/203489244-7f5175da-8cb4-4d63-8cad-5b83db67254c.png">

**Comment by rustem-nasyrov** [comment]
Hello @Valar103769, thank you for your request. We already have a `VaSidebar` component, but docs for it may not cover your or other users' cases.

**Comment by rustem-nasyrov** [comment]
https://vuestic.dev/en/ui-elements/accordion#menu
