### ISSUE TITLE
css bug 

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2728]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/36926073/203921305-7b8cf406-e96a-4b09-b04f-feb4c088fd20.png">

not need 

recommand read 
https://www.zhangxinxu.com/wordpress/2010/10/%e9%a1%b5%e9%9d%a2%e9%87%8d%e6%9e%84%e2%80%9c%e9%91%ab%e4%b8%89%e6%97%a0%e5%87%86%e5%88%99%e2%80%9d-%e4%b9%8b%e2%80%9c%e6%97%a0%e5%ae%bd%e5%ba%a6%e2%80%9d%e5%87%86%e5%88%99/

**Comment by rustem-nasyrov** [comment]
Hi @Valar103769, could you please clarify what's incorrect? Is there any issues with `VaSelect` component?
