### ISSUE TITLE
[vaPagination]: preset= darkPagination not work

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2736]
https://stackblitz.com/edit/vitejs-vite-d73ugv?file=src/main.ts

**Comment by aluarius** [comment]
Checked, everything works well.

I haven't met any pagination presets via the provided example link, but you can try configuration example below:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/64714442/205279087-6ad0cf65-630d-4c3c-b9e8-73b69bf27edd.png">

Additional info: https://vuestic.dev/en/services/components-config#presets-config
