### ISSUE TITLE
nuxt shows warning message

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2741]
**Vuestic-ui version:** 1.5.1

> From email

I have an issue with vuestic where when I add it with nuxt, it shows a warning message. Here is the message.
 
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

**Comment by rain-hsiang** [comment]
+1  in nuxt3

**Comment by dongke404** [comment]
problem+1 in nuxt3
