### ISSUE TITLE
[va-modal] Was it designed that way on purpose? 

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2743]
vuestic 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/36926073/204698680-5dc692be-66a4-463a-aad7-165cc3873a0c.png">

element-plus

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/36926073/204698655-a9caa056-6d48-47b4-a954-f8fdeda41aad.png">

**Comment by rustem-nasyrov** [comment]
Hi @Valar103769! Try to use [`prevent-overflow`](https://vuestic.dev/en/ui-elements/dropdown#prevent-overflow) property on the `va-select` component.

**Comment by aluarius** [comment]
```vue
<va-select prevent-overflow />
```
It solves the problem.

Anyway there is no design issue - our modal window `overflow: auto` by default and this makes content scrollable by default. Element UI `overflow: visible` by default and you need to proceed overflow situations yourself.
