### ISSUE TITLE
[Nuxt 3] Can't import custom svg icon component inside nuxt.config.ts

### ISSUE THREAD

**Issue by bogdan0083** [epicmaxco/vuestic-ui#2758]
Hey guys! I'm trying to use custom svg component as an icon. For this I need to import component into `nuxt.config.ts` and register it inside `vuestic.config.icons`:

```ts
import { VaButton } from 'vuestic-ui'
import UiIconCheck from 'components/ui/Icon/Check'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['@vueuse/nuxt', '@vuestic/nuxt'],
  css: ['@/assets/scss/main.scss'],
  vuestic: {
    fonts: false,
    css: ['grid', 'reset'],
    config: {
      components: {
        // @ts-ignore
        VaButton,
      },
      icons: [
        {
          name: 'check',
          component: UiIconCheck,
        },
      ],
    },
  },
})
```

Here's what my icon component looks like:
```vue
<template>
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" clip-rule="evenodd"
          d="M13.3914 3.87496C13.5867 4.07022 13.5867 4.38681 13.3914 4.58207L6.32038 11.6531C6.22661 11.7469 6.09943 11.7996 5.96682 11.7996C5.83422 11.7996 5.70704 11.7469 5.61327 11.6531L2.31344 8.35331C2.11818 8.15804 2.11818 7.84146 2.31344 7.6462C2.5087 7.45094 2.82528 7.45094 3.02055 7.6462L5.96682 10.5925L12.6843 3.87496C12.8796 3.6797 13.1962 3.6797 13.3914 3.87496Z"
          fill="currentColor" />
  </svg>
</template>

<script>
export default {
  name: "UiIconCheck"
}
</script>

```

But `nuxt` cant find the icon and **throws the error**:
```
 ERROR  Cannot start nuxt:  Cannot find module 'components/ui/Icon/Check'                                                                                                                                                                                              
```

Can you give me an idea what am I doing wrong?

**Vuestic-ui version:** 1.4.10

```
"@vuestic/nuxt": "^1.0.9",
"vuestic-ui": "^1.4.10" // taken from package json inside @vuestic/nuxt

**Steps to reproduce**
Import custom component and apply in inside `nuxt.config.ts` -> `vuestic.components.icons`

**What is the expected behavior?**
Icon is registered and can be used as `<va-icon name="check"></va-icon>`

**What is the current behavior?**
Nuxt throws the error: `  Cannot start nuxt:  Cannot find module 'components/ui/Icon/Check' `

Thank you!

**Comment by m0ksem** [comment]
Hi, @bogdan0083. Have you tried to use relative path instead of `components/` alias?

**Comment by bogdan0083** [comment]
> Hi, @bogdan0083. Have you tried to use relative path instead of `components/` alias?

Hmm, I didn't try it. I'll check tomorrow if it works.

**Comment by rustem-nasyrov** [comment]
> Hi, @bogdan0083. Have you tried to use relative path instead of `components/` alias?

It won't work. Looks like nuxt can't work with imported components.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/29167241/205448883-cfbff0ee-dea0-41ec-a826-3dcb0f3209d9.png">

<details>
<summary>nuxt.config.ts</summary>

```javascript
import UiIconCheck from "./components/ui/Icon/Check.vue";

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['@vuestic/nuxt'],
  vuestic: {
    config: {
      icons: [
        {
          name: 'check',
          component: UiIconCheck,
        },
      ],
    },
  },
})

```
</details>

**Comment by bogdan0083** [comment]
> > Hi, @bogdan0083. Have you tried to use relative path instead of `components/` alias?
> 
> It won't work. Looks like nuxt can't work with imported components. <img alt="image" width="350" src="https://user-images.githubusercontent.com/29167241/205448883-cfbff0ee-dea0-41ec-a826-3dcb0f3209d9.png">
> 
> nuxt.config.ts

Are there any workarounds for using custom components inside nuxt.config.ts? 

Right now I use wrappers for every component with specific slots for icons. Seems like this is the only way to use custom icon components with nuxt 3.

**Comment by rustem-nasyrov** [comment]
@bogdan0083, here is workaround that may help you to solve your problem:
```html
<template>
  <div>
    <va-button icon="check">
      button
    </va-button>
  </div>
</template>

<script setup>
import UiIconCheck from './components/ui/Icon/Check.vue';
import {useGlobalConfig} from 'vuestic-ui';

const {mergeGlobalConfig} = useGlobalConfig()

mergeGlobalConfig({
  icons: [
    {
      name: 'check',
      component: UiIconCheck,
    },
  ],
})
</script>
```
If you will have a lot of custom icons, I'll suggest you to move this code to composable or function.

<details>
<summary>Example</summary>
For example create a `composables/useGlobalConfig.ts` file:

```javascript

import UiIconCheck from './components/ui/Icon/Check.vue';
import {useGlobalConfig} from 'vuestic-ui';

export default function useCustomIcons() {
  const {mergeGlobalConfig} = useGlobalConfig()

  mergeGlobalConfig({
    icons: [
      {
        name: 'check',
        component: UiIconCheck,
      },
    ],
  })
}
```

In the `app.vue` file:

```html
<script setup>
import useCustomIcons from './composables/useCustomIcons';

useCustomIcons();
</script>
```
</details>

**Comment by bogdan0083** [comment]
> @bogdan0083, here is workaround that may help you to solve your problem:
> 
> ```
> <template>
>   <div>
>     <va-button icon="check">
>       button
>     </va-button>
>   </div>
> </template>
> 
> <script setup>
> import UiIconCheck from './components/ui/Icon/Check.vue';
> import {useGlobalConfig} from 'vuestic-ui';
> 
> const {mergeGlobalConfig} = useGlobalConfig()
> 
> mergeGlobalConfig({
>   icons: [
>     {
>       name: 'check',
>       component: UiIconCheck,
>     },
>   ],
> })
> </script>
> ```
> 
> If you will have a lot of custom icons, I'll suggest you to move this code to composable or function.
> 
> Example

Thank you! This seem to be working. 

I wonder if this workaround has runtime overhead though? Will it slow my app if I use lots of custom icons? (I have around 100 icons in my current project and about 8 different layouts).

It would be cool to have some kind of functionality to add icons at the build time instead of runtime.

But anyways, thanks for the answers! ❤️

**Comment by bogdan0083** [comment]
@rustem-nasyrov For some reason `useGlobalConfig` doesn't work. It throws the error when I try to call `useGlobalConfig()`:
```
Can not find icon config from va-check. Please provide default config.
```

I tried to use it inside one of the page `
import useCustomIcons from "@/composables/ui/useCustomIcons";

useCustomIcons();

**Comment by rustem-nasyrov** [comment]
@bodgan, you have `@vuestic/nuxt` module duplication.

**Comment by bogdan0083** [comment]
> @bodgan, you have `@vuestic/nuxt` module duplication.

@rustem-nasyrov  Are you talking about this line?

```ts
  modules: ['@vueuse/nuxt', '@vuestic/nuxt'],
```

It's actually `@vueuse/nuxt` as the first element, not `@vuestic/nuxt`

**Comment by rustem-nasyrov** [comment]
Lol, my bad. Will take a look then. :)

**Comment by rustem-nasyrov** [comment]
@bogdan0083, unfortunately, I can't reproduce it. Could you please share your `useCustomIcons` composable?

**Comment by bogdan0083** [comment]
> @bogdan0083, unfortunately, I can't reproduce it. Could you please share your useCustomIcons composable?

@rustem-nasyrov  I tried to add that `useCustomIcons` composable again and it seems to work fine. Have no idea what happened before. Sorry for bothering you :)

Can you please answer this question? I really want to know if this might hit perfomance on big number of icons.

> I wonder if this workaround has runtime overhead though? Will it slow my app if I use lots of custom icons? (I have around 100 icons in my current project and about 8 different layouts). As far I understand it will merge icons on every server request. Is this correct?

**Comment by rustem-nasyrov** [comment]
@bogdan0083, yes, I think it will. I suggest you to create for the your project an icon font from your custom icons. And then use it with vuestic' [icons configuration](https://vuestic.dev/en/services/icons-config). This solution should much better rather than earlier solution.

**Comment by bogdan0083** [comment]
> @bogdan0083, yes, I think it will. I suggest you to create for the your project an icon font from your custom icons. And then use it with vuestic' [icons configuration](https://vuestic.dev/en/services/icons-config). This solution should much better rather than earlier solution.

Thank you for the answer! I guess using custom icon font is the only option for me.

Closing.
