### ISSUE TITLE
`VaBadge` positioning is weird

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2769]
We can set position of the badge via `left` and `bottom` separate boolean props.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/64714442/205650707-1b446ff7-97f6-4a12-958d-669c2d54941c.png">

That's pretty weird and i'd like to have one `position` prop that will give me a flexibility to set any (top-left, bottom-left, right-top, right-bottom).

**Comment by xiongmao86** [comment]
I am really sorry the words didn't register when I read this comment for the first time. I have added the `left-top`, `left-bottom`, `right-top` and `right-bottom` to be Placement alias in #2777.
