### ISSUE TITLE
Custom transitions

### ISSUE THREAD

**Issue by bogdan0083** [epicmaxco/vuestic-ui#2773]
Hey guys! Is it possible to add custom transitions for `VaPopover` component? I browsed through the source code and didn't find any transition components. Would be cool to have `transition` wrapper component to add `enter` and `leave` transitions the way you like.

Thank you.

**Comment by rustem-nasyrov** [comment]
Hello, @bogdan0083! Have you tried to use built-in [transition component](https://vuejs.org/guide/built-ins/transition.html)?

**Comment by bogdan0083** [comment]
> Hello, @bogdan0083! Have you tried to use built-in [transition component](https://vuejs.org/guide/built-ins/transition.html)?

Hi! I couldn't find a way to apply transition for the popover. To use transition component it needs to be defined inside `VaDropdown` (that's what `VaPopover` uses under the hood). Otherwise I just don't have an element to wrap into custom transition.

Or do you mean that I can wrap popover content in `Transition` inside content slot? I haven't tried this one.

**Comment by rustem-nasyrov** [comment]
Yep, I meant the second option. Sorry that I didn't clarify it.

**Comment by bogdan0083** [comment]
> Yep, I meant the second option. Sorry that I didn't clarify it.

I'll try it in my spare time and come back to say if it worked or not, thanks :)

**Comment by rustem-nasyrov** [comment]
I've checked it for you and unfortunately it doesn't work. We will discuss about adding this feature to the components.

**Comment by asvae** [comment]
I think we need to detail this task:
* figure out which components would benefit from supporting transitions out of the box (selects, popups, modals, popover, notifications)
* For other components - we need some information in docs on how to apply transition.

**Comment by kushich** [comment]
@asvae 
Missing transitions:
-  va-alert - show-hide transition (closeable prop) 
- va-badge - show-hide transition / transform transition
- va-dropdown (and all components which use it)  - show-hide transition
- va-chip - transform transition 
- va-image - _transition between loading slot and loaded image?_
-  va-modal - show-hide transition
-  va-popover - show-hide transition
-  va-backtop - show-hide transition
-  va-color-input - show-hide transition
-  va-infinite-scroll - show-hide transition for new items
- va-inner-loading - show-hide transition for loading prop

Also:
What about a smooth transition for validation?
What about transition scss presets / vue helper components?

**Comment by asvae** [comment]
Moved to #2943
