### ISSUE TITLE
nuxt not operational yet :<

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2784]
**Vuestic-ui version:** 1.5.2
https://discord.com/channels/457593300799717377/862292500039729152/1050773569501675670
Clean project still gives a warn, maybe we missed something or it's something node version specific.

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

**Comment by aluarius** [comment]
Answered in slack, but will take a look at monday.
