### ISSUE TITLE
[big bug]: if fonts.googleapis.com fail, the page is breakdown

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2796]
when 
```js
@import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;1,700&display=swap');
@import url('https://fonts.googleapis.com/icon?family=Material+Icons');

```

fetch error ,
the page's font has problem,
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/36926073/208030257-c0b0467f-c31a-415e-a28b-edb753ac717a.png">

1. the `fonts.googleapis.com/` not just used to icon ?  way can cause font error? 
 
2. in china, can't use  `google` and `googleapis.com`,  There are not many ICONS, can you build in some? Or use the npm package, not the cdn,

**Comment by Valar103769** [comment]
@asvae There's a production problem, one or two more and I'm out of here 
<img width="164" alt="image" src="https://user-images.githubusercontent.com/36926073/208031088-2f43d6eb-7b46-4d1a-87bc-1b48f9e3ddbb.png">

**Comment by Valar103769** [comment]
this is font-family problem? 

https://www.bilibili.com/video/BV1b54y1Z7pu/?spm_id_from=333.999.0.0

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/36926073/208031641-da8de065-80d3-4d23-85ff-687aeacf657c.png">

```js
@font-face {
  font-family: Emoji;
  src: local('Apple Color Emojiji'), local('Segoe UI Emoji'), local('Segoe UI Symbol'), local('Noto Color Emoji');
  unicode-range: U+1F000-1F644, U+203C-3299;
}
.font-serif {
  font-family: Georgia, Cambria, 'Times New Roman', Times, serif;
}
.font-mono {
  font-family: Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}
```
The author of the video is one of the strongest css figures in our country

**Comment by rustem-nasyrov** [comment]
Hi, @Valar103769! If it's possible could you please download fonts directly into the project and use it? [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro?query=source+sans+pro) and replace icons with this [icon library](https://www.npmjs.com/package/material-design-icons-iconfont).

**Comment by rustem-nasyrov** [comment]
And here is [configuration guide](https://vuestic.dev/en/getting-started/configuration-guide#icon-fonts) for the icons.

**Comment by Valar103769** [comment]
ok
