### ISSUE TITLE
[VaAlert] [Safari]  The string did not match the expected pattern.

### ISSUE THREAD

**Issue by bogdan0083** [epicmaxco/vuestic-ui#2805]
**Vuestic-ui version:**
`"@vuestic/nuxt": "^1.0.9"` uses `"vuestic-ui": "^1.4.10"` under the hood

**Steps to reproduce**
1. Open `Safari version 15`
2. Open https://vuestic.dev/en/ui-elements/alert
3. Open Safari devtools and console
4. Check the errors: 
<img width="1426" alt="Снимок экрана 2022-12-21 в 15 10 36" src="https://user-images.githubusercontent.com/7077307/208853444-154d74c8-eb0c-49d1-9736-96cbf84cc8a3.png">

**What is the expected behavior?**
No console errors

**What is the current behavior?**
Error which breaks other components in the project.

**Other information**
The error also happening on `iOS 16` and it basically just breaks all interactions on the page.
As far as I understand it breaks inside `composables/useElementBackground/utils.ts` in `getElementBackgroundFromCSS` function in the `matches` method:

<img width="745" alt="Screenshot 2022-12-21 в 15 13 58" src="https://user-images.githubusercontent.com/7077307/208854061-0e1b83a5-f041-4dee-b59c-2ac25f2051e3.png">

For some reason safari cannot handle the selector (or element?) and explodes. Here's other reference to the issue: https://www.reddit.com/r/firefox/comments/5nbmqi/on_handling_invalid_selector_strings/

**Comment by rustem-nasyrov** [comment]
Hello, @bogdan0083! Thank you for your research and report. We'll fix asap.
