### ISSUE TITLE
Horizontal align of the dropdown content after autoplacement change

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2806]
I don't know is it problem with dropdown or time picker component configuration, but I'm facing this bug. When you open focus on time picker component and scroll up, it automatically positionates to the center.
Before scrolling:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/29167241/208915087-e37b845d-20d7-4b91-9faa-92fbcd451769.png">
After:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/29167241/208915144-60658907-9a69-46fe-8fbc-f753169aaea9.png">

_Originally posted by @rustem-nasyrov in https://github.com/epicmaxco/vuestic-ui/issues/2804#issuecomment-1361307555_

**Comment by m0ksem** [comment]
It is auto-placement bug, it moves dropdown in opposite direction if it doesn't fit the screen. It doesn't count -start or -end position.

**Comment by m0ksem** [comment]
@rustem-nasyrov let's think about floating ui at first

**Comment by m0ksem** [comment]
It is fixed after we migrated to floating-ui.
