### ISSUE TITLE
Dance party on vuestic.dev 💃

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2812]
https://user-images.githubusercontent.com/5394573/209353989-2b5649ba-7ca0-4ed3-9eff-b11ba4343774.mov

Vuestic-ui version:** 1.5.3
 
When you go to vuestic.dev, then you open console - dance party begins.

Seems like css is getting re-added

**Comment by LighthouseKeeperYN** [comment]
Can't reproduce. 
https://drive.google.com/uc?id=1suVke2ok7xqcFZA8ECN2BnsoK4sCHh4n

**Comment by asvae** [comment]
Seems to have been fixed 🤷
