### ISSUE TITLE
va-on-primary is not available CSS variable in nuxt

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2818]
![image](https://user-images.githubusercontent.com/23530004/209815021-fad54b3b-1be2-4018-b8e3-44817445d1b7.png)
nuxt: 3.0.0
vuestic-ui: 1.5.3
@vuestic/nuxt: 1.0.9

But, should be available in vuestic-plugin.

**Comment by rustem-nasyrov** [comment]
I've checked with latest vuestic' build and it works seems to me. Let's check this issue after release.

<details>
<summary>Context</summary>

I've created new nuxt project and installed latest `@vuestic/nuxt` package - it didn't fix. After that I tried to build latest version of the Vuestic UI and replaced `dist` in nuxt project, after restart it worked, though most of colors are were white.
</details>

**Comment by m0ksem** [comment]
> I've checked with latest vuestic' build and it works seems to me. Let's check this issue after release.
> 
> <details>
> <summary>Context</summary>
> 
> I've created new nuxt project and installed latest `@vuestic/nuxt` package - it didn't fix. After that I tried to build latest version of the Vuestic UI and replaced `dist` in nuxt project, after restart it worked, though most of colors are were white.
> </details>

Likely, I did a pr recently fixing it, but don't remember which one.

**Comment by rustem-nasyrov** [comment]
@m0ksem, is this [PR](https://github.com/epicmaxco/vuestic-ui/pull/3185)? Let's close this issue then.

**Comment by m0ksem** [comment]
> @m0ksem, is this [PR](https://github.com/epicmaxco/vuestic-ui/pull/3185)? Let's close this issue then.

Yeah. Thanks!
