### ISSUE TITLE
[Nuxt 3] Custom icon font in nuxt.config.ts

### ISSUE THREAD

**Issue by bogdan0083** [epicmaxco/vuestic-ui#2822]
**Vuestic-ui version:**
`"@vuestic/nuxt": "^1.0.9"` uses `1.5.3`

I'm trying to add custom icon font to my `nuxt 3` project. Here's `nuxt.config.ts`:

```ts
import { createIconsConfig, IconConfiguration, VaButton, VaIcon } from "vuestic-ui";

// @ts-ignore
const fonts: IconConfiguration[] = [{
  name: 'ia-{name}',
  resolve: ({ name }) => ({
    class: `icon ia-${name}`,
  }),
}];

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['@vueuse/nuxt', '@vuestic/nuxt'],
  css: ['@/assets/scss/main.scss'],
  build: {
    transpile: ['swiper'],
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "./assets/scss/_mixins.scss";',
        },
      },
    },
  },
  vuestic: {
    fonts: false,
    css: ['reset'],
    config: {
      icons: createIconsConfig({fonts}),
      components: {
        // @ts-ignore
        VaButton,
        VaIcon: {
          sizesConfig: {
            defaultSize: 16,
            sizes: {
              small: 16,
              medium: 24,
              large: 32,
              extraLarge: 48,
              huge: 56,
            },
          },
        },
      },
    },
  },
})
```

As you can see I'm adding a font icon resolver, which should resolve icons by adding a custom `icon ia-{name}` class. But instead the icon resolves to this:

<img width="872" alt="Снимок экрана 2022-12-29 в 13 52 13" src="https://user-images.githubusercontent.com/7077307/209914864-86e23681-da58-4537-b1bb-0b7f5700b2b9.png">

What am I doing wrong? Please note that vuestic *detects* custom `ia-` prefix (no errors is thrown on using `<va-icon name="ia-arrow-down"></va-icon>`) but it doesn't add needed classes.

Thanks!

**Comment by m0ksem** [comment]
Hey, @bogdan0083. Nuxt doesn't allow us to pass function as value to vuestic-ui yet. 

I can suggest use `const { updateGlobalConfig } = useGlobalConfig()` in app.vue during runtime.

For now, I can not figure out how to pass a function from nuxt config to nuxt plugin.

**Comment by m0ksem** [comment]
Scope for this task:
- Tried to pass function from Nuxt's Runtime config and it ignores functions.
- Tried to serialize function, but there are errors caused by deserialization via eval.

**Comment by bogdan0083** [comment]
> Hey, @bogdan0083. Nuxt doesn't allow us to pass function as value to vuestic-ui yet.
> 
> I can suggest use `const { updateGlobalConfig } = useGlobalConfig()` in app.vue during runtime.
> 
> For now, I can not figure out how to pass a function from nuxt config to nuxt plugin.

This solution seems to be working, thanks! Will wait for a fix to use icons without a small runtime overhead.

**Comment by aleavikraman** [comment]
@bogdan0083 can you please share where you put `const { updateGlobalConfig } = useGlobalConfig()`

I added it to my app.vue but that didn't work

**Comment by bogdan0083** [comment]
> @bogdan0083 can you please share where you put `const { updateGlobalConfig } = useGlobalConfig()`
> 
> I added it to my app.vue but that didn't work

I created composable in `composables/ui/useCustomIcons.js`. It looks like this:

```js
import UiIconCheck from '@/components/ui/Icon/Check.vue'
import UiIconCourse from '@/components/ui/Icon/Course'
import UiIconChart from '@/components/ui/Icon/Chart'
import UiIconQuestion from '@/components/ui/Icon/Question'
import UiIconArrowLeft from '@/components/ui/Icon/ArrowLeft'
import UiIconArrowDown from '@/components/ui/Icon/ArrowDown'
import UiIconClose from '@/components/ui/Icon/Close'
import UiIconWarning from '@/components/ui/Icon/Warning'

import { useGlobalConfig } from 'vuestic-ui'

let useCustomIcons = () => {
  const { mergeGlobalConfig } = useGlobalConfig()

  mergeGlobalConfig({
    icons: [
      {
        name: 'ia-{name}',
        resolve: ({ name }) => ({
          class: `ia-icon ia-icon-${name}`,
        }),
      },
      {
        name: 'check',
        component: UiIconCheck,
      },
      {
        name: 'va-check',
        component: UiIconCheck,
      },
      {
        name: 'course',
        component: UiIconCourse,
      },
      {
        name: 'chart',
        component: UiIconChart,
      },
      {
        name: 'close',
        component: UiIconClose,
      },
      {
        name: 'question',
        component: UiIconQuestion,
      },
      {
        name: 'va-warning',
        component: UiIconWarning,
      },
      {
        name: 'arrow-left',
        component: UiIconArrowLeft,
      },
      {
        name: 'va-arrow-down',
        component: UiIconArrowDown,
      },
    ],
  })
}
export default useCustomIcons
```

And then in layout file I use it like this:

```vue
<script setup>
import useCustomIcons from '@/composables/ui/useCustomIcons'
import { useCookie, useRoute } from 'nuxt/app'
import { computed, watchEffect } from 'vue'

useCustomIcons()

...
```
```

**Comment by m0ksem** [comment]
We updated nuxt module so it supports function now: https://vuestic.dev/getting-started/nuxt#nuxt-vuestic-config-title
