### ISSUE TITLE
Move all integrations to separate sections

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2823]
Right now integrations are spread out, we want to keep them in one category, but link in other places so that users will have an easier time finding them.

**Comment by aluarius** [comment]
And I would reorder styles nav menu:

Colors
CSS Variables
Typography
GrId (Make alert in grid and say that we recommend use Tailwind)
Tailwind Integration
Smart Helpers
CSS reset (Make alert that we will remove it, because components work great without reset).

(c)
