### ISSUE TITLE
Button toggle re-design

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2831]
Make a little ui change?
<img width="752" alt="image" src="https://user-images.githubusercontent.com/36926073/203510648-3f897fca-9161-4663-bc35-e4cfd2dda60e.png">

https://www.primefaces.org/primevue/selectbutton

<img width="592" alt="image" src="https://user-images.githubusercontent.com/36926073/203510475-d73be920-9b9c-405f-bd27-f85713662ea0.png">

_Originally posted by @Valar103769 in https://github.com/epicmaxco/vuestic-ui/discussions/2715_

**Comment by m0ksem** [comment]
I like it. Having white buttons looks appropriate.

**Comment by asvae** [comment]
There should be already a way to do this

**Comment by asvae** [comment]
Would be part of bigger docs rework.
