### ISSUE TITLE
Navbar center slot disappears on mobile screen size

### ISSUE THREAD

**Issue by JohanAndreVisma** [epicmaxco/vuestic-ui#2841]
**Vuestic-ui version:** 1.5.3

**Steps to reproduce**

Open https://vuestic.dev/en/ui-elements/navbar in chrome open dev tools and change to mobile resolution.

**What is the expected behavior?**

All slots should be shown in first example

**What is the current behavior?**

Center slot is not visible.

**Other information**
![Vuestic navbar bug](https://user-images.githubusercontent.com/78589576/210662171-a4bc8ab8-1f5c-4f08-9b71-b2daf2d19c00.png)

**Comment by LighthouseKeeperYN** [comment]
Should be fixed by https://github.com/epicmaxco/vuestic-ui/pull/2835

**Comment by JohanAndreVisma** [comment]
@LighthouseKeeperYN Good, looking forward to the fix 👍
