### ISSUE TITLE
Switch height bug

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2864]
In flex container va-switch with, for example, error label will be rendered in this weird way:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/64714442/212016798-b5c97064-d8cd-4fb0-a9df-76275dcde6fc.png">

No problem for block:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/64714442/212016868-e7f08208-f0af-4887-a44a-5004cb77e24a.png">

User can solve this with align-items: flex-start, but it's not good :)

This behaviour is caused by height: 100% of the va-switch container and @m0ksem says that we need it.

So, we should solve this situation.

**Comment by m0ksem** [comment]
Might be related to this issue https://github.com/epicmaxco/vuestic-ui/issues/1323
