### ISSUE TITLE
Virtual Scroller one slot based behavior

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2866]
Current implementation works great if we have items with fixed size. What I propose to use child-based calculations.

```html
<va-virtual-scroller
  :wrapper-size="200"
>
  <va-virtual-scroller-item
     v-for="user in users"
     :size="user.guest ? '200px' : '500px'"
  >  
     <UserCard :user="user" :show-full-info="!user.guest" />
  </va-virtual-scroller->
</va-virtual-scroller>
```

This make user so much easier to control item size.

Can see a lot provide/inject here or checking for some data-size attribute.

The original idea comes from Web Component's biggest limitation - Web Components do not support slot binds. So, the current VirtualScroller implementation isn't ready for Web Components usage. Beside there are some other difficult bugs, 

Until then, I can't see any good implementation of VirtualScroller https://www.webcomponents.org/search/virtual%20scroll

**Comment by aluarius** [comment]
> Current implementation works great if we have items with fixed size. 

It works with different sizes as well and absolutely no need to set item size at all - it's calculated by component anyway.

But i'll take a look at the slot idea.

**Comment by m0ksem** [comment]
Decided to move it on hold and deal with it later.
