### ISSUE TITLE
VaImage zoom behaviour

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2869]
Add built-in zoom behaviour (https://ant.design/~demos/components-image-demo-basic). Do we need this? Own implementation or side package? Enable boolean props or make it enabled by default and add disable-preview prop? Also i'm not sure if we need controls for the zoomed image (in case of our implementation), but Ant Design and Naive Ui have it.

From: https://github.com/epicmaxco/vuestic-ui/issues/2537

**Comment by m0ksem** [comment]
Let's call it image viewer, not va-image
