### ISSUE TITLE
Quill or some other WYSIWYG editor integration

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2877]
- [ ] Check which wysiwyg editor do we want to use
- [ ] add to vuestic-cli
- [ ] have a validation functionality
- [ ] have a restyling

**Comment by asvae** [comment]
Would be nice to have some more research on this - then another small discussion - then implementation.

**Comment by kushich** [comment]
same issue: https://github.com/epicmaxco/vuestic-ui/issues/2660

**Comment by asvae** [comment]
Moved to #2660
