### ISSUE TITLE
Make vuestic.config.ts in nuxt applications

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2881]
Regarding this issue (https://github.com/epicmaxco/vuestic-ui/issues/2822) I come up with solution: Simply to make our separate config, which we can inject in plugin.

So idea to have vuestic.config.ts parsed from separate file:

module.ts
```ts
const useVuesticConfigAlias = async () => {
  const configPath = await resolvePath('~/vuestic.config.ts')

  if (!existsSync(configPath)) { return }

  const nuxt = useNuxt()

  nuxt.options.alias['#vuestic-config'] = configPath
}
```

runtime:

```ts
import config from '#vuestic-config'

const useVuesticConfig = () => {
  return config
}
```

**Comment by asvae** [comment]
Waiting for you on this @m0ksem :).

**Comment by m0ksem** [comment]
@asvae, @aluarius please check what need to expose from vuestic.config.ts
For now, I made it expect export default as PartialGlobalConfign. How about Tailwind? I assume we will have some configuration here related to Tailwind as well.

**Comment by aluarius** [comment]
For Tailwind we need current Vuestic thresholds and colors settings.

**Comment by aluarius** [comment]
+ describe requirements for the vuestic.config.*
