### ISSUE TITLE
VaAvatar's background color is hardcoded. 

### ISSUE THREAD

**Issue by Sadnessa** [epicmaxco/vuestic-ui#2897]
**Vuestic-ui version:** 
1.5.3

**What is the expected behavior?**
I want to use my own color theme, so I changed primary color from blue to red.

**What is the current behavior?**
VaAvatar's background color still blue.

**Other information**
According to devtools background color hardcoded for VaAvatar.
![image](https://user-images.githubusercontent.com/67637329/214782641-7295a726-f61f-436c-8abb-2a942ec8e8da.png)

**Comment by rustem-nasyrov** [comment]
@Sadnessa, thank you for the report. I checked it recently with the latest version and it can't be hardcoded like in your case.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/29167241/214849044-aaca80cf-207d-4772-9e4e-423f70bfd9a8.png">
Is it possible that you have an extra styles over `VaAvatar` component? Could you please check it?

**Comment by m0ksem** [comment]
> @Sadnessa, thank you for the report. I checked it recently with the latest version and it can't be hardcoded like in your case. <img alt="image" width="322" src="https://user-images.githubusercontent.com/29167241/214849044-aaca80cf-207d-4772-9e4e-423f70bfd9a8.png"> Is it possible that you have an extra styles over `VaAvatar` component? Could you please check it?

I think issue here because VaAvatar default color is info.
@rustem-nasyrov, can you explain why it is `info` instead of `primary`?

**Comment by rustem-nasyrov** [comment]
> @rustem-nasyrov, can you explain why it is info instead of primary?

Nope, as I remember it was already.

**Comment by m0ksem** [comment]
> > @rustem-nasyrov, can you explain why it is info instead of primary?
> 
> Nope, as I remember it was already.

I found out the same problem with VaBadge. I would prefer to use everywhere `primary` as default color, which is intuitive for user.

**Comment by rustem-nasyrov** [comment]
Imo avatar it is more visual component and it shouldn't get users' attention.

**Comment by aluarius** [comment]
Decided just to change default avatar and badge colors to primary.
