### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#291]
Not sure what that means, but we need it!

* See [Vuetify wireframes](https://vuetifyjs.com/en/getting-started/wireframes/)

or see https://mui.com/material-ui/react-box/

**Comment by asvae** [comment]
CSS helpers could be more usefult than layout components right now.

**Comment by m0ksem** [comment]
Closing, let's use this issue intead: https://github.com/epicmaxco/vuestic-ui/issues/1430
