### ISSUE TITLE
It would be nice if VaImage's ratio prop have auto value.

### ISSUE THREAD

**Issue by Sadnessa** [epicmaxco/vuestic-ui#2914]
**Vuestic-ui version:** 
1.5.3

**What is the expected behavior?**
I want to use the original height and width of the image.

**What is the current behavior?**
Got this instead:  
![image](https://user-images.githubusercontent.com/67637329/216596950-2bd57e45-4a16-46bd-9191-5d30c1411f6b.png)

**Other information**
It's impossible to use ratio prop, since it receive fixed number value and doesn't have "auto".

**Comment by aluarius** [comment]
The nearest Vuestic release will include full `VaImage` reimplementation. It already contains `auto` prop for aspect ratio.
