### ISSUE TITLE
Docs code examples viewer

### ISSUE THREAD

**Issue by damirJa** [epicmaxco/vuestic-ui#2929]
Docs code examples looks good, but code spaces feels very skinny. I would use more like Github gists code style.
- The old one:
<img width="1070" alt="CleanShot 2023-02-08 at 15 25 17@2x" src="https://user-images.githubusercontent.com/10356386/217557619-855c7295-120b-4878-bcbb-f0a4116d0e9b.png">

- Suggestion:
<img width="919" alt="CleanShot 2023-02-08 at 15 27 42@2x" src="https://user-images.githubusercontent.com/10356386/217558249-41b09444-ecc4-400c-99c2-5d9272f7bece.png">

Link - https://gist.github.com/damirJa/1cf9a9f543593c39630695fb50d40464

@asvae I can take this improvement if you guys don't mind

**Comment by m0ksem** [comment]
Spaces are fixed in nuxt-docs, with slighty different color scheme. We can update it after nuxt-docs are merged.

**Comment by m0ksem** [comment]
Fixed here: https://develop.vuestic.dev/en/getting-started/installation
