### ISSUE TITLE
Fix font-size for text and font-family for code

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#2936]
**Vuestic-ui version:** 1.5.3

font-size for P element (and all default text) - 18px
for all code examples (inline, snippet, API container) ‘source code pro’

**Comment by asvae** [comment]
Regarding font size, take note this refers to `p` and alert elements.

If it's too hard to implement (something else breaks hard) - please close the issue without changing font size.
