### ISSUE TITLE
Update Inline Code text

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#2947]
change styles for inline code text (only in text, not for bottom table with API)

    background: rgba(0, 0, 0, 0.04);
    border: 1px solid rgba(5, 5, 5, 0.06);
    border-radius: 3px;
    padding: 2px 5px;
    font-size: 14px;
    color: currentColor; (or what you use for default text color)

![image](https://user-images.githubusercontent.com/35342240/218067459-a7fb021e-e5bf-451a-a3ac-5bc805b57041.png)

**Comment by asvae** [comment]
@zvenigorodskaia can't we do the same font size for inline code? makes text uneven

**Comment by zvenigorodskaia** [comment]
@asvae if we use 16px for default text and 16px for inline code - (not good)
![image](https://user-images.githubusercontent.com/35342240/218494060-590e11b5-11c7-4eb4-a011-bba2601d48bf.png)

If we leave 16px for text, please use 14px for inline code 
![image](https://user-images.githubusercontent.com/35342240/218494280-43c9444a-c29d-42f8-8c34-46711e46a104.png)

**Comment by asvae** [comment]
Cool, my concern was to have uniform line spacing, but that seems to be handled well.

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/5394573/218584685-50f19bf3-7345-4dfa-adc0-0cca86e8c209.png">

**Comment by asvae** [comment]
Table should keep the same style.

**Comment by m0ksem** [comment]
@asvae, which one?
<img width="898" alt="image" src="https://user-images.githubusercontent.com/23530004/219750223-15436eb6-0c0d-41ae-9a3b-4ff24fc39323.png">
