### ISSUE TITLE
va-image doesn't show images from assets in nuxt3

### ISSUE THREAD

**Issue by martin-ruby** [epicmaxco/vuestic-ui#2952]
**Vuestic-ui version:** 1.5.3, nuxt module version 1.0.10

**Steps to reproduce**
In a nuxt3 project 
```
<template>
  <va-image src="~/assets/img/overview.png" />
</template>
```
does not show the image while a normal image tag (`<img src="~/assets/img/overview.png" />`) would render fine. 
**What is the expected behavior?**
Image should be rendered.
**What is the current behavior?**
Image is not rendered.
**Other information**
There must be an issue with the correct path to the image. If I check the dev-tools, the path for the `img`-tag is `/_nuxt/assets/img/overview.png` while it stays unchanged with `va-img`.

**Comment by m0ksem** [comment]
This path is handled by build plugins. For a Vue component, you should import the image in a script tag and then pass it.

```vue
<script setup>
import AppLogo from '~/assets/app-logo.png';
</script>

<template>
   <va-image :src="AppLogo" />
</template>
```

**Comment by m0ksem** [comment]
We could actually make a plugin since we have nuxt module.

**Comment by asvae** [comment]
Let's just add an example to the docs instead of going with nuxt plugin etc for now.
