### ISSUE TITLE
VaRating - text color is dark

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#2963]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/29167241/218680725-4444b22c-e0b0-4369-8634-7000eb24b0f5.png">

**Comment by m0ksem** [comment]
Partially fixed in nuxt docs branch, but I would like to calculate bg for semitransparent bg.

**Comment by aluarius** [comment]
Implemented, but won't leave this feature because Vasyli rejected it.
