### ISSUE TITLE
Pictures on the Roadmap page

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#2966]
Please change pictures on the Roadmap page (use SVG from https://vuestic.dev/en/introduction/roadmap)
Make titles for cards centered

https://www.figma.com/file/PflCWFZC3xz3YCt7uX3MpP/Documentation?node-id=213%3A956

![image](https://user-images.githubusercontent.com/35342240/218705488-a14012ed-6bc7-4619-b4ad-160de4f6fbec.png)

**Comment by m0ksem** [comment]
I don't like this idea in general. Having specific images will force us to wait until their design is ready. But now we could provide images made as sketch in https://excalidraw.com/ - this can do anyone. Having it in sketch style make sense for roadmap because it is about future.

**Comment by m0ksem** [comment]
And I wouldn't say it is a "high priority", cuz it doesn't break anything and surely can wait few weeks...
