### ISSUE TITLE
Split translation across pages

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2970]
Idea is that 
* vue-18n-unused would just compare other translations to en, then developer would compare to examples etc.
* tree shaking would work properly (right now we're using full translation file everywhere)
* more convenient to work with (all files for page are in one folder)
* do not forget to add "all" translations

**Comment by m0ksem** [comment]
Might worth it to add TS support.

export default definePageTranslation({
  title: string,
  description?: string
  examples?: Record<string, {
     title: string,
     description?: string
  }>
})
