### ISSUE TITLE
[VaTreeView] pointer or cursor option when hovering over Expandable Node

### ISSUE THREAD

**Issue by thunfisch987** [epicmaxco/vuestic-ui#2980]
**Is your feature request related to a problem? Please describe.**

I think it's not clear enough that you can click on the nodes themselves to expand them (instead of clicking on the arrow).

**Describe the solution you'd like**

I think it would be more clear if the cursor style would be `pointer` when hovering over the node (except for the text).

**Describe alternatives you've considered**

--

**Additional context**

Clicking on the nodes also does not work in the docs.

**Comment by rustem-nasyrov** [comment]
Hello, @thunfisch987! Thank you, I'll work on it.
