### ISSUE TITLE
Page config compilation optimization

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2997]

**Comment by asvae** [comment]
Can you describe this in a couple of words? )

**Comment by m0ksem** [comment]
Currently, we parse or vue components and transform translation strings in runtime. I want this to be a build step. As example, file with CSS variables is parsed in build time and we ship only array of parsed data for data table. We had a bad lighthouse score and this could fix it, but as I can see now mostly of performance issues comes from bad hosting. We have a pretty good score on develop.vuestic.dev.

**Comment by m0ksem** [comment]
closed in https://github.com/epicmaxco/vuestic-ui/pull/3352
