### ISSUE TITLE
Code generators

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2998]
We gonna need something new instead of plop.

**Comment by asvae** [comment]
Why?

**Comment by m0ksem** [comment]
Plop has issues with TS and doesn't work in esm mode with nuxt... This cause dependencies mismatch. It is easier to have other generators or made by our own.

**Comment by m0ksem** [comment]
Looks like we don't need it actually. The new page-config API works great enough.
