### ISSUE TITLE
Dance party 2: Eyepopper

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3002]
https://vuestic.dev/en/ui-elements/badge

https://user-images.githubusercontent.com/5394573/219359410-4bf194b2-30a9-407a-b474-d4375159397a.mov

Same issues as https://github.com/epicmaxco/vuestic-ui/issues/2812

**Comment by m0ksem** [comment]
It is not nuxt docs. Also, I saw this kind of issue in Chrome only and I think it is related to Chrome... We had this in thirdparty sites build with Muddle recently.

**Comment by asvae** [comment]
Let's leave it for a bit then.
