### ISSUE TITLE
Use NuxtLink using resolveComponent in useRouterLink composable

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3024]

**Comment by aluarius** [comment]
We've already tried to use `resolveComponent` to resolve `NuxtLink`. No results.

**Comment by thunfisch987** [comment]
The Component Library i've used before had a similar Composable:
https://github.com/inkline/inkline/blob/main/src/composables/linkable.ts
it also works with `<component :is="..."` but resolves the Component beforehand if it's a string, or directly passes it if not.
It's not confined to just routerlink&nuxtlink but rather every component (or component name) you pass in through the routerComponent config option.

**Comment by m0ksem** [comment]
@aluarius, we could pass NuxtLink imported from nuxt via GlobalConfig if there is no other solutions. But it will require us to update both nuxt and ui modules.

**Comment by thunfisch987** [comment]
in the nuxt plugin of the mentioned library (inkline/plugin/nuxt) the NuxtLink component is imported in the EJS Plugin Template file and then assigned to the config option
