### ISSUE TITLE
[Virtual Scroller] Некорректная работа скролла

### ISSUE THREAD

**Issue by teleskop150750** [epicmaxco/vuestic-ui#3025]
**Vuestic-ui version:** 1.5.3

**Steps to reproduce**
https://vuestic.dev/ru/ui-elements/virtual-scroller#any-list-items

Если пролистывать список зажав скроллбар, скролл происходит в обратную сторону

**Comment by aluarius** [comment]
Hi, thanks for the report. Can you please provide more information: os and browser versions. By now we can't repro this problem.

**Comment by teleskop150750** [comment]
fedora 37 kde
Google Chrome 110

https://user-images.githubusercontent.com/62594983/220266662-8b421922-2a0e-42c2-8338-4d036b788a72.mp4

**Comment by asvae** [comment]
Seems to be linux only issue
