### ISSUE TITLE
`npm create vuestic@latest` is broken

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3026]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/5394573/220120904-9c49333a-4c34-4c03-87a2-775dda22321e.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5394573/220120825-ae8ebd30-d37f-40e0-a064-c9f16b17c796.png">

**Comment by asvae** [comment]
@m0ksem should I close it? "Done" status is confusing.

**Comment by m0ksem** [comment]
I think moving to done should close the issue automatically.
