### ISSUE TITLE
Can we preselect TypeScript for vuestic create script?

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3027]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/5394573/220121423-5f1b081b-11a9-47ad-aa04-faf1168456d6.png">

Maybe also eslint?

@m0ksem what do you think?

**Comment by m0ksem** [comment]
I did it at first, but then me and @aluarius realized this idea sucks. Cuz it makes unintuitive which options are selected. And also, people make project not so often, so it is easier to manually choose options.

**Comment by asvae** [comment]
Solid point :)
