### ISSUE TITLE
Images are broken in dev mode....

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3030]
I looks good in prod, but in dev there are no images at all. BTW, warning with pattern.svg isn't fixed. I think we need to bring back nuxt-image module.

**Comment by aluarius** [comment]
Does this task about VaImage or something else? Just have checked dev mode - everything is ok.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/64714442/221508244-514e6013-7bc9-4237-9109-fcded6ea7106.png">

**Comment by rustem-nasyrov** [comment]
@aluarius, I think it's related to this [issue](https://github.com/epicmaxco/vuestic-ui/issues/2996).
