### ISSUE TITLE
Algolia search doesn't work properly

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3039]
We decided to use #3425 approach instead

In context of this task please only do enough to make search work.
There is no need to go through all examples and remove translations completely.

----

Algolia doesn't show some pages. I know that it takes some time to refresh its data after updates but we can't find even a scroll container component which we have for a long time.

Child issues: 
Closes https://github.com/epicmaxco/vuestic-ui/issues/2691
Closes https://github.com/epicmaxco/vuestic-ui/issues/2645

- [ ] When you search in vuestic.dev -> it opens the page, but only skeleton in shown; with open dev tools with cache disabled page is shown

Also see #3363

* see #2691

**Comment by rustem-nasyrov** [comment]
Waiting for migration docs to the another hosting.

**Comment by rustem-nasyrov** [comment]
Pages are crawled, except few ones.

**Comment by misterpekert** [comment]
The configuration of Algolia to support multilanguage search is not easily implemented with indices built by the Algolia crawler. We should either consider providing a custom config for Algolia (sitemap with specific language for each page) and pass user language as a query to Algolia or have a separate index for each language. We can do so, as all localized pages are split by the lang prefix in the URL. After that, we would change the Algolia search index depending on the user's language in the doc settings. 2nd approach is more robust, but it'd be a problem to maintain (and support new languages). 
Or we can drop translation support, stick to the English-only version, and reconsider this decision when necessary.

**Comment by m0ksem** [comment]
> The configuration of Algolia to support multilanguage search is not easily implemented with indices built by the Algolia crawler. We should either consider providing a custom config for Algolia (sitemap with specific language for each page) and pass user language as a query to Algolia or have a separate index for each language. We can do so, as all localized pages are split by the lang prefix in the URL. After that, we would change the Algolia search index depending on the user's language in the doc settings. 2nd approach is more robust, but it'd be a problem to maintain (and support new languages). Or we can drop translation support, stick to the English-only version, and reconsider this decision when necessary.

Dropping translation support is the solution. At least for now.

**Comment by asvae** [comment]
Fixed in 323a24a18538481f206471a66b5d24d5d83d413f

It was hard to do in pull request (algolia only crawled ui.vuestic.dev), so hacked everything in master 🥷.
