### ISSUE TITLE
Sponsors are off center on mobile

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3040]
**Vuestic-ui version:** 1.6.1
![Screenshot_2023-02-21-16-50-45-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/5394573/220364027-99cd8125-1e59-4744-a5e5-d14f7b03cac2.jpg)

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

**Comment by rustem-nasyrov** [comment]
I suggest to create a figma template and use it as a single image in the readme files.

**Comment by asvae** [comment]
@rustem-nasyrov huh?

You mean using one image instead of 7 we got?

**Comment by rustem-nasyrov** [comment]
@asvae, yup, like in the [vue](https://github.com/vuejs/vue) repository.

**Comment by asvae** [comment]
@rustem-nasyrov hmm, pretty good.

The only thing I'd like to have is semi-trasparent background as with vue repo I get flashbang (using dark theme).

**Comment by m0ksem** [comment]
We can make Get API end-point in nuxt docs which will render the same sponsors component using vue's renderAsString method. We can pass props as well here.

[sponsors.get.ts]
```ts  
import { renderToString } from '@vue/ssr-rendere' 
import Sponsors from '@/components/sponsors.vue'

export default ({ hash }) => renderToString(Sponsors , { color: hash })
```

**Comment by rustem-nasyrov** [comment]
@m0ksem, generated string will be written into `README.md` file?

**Comment by m0ksem** [comment]
> @m0ksem, generated string will be written into `README.md` file?

Can be used as
```
![Sponsors](https://vuestic.dev/api/sponsors#light)
```
