### ISSUE TITLE
Table seems to be broken in 1.6.0 somehow

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3041]
**Vuestic-ui version:** 1.6.1

**User story**

> I don't know how you decide what is Vuestic support now and what is my project specific. I love the fast new data-table, but now it suddenly seems to be toast. it does not show the list at all (only if I change the window size), it makes the container longer that the list. I tried to find out how to tackle this but I think it's Vuestic problem?

**Steps to reproduce**

**What is the expected behavior?**

**What is the current behavior?**

**Other information**

Table was working fine before, but not anymore.
I asked for definite repro, but current description might be good enough.

**Comment by m0ksem** [comment]
It is related to how table is used. In this case it uses virtual-scroller prop and height set by css with flex. Should be hard to reproduce in demo, but that's the case.

**Comment by m0ksem** [comment]
We fixed it. It was not related to vuestic.
