### ISSUE TITLE
SSR does not add component variables

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#3046]
**Vuestic-ui version:** 1.6.1

**Steps to reproduce**
Use VaAvatar component with SSR with Nuxt, although it happens with several components.

**What is the expected behavior?**
Should render the necessary visual variables by default:

![image](https://user-images.githubusercontent.com/46224115/220625711-3415a90d-57ab-4b25-b27f-76da9be46b35.png)

![image](https://user-images.githubusercontent.com/46224115/220625366-5af82802-eb97-4a82-9920-f5a955eaa168.png)

**What is the current behavior?**
It does not render the variables and makes it look broken while it hydrates

![image](https://user-images.githubusercontent.com/46224115/220625868-1a193c15-6663-4d62-bf1c-95c9b01c1148.png)

![image](https://user-images.githubusercontent.com/46224115/220625514-6984bad3-866a-4522-8584-32e9f1382e7d.png)

**Other information**
This was not happening in version 1.5.x, for what I can see then we were not using CSS variables for some values (like size) which seems to be the source of the issue as they don't get added until hydration.

**Comment by asbermudez** [comment]
Want to point out, that this was happening with few components that used the same technique for handling things like colors in version `1.5.x`, like the **VaButtonDropdown** using color "danger".

![image](https://user-images.githubusercontent.com/46224115/220628703-5e45ec2e-8eaa-4239-bbf5-365f4d93e6e3.png)

**Comment by m0ksem** [comment]
Scope: This is related to Vue's `v-bind` in CSS. For some reason, some CSS variables are not rendered in Nuxt SSR. In VaButton for example, `backgroundColor` renders, but not `backgroundColorOpacity`. We have this issue on docs landing page.

Possible solutions:
- Use `:style="{}"` instead of `v-bind`.

**Comment by m0ksem** [comment]
@asbermudez, what nuxt modules do you use?

**Comment by asbermudez** [comment]
@m0ksem this is the output of `nuxi info`

```bash
Nuxt project info:                                                          09:49:59

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `app`, `modules`, `postcss`, `vite`, `typescript`, `runtimeConfig`, `imports`, `umami`, `auth`, `nitro`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.2`, `nuxt-umami@1.2.0`, `@pinia/nuxt@0.4.6`, `@vuestic/nuxt@1.0.9`
- Build Modules:    `-`
------------------------------
```

**Comment by m0ksem** [comment]
@asbermudez, and the last question. Do you have `vite.optimizeDeps.exclude.push('vuestic-ui')` somewhere in you project? Maybe in `nuxt.config.ts`? If so, try to remove it and see if it helps. Because it was the issue for me in our docs.

**Comment by asbermudez** [comment]
@m0ksem not as far as I can see, even in the autogenerated code is not showing

![image](https://user-images.githubusercontent.com/46224115/220886292-cf6f4c7c-6c84-483c-8003-2cc7bec07933.png)

**Comment by m0ksem** [comment]
Hey, @asbermudez. Can you try `vuestic-ui@0.0.0-experimental-14454314a-20230223` version? I made a pretty heavy change here, so maybe something can break. Tested in our docs, but want you to double-check if it solves your issue.

**Comment by m0ksem** [comment]
And also check this `vuestic-ui@0.0.0-experimental-e82eb2bae-20230223` version and LMK which feels better. (I assume the last one mustn't work in pure SSR, but somehow it works with Nuxt 🦄)

**Comment by asbermudez** [comment]
@m0ksem after checking, both seems to still have the issue. Both cases I get this:

![image](https://user-images.githubusercontent.com/46224115/221803076-69b09a40-428c-4e42-9d8c-c0d58fcffb68.png)

VS how it was in 1.5.3:

![image](https://user-images.githubusercontent.com/46224115/221802980-b89d3a33-77e6-4f02-b58f-ef91e0223858.png)


VS fully loaded (with JS hydration)

![image](https://user-images.githubusercontent.com/46224115/221802853-8ae4f4b4-dc54-4516-8c12-03b2779fb810.png)

**Comment by m0ksem** [comment]
I can confirm that `vuestic-ui@0.0.0-experimental-e82eb2bae-20230223` doesn't fix this issue for input.

But I checked `vuestic-ui@0.0.0-experimental-14454314a-20230223` and it works for me in SSR and SSG builds. Can you double-check if it wasn't used old 1.6.1 version or something is cached.

You can use this command `curl localhost:3000 | grep -e "--va-0-background-computed:#\w*;" -o` to insure that CSS variable is now present in rendered DOM during SSR.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/23530004/221827453-c38550e2-764e-4cc7-8b46-6156aa249b12.png">

And .va-input-wrapper must use this CSS variable:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/23530004/221844146-97442074-7d99-481a-9fb9-262092805cc0.png">

**Comment by m0ksem** [comment]
@asbermudez, looks like you still using 1.6.1, not experimental verison I made. `--va-input-wrapper-background` must be `var(--va-0-background-computed)`, not `var(--a310421c)`. The difference here is that I tweaked the compiler a bit, so it is generating css variables that work in CJS builds and its name is changed to --va-0-vbind-name, instead of vue's --hash. Try to change version, clean .nuxt, .output and node_modules/.vite (if exists).

**Comment by asbermudez** [comment]
Removed my .nuxt, .output and node_modules folder, I've forced my package.json and package-lock to not have any reference to 1.6.1 and yet it still happens the same.

![image](https://user-images.githubusercontent.com/46224115/221852472-15ae7a32-9c3c-4aa8-ad0d-b0520bd8ba29.png)

So not sure what's going on...

**Comment by m0ksem** [comment]
@asbermudez, npm creates `node_modules/@vuestic/nuxt/node_modules/vuestic-ui` as sub package which will contain 1.6.1 even if you have `node_modules/vuestic-ui` experimental. I think it is because npm treats 0.0.0-experimental as not valid version for @vuestic/nuxt. You can manually copy content from `node_modules/vuestic-ui` to `node_modules/@vuestic/nuxt/node_modules/vuestic-ui` and I'll stop torturing you :D

**Comment by asbermudez** [comment]
@m0ksem seems I keep having the same issue.... sorry 😅  
I would suggest to move this change forward as it might be something related on how the experimental is being loaded or something, maybe once it's released all works good. Worse-case scenario we can dig around again.

**Comment by asbermudez** [comment]
@m0ksem as update, if I do the same with @vuestic/nuxt@1.0.11 it gets even worse, it just shows everything broken xD

![image](https://user-images.githubusercontent.com/46224115/221859688-be3116f5-a0e7-463b-b409-5e13f664056d.png)

**Comment by m0ksem** [comment]
My test setup is clean nuxt project with few components inside:
```json
  "devDependencies": {
    "nuxt": "^3.2.2"
  },
  "dependencies": {
    "@vuestic/nuxt": "^1.0.11",
    "vuestic-ui": "0.0.0-experimental-14454314a-20230223"
  }
```

We will do 1.6.2 this week.

**Comment by asbermudez** [comment]
@m0ksem Ok, if I build and run `nuxi preview` colors do work, if I run it in dev mode it doesn't... somehow the `nav bar` layout it breaks though with `@vuestic/nuxt@1.0.11`, everything looks good with build with @vuestic/nuxt@1.0.9 and the experimental branch of yours.

**Comment by asbermudez** [comment]
@m0ksem for reference, you can see the colors are not the custom ones, but it does load the base ones in the server side response:

![image](https://user-images.githubusercontent.com/46224115/221866727-d56cf679-d74a-4413-8f0a-e0c716d0a340.png)

**Comment by m0ksem** [comment]
I have the same issue with Navbar, but if I change colors via nuxt-config
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['@vuestic/nuxt'],

  vuestic: {
    config: {
      colors: {
        variables: {
          primary: '#ff0000'
        }
      }
    }
  }
})
```
colors are applied correctly...

**Comment by asbermudez** [comment]
@m0ksem unfortunately I cannot depend on fixed build custom colors (as everything in the nuxt-config gets embedded in build time), my application will have to load a different palette based on user settings. This means ideally it needs to be handled by the SSR in runtime, otherwise I will have a first load with wrong colors and the flick to the right ones, which is far from a good UX experience.  But as long as for now they load later in runtime (so when the app is hydrated) I can roll with it for now. So probably we can separate that issue in a new issue.

**Comment by m0ksem** [comment]
As far as I can see Navbar issue is OK, because page need to load css in dev as module (likely need for hot reload). If this works OK in prod, then we will not fix it.

For colors depended on request... Will handle it in a separate issue. Thanks for great conversation over here!
