### ISSUE TITLE
Some select is probably broken on landing page

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3047]
**Vuestic-ui version:** 1.6.1

> Why does the select width expand to 100% when you open it and go smaller again after selecting an option?

> iOS chrome and safari

https://vuestic.dev

**Comment by m0ksem** [comment]
I think it is related to VaDropdown. I'm not able to reproduce it in Safari 16.3.

**Comment by asvae** [comment]
See https://github.com/epicmaxco/vuestic-ui/issues/3047

**Comment by aluarius** [comment]
As for Maxim, wasn't able to reproduce for Chrome, Safari and Firefox.

Suggest to close it for now and reopen if someone will complain.

**Comment by m0ksem** [comment]
@aluarius, check mobile safari

**Comment by rustem-nasyrov** [comment]
@aluarius, here is reproduction:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/29167241/221797218-a1bed7ec-43cc-4bd3-9646-96008e5abdac.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/29167241/221797290-d1d3dc57-fe58-45f8-ad06-7e467662f37c.png">

**Comment by aluarius** [comment]
Yea, thnx, already found it.

**Comment by aluarius** [comment]
All in all, this issue is related to https://github.com/epicmaxco/vuestic-ui/issues/3049 

To solve it in optimal way, me and Maxim decided to rewrite VaDropdown via render function.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/3119
