### ISSUE TITLE
Commands to integrate Tailwind into Vuesitic don't work

### ISSUE THREAD

**Issue by louiss0** [epicmaxco/vuestic-ui#3057]
**Vuestic-ui version:** 1.6.1

The commands for the integration with tailwind is just not working at all I keep getting it's not in the registry response. 

npm install @vuestic/tailwind
2. After installation, three commands become available to you:

npx sync-tailwind-with-vuestic 
npx watch-tailwind 
npx sync-vuestic-with-tailwind 
**None of these commands work!!! **

**Steps to reproduce**

**What is the expected behavior?**

I expected to be able to use the  

**What is the current behavior?**

**I get this error**
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/sync-tailwind-with-vuestic - Not found
npm ERR! 404
npm ERR! 404  'sync-tailwind-with-vuestic@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\louis\AppData\Local\npm-cache\_logs\2023-02-23T23_29_44_456Z-debug-0.log

```

**Other information**

- I'm using windows. 
- I tried either npm or pnpm they did not work.

**Comment by aluarius** [comment]
Ours bad :c We haven't published lastest version with these commands to `npm`. We will do it today, as soon as possible.

**Comment by m0ksem** [comment]
🫡Published

**Comment by J4LM** [comment]
Same thing happens again!
