### ISSUE TITLE
Filtering for the complex tree structures doesn't work as expected.

### ISSUE THREAD

**Issue by ssemenkoff** [epicmaxco/vuestic-ui#3059]
**Vuestic-ui version:** 1.6.1

**Steps to reproduce**
- Create treeView with filtering enabled.
- Add data with depth > 2
- Apply filter

Sandbox with the issue example
[https://codesandbox.io/p/sandbox/wizardly-galileo-2tpviu](https://codesandbox.io/p/sandbox/wizardly-galileo-2tpviu)

**What is the expected behavior?**
All nodes are filtered
![image](https://user-images.githubusercontent.com/10769790/221102547-b429d2e3-3544-4ece-b2bb-756f6ccbd1f3.png)

**What is the current behavior?**
Only root nodes are filtered
![Снимок экрана 2023-02-24 в 09 49 30](https://user-images.githubusercontent.com/10769790/221102313-07f6ab56-b555-4bcb-8676-8745bd4dc8f8.png)

**Other information**

**Comment by asvae** [comment]
@misterpekert will you be able to finish this?
