### ISSUE TITLE
Documentation page navigation broken on mobile

### ISSUE THREAD

**Issue by devzom** [epicmaxco/vuestic-ui#3070]
The documentation page on mobile have broken navigation. 
During opening it by hamburger menu, look like the opened nav (droodown?) doesn't have background and lower `z-index` than the rest of the page. 

Also no close btn is shown. 

![Mobile screenshot](https://i.imgur.com/oBKz5TM.png)

Android 9, latest Chrome Browser

**Comment by m0ksem** [comment]
closed here: https://github.com/epicmaxco/vuestic-ui/pull/3063
