### ISSUE TITLE
Old typography classes are used in input example

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3071]
https://vuestic.dev/en/ui-elements/input#input-class

Should be .va-text-right, see typography

**Comment by scorcism** [comment]
Hello there, can i work on this ?

**Comment by m0ksem** [comment]
Sure. Thanks!

**Comment by scorcism** [comment]
Hello, for little confirmation i just have to change 
`input-class="text--right color mb-2"`
TO
`input-class="va-text--right color mb-2"`
and
 to align the input text — text--center and text--right to align the center or right.
TO
 to align the input text — va-text--center and va-text--right to align the center or right.

**Comment by m0ksem** [comment]
We made our helpers non-bem and added prefixes, so it is `va-text-right`, no `text--right`. List of all helpers you can find here: https://vuestic.dev/en/styles/typography#typography-text-helpers.

**Comment by scorcism** [comment]
okay sure, I will start working on this.

**Comment by scorcism** [comment]
Hello, 
I have created PR.
If anything, let me know
Thank you

**Comment by xiongmao86** [comment]
Should this issue be closed since pr is merged?

**Comment by rustem-nasyrov** [comment]
> Should this issue be closed since pr is merged?

Yes, thank you! :)
