### ISSUE TITLE
Select value by must return value, but textBy should be found from options

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3072]
For now if user passes valueBy then textBy doesn't work because it will be impossible to get text filed in value. Value can be found from options. But what to do if value not found in options and therefore there is not textBy.

**Comment by asvae** [comment]
@m0ksem can you show an example of that? I don't follow :).

**Comment by asvae** [comment]
@aluarius and @m0ksem could discuss this issue.

**Comment by aluarius** [comment]
@m0ksem can we close it now?
