### ISSUE TITLE
Nuxt prerender doesn't work with Prism.js

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3075]
We need a different solution for code rendering solution. 

Languages undefined, pattern.exec isn't function errors.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/23530004/221410109-a888cfd8-8e22-4b7f-b0a5-b5abc3120dcf.png">

**Comment by rustem-nasyrov** [comment]
Earlier I suggested to move to the Highlight.js, hope migration will fix it. 😄

**Comment by asvae** [comment]
@m0ksem can't prism.js be client only?

**Comment by m0ksem** [comment]
> @m0ksem can't prism.js be client only?

Good point. We can try this.
