### ISSUE TITLE
Ag-grid with ag-theme-vuestic--hoverable make button inside the table is unclickable

### ISSUE THREAD

**Issue by mikysetiawan** [epicmaxco/vuestic-ui#3079]
**Vuestic-ui version:** 1.5.3

**Steps to reproduce**
I created a table with ag-grid, on that table I have an action button on each row for edit and delete, but because I using ag-theme-vuestic--hoverable it makes my button unclickable, I already give the button z-index: 99999 but still unclickable, if I remove that class, I can click that action button

**What is the expected behavior?**
The button still clickable

**What is the current behavior?**
The button unclickable

**Other information**

**Comment by rustem-nasyrov** [comment]
Hello, @mikysetiawan! Please, could you also share version of the @vuestic/ag-grid-theme?

**Comment by mikysetiawan** [comment]
> Hello, @mikysetiawan! Please, could you also share version of the @vuestic/ag-grid-theme?

Hi @rustem-nasyrov thanks for your reply, vuestic/ag-grid-theme version: "1.1.3"

**Comment by rustem-nasyrov** [comment]
Hello, @mikysetiawan, sorry for long wait. I researched issue and luckily found a solution, you need to set to your button or its container next styles:
```css
/* Button selector or its container */ {
  position: relative;
  z-index: 1;
}
```

**Comment by m0ksem** [comment]
> Hello, @mikysetiawan, sorry for long wait. I researched issue and luckily found a solution, you need to set to your button or its container next styles:
> 
> ```css
> /* Button selector or its container */ {
>   position: relative;
>   z-index: 1;
> }
> ```

I assume hoverable adds some after which prevents user from clicking on button... Double check if we can put this after under with z-index or add pointer-events: none, so pointer events come trough this bg.

This must work out of box, without any effor from user.

**Comment by rustem-nasyrov** [comment]
> > Hello, @mikysetiawan, sorry for long wait. I researched issue and luckily found a solution, you need to set to your button or its container next styles:
> > ```css
> > /* Button selector or its container */ {
> >   position: relative;
> >   z-index: 1;
> > }
> > ```
> 
> I assume hoverable adds some after which prevents user from clicking on button... Double check if we can put this after under with z-index or add pointer-events: none, so pointer events come trough this bg.
> 
> This must work out of box, without any effort from user.



> > Hello, @mikysetiawan, sorry for long wait. I researched issue and luckily found a solution, you need to set to your button or its container next styles:
> > ```css
> > /* Button selector or its container */ {
> >   position: relative;
> >   z-index: 1;
> > }
> > ```
> 
> I assume hoverable adds some after which prevents user from clicking on button... Double check if we can put this after under with z-index or add pointer-events: none, so pointer events come trough this bg.
> 
> This must work out of box, without any effort from user.

Under the latest version it works fine.
