### ISSUE TITLE
Something wrong with images

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3080]
**Vuestic-ui version:** 1.6.1

**Steps to reproduce**
go to image or carousel page

**What is the expected behavior?**
Correct image sizes

**What is the current behavior?**
<img width="1072" alt="Screenshot 2023-02-27 at 09 35 02" src="https://user-images.githubusercontent.com/45711229/221491936-88f579b7-3aed-492e-b97f-7f2914706d1d.png">
<img width="1099" alt="Screenshot 2023-02-27 at 09 35 12" src="https://user-images.githubusercontent.com/45711229/221491940-136d533a-fb30-48af-b4f1-4a9bfa95d845.png">
![Uploading Screenshot 2023-02-27 at 09.37.34.png…]
<img width="1025" alt="Screenshot 2023-02-27 at 09 37 46" src="https://user-images.githubusercontent.com/45711229/221492121-e89e5f1c-daf5-4369-be7d-03d84c0aa34e.png">
<img width="1096" alt="Screenshot 2023-02-27 at 09 37 54" src="https://user-images.githubusercontent.com/45711229/221492128-b973f8e2-e1b4-439a-86d8-2ef14dc83686.png">

**Comment by aluarius** [comment]
Seems to be just a problems with docs examples, but i'll check.
