### ISSUE TITLE
Broken docs cache or something else

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3081]
**Vuestic-ui version:** 1.6.1

There is something broken with docs. If you'll try to reload page you'll see landing page or colored containers instead of flat buttons.

**Steps to reproduce**
go to docs => reload page repeatedly

**What is the expected behavior?**

- Don't show landing on reload
- Don't show background for flat buttons

**What is the current behavior?**

https://user-images.githubusercontent.com/45711229/221494324-8fc546a6-aba9-4ec4-8ee9-bf68a53dc6fa.mov

**Comment by m0ksem** [comment]
Related to hosting. Likely moving to Railway will fix it.

**Comment by asvae** [comment]
See #3196
