### ISSUE TITLE
Landing svg images are broken

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3082]
**Vuestic-ui version:** 1.6.1

**Steps to reproduce**
go to docs => change topics and reload page => go back to landing page

**What is the expected behavior?**
Show images

**What is the current behavior?**
https://user-images.githubusercontent.com/45711229/221499183-6dfde98b-863c-47c3-9a4d-9681557b8fe7.mov

**Other information**

**Comment by rustem-nasyrov** [comment]
Doesn't it duplicate this #3030?

**Comment by kushich** [comment]
@rustem-nasyrov nope, it's on production

**Comment by rustem-nasyrov** [comment]
Fixed in `develop` branch.
