### ISSUE TITLE
Missing bundle size info

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3084]
**Vuestic-ui version:** 1.6.1

**Steps to reproduce**
[page](https://vuestic.dev/en/getting-started/tree-shaking#tree-shaking-bundle-size-title)

**What is the expected behavior?**
Info about bundle size

**What is the current behavior?**
<img width="1129" alt="Screenshot 2023-02-27 at 10 42 16" src="https://user-images.githubusercontent.com/45711229/221503319-aea3eca1-caa6-4940-ae5a-e37305a73565.png">

**Comment by aluarius** [comment]
It's already fixed in develop.
