### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#31]
# Mixins
- [x] Stateful mixin
- [x] Color

# Props
- [x] `title: String` - title should be optional. (alert should look fine with description alone).
- [x] `description: String`
- [x] `center: Boolean` - add center alignment for title and description 
- [x] `icon: String` - icon alias.
- [x] `closeable` - displays close area on component.
- [x] `close-icon: String, default: (find correct icon)
- [x] `close-text: String` - if this prop is provided text should be shown instead of icon.

# Slots
- [x] `default` - insert description 
- [x] `title` - insert title
- [x] `icon` - insert icon from the left side of alert description. Overrides prop if it's set.
- [x] `close` - replace close icon area. Slot overrides `close-icon` and gets onClose method from scope scope. 

# Events
- [x] `input` - fires when close icon is clicked. This should work with slot as well.

# Design
- [ ] Present to @xx13 after finishing.

# Notes
- [ ] This component named as `va-notification` in vuestic-ui
- [ ] Test various text sizes to prevent overflow issues (i.e. when title goes below close icon).

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/alerts)
* [Ant Design](https://ant.design/components/alert/)
* [Element UI](https://element.eleme.io/#/en-US/component/alert)

**Comment by asvae** [comment]
@AlexanderBoriskin any reason to change name to alert from notification?

**Comment by asvae** [comment]
@AlexanderBoriskin 
> close-text

Probably would make more sense to do a slot.

> text: Boolean - applies the defined theme to text

That doesn't seem right to me.

**Comment by AlexanderBoriskin** [comment]
Hi, @asvae !

1) Please, look through the refs: the component that we've already named 'va-notification' in other framework named as 'alert'. At the same time 'notification' component (see [Ant Design](https://vue.ant.design/components/notification/) and [Element UI](https://element.eleme.io/#/en-US/component/notification)) has some differences with 'alert' - for notification, f.e. we can set a corner of the page - and looks similar to our 'toast-position-picker'. 
So, we should come to a common naming convention for these group of components (notification, alert, toast): based on other frameworks or our own convention.

2) close-text - I remove this prop and make slot
As I understand, other frameworks doesn't any other options except of close icon or text

3) text: Boolean -> text-color: String?
Perhaps using theme plugin is more suitable option?
As I saw, some other components in issues also support this property
