### ISSUE TITLE
Active class for Sidebar item 

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3105]
**Current behavior**
If you go some component page by the link https://vuestic.dev/ui-elements/alert
You dont have an active class on the item in the left sidebar
![image](https://user-images.githubusercontent.com/35342240/222374712-8a649562-1c84-4200-b87d-059ef6508676.png)

**Expected behavior**
Should have active style for sidebar element for current pae 
![image](https://user-images.githubusercontent.com/35342240/222374860-d6b6b62b-fdbe-4ab7-be86-0597e689619e.png)

**Comment by m0ksem** [comment]
Looks like it works good with url with locale prefix, but doesn't work for urls without local prefix.
