### ISSUE TITLE
Modal docs still needs fixes!

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3106]
In context of this task we want
- [ ]  To update visual look of modal
- [x]  To upldate docs

### Mockup:
https://www.figma.com/file/PflCWFZC3xz3YCt7uX3MpP/Documentation?type=design&node-id=401-1233&t=a9IDf2punPzei6Zu-0

### Care about Nested Please 

![Image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/a326c167-6d69-4b9a-9432-9eec58e29608)

### it should look exactly like this:

![Image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/62dc25dc-7e62-4a70-9197-1c913c9927d4)

**Comment by m0ksem** [comment]
@zvenigorodskaia, TIP: VaDateInput should have `prevent-overflow="true"`.

**Comment by zvenigorodskaia** [comment]
Nested modal still need to be fixed - 
1. please add Set default button and toast (see mockup here https://www.figma.com/file/PflCWFZC3xz3YCt7uX3MpP/Documentation?type=design&node-id=401-1233&mode=design&t=2TUbRtZYi5oPcS5I-0)

2. fix bug with choosing date in the datepicker (modal should not close on click on the calendar, the date should be shown in the input )
