### ISSUE TITLE
VaDataTable filter per column

### ISSUE THREAD

**Issue by ralpheichelberger** [epicmaxco/vuestic-ui#3123]
Please enable the data table to filter for multiple specific columns - ideally with optional regex functionality

**Describe alternatives you've considered**

The alternative would be to make lots of individual API calls for every search within a data table that is already fully loaded in the browser.
This is mostly slower, ineffective on the API side, and offline not possible.

**Comment by asvae** [comment]
Hey,

can you explain how [current solutions](https://vuestic.dev/en/ui-elements/data-table#filtering) doesn't work for you? Maybe you have an example?

**Comment by ralpheichelberger** [comment]
well if there is a number - e.g. EAN codes and on filter there are lines where those same first numbers are in a price, or a name etc. then the list is filtered but includes false positives
