### ISSUE TITLE
Divider is missing color prop

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3153]
Solution: ```<va-divider :style="`--va-divider-border-top-color: ${dividerColor}`"/>```, but should have a `color` prop.

**Comment by akzz-at** [comment]
Hi!, I am new to opensource contributions and new to this project, I cannot see the hashtag for the issue in code could you guide me a little.

**Comment by Yasir761** [comment]
@m0ksem Can u please provide more information on this?

**Comment by m0ksem** [comment]
Hey. We have a component called VaDivider in UI package. It is missing a color prop, which must be v-binded as border color using vue's v-bind in css feature. Each of our components have a colour prop, but for divider, it is possible to change divider color only using CSS variables.

**Comment by akzz-at** [comment]
Got it, Can you assign this work to me?

**Comment by akzz-at** [comment]
Can you kindly point to the exact file name where changes are to be made.
