### ISSUE TITLE
Size Modal, so that a dropped VaSelect fits in it

### ISSUE THREAD

**Issue by FFG-IT** [epicmaxco/vuestic-ui#3160]
Hi, If you open a modal, it fits to the content. But if you have a very small modal, with only a VaSelect in it, it becomes very unhandy:

![Screenshot_20230313_154920](https://user-images.githubusercontent.com/94543943/224738295-04e5b9e2-e79a-42c1-85e7-82b6222f66a1.png)

This is a submodal of a modal. As you can see, i have that Select dropped down, and i get this ugly overflow. It would be nice, i f i could set the size of the modal manually, or if the dropdown wouldn cause an overflow, but just takes the place it need outside the modal. 

Also as you can see, the submodal doesnt grey out the parent modal, which is also a bit unconvienient

Thx

**Comment by m0ksem** [comment]
Please, use `prevent-overflow` prop. I think we had `prevent-overflow` by default true, which cause performance issues. We changed it to false by default in 1.5.0 or 1.6.0.
