### ISSUE TITLE
With closed dev-tools new docs do not work properly

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3194]
**Vuestic-ui version:** 1.6.2

* Go to https://vuestic-ui.up.railway.app/en/styles/colors, then navigate through pages.

Result:
* no navigation happening, I stay on the same page

Expecting:
* navigation to work

We have to fix that before we move docs to railway fully.

**Comment by m0ksem** [comment]
@asvae, please, double check if it fixed on https://develop.vuestic.dev/getting-started/tree-shaking

**Comment by m0ksem** [comment]
Likely fixed somewhere... Not able to reproduce it anymore.
