### ISSUE TITLE
composable VaModal unexpected style

### ISSUE THREAD

**Issue by damonto** [epicmaxco/vuestic-ui#3199]
**Vuestic-ui version:** 
1.6.2

**Steps to reproduce**

![PixelSnap 2023-03-19 at 21 37 05@2x](https://user-images.githubusercontent.com/9162521/226178810-dfe28ebf-962c-478e-9155-9e2d4b4f8e96.png)

```javascript
const modal = useModal()

modal.init({
      title: 'Click Event',
      message: 'Modal from plugin',
      blur: true,
      onOk: () => console.log('clicked OK'),
      onCancel: () => console.log('clicked CANCEL')
})

```

**What is the expected behavior?**

1. The OK button should be visible.
2. The Vuestic color preset is dark, so the programmatic modal should also be dark

**What is the current behavior?**

**Other information**

**Comment by m0ksem** [comment]
Can you make a reproduction or share a bit more about your environment? I'm not able to reproduce it locally and in sandbox.
https://codesandbox.io/p/sandbox/interesting-solomon-pu1l7f?file=/src/main.ts&selection=%5B%7B%22endColumn%22:7,%22endLineNumber%22:13,%22startColumn%22:7,%22startLineNumber%22:13%7D%5D

**Comment by damonto** [comment]
I don't know what happened, but currently it's working well.

**Comment by VlaSapRos** [comment]
![image](https://github.com/user-attachments/assets/a2333712-bc41-4887-9d30-9d299a39a092)
![image](https://github.com/user-attachments/assets/eb5d64aa-43c6-441a-ab74-28cb5dc7c4bc)
![image](https://github.com/user-attachments/assets/0f3b6e23-0634-4256-8b87-1bc47d48d50c)

I have the same problem. Take some screenshots maybe it will clarify the situation.

As far as I understand, the error is that the css variable --va-background-color does not receive a value (instead, the variable --16fe6bdb receives it)

**Comment by m0ksem** [comment]
> ![image](https://private-user-images.githubusercontent.com/59449907/370627113-a2333712-bc41-4887-9d30-9d299a39a092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjUzODYsIm5iZiI6MTcyNzM2NTA4NiwicGF0aCI6Ii81OTQ0OTkwNy8zNzA2MjcxMTMtYTIzMzM3MTItYmM0MS00ODg3LTlkMzAtOWQyOTlhMzlhMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE1MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZGU2YTU4ZDhmNTE4YTU5NzM0YTJlODI2MDlmNmE2ZmU2NWY5ZWE3MGRmZGQxNzY2Yzg5ZjJiMThhYjVlOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0oFaumoxCBDkNfy8Cy56H6t9peKIcrCc8qoP5N3TrGg) ![image](https://private-user-images.githubusercontent.com/59449907/370627495-eb5d64aa-43c6-441a-ab74-28cb5dc7c4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjUzODYsIm5iZiI6MTcyNzM2NTA4NiwicGF0aCI6Ii81OTQ0OTkwNy8zNzA2Mjc0OTUtZWI1ZDY0YWEtNDNjNi00NDFhLWFiNzQtMjhjYjVkYzdjNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE1MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYzQ0ZDIwNmYyNzc1NTQ0ODc1MDA5NzZlYmYzYTZmYjE3ODg5MmUxNmYyNjhhNTcwYTQyZTdhMGNlMjAwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RL0a4yXTeXQy0_7Yi64_gox8wCHUrS4Wp46X-jxotec) ![image](https://private-user-images.githubusercontent.com/59449907/370627965-0f3b6e23-0634-4256-8b87-1bc47d48d50c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjUzODYsIm5iZiI6MTcyNzM2NTA4NiwicGF0aCI6Ii81OTQ0OTkwNy8zNzA2Mjc5NjUtMGYzYjZlMjMtMDYzNC00MjU2LThiODctMWJjNDdkNDhkNTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE1MzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZWU2NDc5ZThlY2EwNGRhMTQ2ZjhjMTFhMzBjNjg5N2UxNWE1MTJhZWQwMGUxYTUwMDU5YjE2YTJhOWIxMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OC0ZByRV885Lbb9eem3xca1Dmyn13eCLMi3uNwD-Cfo)
> 
> I have the same problem. Take some screenshots maybe it will clarify the situation.
> 
> As far as I understand, the error is that the css variable --va-background-color does not receive a value (instead, the variable --16fe6bdb receives it)

Can you share your environment? Nuxt? Vue and vuestic version. Vite version.
