### ISSUE TITLE
Gradient background for VaButtonGroup component

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3209]
Right now we apply gradient color for each element of the group. It makes no sense at all.
<img width="609" alt="Screenshot 2023-03-21 at 10 31 21" src="https://user-images.githubusercontent.com/45711229/226542640-5ca995bb-f5b7-48de-b263-9373f9bf74b1.png">

**Describe the solution you'd like**
Gradient should be applied to group itself
<img width="352" alt="Screenshot 2023-03-21 at 10 24 58" src="https://user-images.githubusercontent.com/45711229/226542773-2ac51e37-9cb8-4c08-bac7-d9c9bd85ee87.png">

**Comment by m0ksem** [comment]
I've fixed this a year ago... 😡

**Comment by rustem-nasyrov** [comment]
@kushich, @m0ksem do we need to discuss about it?
