### ISSUE TITLE
a11y: va-alert

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3231]
- [x] step 1: investigate a11y guides for this component;
- [ ] step 2: discuss with team;
- [ ] step 3: implement required functionality;
- [ ] step 4: add docs page section about a11y.

**Comment by kushich** [comment]
We use role="alertdialog" for closeable alerts. I think that it isn't correct. That's why: [ref](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alertdialog_role)
> The alertdialog role is to be used on modal alert dialogs that interrupt a user's workflow to communicate an important message and require a response.

> As the name implies, alertdialog is a mashup of the [dialog](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role) and [alert](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role) roles. alertdialog is a type of dialog with similar use cases as alert, but for when a user response is required.

The same thing we can say about `aria-labelledby` and `aria-describedby` attributes. 

I think that we should remove them because our alert component is not modal

@zvenigorodskaia @asvae @RVitaly1978

**Comment by asvae** [comment]
We decided to use `alert` role here.

We should remove `aria-labelledby` and `aria-describedby` for alert component.
