### ISSUE TITLE
Docs: Date Input 

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3233]
**Vuestic-ui version:** 1.6.2

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/35342240/227322349-f47e781f-3be6-484a-8fb2-40166183a5dd.png)

**What is the expected behavior?**
By click inside the input I can see a calendar or I can type the date

**What is the current behavior?**
Clicking on the input (not on the icon) does nothing

**Other information**

Examples:
https://element-plus.org/en-US/component/date-picker.html#date-formats
https://ant.design/components/date-picker
https://primevue.org/calendar

**Comment by m0ksem** [comment]
For some reason, it opens only on icon click from 1.6.2...
