### ISSUE TITLE
Docs: fix Color Palette 

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3237]
**Vuestic-ui version:** 1.6.3

**Steps to reproduce**
1. https://vuestic.dev/ui-elements/color-palette
2. colors dropdown in the header
3. https://vuestic.dev/en/styles/colors
4. https://vuestic.dev/en/getting-started/kitchensink#color-palette-title

**What is the expected behavior?**
add `elementBorder` 1px inner border only for colours with contrast <1, white in this case.
all other colours shouldn’t have the border

![image](https://user-images.githubusercontent.com/35342240/227468624-2c72ea8f-2fe2-4652-8845-cb91b0152570.png)

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/35342240/227468769-9bd94e30-2a15-4a9d-81c8-47952416eb73.png)
![image](https://user-images.githubusercontent.com/35342240/227468812-fb106650-396c-48c0-882a-b55ecc8ced7d.png)
![image](https://user-images.githubusercontent.com/35342240/227469026-d5e10efd-b744-4610-b0bb-cad5f67e73f8.png)
![image](https://user-images.githubusercontent.com/35342240/227469356-c4ce3abf-80fc-4dd5-a9f4-3e00a98ef638.png)

**Other information**
Mockup
https://www.figma.com/file/PflCWFZC3xz3YCt7uX3MpP/Documentation?node-id=104-2262&t=dqvY8pPywdnx8hzB-0

**Comment by m0ksem** [comment]
Docs issue is closed in https://github.com/epicmaxco/vuestic-ui/pull/3393, because this example is reworked.
