### ISSUE TITLE
Checkbox error message 

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3238]
**Vuestic-ui version:** 1.6.3

**Steps to reproduce**

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/35342240/227471205-20741dc6-2130-4c17-8d97-dbecbb26c6ac.png)
![image](https://user-images.githubusercontent.com/35342240/227471068-f17cbd8e-b1d8-4577-aa3b-9637eb5b2494.png)
![image](https://user-images.githubusercontent.com/35342240/227471016-59987e24-8dff-4e22-9686-8257bcfadca2.png)

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/35342240/227470710-71800b7b-3430-4427-b56c-833c390dfef1.png)

**Other information**

**Comment by m0ksem** [comment]
Looks fixed.
