### ISSUE TITLE
Table Component: Hoverable & Clickable doesnt work

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3241]
**Vuestic-ui version:** 1.6.3

Hoverable and Clickable doesnt work

![image](https://user-images.githubusercontent.com/35342240/227506198-378d09d8-707b-4d42-8f0c-380ecd4f993d.png)
![image](https://user-images.githubusercontent.com/35342240/227506602-5b2842c9-99f7-4fd4-bf4f-fd3824e1b094.png)

https://develop.vuestic.dev/en/ui-elements/table
Component doesnt have API information

**Comment by Skander999** [comment]
Hi! Tried to replicate it the hoverable is indeed not working the rows are not highlighted but the clickable seems to be working fine the cursor changes when on the table
