### ISSUE TITLE
Badge component: improvements and position fixes 

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3246]
**Vuestic-ui version:** 1.6.3

**Steps to reproduce**
!!! please Remove transparent prop from Barge component ---> https://github.com/epicmaxco/vuestic-ui/issues/3262

![image](https://user-images.githubusercontent.com/35342240/228265927-d1219071-acce-46aa-87c4-2fac32b96202.png)
![image](https://user-images.githubusercontent.com/35342240/228265966-162fd5ec-1587-4482-8d77-91fb3f0a56cd.png)
![image](https://user-images.githubusercontent.com/35342240/228266011-0736ed49-92ab-4cba-875f-756aa2673ba9.png)
![image](https://user-images.githubusercontent.com/35342240/228266136-d23dfef2-12b4-4cb1-89d2-e702b156920a.png)

**Other information**
https://www.figma.com/file/PflCWFZC3xz3YCt7uX3MpP/Documentation?node-id=301-1200&t=nNeJcdY6YTDCVeHr-0

**Comment by asvae** [comment]
@rustem-nasyrov please let me know if you want to continue working on that.

Sorry for snatching.

**Comment by rustem-nasyrov** [comment]
@asvae, I will work on it, because it is almost done.

**Comment by asvae** [comment]
@rustem-nasyrov can we take it over?

**Comment by rustem-nasyrov** [comment]
@asvae yeah, sure.

**Comment by asvae** [comment]
@zvenigorodskaia why?

**Comment by asvae** [comment]
Docs were not deployed 😞

Check here - https://ui-develop.vuestic.dev/ui-elements/badge.
