### ISSUE TITLE
a11y: va-badge

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3254]
- [x] step 1: investigate a11y guides for this component;
- [x] step 2: discuss with team;
- [ ] step 3: implement required functionality;
- [ ] step 4: add docs page section about a11y.

**Comment by kushich** [comment]
Right now we are using `role="alert"` for our badge component. Looks like this is not correct ([1](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role)):
<img width="776" alt="Screenshot 2023-03-27 at 15 15 57" src="https://user-images.githubusercontent.com/45711229/227940574-89ddbe5d-219b-4c95-9cc4-65be35e23da6.png">
I think we should use `role="status"` instead ([2](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions#roles_with_implicit_live_region_attributes)):
<img width="778" alt="Screenshot 2023-03-27 at 15 25 00" src="https://user-images.githubusercontent.com/45711229/227940945-35589ac2-8648-4e56-abca-631feb7f502f.png">

According to `role="status"` docs page ([3](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/status_role)) we should use `aria-labelledby` if text is visible. In our case I think we should pass value of `text` prop into this attribute. 



Here is an implementation example on w3 ([4](https://www.w3.org/WAI/WCAG21/working-examples/aria-role-status-shoppingcart/)).

**Comment by rustem-nasyrov** [comment]
Right now I'm working on va-badge component, I can handle this issue, after discussion.
