### ISSUE TITLE
Remove transparent prop from Badge component

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3262]
**Is your feature request related to a problem? Please describe.**
Do we need this prop? I can't find any use cases in other frameworks or UI patterns. It seems strange to just add opacity to a component using inline styles
**Discussed: Remove transparent prop from Badge component**

![image](https://user-images.githubusercontent.com/35342240/228176264-e04b54ae-ef05-42a2-8713-fc73017d8e3b.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gweesin** [comment]
@zvenigorodskaia Hello, I found the transparent prop in Quasar framework.

I think this scene needs to be used when the underlying element needs to be fully displayed, so the floating element needs to be transparent.
