### ISSUE TITLE
Google material icons expands the width of va-icon

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#3272]
Using outlined google material icons expands the width of the VaIcon component.

```html
<va-icon name="mail_outlined" />
```
<img width="242" alt="image" src="https://user-images.githubusercontent.com/29167241/228481899-0e371d1b-7662-46e4-8418-fed3f80fa7dc.png">

```html
<va-icon name="mail" />
```
<img width="241" alt="image" src="https://user-images.githubusercontent.com/29167241/228482454-d3790c47-685c-488c-997f-f75118ec502a.png">

Blocker for #3246

**Comment by asvae** [comment]
I would imagine we need some kind of example in docs where we explain what to do in that case.

There are likely other icons that will break the size limit.

**Comment by asvae** [comment]
Please take a look at this and decide the priority and what we want to do with it next.

**Comment by asvae** [comment]
Random info for help:

Here icons are differen size and rating jumps.
![Image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/06db5de7-c0e7-4a41-a064-b19370dc2b27)

See https://fontawesome.com/docs/web/style/fixed-width

For icon we probably want to have priority for css variables to transition from inline style to css variables (v-bind).

Overall this is pretty important (very annoying for user to deal with).

**Comment by m0ksem** [comment]
It must be `mail_outline` without `d` at the end (see https://github.com/google/material-design-icons/issues/390)

<img width="674" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/9abce6cb-5631-49c1-ad1f-f26ed89f1e88">




lol
