### ISSUE TITLE
a11y: va-collapse

### ISSUE THREAD

**Issue by kushich** [epicmaxco/vuestic-ui#3282]
- [x] step 1: investigate a11y guides for this component;
- [x] step 2: discuss with team;
- [ ] step 3: implement required functionality;
- [ ] step 4: add docs page section about a11y.

**Comment by kushich** [comment]
I found nothing about accessible aspect-ratio :)

**Comment by kushich** [comment]
Task described here #3288

**Comment by xiongmao86** [comment]
@asvae, this should probably close because of #3499.
