### ISSUE TITLE
Modal triggered by button inside dropdown list does not show up

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3298]
Heelo!

What I am trying to do is:
1. Have a menu dropdown in a page (let's call it details page)
2. The dropdown has a list of buttons
3. Each button triggers a modal with a form

I have a Modal component defined. If I insert it directly in details page, it works as expected, but when I insert it into the dropdown list in the details page, it never shows up when its button is clicked.

Sample code:

```vue
// details page
<template>
  <death-modal :animal-id="props.animalId" />
  <animal-dropdown :animal-id="animal?.id" />
</template>


<script setup lang="ts">
  import AnimalDropdown from './registry/AnimalDropdown.vue'
  import Modal from './registry/Modal.vue'

</script>
```

``` vue
// animal-dropdown
<template>
  <va-dropdown>
    <template #anchor>
      <va-button icon="more_vert"> Registrar </va-button>
    </template>
    <va-dropdown-content>
      <va-list :fit="true">
        <va-list-item class="list__item">
          <modal :animal-id="props.animalId" />
        </va-list-item>
      </va-list>
    </va-dropdown-content>
  </va-dropdown>
</template>

<script setup lang="ts">
  import Modal from './Modal.vue'

  const props = defineProps<{
    animalId?: string | number
  }>()

</script>
```

```vue
// Modal
<template>
  <va-button @click="showContent = !showContent"> Registry </va-button>
    <va-modal v-model="showContent" :title="'Registry'" :message="'Test message'">
    </va-modal>
</template>

<script setup lang="ts">
  import { ref } from 'vue'
  const showContent = ref(false)

</script>
```

_Originally posted by @pedrovgp in https://github.com/epicmaxco/vuestic-ui/discussions/3292_

**Comment by ilearnjs** [comment]
Hi.
From my point perspective it is not an issue but expected behaviour.
Once dropdown becomes invisible everything defined in scope of it become invisible as well.

The approach you described seems right to me
> If I insert it directly in details page, it works as expected

@pedrovgp @m0ksem

**Comment by asvae** [comment]
Seems like not an issue.

Popover does v-if, so modal won't even be rendered.
