### ISSUE TITLE
`VaInput` and `VaSelect` text color

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#3307]
**Vuestic-ui version:** 1.6.3

- `outline` style
![image](https://user-images.githubusercontent.com/55198465/230384609-f5c541c9-45d0-4243-aa38-ca0d28a3d17c.png)

- `solid (default)` style
![image](https://user-images.githubusercontent.com/55198465/230384816-95da5efd-24f6-4edd-8819-ecf0a0960419.png)

**Comment by peoray** [comment]
can I pick this up?

**Comment by m0ksem** [comment]
> can I pick this up?

Sure. I'll simplify this task. We need to use `useTextColor` and `useElementBackground` composables in Select. LMK, if you have any questions.

**Comment by peoray** [comment]
@m0ksem thank you. I'll send a pr asap

**Comment by asvae** [comment]
@peoray hey, do you have any plans to work on this?

**Comment by peoray** [comment]
@asvae yes, I'll get to it asap

**Comment by peoray** [comment]
Struggling to replicate this. Any help please?

**Comment by m0ksem** [comment]
Hi @peoray. it is in https://ui.vuestic.dev/en/ui-elements/config#default-usage docs example. You can make own demo in VaInput.demo.vue and run it with `yarn serve`. Just show outline input on some colorfull bg.

**Comment by asvae** [comment]
@peoray hey, still need help?

You can ask in discord, should work faster. :)

**Comment by m0ksem** [comment]
Fixed in Inputs redesign PR.
