### ISSUE TITLE
Components should have full names

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3313]
**Vuestic-ui version:** 1.6.3

<img width="272" alt="image" src="https://user-images.githubusercontent.com/5394573/230503232-51180389-9211-48c4-8146-fada1c31f454.png">

Should be LayoutHeader etc.

**Comment by m0ksem** [comment]
In nuxt app architecture component name is using folder name. So when you have

`layout/Header.vue`

it has a `LayoutHeader` name.

For `layout/LayoutHeader.vue` you will get `LayoutLayoutHeader`

**Comment by asvae** [comment]
Discussed with @m0ksem and decided not to do this.
