### ISSUE TITLE
Example dropdown-buttons on split does not wrap on mobile view.

### ISSUE THREAD

**Issue by a-3140** [epicmaxco/vuestic-ui#3314]
![image](https://user-images.githubusercontent.com/94731422/230531678-b60bab1d-e532-4904-a21a-8703f0e7cdd5.png)

I have a fix for this which just adds a 'flex-wrap: wrap;' on the docs. I can make a PR if possible?

**Comment by rustem-nasyrov** [comment]
Hello, @a-3140! Thank you for your interest in Vuestic UI.

> I have a fix for this which just adds a 'flex-wrap: wrap;' on the docs. I can make a PR if possible?

Yes, you can make a PR, also, we have integrations with Tailwind CSS in docs, so you can use its classes.

**Comment by a-3140** [comment]
Hi @rustem-nasyrov, thanks for the reply!

I also noticed that there are several inline styles on the docs, I can migrate it to using solely tailwind classes.

**Comment by rustem-nasyrov** [comment]
> I also noticed that there are several inline styles on the docs

Could you please share more details? If these inline styles are for docs markup itself, then will be better to make separate PR.

**Comment by a-3140** [comment]
There are several instances inside the `docs/page-config/ui-elements/` like this:

![image](https://user-images.githubusercontent.com/94731422/230714864-f0e0f0a2-310b-4661-9a02-ef34912522fd.png)

Can be replaced with tailwind `max-w-sm` which is 24rem ( 384px ) or if we want to maintain the 400px, `max-w-[400px]`.

There are other files within the folder that uses inline styles. I can create a new PR and transform them into tailwind classes instead of inline styles for code uniformity, if we're good to go with these changes?

**Comment by rustem-nasyrov** [comment]
> There are several instances inside the docs/page-config/ui-elements/ like this:
Can be replaced with tailwind `max-w-sm` which is 24rem ( 384px ) or if we want to maintain the 400px, `max-w-[400px]`.

Ok, got it.

> There are other files within the folder that uses inline styles. I can create a new PR and transform them into tailwind classes instead of inline styles for code uniformity, if we're good to go with these changes?

Yes, of course. I'll create a new issue for you. :)
