### ISSUE TITLE
Replace inline styles with tailwind classes

### ISSUE THREAD

**Issue by rustem-nasyrov** [epicmaxco/vuestic-ui#3321]
We need to get rid of inline style in all docs examples if it's possible. :) Context:
> There are several instances inside the `docs/page-config/ui-elements/` like this:
![image](https://user-images.githubusercontent.com/94731422/230714864-f0e0f0a2-310b-4661-9a02-ef34912522fd.png)
Can be replaced with tailwind `max-w-sm` which is 24rem ( 384px ) or if we want to maintain the 400px, `max-w-[400px]`.
There are other files within the folder that uses inline styles. I can create a new PR and transform them into tailwind classes instead of inline styles for code uniformity, if we're good to go with these changes?

_Originally posted by @a-3140 in https://github.com/epicmaxco/vuestic-ui/issues/3314#issuecomment-1500849782_

**Comment by xiongmao86** [comment]
Hi, @rustem-nasyrov, I would like to take a stab of this, could you assign this issue to me?

**Comment by m0ksem** [comment]
> Hi, @rustem-nasyrov, I would like to take a stab of this, could you assign this issue to me?

Hi, @xiongmao86. I think we have already a draft pr for this issue! Sorry, haven't noticed earlier.

**Comment by xiongmao86** [comment]
Ah, I'll close my pr.

**Comment by xiongmao86** [comment]
This should probably close due to #3353.
