### ISSUE TITLE
Inputs design fixes and related updates (change labels)

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3330]
**Is your feature request related to a problem? Please describe.**

Please change default input component (and all components whick used Input 
(https://vuestic.dev/en/ui-elements/input
https://vuestic.dev/en/ui-elements/select
https://vuestic.dev/en/ui-elements/time-input
https://vuestic.dev/en/ui-elements/date-input
https://vuestic.dev/en/ui-elements/counter
https://vuestic.dev/en/ui-elements/color-input
https://vuestic.dev/en/ui-elements/collapse)

![image](https://user-images.githubusercontent.com/35342240/231402183-c11b4824-90a4-44ea-9bda-98c8f48a8ac4.png)

By default all this components should have transparent background and gray border as you can see on design examples

!!! Move all labels outside input

**Design:**
https://www.figma.com/file/2WmjnFhXqMdhcXiRCS9KjK/Work-in-progress?node-id=501-2946&t=hPv10xln0ETEtUxL-0

**Comment by asvae** [comment]
Sure about the collapse?

**Comment by asvae** [comment]
We need here 
* What problem are you looking to fix with that.

Also we need to investigate exact implementation, figure out what breaking changes this leads to.

Then decide on implementation.

**Comment by asvae** [comment]
Also see https://github.com/epicmaxco/vuestic-ui/issues/3512

**Comment by asvae** [comment]
<img width="750" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/a5955025-422c-4fa9-beef-7fe4012675ca">

One more case that's somewhat broken right now (background overlaps outline).

**Comment by m0ksem** [comment]
Also, consider dealing with custom label height https://github.com/epicmaxco/vuestic-ui/issues/3616.

**Comment by asvae** [comment]
Accordion doesn't look according to design.

**Comment by m0ksem** [comment]
> Accordion doesn't look according to design.
> 
> ![Image](https://user-images.githubusercontent.com/5394573/262958900-67330841-9b1c-4628-b65e-3dad5a8c2b13.png)

It was a mistake after merging conflicts in layout and input...
