### ISSUE TITLE
Docs site freezes | Сайт с документацией зависает намертво

### ISSUE THREAD

**Issue by vitjaz** [epicmaxco/vuestic-ui#3331]
**RU**: Сайт с докой периодически намертво зависает, не помогает даже полная перезагрузка страницы. Причина в консоли:
**ENG**: Docs site freezes very often. Reason in console:

![image](https://user-images.githubusercontent.com/47814045/231679669-fd0341c2-2228-4d53-a91f-c39a9c53035b.png)

**RU**: Самые большие проблемы по моим наблюдением на странице с компонентом Form
**ENG**: The biggest problems on this page, according to my observations
https://vuestic.dev/ru/ui-elements/form

**Comment by vitjaz** [comment]
@m0ksem I'm trying again... Page freeze after this logs.
![image](https://user-images.githubusercontent.com/47814045/232697975-390c79e8-8436-4a1f-b8d5-56e321247c0c.png)

**Comment by m0ksem** [comment]
Just deployed to prod. Thanks!
