### ISSUE TITLE
Select prevent-overflow doesn't work

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3334]
Please ping @ssemenkoff after fixing

**Comment by m0ksem** [comment]
![firefox_FukH7NjTqo](https://user-images.githubusercontent.com/23530004/231789338-8a9dd006-badd-4e83-b26b-7e1dd097751d.gif)

Looks like it works for me. I'll need some additional info like lib version, global config, bundler, etc.

**Comment by ssemenkoff** [comment]
https://codesandbox.io/p/sandbox/busy-darkness-dm2urv

**Comment by asvae** [comment]
Blocked by #3083
