### ISSUE TITLE
Config not work outside a vue file

### ISSUE THREAD

**Issue by EugenGedroyc** [epicmaxco/vuestic-ui#3336]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
npm create vuestic (any settings)

add to main.js

`      config: {
        colors: {
          variables: {
            primary: "#7DB713", 
            warning: '#C88817'
            myColor: "#000",
          },
        },
      },
 `
 
 bar.js

    import { useToast } from "vuestic-ui";
    const { init } = useToast();
    
    function foo() {
      init({
        message: "Any Message",
        color: "myColor", //'warning' or without color
      });
    }
    
    export { foo };

component.vue

    <script setup>
    import { foo } from "@/components/bar";
    </script>
    
    <template>
      <VaButton @click="foo">foo</VaButton>
    </template>`

**What is the expected behavior?**

to get colors from variables

**What is the current behavior?**

i get a standart color 'warning' from vuestic

**Comment by m0ksem** [comment]
useToast as the other composables required to be executed in setup state. So it must be used in nested composable like:

bar.js
```ts
import { useToast } from "vuestic-ui";

function useFoo {
  const { init } = useToast();

  return function foo() {
    init({
      message: "Any Message",
      color: "myColor", //'warning' or without color
    });
  }
}

export { useFoo };
```

```vue
<script setup>
import { useFoo } from "@/components/bar";

const foo = useFoo()
</script>

<template>
  <VaButton @click="foo">foo</VaButton>
</template>
```

But for better DX, we can useCurrentApp composable and provide app context to useToast() even if it is inappropriate accordtion to vue arch.
