### ISSUE TITLE
va-select does not show initial value when part of a component that is rendered in a v-for loop

### ISSUE THREAD

**Issue by JohanAndreVisma** [epicmaxco/vuestic-ui#3338]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
Component containing va-select in its template.
This component is rendered multiple times using v-for in another component.
The va-select gets an initial value based on v-model and uses options that is a list of objects.

**What is the expected behavior?** All rendered components should show the initial value if present in the model.

**What is the current behavior?** Only the first rendered component has an initial value.
See screenshot where unit selection is empty for all but the first row.
![va-select inital value bug](https://user-images.githubusercontent.com/78589576/232343092-8cb018e1-9a25-49b3-85b2-fd21907cc597.png)

**Other information**
It seems like the problem is that it tries to show the seleced value before the DOM node exist.
I managed to get all selected values to show by wrapping va-select inside a component that sets the value for va-select first when it's mounted.

![va-select fix](https://user-images.githubusercontent.com/78589576/232612721-0e85e559-f86b-4aa9-831d-8386dcf67a96.png)

**Comment by m0ksem** [comment]
Hey, @JohanAndreVisma. Would you mind creating reproduction on code sandbox, so we can fix it faster?

**Comment by JohanAndreVisma** [comment]
@m0ksem Excuse my newbie question, where is code sandbox?

**Comment by asvae** [comment]
Hey @JohanAndreVisma - this here: https://codesandbox.io/s/gc17dd?file=/src/App.vue

You can also find a link behind examples 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/5394573/232496162-5bc6bdaa-34ce-45cf-9f16-8113e9725ba3.png">

**Comment by JohanAndreVisma** [comment]
@asvae Can I edit and save the sandbox example you just linked to or do you want me to login to code sandbox and create my own sandbox. I have no experience with using sandbox.

**Comment by m0ksem** [comment]
> @asvae Can I edit and save the sandbox example you just linked to or do you want me to login to code sandbox and create my own sandbox. I have no experience with using sandbox.

You can log in, edit existing one sandbox (Select demo for example) and it will be saved with new url as new codesandbox project (fork of demo). BTW, you're not forced to do it. It just will take more time for us to figure out the problem, so reproduction will be appreciated.

**Comment by asvae** [comment]
Please reopen if you can get us repro. Not possible for us to work on this sadly :<.
