### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by Naween-Pasindu** [epicmaxco/vuestic-ui#3343]
**Vuestic-ui version:** 1.6.3

**Steps to reproduce**
- Create a  set of tabs using va-tabs
- Then try to resize the window using inspect element

**What is the expected behavior?**
Normal, responsive behavior

**What is the current behavior?**
Getting an error - ResizeObserver loop limit exceeded
Checked on Chrome, Edge and Firefox

**Other information**
![image](https://user-images.githubusercontent.com/37021586/232704022-023f575a-e6a5-40a2-83d3-3801648cb63b.png)
![image](https://user-images.githubusercontent.com/37021586/232704114-8165a0a9-6099-41ac-87b2-740f113a19f2.png)

**Comment by RVitaly1978** [comment]
Hello, @Naween-Pasindu.
I tried to reproduce this bug, but I didn't succeed. Here is a link to the [CodeSandBox](https://codesandbox.io/p/sandbox/admiring-yonath-k9ci5t?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A11%2C%22endLineNumber%22%3A1%2C%22startColumn%22%3A11%2C%22startLineNumber%22%3A1%7D%5D). Take a look, please. You can make changes to clarify your case.

**Comment by Naween-Pasindu** [comment]
Hello, @RVitaly1978 .
Thank you for the response, I checked the same code on both of vite and vue-cli project initializers. That error raised only on vue-cli project
