### ISSUE TITLE
Document error - UI elements - form

### ISSUE THREAD

**Issue by atilahcS** [epicmaxco/vuestic-ui#3344]
**Vuestic-ui version**: 1.6.4

**Page**: https://vuestic.dev/en/ui-elements/form

Cannot click or do anything since script error.

Here's console log.

![vuestic-doc-error-form](https://user-images.githubusercontent.com/16699548/232719473-4bad86e3-a982-4144-b28f-7a46cf4d7eea.PNG)

**Comment by m0ksem** [comment]
Fixed in scope of https://github.com/epicmaxco/vuestic-ui/issues/3331 (duplicate) 

Thanks for report!
