### ISSUE TITLE
Не работает ввод в поле поиска | Search input not work

### ISSUE THREAD

**Issue by vitjaz** [epicmaxco/vuestic-ui#3350]
![image](https://user-images.githubusercontent.com/47814045/232898605-0630595e-46b4-4e64-b0ca-b391f31b95f8.png)

ENG: This input field has input cursor, but disable. Is it normal behavior?
RUS: Поле ввода имеет характерный курсор для ввода, но оно недоступно. Это штатное поведение?

**Comment by RVitaly1978** [comment]
Our search is temporarily not working. We will fix it as soon as possible.
