### ISSUE TITLE
Seeing duplicated props for example like `text-by` and `textBy` show up at the same api table.

### ISSUE THREAD

**Issue by xiongmao86** [epicmaxco/vuestic-ui#3358]
Is it just me, or someone else could see this:

<img width="869" alt="截屏2023-04-21 下午7 55 32" src="https://user-images.githubusercontent.com/1770218/233629508-798dd30c-dfb1-40a9-9cff-70e4fe90cb43.png">

**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
`yarn serve:docs`

**What is the expected behavior?**
No duplicated properties.

**What is the current behavior?**
Duplicated properties show up in api table. For example, `textBy` and `text-by` show at the same time.

**Other information**
I am adding empty props descriptions, when I came to tree view I saw this duplicated thing showing up, I don't know whether it is because of me, or someone else would see this.

**Comment by m0ksem** [comment]
Probably fixed here: https://github.com/epicmaxco/vuestic-ui/pull/3352

**Comment by xiongmao86** [comment]
Thanks, @m0ksem.
