### ISSUE TITLE
Landing needs bigger left and right margins

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3361]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5394573/233662364-2512e771-605f-4f97-9ed5-a9473caee57a.png">
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5394573/233663103-c19bbe53-9607-4575-8a4b-92847ddbd36b.png">

**What is the expected behavior?**

Bigger margins on the sides of the screen, we can compare with other documentation sites or consult with @xx13 

**What is the current behavior?**

Margins look too small.

**Other information**

**Comment by Udaay** [comment]
Do we have anyt website where we can refer what it's like to be exactly ?
