### ISSUE TITLE
Navigation bar shown by default on mobile

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3362]
**Vuestic-ui version:** 1.6.4
![Screenshot_2023-04-22-00-37-10-99_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/5394573/233730481-d06364c4-49f3-435a-9a2c-fdc71aeea433.jpg)

**Steps to reproduce**

**What is the expected behavior?**

Navigation bar should not cover content

**What is the current behavior?**

**Other information**

Please check all screen sizes

**Comment by m0ksem** [comment]
I want to introduce VaLayout component MPV, and it can be used in docs as an example. Probably will fix this issue.
