### ISSUE TITLE
Error about importing `@nuxt/kit` emitted when I `yarn serve:docs`

### ISSUE THREAD

**Issue by xiongmao86** [epicmaxco/vuestic-ui#3368]
<img width="729" alt="截屏2023-04-24 下午5 03 43" src="https://user-images.githubusercontent.com/1770218/233950902-aff2fed3-9839-4340-b845-75ac2ffc90e1.png">
`fs` cannot be import in my windows lap.
<img width="727" alt="屏幕截图 2023-04-24 212634" src="https://user-images.githubusercontent.com/1770218/234010503-1a743181-3f6e-4d70-8be4-0641f133b164.png">

**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
```powershell
yarn
yarn serve:docs
```

**What is the expected behavior?**
No error.

**What is the current behavior?**
> ERROR  This module cannot be imported in the Vue part of your app. [importing @nuxt/kit from modules/page-config/compiler/create-importer.ts]

**Other information**
This happen on windows and on Mac, On windows there are an extra error complain about importing `fs`. I am on my Mac now, if the error message about `fs` is important, I'll switch to my windows and fetch it. Thanks.

**Comment by sunday9th** [comment]
I encountered the same issue on windows.

```
yarn

yarn add -D tailwindcss

yarn serve:docs
```

![image](https://user-images.githubusercontent.com/1252279/234228332-86e90db0-b668-4d93-a779-2b0ff0e4066d.png)

**Comment by asvae** [comment]
@xiongmao86 can you double check if issue persists for you for now (we updated deps).

We tried to run docs on different mac and windows (wsl or not) and everything was all right. :)

**Comment by xiongmao86** [comment]
And thank you very much for putting your effort to solve this problem.

**Comment by xiongmao86** [comment]
@asvae thanks for the hard working, It's ok that the issue is being left over. I can still work on while the error is being retained.
