### ISSUE TITLE
Using rowData slot results in error

### ISSUE THREAD

**Issue by Bond-Addict** [epicmaxco/vuestic-ui#3373]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
``<template #cell(cell Name)="{ rowData}">``

**What is the expected behavior?**
Accesses ``rowData`` without errors

**What is the current behavior?**
Produces:
Property 'rowData' does not exist on type 'unknown'. 
I believe this will cause issues for cicd pipelines that do a sanity check before deploying. 
**Other information**

**Comment by misterpekert** [comment]
@Bond-Addict, could you please provide the data you are using when facing this issue? 

Or a sandbox would be even better. Thanks!

**Comment by Bond-Addict** [comment]
Suddenly the error isnt appearing. I'll reopen if I see it again.
