### ISSUE TITLE
Memory leak for docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3381]
We have a consistent issue of documentation app going down after a while.

Most likely explanation seem to be node running out of memory.

Here are metrics:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/5394573/234977772-55d79ec8-883c-467f-af85-29cc9df15e75.png">

And here are logs were getting (not sure if relevant):

<img width="859" alt="image" src="https://user-images.githubusercontent.com/5394573/234980439-8561a1ed-5a53-415d-8f85-538f3a4b233a.png">

For deploy the following commands are being used:
```bash
yarn workspace docs build
yarn workspace docs nuxi start
```

I suggest we reproduce it locally - then work on fix.

You can also deploy railway app locally, might be easier to get repro.

We probably can fix this by switching to `generate` flow or use do full SPA mode.

But ideal solution would be to have docs properly server side rendered (which might be not achievable at this point).

-[ ] In scope of grooming we need to figure out exact steps for this.

----

* Try if generate flow is good enough
  * We can do this on test environment on railway. (just use serve for deploy instead of nuxt server)
  * Test communaly if everything is good.
  * We should agree on tradeoffs and decide whether to use generate or move with initial flow.

**Comment by Bond-Addict** [comment]
Not sure if its related, but I've noticed that when hitting the docs usually the first time it "loads" but the page is blank. If I refresh, it takes a few secs and then it slowly loads content.

**Comment by m0ksem** [comment]
I think we're waiting on https://github.com/nuxt/nuxt/issues/12384. Until then, I'll try to move docs to SSG.

**Comment by m0ksem** [comment]
Idea with moving to SSG not really helped. We have theming issues here, because some part of site is rendered on server with light theme and half of pages are light, and the other is dark. (see https://github.com/epicmaxco/vuestic-ui/issues/3395).
