### ISSUE TITLE
VaSwitch true-value and false-value props must have any type, not boolean

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3391]
![image](https://user-images.githubusercontent.com/23530004/235568701-6d275fa0-5262-4e7d-94c2-8c75e87032f0.png)

**Comment by arkmadj** [comment]
Hi @m0ksem Can I work on this issue?

**Comment by m0ksem** [comment]
> Hi @m0ksem Can I work on this issue?

Hi. Sure.

**Comment by tarunsamanta2k20** [comment]
@m0ksem  Can i work on this issue?

**Comment by arkmadj** [comment]
@m0ksem I looked through the code and I think this issue has been resolved. The `VaSwitch` component uses the `useSelectableProps` composable and this set the `trueValue` and `falseValue` types to `null as any as PropType<unknown>`. I've attached images of the sections I'm referring to
### VaSwitch props
<img width="518" alt="Screenshot 2023-05-06 at 23 54 04" src="https://user-images.githubusercontent.com/21014910/236649621-88f3d740-58ad-49a5-bd7d-50cef763fd8a.png">

### useSelectableProps composable
<img width="562" alt="Screenshot 2023-05-06 at 23 54 24" src="https://user-images.githubusercontent.com/21014910/236649618-4b445125-c088-4ddf-8919-4a9f57d06507.png">

**Comment by m0ksem** [comment]
> @m0ksem Can i work on this issue?

Hi, @tarunsamanta2k20. Sorry, but this task was taken before. But we have plenty of other good first issues for new contributors!

**Comment by m0ksem** [comment]
> @m0ksem I looked through the code and I think this issue has been resolved. The `VaSwitch` component uses the `useSelectableProps` composable and this set the `trueValue` and `falseValue` types to `null as any as PropType<unknown>`. I've attached images of the sections I'm referring to
> ### VaSwitch props
> 
> <img alt="Screenshot 2023-05-06 at 23 54 04" width="518" src="https://user-images.githubusercontent.com/21014910/236649621-88f3d740-58ad-49a5-bd7d-50cef763fd8a.png">
> ### useSelectableProps composable
> 
> <img alt="Screenshot 2023-05-06 at 23 54 24" width="562" src="https://user-images.githubusercontent.com/21014910/236649618-4b445125-c088-4ddf-8919-4a9f57d06507.png">

> @m0ksem I looked through the code and I think this issue has been resolved. The `VaSwitch` component uses the `useSelectableProps` composable and this set the `trueValue` and `falseValue` types to `null as any as PropType<unknown>`. I've attached images of the sections I'm referring to
> ### VaSwitch props
> 
> <img alt="Screenshot 2023-05-06 at 23 54 04" width="518" src="https://user-images.githubusercontent.com/21014910/236649621-88f3d740-58ad-49a5-bd7d-50cef763fd8a.png">
> ### useSelectableProps composable
> 
> <img alt="Screenshot 2023-05-06 at 23 54 24" width="562" src="https://user-images.githubusercontent.com/21014910/236649618-4b445125-c088-4ddf-8919-4a9f57d06507.png">



> @m0ksem I looked through the code and I think this issue has been resolved. The `VaSwitch` component uses the `useSelectableProps` composable and this set the `trueValue` and `falseValue` types to `null as any as PropType<unknown>`. I've attached images of the sections I'm referring to
> ### VaSwitch props
> 
> <img alt="Screenshot 2023-05-06 at 23 54 04" width="518" src="https://user-images.githubusercontent.com/21014910/236649621-88f3d740-58ad-49a5-bd7d-50cef763fd8a.png">
> ### useSelectableProps composable
> 
> <img alt="Screenshot 2023-05-06 at 23 54 24" width="562" src="https://user-images.githubusercontent.com/21014910/236649618-4b445125-c088-4ddf-8919-4a9f57d06507.png">

Thanks, I'll double-check how I reproduced it.

**Comment by tarunsamanta2k20** [comment]
@m0ksem  are you working on it? Do you mind if I handle it?

**Comment by asvae** [comment]
It seems we just need to double check if it's fixed or not. (it seems to be fixed)

**Comment by rustem-nasyrov** [comment]
Throws warning if the Number type value passed.

**Comment by m0ksem** [comment]
> Throws warning if the Number type value passed.

Should be type undefined instead of null then?

**Comment by rustem-nasyrov** [comment]
@m0ksem, I mean that we are missing the Number in the`modelValue` prop:
```js
modelValue: {
      type: [Boolean, Array, String, Object] as PropType<boolean | unknown[] | string | number | Record<string, unknown> | null>,
      default: false,
},
```
PropType has number type, but vue prop type doesn't.

**Comment by m0ksem** [comment]
Thanks everyone!
