### ISSUE TITLE
ModalOptions calculated type has missing props

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#3407]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
Check ModalOptions type calculated output

**What is the expected behavior?**
Should infer all the props of the Modal component, like title, message, etc.

**What is the current behavior?**
It only infers the emits, but not the props

![Screenshot 2023-05-05 at 12 52 12](https://user-images.githubusercontent.com/46224115/236439851-e780eb1b-a3c6-494c-8eb4-2b81c3fc0ac0.png)

**Other information**

**Comment by m0ksem** [comment]
I remember fixing it, but not sure if I succeeded. Something related to vue-tsc, ts version and `DefineComponent` type from vue.

@m0ksem, double check it.
