### ISSUE TITLE
Documentation for Select does not mention icon per option

### ISSUE THREAD

**Issue by JohanAndreVisma** [epicmaxco/vuestic-ui#3408]
When looking through your source code I found out that you can specify an icon per option.
This is a great feature but I could not find anything about it in your documentation:
https://ui.vuestic.dev/en/ui-elements/select
The only icons mentioned there are other icons such as the one used to open the drop down list.

To enable this it's enough to use an options array where each element contains an icon property:

`[
                    {
                        code: 'sv',
                        name: 'Svenska',
                        icon: 'flag-se'
                    },
                    {
                        code: 'en',
                        name: 'English',
                        icon: 'flag-gb'
                    }
                ]`

**Comment by Skander999** [comment]
Hello I'd like to work on this issue and update the documentation page since this is a very useful feature
