### ISSUE TITLE
Documenation for using custom icon config does not work

### ISSUE THREAD

**Issue by JohanAndreVisma** [epicmaxco/vuestic-ui#3409]
In your page https://ui.vuestic.dev/en/services/icons-config
this part did not work for me when I tried it:

`.use(createVuestic, {
        config: {
            icons: createIconsConfig({ aliases, fonts })
        }
    })`

To make it work I had to change it to:

`.use(createVuestic({
        config: {
            icons: createIconsConfig({ aliases, fonts })
        }
    }))`

**Comment by arkmadj** [comment]
@m0ksem Can I work on this issue?

**Comment by arkmadj** [comment]
@m0ksem I'm not sure what I should do here. Do I need to update the docs only?

**Comment by m0ksem** [comment]
> @m0ksem I'm not sure what I should do here. Do I need to update the docs only?

Yep. We have outdated docs. Issue author described everything pretty clear.

**Comment by Roman4437** [comment]
@m0ksem I'd like to fix it
