### ISSUE TITLE
Make vuestic docs english only

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3425]
It doesn't seem we want to have translations now or in the future:

Pros:
* right now translations are not full (not perfect to showcase)
* we're targeting international community (translations add to clutter)
* #3039 - search gives multiple results because of translations
* GPTs are on the rise and translations are steadily improving, so it might be very easy to translate full page in a year or two. So no much reason to have translation going forward.

Cons:
* we'll have a cut on russian audience
* we will get rid of translations for good (there won't be a simple way to reenable them)

### Action

- [ ] Remove translation switch from docs page
- [ ] Remove translations from docs (to research and detail - would probably include router, page configs and translation files, but there might be edge cases)

**Comment by KazimirPodolski** [comment]
Также может помочь обязательный спеллчекер для всех разрабов :wink:. Сейчас документация выглядит как _очевидно_ написанная людьми с неродным английским.

![image](https://github.com/epicmaxco/vuestic-ui/assets/6647438/fd05967d-24ab-4cd7-8af8-ad8d04ce9af8)

![image](https://github.com/epicmaxco/vuestic-ui/assets/6647438/561b945d-eb5a-4bd8-8e54-37a58d4f6b3a)

![image](https://github.com/epicmaxco/vuestic-ui/assets/6647438/08a6d246-b5f6-4689-954b-996d87029de7)
