### ISSUE TITLE
weird icon display style

### ISSUE THREAD

**Issue by shiina7** [epicmaxco/vuestic-ui#3432]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
1. When I use 'md:hidden' in the va-icon components
![image](https://github.com/epicmaxco/vuestic-ui/assets/59157966/de2f5174-2f46-4d64-b155-cccaec42a8f5)
2. It's not working, Because the '.material-icons' class has a 'display: inline-block' attribute and  has a higher priority
![image](https://github.com/epicmaxco/vuestic-ui/assets/59157966/b8748322-0fac-4850-a36a-e10db971290f)
3. How can I solve this problem?

**Comment by m0ksem** [comment]
Hi @shiina7. Are you using nuxt or it is a vite project?

**Comment by shiina7** [comment]
> Hi @shiina7. Are you using nuxt or it is a vite project?

Yeap, it’s a vite project.

**Comment by m0ksem** [comment]
> > Hi @shiina7. Are you using nuxt or it is a vite project?
> 
> Yeap, it’s a vite project.

Try to rearrange imports. Because you have fonts imported after tailwind (or whatever styling you use) it has a higher priority. Otherwise, to help this out, I'll need to ask for reproduction.

**Comment by shiina7** [comment]
> > > Hi @shiina7. Are you using nuxt or it is a vite project?
> > 
> > 
> > Yeap, it’s a vite project.
> 
> Try to rearrange imports. Because you have fonts imported after tailwind (or whatever styling you use) it has a higher priority. Otherwise, to help this out, I'll need to ask for reproduction.

you are right, I solved the problem when I import tailwind after the other styles, thanks a lot.

**Comment by shiina7** [comment]
@m0ksem Thanks a lot.
