### ISSUE TITLE
type error: va-switch 'trueValue' and 'falseValue'

### ISSUE THREAD

**Issue by shiina7** [epicmaxco/vuestic-ui#3434]
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**
1. va-swtich setup trueValue and falseValue
2. typescript error：
![image](https://github.com/epicmaxco/vuestic-ui/assets/59157966/d87523b4-f257-4360-a736-081af5b13e4a)
3. check declaration file
![image](https://github.com/epicmaxco/vuestic-ui/assets/59157966/2839685c-a389-4d63-9de3-932dee11a6fe)
4. docs display
![image](https://github.com/epicmaxco/vuestic-ui/assets/59157966/7093094b-f6c2-4dfe-bbf9-3b563b6e3807)
![image](https://github.com/epicmaxco/vuestic-ui/assets/59157966/ec9d2123-403b-4424-8330-5710c626b2f9)
5. Maybe I'm not familiar enough with typescript, but I'd like to solve this problem

**Comment by rustem-nasyrov** [comment]
Duplication #3391
