### ISSUE TITLE
Test coverageto make sure applyPreset and currentPresetName work correct

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3439]
Would be nice to have test coverage here to make sure applyPreset and currentPresetName work correct.

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/issues/3431#issuecomment-1561538622_

**Comment by Evobaso-J** [comment]
@m0ksem Good, I can work on this. I was tempted to add tests right away in the previous issue but I did not find any mention of those in the contribution guidelines, so I'm wondering what the standard is here: do we need to open new issues each time to include tests or can those be added regardless?

**Comment by m0ksem** [comment]
> @m0ksem Good, I can work on this. I was tempted to add tests right away in the previous issue but I did not find any mention of those in the contribution guidelines, so I'm wondering what the standard is here: do we need to open new issues each time to include tests or can those be added regardless?

Hi. There is no standard. Sometimes tests are required, especially for complex things, but in most cases we can live without them. We prefer visual testing right now.

value2 labled issue is something useful, but we don't need to rush with this.

**Comment by Evobaso-J** [comment]
@m0ksem hello again! I managed to add the tests
