### ISSUE TITLE
Remove CSS variable from root(html element)

### ISSUE THREAD

**Issue by shiina7** [epicmaxco/vuestic-ui#3442]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
1. vuestic-ui places CSS variable in the style attribute of the root(html) element.

2. that's no problem, but only when there are few CSS variables, when there are many (e.g. integrated tailwindcss).

3. when I use browser(e.g. chrome) debug, CSS variables will fill the console.

4. I know it doesn't affect the functionality, but the experience is very bad (at least for me it affects my debugging).

5. Please move these CSS variables to a style tag if you can.

**Describe alternatives you've considered**

**Additional context**
Maybe this can be changed through configuration but I missed it, please let me know thanks.

**Comment by shiina7** [comment]
There is a problem with gitbub which can't upload pictures right now, I will add screenshots later.

**Comment by m0ksem** [comment]
Yeah. We 100% can do that. Must be easy to change "updateColors" method. 
https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/services/color/plugin/create-color-config-plugin.ts

**Comment by shiina7** [comment]
> Yeah. We 100% can do that. Must be easy to change "updateColors" method. https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/services/color/plugin/create-color-config-plugin.ts

I create a pull request #3466 for this issue. If you check after no problems please merge it. Thanks.

**Comment by shiina7** [comment]
added new feature for this. #3466
