### ISSUE TITLE
VaTreeView add selected node class

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3456]
Hi Team,

I have a question around highlighting (adding the background-color property) for the selected node in the Tree component.
Is this possible?

Do let me know your thoughts around it.

Thanks & Regards,
Manjari Kumari

_Originally posted by @codeonmoon in https://github.com/epicmaxco/vuestic-ui/discussions/3448_

We could add `va-tree-node--active` class, so user can stylize any state as he wants.

**Comment by codeonmoon** [comment]
@m0ksem - By when we can expect this feature?
