### ISSUE TITLE
Multiple input elements do not render properly. 

### ISSUE THREAD

**Issue by Bond-Addict** [epicmaxco/vuestic-ui#3458]
**Vuestic-ui version:** 1.6.5
**Steps to reproduce**
https://codesandbox.io/p/sandbox/relaxed-roentgen-g923yx?file=%2Fsrc%2FApp.vue%3A1%2C1&selection=%5B%7B"endColumn"%3A25%2C"endLineNumber"%3A85%2C"startColumn"%3A25%2C"startLineNumber"%3A85%7D%5D
**What is the expected behavior?**
The dropdown and date picker should appear above the rest of the content.
**What is the current behavior?**
![image](https://github.com/epicmaxco/vuestic-ui/assets/117455332/0d54c14e-085a-480a-8904-36d2223e0df1)
![image](https://github.com/epicmaxco/vuestic-ui/assets/117455332/d2e12c70-09c2-472d-9d98-43efa45241b1)

This can be resolved by setting    
``z-index: 99;``
![image](https://github.com/epicmaxco/vuestic-ui/assets/117455332/9bdd89f8-80eb-4db8-a259-a862f5b97b07)

**Other Info**
These are the components I've found so far, but it seems widespread so there are probably others that have the same issue.

**Comment by Bond-Addict** [comment]
@m0ksem that does indeed fix the issue. Is it appropriate for it to be necessary to add add the property? It seems that its more common (From my experience and the code sandbox yall provided) for it to be needed than not. Should the behavior be reversed? This will require me to go through every view and make sure that all my selects and date inputs have this property and will force new devs to know this property exists and is needed when maintaining the app in the future.

**Comment by Bond-Addict** [comment]
@m0ksem 

```
const vuesticConfig = computed(() => ({
  all: { preventOverflow: false },
}));
```

Should work right? This doesn't work for either the date input or select.

**Comment by m0ksem** [comment]
> @m0ksem
> 
> ```
> const vuesticConfig = computed(() => ({
>   all: { preventOverflow: false },
> }));
> ```
> 
> or
> 
> ```
> const vuesticConfig = computed(() => ({
>   components: {
>     all: { preventOverflow: false },
>   },
> }));
> ```
> 
> Should work right? This doesn't work for either the date input or select.

It must be used in `createVuestic` in spa or `vuestic: {}` in `nuxt.config.ts`. 

Here is detailed examples: 
https://ui.vuestic.dev/en/services/global-config#global-config-title
https://ui.vuestic.dev/en/services/components-config#components-config-components-all-title
