### ISSUE TITLE
Date Input `close-on-value-updated` prop

### ISSUE THREAD

**Issue by Bond-Addict** [epicmaxco/vuestic-ui#3459]
**Vuestic-ui version:** 1.6.5
**Steps to reproduce**
Set date input behavior using close-on-content-click.
**What is the expected behavior?**
You should be able to cycle through months using the arrows and clicking on a date should close the popup and select the date.
**What is the current behavior?**
https://codesandbox.io/p/sandbox/nice-darwin-iqjx2m
You cannot cycle through the months, but clicking on a date does close the popup and select the date.

**Comment by Bond-Addict** [comment]
@m0ksem Is there a workaround you're aware of? This is making the component almost unusable.

**Comment by m0ksem** [comment]
> @m0ksem Is there a workaround you're aware of? This is making the component almost unusable.

Hi. I think the whole approach with close-on-content-click event is not right. You want a prop close-on-value-updated. ` close-on-content-click` is event that comes from VaDropdown and it is not actually helpful. I would change this approach and add additional prop, that looks for value and if it is updated closes dropdown.

**Comment by Bond-Addict** [comment]
@m0ksem Do you mean the approach that I'm using with the prop or how its currently being implemented on the base component? What event would you suggest I look for to close it. I cant seem to trigger a function on clickDay. Are the events listed under "Events" for the component just simply a list of events that are called behind the scenes or are they supposed to be events that we can hook into? This isnt clearly stated.

**Comment by m0ksem** [comment]
> @m0ksem Do you mean the approach that I'm using with the prop or how its currently being implemented on the base component? What event would you suggest I look for to close it. I cant seem to trigger a function on clickDay. Are the events listed under "Events" for the component just simply a list of events that are called behind the scenes or are they supposed to be events that we can hook into? This isnt clearly stated.

Yeah. You absolutely   can listen for `@click-day` event!

I think this might work:
```html
<VaDateInput :show="doShow" @clickDay="doShow = false" />
```

But you will need to do it everywhere, so we need to provide you a simple prop for it...

```html
<VaDateInput close-on-value-updated />
```

or

```ts
createVuestic({
  components: {
     VaDateeInput: {
        closeOnValueUpdated: true
     }
   }
})
```

**Comment by m0ksem** [comment]
We might also want to provide `close-on-value-updated` prop for VaSelect, VaTimeInput, etc...

**Comment by Bond-Addict** [comment]
https://codesandbox.io/p/sandbox/nice-darwin-iqjx2m?file=%2Fsrc%2FApp.vue%3A75%2C66

So ``@click-day`` doesnt seem to work

**Comment by Bond-Addict** [comment]
@m0ksem  ya I think that simple prop would be super helpful. I think it would be good to update the current docs as well as I think they give the wrong impression. Based on the current docs ("Dropdown will be closed when clicked inside dropdown content") I should be implementing it properly I would think.

**Comment by Bond-Addict** [comment]
@m0ksem do you have a ballpark on when this would be fixed? Is it possible for it to make it into the June 10th sprint? If so, whats the general release dates? Do yall do a monthly release on x day?

**Comment by m0ksem** [comment]
> @m0ksem do you have a ballpark on when this would be fixed? Is it possible for it to make it into the June 10th sprint? If so, whats the general release dates? Do yall do a monthly release on x day?

We usually have release every two weeks. Next release is going to be on Friday, 9th.

**Comment by Bond-Addict** [comment]
@m0ksem thanks for getting right on this! Thanks to your answer on #3457 I was able to get a workaround in the meantime. 

```
const togglePicker = (() => {
  showDatePicker.value = !showDatePicker.value
});
```

```
<va-date-input :is-open="showDatePicker" @update:is-open="togglePicker" @update:model-value="togglePicker"
        v-model="myDate" label="Date"></va-date-input>
```

**Comment by m0ksem** [comment]
> @m0ksem thanks for getting right on this! Thanks to your answer on #3457 I was able to get a workaround in the meantime.
> 
> ```
> const togglePicker = () => {
>   showDatePicker.value = !showDatePicker.value
> };
> ```
> 
> ```
> <va-date-input :is-open="showDatePicker" @update:is-open="togglePicker" @update:model-value="togglePicker"
>         v-model="myDate" label="Date"></va-date-input>
> ```

You can also simplify it to `v-model:is-open="showDatePicker" @update:modelValue="showDatePicker = false"`.

BTW here is a pr for `close-on-value-update` prop.

**Comment by Bond-Addict** [comment]
@m0ksem that is simpler! I did notice the pr which is the reason for the callout for "getting right on this" lol

**Comment by m0ksem** [comment]
> @m0ksem that is simpler! I did notice the pr which is the reason for the callout for "getting right on this" lol
> 
> Just for my understanding, does model binding :is-open cause showDatePicker to be updated when the calendar icon is clicked? 

Yeah. It must set showDatePicker to true whenever drop-down is shown.

**Comment by Bond-Addict** [comment]
@m0ksem I just now thought about this, but will the new prop also work for manual entry date inputs?

**Comment by Bond-Addict** [comment]
@asvae I think you have the right idea for sure. I was just now thinking, could these features be combined somehow? They are different but essentially would need the same type of solution. #3455
