### ISSUE TITLE
Icons are not displayed in the Tauri app

### ISSUE THREAD

**Issue by VladKoroliuk** [epicmaxco/vuestic-ui#3460]
I use Vuestic in tauri app.

![image](https://github.com/epicmaxco/vuestic-ui/assets/86667941/78d5ffd5-5530-4810-8a59-a61d8113c3a2)

Icons are not displaying, only text. Example: 
![image](https://github.com/epicmaxco/vuestic-ui/assets/86667941/5fede641-6502-4b73-b5d0-dfec9d17c83b)

**Comment by Bond-Addict** [comment]
Have you imported the stylesheets?

@import"https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;1,700&display=swap";
@import"https://fonts.googleapis.com/icon?family=Material+Icons";
