### ISSUE TITLE
switch languages, the navigation url doesn't change

### ISSUE THREAD

**Issue by mengqiuleo** [epicmaxco/vuestic-ui#3463]
When I switch languages, the navigation doesn't change.
![Snipaste_2023-06-02_08-20-10](https://github.com/epicmaxco/vuestic-ui/assets/85825776/01671e9c-5aa4-4575-adcc-6a834b5517cf)

**Comment by gweesin** [comment]
The team want to remove translations now, you can see #3451 for more details.

**Comment by m0ksem** [comment]
> When I switch languages, the navigation doesn't change. ![Snipaste_2023-06-02_08-20-10](https://user-images.githubusercontent.com/85825776/242755688-01671e9c-5aa4-4575-adcc-6a834b5517cf.jpg)

This is likely an issue related to `@nuxt/i18n`.

We want to remove translations, so it will be easier for us to write docs, so you might expect translation removed from docs... This is why I'll close this issue.
