### ISSUE TITLE
VaTreeView: display as cursor style maybe better  when the mouse moves over the tree node

### ISSUE THREAD

**Issue by mengqiuleo** [epicmaxco/vuestic-ui#3465]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

VaTreeView:
display as cursor style maybe better when the mouse moves over the tree node.
currently the mouse is the style of the selected text

**Describe alternatives you've considered**

**Additional context**

**Comment by codeonmoon** [comment]
@mengqiuleo - Can we also add a feature that once user clicks on Label also of the nodes it could be expanded and collapsed.
Because as of now, we need to explicitly click on the arrow always.

**Comment by m0ksem** [comment]
We can have additional prop to set whole tree-node clickable.
```
clickableArea: { type: String as PropType<'button' | 'node'> }
```

Then, if the clickable area is a node, the whole node must have `cursor: pointer`.

**Comment by mengqiuleo** [comment]
> We can have additional prop to set whole tree-node clickable.
> 
> ```
> clickableArea: { type: String as PropType<'button' | 'node'> }
> ```
> 
> Then, if the clickable area is a node, the whole node must have `cursor: pointer`.

We can add `cursor: pointer` to `va-tree-node-root`, then the whole node can have `cursor: pointer`, because class `va-tree-node-root` wrap the whole node.  And now can  removes the arrow style.

**Comment by mengqiuleo** [comment]
> @mengqiuleo - Can we also add a feature that once user clicks on Label of the nodes it could be expanded and collapsed. Because as of now, we need to explicitly click on the arrow always.

I'm not sure. I haven't tried it.  It might conflict with the selected style.  About the selected style in #3456 .  Because selecting the parent node also causes the node to collapse, maybe the user just wants to select the parent node.

**Comment by mengqiuleo** [comment]
@m0ksem I want to solve this issue.

**Comment by codeonmoon** [comment]
> @m0ksem I want to solve this issue.

@mengqiuleo - Is this issue resolved? If yes, by when we can take those changes in our project?
