### ISSUE TITLE
VaInput autosize prop doesn't work in Firefox

### ISSUE THREAD

**Issue by Strongleong** [epicmaxco/vuestic-ui#3470]
**Vuestic-ui version:** `@vuestic/nuxt` 1.0.14 (includes `vuesic-ui` 1.4.10)

**Steps to reproduce**
1) Start Firefox
2) Open official [VaInput textarea documentaion](https://ui.vuestic.dev/en/ui-elements/input#textarea)
3) Start typing inside `with autoresize` textarea

**What is the expected behavior?**
Autoresize happens

**What is the current behavior?**
Autoresize don't happens. Textareas height is kept at minimum

**Other information**
![image](https://github.com/epicmaxco/vuestic-ui/assets/17177071/a6851982-d77e-4417-8e91-882b871cce9f)

This works propely in chrome

P.S. Sorry for bad English 😅 

Tasks:
- [ ] VaInput remove resize property from text-area if autosize prop is set to `true`
- [ ] Fix autoresize prop in Firefox - when typing textarea must become bigger

**Comment by asvae** [comment]
Let's take into account firefox usage if this bug is hard to fix.

**Comment by m0ksem** [comment]
I think it is not a Firefox bug. The auto-size props means that text-area gets bigger when there are new line breaks. We must remove resize property for auto-size, because with auto-size, user should not resize text-area manually.

**Comment by Strongleong** [comment]
@m0ksem this is works as intented in chrome. My bad for not mentioning this in issue, sorry

**Comment by m0ksem** [comment]
My bad, your issue description was correct.

**Comment by asvae** [comment]
<img width="350" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/0af0841f-dd08-4ac7-9eab-99b82527e7a0">

tested in firefox, works fine for me
