### ISSUE TITLE
VaInput input-class dosen't work properly with textarea type

### ISSUE THREAD

**Issue by Strongleong** [epicmaxco/vuestic-ui#3471]
**Vuestic-ui version:** `@vuestic/nuxt` 1.0.14 (includes `vuesic-ui` 1.4.10)

**Steps to reproduce**
1) Make Nuxt3 project with `@vuestic/nuxt` module
2) Create `VaInput` component with type `textarea`
```vue
<VaInput type="textarea" label="test" />
```
3) Add `input-class="padding"` property
```vue
<VaInput type="textarea" label="test" input-class="padding" />
```
4) Create css class `padding` with style `padding: 5px;`
```css
.padding {
  padding: 5px;
}
```

**What is the expected behavior?**
Style `padding: 5px` applied normally 

**What is the current behavior?**
Style `padding: 5px` gets applied, but it got overridden by `padding` style in `.textarea` class

**Other information**
In screenshot I used `p-4` tailwindcss class, but it it doesn't matter.  Classes are applied to `textarea` element in wrong order anyway.
![image](https://github.com/epicmaxco/vuestic-ui/assets/17177071/4d414d69-0f9d-4a23-ba61-3fe3f2fff19e)

**Comment by m0ksem** [comment]
Hi, @Strongleong. Can you share your `nuxt.config.ts`. I bet you need to register modules in order:

```ts
  modules: [
    '@vuestic/nuxt',
    '@nuxtjs/color-mode',
  ],
```

**Comment by Strongleong** [comment]
Hi, @m0ksem. Thx for answering me)

Here is my `nuxt.config.ts`:

```javascript
export default defineNuxtConfig({
  ssr: false,
  modules: ['@pinia/nuxt', '@vuestic/nuxt'],
  components: [
    {
      path: '~/components',
      pathPrefix: false,
    },
  ],
  postcss: {
    plugins: {
      'tailwindcss/nesting': {},
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  telemetry: false,
  css: ['~/assets/css/main.css', 'vue-json-pretty/lib/styles.css'],
  plugins: ['@/plugins/vue-json-pretty'],
  vuestic: {
    config: {},
  },
  runtimeConfig: {
    public: {
      apiUrl: process.env.API_BASE_URL,
    },
  },
});
```

**Comment by m0ksem** [comment]
It is related to your bundler (e.g. nuxt) configuration, not UI library itself.
You need somehow inject tailwind after nuxt register vuestic component from `@vuestic/nuxt`.

I can recommend using `@nuxtjs/tailwindcss` module like we do in our docs: https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/docs/nuxt.config.ts#L80
