### ISSUE TITLE
VaTreeView collapse disable

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3485]
Sometimes we need a tree view without an ability to collapse. Actually that's the case for [our docs](https://ui.vuestic.dev/contribution/structure).

Here's how component looks like:
<img width="482" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/78da3577-45c0-4768-aa8a-1cc1f64ae09e">

Here what I'm suggesting:
<img width="485" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/3921b978-9101-4398-ad29-50b4ac2dd0fd">

Here's the API I'm imagining:

```html
<va-tree-view
  :expandable="false"
  :nodes="nodes"
>
``` 

You would only be able to use this prop at root level - which would prevent expand for all nodes.

I was thinking to allow prevent expand for specific nodes, but didn't find that useful. It's also hard to implement from design perspective:

<img width="479" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/7cb32e49-b9bd-47dc-baae-24c0a4839f1d">

@xx13 would be great to know what do you think.

**Comment by anviksuteiriy** [comment]
hey @m0ksem @asvae is there a way to identify if the parent node for selectable is clicked or checked/unchecked ?

for now i clicked on top mercedes label but rest are removed but not in disabled one, i want to select all or remove all by clicking on mercedes checkbox. any help ?

![Screenshot from 2024-11-06 09-12-37](https://github.com/user-attachments/assets/c5f4f082-3eb7-47a2-b9f1-a566efb2042d)
