### ISSUE TITLE
Use codesandbox to simplify review process

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3510]
Right now it's pretty hard to check PR for bug fix. What I'm generally doing is:
* Opening vuestic.dev, finding relevant example.
* Running local version of the app and comparing with docs version.

My idea is to instead to have an automated process that would:
* Publish experimental build for PR. (maybe as a github action in background)
* Create a codesandbox for case you're targeting (probably could be POSTed from story similarly to how we do with docs)/
* Attach link to sandbox to PR.

Why this is better:
* Developer and reviewer won't spend time on that. (they won't even need screenshot)
* It's future proof (you can double check everything in a couple of years even).
* It clearly outlines test case.

**Comment by m0ksem** [comment]
We're using Vue repl.
