### ISSUE TITLE
Feedback from scope review

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3529]
# Medium prio

These bugs it would be ideal to handle before release:

- [x] Keyboard navigation works, but I can't open select 
<img width="343" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/ce675364-8d76-4db7-b92f-cec060ed5880">

- [x] #3596
<img width="860" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/2c967207-8eb4-432c-8228-8874d125fda8">

- [x] #3597
<img width="646" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/91af5c87-9cf4-49cf-a18b-0d5303150cdc">

- [x] Navbar looks broken on mobile
<img width="440" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/fd940c55-894d-49b0-8c8f-ec9a5be4433a">

- [x] 404 page looks broken
<img width="808" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/10afa21a-4d64-4f05-b1dc-5e84035b3aca">

# Low prio

These we can handle after release - they're lower prio.

- [x] Shape is broken, was missing CSS variables hard to use. let's either fix it or remove it.
<img width="906" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/cf9ed5a5-4c9d-45ff-8a8e-6256b458bd82">

- [ ] This menu is missing on mobile. It's also not exactly sure what it does:
<img width="334" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/1db45e43-f4b5-4ddf-9f3e-224f1c88f78d">

- [x] #3592
<img width="283" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/71d85517-0db2-4acd-a3fb-a49954430e4e">

- [x] We're missing privacy policy. (compare to epicmax.co)

- [x] #3593

- [x] #3600

- [x] When you scroll down on one page, then navigate to another - page will scroll up. Should go instantly.

**Comment by m0ksem** [comment]
I'd ignore issue with colors dropdown on mobile. We don't need it on mobile, because we have this section in navbar menu.

Otherwise everything else looks fixed.
