### ISSUE TITLE
Modal events

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#353]
## Usecases
* could be used to focus user on specific part of modal

// Needs more use cases.

## Props
* `@open` and `@close` triggered when transition is complete.
* `@beforeOpen` and `@beforeClose` triggered right after transition started.
--------------
- [ ] `@open`
- [ ] `@beforeOpen`
- [ ] `@close`
- [ ] `@beforeClose`

## Refs
* [Quasar](https://quasar.dev/vue-components/dialog)
* [Element UI](https://element.eleme.io/#/en-US/component/dialog#events)

## Related
https://github.com/epicmaxco/vuestic-admin/issues/751

**Comment by grippon** [comment]
More generally, a way to focus on a va-button via code (maybe you will naturally need this)
```
<button ref="focus_me" ... >
this.$nextTick(() => this.$refs.focus_me.focus()) // will focus the button
```
but if the ref is on a `va-button`, it doesn't work.

**Comment by asvae** [comment]
@grippon good catch, thanks. Moved to another [issue](https://github.com/epicmaxco/vuestic-ui/issues/361).
