### ISSUE TITLE
Custom Content Modal does not close on outside click

### ISSUE THREAD

**Issue by Bond-Addict** [epicmaxco/vuestic-ui#3540]
**Vuestic-ui version:** 1.7.0

**Steps to reproduce**
Create a modal using the custom content modal approach. (``<template #content>``)
**What is the expected behavior?**
When you click outside the modal closes.
**What is the current behavior?**
The modal does not close.
**Other information**
You can reproduce by going to https://codesandbox.io/p/sandbox/nice-darwin-iqjx2m?file=%2Fsrc%2FApp.vue and clicking the 'Open Content Modal' Button.

**Comment by m0ksem** [comment]
Hi @Bond-Addict. You need to change `:model-value` to `v-model` in `ContentModal.vue`. Otherwise, `showModal` will always stay `true` becuae there is no listener for `@update:model-value` from `v-model`.

**Comment by m0ksem** [comment]
Will be handled in separate issue: https://github.com/epicmaxco/vuestic-ui/issues/3577
