### ISSUE TITLE
Update image for sponsors and partners section

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3544]
Change from this:
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/ebbc2716-5def-48f4-b818-87800fe3adde)

to this:
![github logos](https://github.com/epicmaxco/vuestic-ui/assets/35342240/8cb5b711-4b1f-49c3-93d2-e231ff802f36)

### In three places:
https://github.com/epicmaxco/vuestic-ui
https://github.com/epicmaxco/vuestic-admin
https://github.com/epicmaxco/epic-spinners

**Comment by zvenigorodskaia** [comment]
fix image size and margin-left please

![Image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/bd310bb8-af37-475a-bcce-e06784c22707)

**Comment by m0ksem** [comment]
> fix image size and margin-left please
> 
> ![Image](https://user-images.githubusercontent.com/35342240/249343731-bd310bb8-af37-475a-bcce-e06784c22707.png)

Please, double check and close this issue if all OK.
