### ISSUE TITLE
Update NEW label in docs for 1.7

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#3546]
### Update NEW label in docs for 1.7

![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/25a5145d-4f76-4e0c-a9d9-e191cc168701)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/7b3cbc72-d37d-49cf-8148-1275cd243f9f)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/354d02d7-7c5a-43ab-a65a-17467e0d529a)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/3fab5b1c-7a6f-456f-b9ac-056388be83c1)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/a2d4bbbd-d4ac-40fe-8908-9508d9f99673)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/6a650cb1-743e-482e-936c-bb34a31466c8)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/5d71b6e4-5369-448e-bee5-14e5b89f04d7)
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/91892e08-53f9-471a-a96c-244a8054d004)

maybe Colors Classes it is from 1.6 too?
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/3dc08d29-dd60-430e-a30f-71b52802dd95)

### 2. Change Q1 to Q2 in the title!
 https://github.com/epicmaxco/vuestic-ui/releases/tag/v1.7.0

**Comment by thesheppard** [comment]
https://github.com/epicmaxco/vuestic-ui/pull/3538 Can partly assist with this
