### ISSUE TITLE
VaInput: Clearable icon in wrong size

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#3551]
**Vuestic-ui version:** 1.7.0 (at least)

**Steps to reproduce**
Add the clearable prop in the input, write some test.
Example here from documentation.
https://codesandbox.io/p/sandbox/cool-jackson-9tw3t8

**What is the expected behavior?**
Should show the clearable icon in the correct size (like in VaSelect)

![image](https://github.com/epicmaxco/vuestic-ui/assets/46224115/60872b61-10ef-4817-a1d4-1f1eba9d96dd)

**What is the current behavior?**
Shows a clearable icon oversized 

![image](https://github.com/epicmaxco/vuestic-ui/assets/46224115/8132cb91-7b45-4029-8ec4-045be3227843)

**Comment by mrniamster** [comment]
@m0ksem  @zvenigorodskaia 

Would like to understand how to show icon dynamically ,

In the the below code i want to display "imgUrl" to #prependInner template how would i do it ? 
<VaSelect 
            label="Select step"
            @update:modelValue="(e)=>console.log(e)"
            :options="[{title:"iam a title",value:1,imgUrl:"imgurl"}]"
            text-by="title"
           value-by="value"

            >
        <template #prependInner>
        <VaAvatar :src="imgUrl" />
        </template>

        </VaSelect>
```
