### ISSUE TITLE
Loosing Vuestic-ui @types when importing useForm in NUXT 3

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3552]
**Vuestic-ui version:** 1.7.0
"@vuestic/nuxt": "^1.0.14",
**Steps to reproduce**
Before : Importing useForm
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/76185353-8882-4714-8bcd-778aeacbbb09)

After: importing useForm2
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/2ac8dc75-b90c-4638-9289-337bbe62827e)

**What is the expected behavior?**
1. There should be auto import of the composables like useForm 
2. The type should not disappear when importing useForm etc hooks.
3. auto-imported types provided by nuxt should not be  lost.
**What is the current behavior?**
Unable to use useForm, since causing difficulty in coding since the auto-imported types provided by nuxt is lost.
**Other information**
Nuxt project info:                                                             8:46:36 AM  

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      routeRules, vuestic, nitro, css, vite, postcss, app, modules, content, 
googleSignIn, runtimeConfig, devtools, plugins
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @vuestic/nuxt@1.0.14, @pinia/nuxt@0.4.11, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0
- Build Modules:    -
------------------------------

**Comment by m0ksem** [comment]
Hi, @mrniamster. Can you try to install `vuestic-ui@0.0.0-experimental-b48939178-20230630` to see if I've got your issue fixed. Also, don't forget to clean `.nuxt` cache and `node_modules/.vite/deps`.

**Comment by mrniamster** [comment]
@m0ksem  Thanks a ton! its working now ,

> Removed vuestic/nuxt  from package.json 
> npm i vuestic-ui@0.0.0-experimental-b48939178-20230630
> npx nuxi clean   (removes .nuxt .output node_modules/.vite & /.cache )

![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/583db4be-2765-4265-94ce-c5aa38266fd9)

**Comment by m0ksem** [comment]
It is going to be in 1.7.1 and next @vuestic/nuxt release. You can use experimental version for now, since it is 1.7.0 but with the fix.

**Comment by mrniamster** [comment]
@m0ksem  Urgent,

After installing the above , the buttons , none of vuestic components are loading, 
its giving below error :

![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/07a772d4-41f9-4dc0-9098-44577d689229)

**Comment by m0ksem** [comment]
> For future readers,
> 
> if After installing the above , the buttons , none of vuestic components are  not loading &  giving below warning:
> 
> ![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/07a772d4-41f9-4dc0-9098-44577d689229)
> ![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/fcdd5dbc-c334-4978-b5e3-cd49bdf32738)
> 
> Here is the fix ,
> 
> _plugins/vuestic.ts_
> ```
> import {createVuestic} from "vuestic-ui"
> export default defineNuxtPlugin((nuxtApp) => {
>     nuxtApp.vueApp.use(createVuestic())
> })
> 
> ```
> 
> _App.vue_
> `import "vuestic-ui/css";`
> 
> We can add the above guide for Nuxt here at https://ui.vuestic.dev/getting-started/nuxt
> @m0ksem 

It is because @vuestic/nuxt probably uses it own version of vuestic-ui. Try to set resolutions in package.json and make sure you have only one `vuestic-ui` in node_modules. If you have two different versions there might be bugs. Or for local development, you can just copy paste this folders...

**Comment by mrniamster** [comment]
@m0ksem  
On the same release : vuestic-ui@0.0.0-experimental-b48939178-20230630, 

Issue: finishButtonHidden on Stepper component is not  hiding ,
https://ui.vuestic.dev/ui-elements/stepper

Please check the below image.

![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/20a8db29-4f10-4e48-b51c-3f4eff2c9ada)

**Comment by mrniamster** [comment]
Thanks @m0ksem  💜
