### ISSUE TITLE
@input event is not supported by VaInput

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3558]
**Vuestic-ui version:** 1.7.0

**Steps to reproduce**
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/e4785165-1532-4eeb-8ff9-11c01746efc2)

**What is the expected behavior?**
```@input``` should be working
**What is the current behavior?**
```@input``` event is not working 
**Other information**

**Comment by m0ksem** [comment]
You can use @update:modelValue.
