### ISSUE TITLE
Stepper. Add additional functionality to slot="controls"

### ISSUE THREAD

**Issue by EugenGedroyc** [epicmaxco/vuestic-ui#3568]
**Is your feature request related to a problem? Please describe.**

If use slot="controls" you have not the functionality of props(nextDisabled, currentStep, etc) and have not functionality with the button 'finish'. 

**Describe the solution you'd like**

For example if I use custom button 'Next' I need to change it to 'Finish' in last step or I need to use the prop 'finishButtonHidden'.
In general, bind all current functionality to custom buttons

**Comment by m0ksem** [comment]
@EugenGedroyc, would you be able to make a review for #3573? Maybe I missed something.

**Comment by EugenGedroyc** [comment]
@m0ksem Yes, I'll review this now

**Comment by EugenGedroyc** [comment]
After review the code, I didn't see any issues except for:
- For some reason, the single quotes are being changed to double quotes in the <script> section.
- After running Prettier, it would have been better to make a separate commit (for easy review).
I decided to add a demo with the controls slot in VaStepper.demo.vue, and I have to disable Prettier for that.

**Comment by EugenGedroyc** [comment]
not the Prettier. it's ESLint

**Comment by m0ksem** [comment]
> After review the code, I didn't see any issues except for:
> 
> * For some reason, the single quotes are being changed to double quotes in the <script> section.
> * After running Prettier, it would have been better to make a separate commit (for easy review).
>   I decided to add a demo with the controls slot in VaStepper.demo.vue, and I have to disable Prettier for that.

The most important that it contains changes you need.

**Comment by EugenGedroyc** [comment]
@m0ksem  I'm sorry, but i review functional only now. And it's not working:	
	
https://www.awesomescreenshot.com/video/18946183?key=d097bcb6fcafc83e88a33886cd60751d

https://github.com/EugenGedroyc/vuestic-ui-blizzart/commit/71d840ed8878f8c2a2d72066c07f4318e1c48620

Previous commit:
	
commit 85bf5996efbf750a4435fd7d4f2722a50f0ef63e (HEAD -> feat/stepper-demo-controls, moksem/fix#3568/provide-more-things-to-stepper-slot, fix#3568/provide-more-things-to-stepper-slot)
Author: Maksim Nedoshev <m0ksem1337@gmail.com>
Date:   Thu Jul 6 16:56:00 2023 +0300

    fix(#3560): stepper hide-disabled-button prop

**Comment by m0ksem** [comment]
There are should be available more slot params in 1.7.1.

**Comment by m0ksem** [comment]
There are should be available more slot params in 1.7.1.

**Comment by m0ksem** [comment]
There are should be available more slot params in 1.7.1.
