### ISSUE TITLE
Proper upgrade steps

### ISSUE THREAD

**Issue by Bond-Addict** [epicmaxco/vuestic-ui#3571]
### Discussed in https://github.com/epicmaxco/vuestic-ui/discussions/3569

<div type='discussions-op-text'>

<sup>Originally posted by **Bond-Addict** July  5, 2023</sup>
Can someone explain the specific steps to update? 
I tried recently and mutiple components stopper functioning correctly. I suspect its because I upgraded incorrectly which could include incompatible versions for dependencies.

current package.json

```
{
	"name": "MyApp.Web",
	"version": "0.0.0",
	"private": true,
	"scripts": {
		"debug": "vite --mode debug",
		"dev": "vite --mode dev",
		"build": "vue-tsc --noEmit && vite build",
		"build-dev": "vite build --mode dev --base=/webapps/maintenance/",
		"preview": "vite preview",
		"lint": "eslint . --fix --ignore-path .gitignore"
	},
	"dependencies": {
		"@mdi/font": "7.0.96",
		"@vuelidate/core": "^2.0.2",
		"@vuelidate/validators": "^2.0.2",
		"@vuestic/tailwind": "^0.1.3",
		"axios": "^1.3.4",
		"axios-retry": "^3.5.0",
		"bootstrap": "^5.2.3",
		"core-js": "^3.8.3",
		"pinia": "^2.0.23",
		"pinia-plugin-persistedstate": "^3.1.0",
		"roboto-fontface": "*",
		"vite-plugin-rewrite-all": "^1.0.1",
		"vue": "^3.2.13",
		"vue-cli-plugin-vuestic-ui": "^1.0.11",
		"vue-cookies": "^1.8.3",
		"vue-router": "^4.0.0",
		"vuestic-ui": "^1.6.4",
		"webfontloader": "^1.0.0"
	},
	"devDependencies": {
		"@types/bootstrap": "^5.2.6",
		"@types/node": "^18.15.5",
		"@types/webfontloader": "^1.6.35",
		"@vitejs/plugin-vue": "^3.0.3",
		"sass": "^1.59.3",
		"typescript": "^4.9.5",
		"vite": "^3.2.5",
		"vue-tsc": "^1.0.9"
	}
}
```

TIA!</div>

After attempting to upgrade my toast no longer work. 

I have a wrapper service that I call (successful before upgrade).

I use it like:

``notify('Save successful.', 'success');``

my wrapper service:

```
import { useToast } from 'vuestic-ui/web-components';

const { init } = useToast();

export function notify(message: string, color: string, duration: number = 5000) {
	init({ message, color, duration });
}
```

Error:
```
Uncaught (in promise) Error: Vuestic cache plugin is not registered!
    at useCache (useCache.ts:8:11)
    at useColors (useColors.ts:121:17)
    at Object.setup (VaToast.vue:89:26)
    at customSetup (createProxyComponent.ts:78:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7265:29)
    at setupComponent (runtime-core.esm-bundler.js:7220:11)
    at mountComponent (runtime-core.esm-bundler.js:5542:13)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
```

**Comment by Bond-Addict** [comment]
Just for extra research purpose, I did try and use the toast exactly how its shown in the docs and the same issue appears. It doesn't seem to be related to my wrapper service.

**Comment by m0ksem** [comment]
Actually, you musn't use `useToast` outside of setup function context. 

```ts
const useMyApi = () => {
   useToast // can be used in composables or setup function
}
```

```
<script setup>

useMyApi()
```

**Comment by Bond-Addict** [comment]
> Actually, you musn't use `useToast` outside of setup function context.
> 
> ```ts
> const useMyApi = () => {
>    useToast // can be used in composables or setup function
> }
> ```
> 
> ```
> <script setup>
> 
> useMyApi()
> ```

This should be correct right?

Composable:
```
import { useToast } from 'vuestic-ui/web-components';

const { init } = useToast();

export const useNotiService = () => {
	function notify(message: string, color: string, duration: number = 5000) {
		init({ message, color, duration });
	}

	return { notify };
};
```

Used in function:
```

<script setup lang='ts'>
const { notify } = useNotiService();

onMounted(() => {
    notify('This is successful', 'success');
});
</script>
```

If so, I still receive the same cache error in the console and the toast still doesn't work.

**Comment by m0ksem** [comment]
This is correct one.

```vue
import { useToast } from 'vuestic-ui/web-components';

export const useNotiService = () => {
        const { init } = useToast();

	function notify(message: string, color: string, duration: number = 5000) {
		init({ message, color, duration });
	}

	return { notify };
};
```

**Comment by m0ksem** [comment]
What vue makes is 

```
setSetupContext(context)
⬇️
setup()  ➡️  useNotiService()  ➡️ useToast()
⬇️
setSetupContext(null)
```

If you use `useToast` not in setup() function chain, context will not be provided.

This is wrong:

```
const {init} = useToast() // Not context yet

setSetupContext(context)
⬇️
setup()  ➡️  useNotiService()  ➡️ init() // throws error
⬇️
setSetupContext(null)
```

**Comment by Bond-Addict** [comment]
> This is correct one.
> 
> ```
> import { useToast } from 'vuestic-ui/web-components';
> 
> export const useNotiService = () => {
>         const { init } = useToast();
> 
> 	function notify(message: string, color: string, duration: number = 5000) {
> 		init({ message, color, duration });
> 	}
> 
> 	return { notify };
> };
> ```

Ah, I guess I didnt understand the setup context part. 

This is now my current code, and I still get the cache message.

```
import { useToast } from 'vuestic-ui/web-components';

export const useNotiService = () => {
	const { init } = useToast();

	function notify(message: string, color: string, duration: number = 5000) {
		init({ message, color, duration });
	}

	return { notify };
};
```

**Comment by m0ksem** [comment]
> > This is correct one.
> > ```
> > import { useToast } from 'vuestic-ui/web-components';
> > 
> > export const useNotiService = () => {
> >         const { init } = useToast();
> > 
> > 	function notify(message: string, color: string, duration: number = 5000) {
> > 		init({ message, color, duration });
> > 	}
> > 
> > 	return { notify };
> > };
> > ```
> 
> Ah, I guess I didnt understand the setup context part.
> 
> This is now my current code, and I still get the cache message.
> 
> ```
> import { useToast } from 'vuestic-ui/web-components';
> 
> export const useNotiService = () => {
> 	const { init } = useToast();
> 
> 	function notify(message: string, color: string, duration: number = 5000) {
> 		init({ message, color, duration });
> 	}
> 
> 	return { notify };
> };
> ```

Change `import { useToast } from 'vuestic-ui/web-components';`

to `import { useToast } from 'vuestic-ui';`

And then you must use `useNotiService` in setup context.

I also made a PR (https://github.com/epicmaxco/vuestic-ui/pull/3572) so useToast can be used outside of setup context.

**Comment by Bond-Addict** [comment]
@m0ksem thanks! Changing that import did it!
