### ISSUE TITLE
Handle click outside with floating dropdown

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3577]
Right now floating drop-down teleports Dom elements to the body.

```
body
  .va-modal
  .va-dropdown
```

`useClickOutside` must handle `.va-dropdown` as if it inside .va-modal actually. 

Possible solution:
add data attribute to floating elements (`data-va-teleported-[hash]`) and it's actual parent (`data-va-teleport-from-[hash]`). Then click outside can find where actually drop-down must be rendered, without teleport.
You can find useUuid or something like this to get component instance uuid.

**Comment by Bond-Addict** [comment]
@m0ksem when should this fix be available?

Thanks

**Comment by m0ksem** [comment]
> @m0ksem when should this fix be available?
> 
> Thanks

Should be available now in 1.7.1

**Comment by Bond-Addict** [comment]
@m0ksem I just tested and everything looks great! The auto close for the date input even works!

Thanks for the super quick turn around! 😄
