### ISSUE TITLE
VaRadio | Not rendering in new release 1.7.1

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3582]
**Vuestic-ui version:** 1.7.1

**Steps to reproduce**
Installing the latest version "vuestic-ui": "^1.7.1" , varadio are not displayed 

**What is the expected behavior?**
Varadio should display radio buttons

**What is the current behavior?**
- Not displaying on DOM 
 - Also failing on Vuestic UI docs page
https://ui.vuestic.dev/ui-elements/radio

![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/f31c19fe-ca4b-48ad-8c65-24696ebefe98)

**Other information**
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.11.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      vue, routeRules, nitro, css, vite, postcss, app, modules, content, googleSignIn, runtimeConfig, 
devtools, plugins
- Runtime Modules:  nuxt-vue3-google-signin@0.0.8, @pinia/nuxt@0.4.11, @nuxt/content@2.7.0, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0
- Build Modules:    -
------------------------------

**Comment by mrniamster** [comment]
@m0ksem

**Comment by m0ksem** [comment]
Hi, @mrniamster. VaRadio now accepts `options` prop instead of `option`. I didn't noticed this breaking change, but it needed for correct validation handling.

**Comment by mrniamster** [comment]
Hi @m0ksem , Thanks for letting know about this, but the problem due to options prop is how to now do a v-for in on-going loop 
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/20c9c87b-01b8-4260-a806-4fd08f2b4af3)

**Comment by m0ksem** [comment]
```
:options="[createLink.capaingType.allIds]"
```

I'll add `option` prop back, but recommend using `options`.

**Comment by mrniamster** [comment]
Thanks m0ksem, we have a release  today   which version to update to ..

**Comment by m0ksem** [comment]
> Thanks m0ksem, we have a release today which version to update to ..
> 
> Tried what you mentioned, but the v-model is not updating it returning "undefined"
> 
> > Vue dev tool
> > ![image](https://user-images.githubusercontent.com/52563039/251979898-e65bcf2b-a75a-47ee-ac92-ebdfdbb11d93.png)
> 
> given, createLink.capaingType.allIds = ['option1','op2','op3']
> 
> ![image](https://user-images.githubusercontent.com/52563039/251977964-396227d1-b0d4-4c7d-9a8d-46cd6db82ca2.png)

I'm working on fix for this. 

:option will work the same way it worked before
:options will work as now and render few radio buttons inline.

Wondering what to do if there is no option. The modelValue is going to be boolean, I guess. Probably will do a new release in few hours.

**Comment by mrniamster** [comment]
> :options will work as now and render few radio buttons inline.
This is correct,

Just checked how quasar provides the options,
https://quasar.dev/vue-components/radio
Ideally should have kept as single parent , & let the user explicitly render the element using v-for.

modelValue for radios shouldn't be boolean,it should return the label (string),  checkbox should be the one returning the boolean instead 
<img width="1432" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/52563039/3e281693-d7e5-4e7c-b82f-ffdd83b19f7a">


<img width="641" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/52563039/c51822c3-ef89-4522-a195-241700845e8c">

<img width="713" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/52563039/f0dab549-6586-43dd-9d3e-90ff48507a5c">


I personally like this UI framework and would love to contribute more <3

**Comment by m0ksem** [comment]
> I personally like this UI framework and would love to contribute more <3

Glad to hear that!

Please review `vuestic-ui@1.7.2-next-8bc541aa3-20230708` version with VaRadio fixes. 
Here you can find new updated docs: https://ui-develop.vuestic.dev/ui-elements/radio

I'm not really able to build something with Vuestic at this moment, so I'd like to hear a lot of feedback from people who actually use it every day.

**Comment by mrniamster** [comment]
Hello @m0ksem  Thanks for the update, but now the problem is unable to empty the label previously it was happning when provided empty 
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/cafe1421-bde0-49c3-b9f2-4eb789d39d9d)

**Comment by m0ksem** [comment]
> Hello @m0ksem Thanks for the update, but now the problem is unable to empty the label previously it was happning when provided empty ![image](https://user-images.githubusercontent.com/52563039/252139602-cafe1421-bde0-49c3-b9f2-4eb789d39d9d.png)

You should be able to do it with `:option="{ value: ctype }"`. But I'll move label prop back.

**Comment by mrniamster** [comment]
@m0ksem  Few bugs found continuing above example ,

` <VaRadio   :option="{value:ctype,text:''}" name="type"
                                    left-label
                                    :model-value="state.s2u.type"
                                    @change="(e)=>console.log(e)"
                                      />`

In above code the value is not set after using modevalue

` <VaRadio   :option="{value:ctype,text:''}" name="type"
                                    left-label
                                    v-model="state.s2u.type"
                                    @change="(e)=>console.log(e)"
                                      />`
In above the  label do gets empty, but te v-model saves it as object instead of taking the "value" instead.

I would strongly recommend just have an option and label, and make it less complex

**Comment by m0ksem** [comment]
We have the the system across components. If you need value, instead of object, you can use `value-by` prop.

**Comment by mrniamster** [comment]
Got to know late! Thanks  a ton! @m0ksem
