### ISSUE TITLE
Return to current pagination number?

### ISSUE THREAD

**Issue by phpricardo** [epicmaxco/vuestic-ui#359]
I'm trying to make a button that when returning to the form (edit) it goes back to the page number where that record was.

I tried to manipulate this.$refs.table.inputPage() but failed.

Someone could help me with this, as I have a few days with this problem.

this is my code:
https://gist.github.com/phpricardo/5734d1dd161da12f992e7113a371f025

If you need any more details just talk please.

**Comment by asvae** [comment]
Hey.

So user opens a form
Then changes page in table
Then presses some "Show in Table" button on form
Then table is expected to show that page, but it doesn't?

Smaller repro helps immensely.

**Comment by phpricardo** [comment]
@asvae That.
If you are on PAGE 3 and enter a record, for example edit, when you return (button on the back button) it will return to PAGE 3.

This has to be on the back button.

**Comment by asvae** [comment]
Mmm.
Still struggling to understand.
Maybe a gif if that's possible (emaling me also works).

**Comment by phpricardo** [comment]
Hey, I'm create a gif. 
https://giphy.com/gifs/Yo2LZrFAkU4gkNtvPt
