### ISSUE TITLE
Accordion & Select -  Text not displaying in dark theme

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3604]
**Vuestic-ui version:** 1.7.2

**Steps to reproduce**
https://ui.vuestic.dev/ui-elements/accordion
**What is the expected behavior?**
Text not displaying in dark theme

**What is the current behavior?**
Text should show white!
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/fd33a4ad-796d-4095-9452-1e359ab32007)
**Other information**

**Comment by mrniamster** [comment]
@m0ksem  

Similar issue for select - When selected, List Dialog is showing perfect.
<img width="424" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/52563039/5647935d-0104-4a83-8af7-75d715aa6837">

**Comment by xiongmao86** [comment]
Hi, @mrniamster, are you specifying `Searchable` example of `Select`? I checked every item on `v1.7.4` but everything seems to be fine, and I also checked `Searchable` example in `v1.7.2` but I didn't see anything special. Can you point out specifically where is wrong in the `Select` component?

**Comment by m0ksem** [comment]
This is 100% gonna be fixed in 1.8.0 after new inputs design is made. (see https://github.com/epicmaxco/vuestic-ui/pull/3642)
