### ISSUE TITLE
VaAvatarGroup  | Options not rendering src

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3611]
**Vuestic-ui version:** 1.7.2

**Steps to reproduce**
As shown in https://ui.vuestic.dev/ui-elements/avatar#grouped

**What is the expected behavior?**
Src should be shown, or value-by prop should be supported when :options are used.
**What is the current behavior?**
Passing options props with array of object having src inside it blue avatar renders!
![image](https://github.com/epicmaxco/vuestic-ui/assets/52563039/b849ad52-744e-4b8c-8dd8-3906bb122cb3)

**Other information**
```
<VaAvatarGroup
        :value-by="'src'"
        :options="Array.from(Array(10).keys()).map((e) => new Object({ src: `https://randomuser.me/api/portraits/women/${e}` }))"
 />

```

**Comment by m0ksem** [comment]
It works for me. In your example, you should add `.jpg` to the end of the link.
``https://randomuser.me/api/portraits/women/${e}``
``https://randomuser.me/api/portraits/women/${e}.jpg``

https://codesandbox.io/p/sandbox/prod-wildflower-x4rjdh?file=/src/App.vue:14,1
