### ISSUE TITLE
va-input label's height is narrow

### ISSUE THREAD

**Issue by varhuman** [epicmaxco/vuestic-ui#3616]
**Vuestic-ui version:** 1.7.2

**Steps to reproduce** nothing

**What is the expected behavior?** va-input label's height is narrow,the label is display incompletely, it even Appear on the website

**What is the current behavior?**

**Other information** chrome, 4k , windows scaling is 175%

![image](https://github.com/epicmaxco/vuestic-ui/assets/53512871/c73a3372-8bf3-4ae4-b99a-372b943ce5b4)
![image](https://github.com/epicmaxco/vuestic-ui/assets/53512871/0a5b1f18-47c6-4d58-a17d-054cc8185e38)

**Comment by varhuman** [comment]
I can fix it by change va-input-wrapper__Label's height to 20px, but I think it should be flexible heigh
![屏幕截图 2023-07-16 190249](https://github.com/epicmaxco/vuestic-ui/assets/53512871/da6dbd13-08e8-4b52-9987-7d55d4df4991)

**Comment by varhuman** [comment]
I found out that the reason is because I changed the font size of chrome
![image](https://github.com/epicmaxco/vuestic-ui/assets/53512871/7982752a-82e8-41d2-be22-51372e807ca2)

**Comment by m0ksem** [comment]
Hi. We're working on new input design with labels outside of input, so labels can be any height. Thanks for the report.

**Comment by asvae** [comment]
Seems fixed (would be in 1.8.0)

![Image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/b722c7c8-bf1c-40a7-901d-e09a1e4a11a2)
