### ISSUE TITLE
Let's improve discord server

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3617]
There are some recommendations for community servers, we can probably go through these.

<img width="1358" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/c1364f7a-4945-4b62-9b51-38659f3f3bd6">

They also have insights on server state, which is probably something we want to rely on:

<img width="1180" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/4b3cf1f8-ec9f-4cc6-8dc3-33fb1f78c3e3">

**Comment by m0ksem** [comment]
I think we are good enough for now, so we can close it.
