### ISSUE TITLE
create-vue error in mac

### ISSUE THREAD

**Issue by zepinos** [epicmaxco/vuestic-ui#3643]
**Vuestic-ui version:** 1.7.3

**Steps to reproduce**

execute "npm create vuestic@latest" -> project name -> choose Create-vue -> all default -> freeze "Creating Vue 3 project in /Users/***/vuestic-app"

**What is the expected behavior?**

**What is the current behavior?**

I'm tring to create a Create-vue with "npm create vuestic@latest" command, it will not be created and freeze in Mac Ventura 13.5 and npm 6.14.17. Vuestic Admin is generated normally and normal in Windows.

**Other information**

**Comment by m0ksem** [comment]
Does `npm create vue@latest` works for you?

**Comment by zepinos** [comment]
> Does `npm create vue@latest` works for you?

https://github.com/epicmaxco/vuestic-ui/assets/6926839/6b64e06c-12d6-4737-98e4-ff636664d1ac

**Comment by asvae** [comment]
@zepinos 

hey, it's `npm create vue@latest` not `npm create vuestic@latest`. :)

**Comment by m0ksem** [comment]
I'm not able to reproduce it. What it does is basically calling `npm create vue`. I'm not able to find issue in other package without correct reproduction.
