### ISSUE TITLE
Warning about va-date-input "scroll-blocking 'touchstart' event"

### ISSUE THREAD

**Issue by tassin-gauthier** [epicmaxco/vuestic-ui#3661]
**Vuestic-ui version:** 1.7.4

**Steps to reproduce**

- Use the va-date-input component and open the app with google chrome
- click on the datepicker input to open it

**What is the expected behavior?**

Getting no warning in the console

**What is the current behavior?**

I have a warning in the console, displayed 3 times : 
"[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952". Each time the datepicker is opened, this thing is happening

**Comment by xiongmao86** [comment]
Is this issue going to be solved by redesign of input in `v1.8.0` (#3642)?

**Comment by m0ksem** [comment]
> Is this issue going to be solved by redesign of input in `v1.8.0` (#3642)?

Hi. Nope. It is something related Dropdown, not DateInput or Select.

**Comment by xiongmao86** [comment]
The `yarn serve:book` is taken out, so I try storybook to reproduce the issue.  I opened storybook's `VaDateInput` item, and didn't see the specific warning in chrome when I clicked `date-picker`. 

Is `VaDateInput`'s standard output redirected in storybook?

**Comment by m0ksem** [comment]
> The `yarn serve:book` is taken out, so I try storybook to reproduce the issue. I opened storybook's `VaDateInput` item, and didn't see the specific warning in chrome when I clicked `date-picker`.
> 
> Is `VaDateInput`'s standard error output redirected in storybook?

Nope. I can't see this in VaDateInput docs.

@tassin-gauthier, are you sure this issue exists in version 1.7.4? I do remember this issue existed, but we might fix it in 1.7.0 with VaDropdown migration to floating ui.
