### ISSUE TITLE
VaDropdown: Dropdown ignores page structure

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3662]
**Vuestic-ui version:** 1.7.1

My guess would be is that we changed default behaviour for location. Dropdown is in body, so overflow: hidden won't make a difference.

Notice change was introduced in 1.7.1.

We have a couple of broken examples (but please check other places and other examples):

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/9fae3fdc-e156-482b-85da-f9e2ac30d6fa)

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/ff73ddc9-a5a6-4c2d-9ea7-d931edd0f673)

**Comment by Roman4437** [comment]
Want to work on it
