### ISSUE TITLE
VaSelect/VaDateInput: Wrong autoscroll when rendering dropdown for first time

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#3669]
**Vuestic-ui version:** 1.7.x

**Steps to reproduce**
1 - Add a VaSelect with searchable property true or a VaDateInput in a page that has enough scroll to have to scroll to reach those elements. 
2 - Click to open the select or the date picker

**What is the expected behavior?**
The scroll stays where it is

**What is the current behavior?**
The scroll jump in what seems to be some issue related to autofocusing + positioning happening at the same time

**Other information**
Seems that in the case of VaSelect only happens when is searchable, which is what makes me think it's related to the fact we autofocus on the searchbox.

Also only happens the first time you open a given component, when you already have done it at least once, the scroll jump doesn't happen anymore.

Here is a code sandbox where you can see the the effect:
https://codesandbox.io/p/sandbox/vuestic-scroll-bug-gh4n5m

In version 1.6.6 doesn't happen this:
https://codesandbox.io/p/sandbox/vuestic-scroll-bug-forked-xrs2xt

**Comment by asvae** [comment]
Not seeing it's being fixed. Let's have some sort of gif before/after.
