### ISSUE TITLE
va-modal prevent closing on "OK" click if noDismiss 

### ISSUE THREAD

**Issue by Bond-Addict** [epicmaxco/vuestic-ui#3690]
**Vuestic-ui version:** 1.7.4

**Steps to reproduce**
https://codesandbox.io/p/sandbox/suspicious-sammet-f2l3kz?file=%2Fsrc%2Fviews%2FStepper.vue%3A1%2C1
**What is the expected behavior?**
If you set noDismiss the modal will not close unless the v-model is updated manually.
noDismiss isnt what I actually wanted to use, but I wanted to test if that would work as intended. 
I should be able to only close the modal when I manually set showModal to false.
**What is the current behavior?**
The modal closes automatically. This causes and issue if you want to ensure a form in the modal is valid before submitting as it closes the modal and doesnt allow you correct form errors and resubmit.

I think I recall there being this issue which had something to with a close on click feature so I think this might be a regression.

**Comment by m0ksem** [comment]
You should be able to do something like this:

```html
<va-modal :model-value="doShow" @update:modelValue="form.validate() && doShow = false" />
```

**Comment by m0ksem** [comment]
> Is this a workaround or is this functioning as intended? This was working perfectly until very recently

It is a workaround. Definitely bug if it was working recently.

**Comment by m0ksem** [comment]
I dig into this issue and `noDismiss` actually should disable closing modal with esc button and clicking on overlay.

You can use [@before-close event ](https://ui.vuestic.dev/ui-elements/modal#before-close) to prevent closing if modal is not valid.

**Comment by m0ksem** [comment]
Maybe we need before-ok and before-cancel events which work the same way as before-close in this case.
