### ISSUE TITLE
Hover component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#37]
# Description
Wrapper, which provides an interface for handling hover state for any component.

# Docs
- [ ] Do after [docs boilerplate](#17) is done.

# Props
- [ ] `value: Boolean` - v-model (if provided - component becomes stateless)
- [ ] `disabled: Boolean`

# Slots
- [ ] `default` - should pass down hover (`v-slot:default="{ hover }"`)

# Details
- [ ] Should not create a wrapper element (such as parent div).

# Design
- [ ] Present to @xx13 after finishing.

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/hover)

**Comment by asvae** [comment]
I removed timeouts and added some details
