### ISSUE TITLE
Rework roles

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3723]
I have the following suggestions regarding roles display:
* Hide founder. It doesn't really matter who's the founder.
* Hide `epicmax team`. Epicmax team should also get label of `contributor`. The only epicmax-exclusive thing should be maybe a private in-company chat.

So in total we should have 3 groups:
* core team
* contributor
* online

Current state:
<img width="917" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/fae5accd-fcbd-4d0a-8cb4-49d32bca256d">

<img width="300" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/e97b80b1-f39e-440d-b0d3-064db3bef7fe">

**Comment by m0ksem** [comment]
It's done.
