### ISSUE TITLE
va-input and v-model update has not the same behavior every time

### ISSUE THREAD

**Issue by tassin-gauthier** [epicmaxco/vuestic-ui#3726]
**Vuestic-ui version:** 1.7.5

I want a pagination system with "smart" input. In this example, let's suppose that the user will type number only.
If a value > max page is entered by the user, the input must change the value by the max page INSTANTLY.

after some research, I made this :
```html
<va-input
  :model-value="currentTablePage"
  @update:modelValue="onUpdateCurrentTablePage($event)"
/>
```
```ts
onUpdateCurrentTablePage(inputValue: any): void {
  let valueToApply = parseInt(inputValue);
  if (valueToApply > this.totalTablePages) {
    valueToApply = this.totalTablePages;
  }
  this.currentTablePage = valueToApply;
}
```

And this is working... only the first time the user is entering a wrong value. 

Let's say the max page is 10. If the user type "11", **the value will instantly change to 10 even if he didn't unfocus, which is the expected behavior**. But if he type another digit like 3, so he typed "103", the value doesn't change anymore. **It change only if the user unfocus the input.**

In fact, I can reproduce this with a simple input : 
```html
<input
  :value="currentTablePage"
  @input="onUpdateCurrentTablePage($event)"
/>
```
```ts
onUpdateCurrentTablePage(inputValue: any): void {
  let valueToApply = parseInt(inputValue.target.value);
  if (valueToApply > this.totalTablePages) {
    valueToApply = this.totalTablePages;
  }
  this.currentTablePage = valueToApply;
}
```
this thing does the exact same result.

The thing is, with a raw input, I can fix this problem by doing this : 

```html
<input id="my-input" @input="onUpdateCurrentTablePage($event)" />
```
```ts
onUpdateCurrentTablePage(inputValue: any): void {
  let valueToApply = parseInt(inputValue.target.value);
  if (valueToApply > this.totalTablePages) {
    valueToApply = this.totalTablePages;
  }
  document.getElementById("my-input").value = valueToApply;
}
```

The problem is I can't do that with vuestic input because the `@input` event doesn't exist. `@update:modelValue` event exists, but in this case I don't want to bind a modelValue, because I want to set the input value directly into the HTML element.

**Comment by asvae** [comment]
Hey, interesting quesion.

The simplest solution for us would be probably to expose input event.

More robust solution I see could be either different mode of operation (instant change) or perhaps some trickery with cleave.js.

**Comment by asvae** [comment]
@m0ksem maybe you have an opinion here?

**Comment by m0ksem** [comment]
> @m0ksem maybe you have an opinion here?

Looks like we just need to pass `value` attribute to input. I thought Vue does it automatically. We also have issue with content and default slot, so it is impossible to pass custom input in VaInput since some version... Exposing events seems useful too. How about making 1.7.6 before 1.8.0?

**Comment by asvae** [comment]
@m0ksem that would be tight, but let's give it a try.

We can actually leave 1.6 branch hang for a bit.
