### ISSUE TITLE
a11y: va-counter

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3742]
Input must have aria-live="polite" if counter is not disabled.

Increase and decrease buttons must have aria-labels, so screen readers can read button name.

**Comment by xiongmao86** [comment]
@m0ksem, can I take a stab of this?

**Comment by m0ksem** [comment]
> @m0ksem, can I take a stab of this?

Hi. I think I have done it already in my PR with input redesign. Thanks!

**Comment by xiongmao86** [comment]
Ok, thanks for reaching back.
