### ISSUE TITLE
Vuestic x Nuxt 3.7 - Not coming out of terminal – stuck in npm install 

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3746]
**Vuestic-ui version:** 
 "@vuestic/nuxt": "^1.0.14",
 
**Steps to reproduce**
Removing "@vuestic/nuxt" from modules in nuxt.config.ts fixes the issue

https://stackblitz.com/edit/github-khexbq?file=nuxt.config.ts,package.json

**What is the expected behavior?**
Should be working with NUXT 3.7, and able to install .

**What is the current behavior?**
Stuck in installing dependencies,
<img width="667" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/52563039/db6b5517-5f66-4bd2-8ad8-cf5581a3965c">

**Other information**
Previously reported: https://github.com/nuxt/nuxt/issues/22844

**Comment by mrniamster** [comment]
it was working well in nuxt 3.5.2 release && same "@vuestic/nuxt": "^1.0.14",

**Comment by m0ksem** [comment]
Hi, @mrniamster. Thanks for report. Can you check if `@vuestic/nuxt@1.0.15-pre-release` version works great?
