### ISSUE TITLE
Fix build label in readme

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3758]
**Vuestic-ui version:** 1.7.6

We should either remove or fix build label - it's giving bad impression (and build is fine).

Might be related to #3668 

<img width="512" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/df67cf32-86b2-49bc-a2d5-00e7b0074ed7">

**Comment by m0ksem** [comment]
Fixed :)
<img width="479" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/5dbf3a8a-a0fa-4dde-b6b5-002a6cf00480">
