### ISSUE TITLE
Checkbox label doesn't have pointer cursor

### ISSUE THREAD

**Issue by KazimirPodolski** [epicmaxco/vuestic-ui#3785]
**Vuestic-ui version:** 1.7.6

**Steps to reproduce**
1. Open https://ui.vuestic.dev/ui-elements/checkbox
2. Point to a label

**What is the expected behavior?**
Pointer cursor like everywhere else (e.g. va-radio or other UI frameworks)

**What is the current behavior?**
Default cursor

**Other information**

[recording-2023-09-01_17.54.09.webm](https://github.com/epicmaxco/vuestic-ui/assets/6647438/d3b1fdab-34f8-4eab-83ac-a3f032db6f70)

**Comment by Udaay** [comment]
Have raised the PR for the same please have a look suggest if any change is required.
#3787
