### ISSUE TITLE
Accordion v-model not effective

### ISSUE THREAD

**Issue by iynehz** [epicmaxco/vuestic-ui#3789]
**Vuestic-ui version:** 1.7.6

**Steps to reproduce**

Take an accordion example like the default one https://ui.vuestic.dev/ui-elements/accordion#default , change that “value” array from `[false, false, false]` to like `[true, false, false]`, restart server and see if the first collapse expands or not.

**What is the expected behavior?**

A default true value in accordion's v-model array should expand the corresponding collapse on page load.

**What is the current behavior?**

A true value in accordion's v-model array is not effective.

**Other information**

version 1.7.5 is good. So it breaks since 1.7.6.

**Comment by m0ksem** [comment]
Must be fixed in 1.7.7 and 1.7.8
