### ISSUE TITLE
Add va- class to input messages ul element

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3792]
<img width="488" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/d567ee16-7d9a-4cb0-bf1e-afcad6c69ce7">
<img width="352" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/5f958a29-5070-4aac-b787-23ad023c7183">
<img width="91" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/d50bd9f1-1b6b-44f9-a1ca-76b3a06cbb37">

**Comment by Udaay** [comment]
![Screenshot 2023-09-05 at 11 12 25 AM](https://github.com/epicmaxco/vuestic-ui/assets/26655564/18da782f-7a9c-40ca-ba81-076cd2b1da67)
In this case `list-style: none` is being applied properly.

**Comment by m0ksem** [comment]
Sorry! This issue occurs when you use VaContent, which applies typography styles globally. Because of it, we have typography styles applied to ul (see https://ui.vuestic.dev/styles/typography#list-styles)
