### ISSUE TITLE
Modal component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#38]
# Docs
 - [ ] Expecting docs to be fully implemented in context of this task.

## Mixins
- [x] Stateful
- [x] Context

# Props
- [x] `no-dismiss` - shortcut for `no-outside-dismiss` + `no-esc-dismiss`
- [x] `overlay` Boolean - enables/disables overlay behind modal, true by default
- [x] `overlay-opacity` Number - set overlay opacity (0-1)
- [x] `z-index` sets z-index of modal (also use css variable for default z-index, which would be used as fallback if prop is not defined).

Following points are relatively complex and not too high priority, so you might want to attempt them, then drop/move to another issue if it seems to take too much time:
- [ ] `draggable` boolean enables/disables drag on modal. Ideally we want drag to work via `position` sync (emit). If that doesn't work for some reason - you can keep state in modal.
- [ ] `position` should be sync prop + accept the following format: `{[top|left|right|bottom]?: number|string}`. The idea is that it would allow it to be used with `draggable`, i.e.:

```vue
<va-modal draggable :position.sync="currentPosition"/>
```

Here's some cases where this could be useful:
* user clicks on button, that creates multiple modals (widgets) on the screen.
* user can reposition modals and we can save position in local storage or on server, 

# Slots
- [x] `default` - custom content
- [x] `header` - custom header
- [x] `footer` - custom footer

# Events 
- [x] `click-outside` emitted when backdrop clicked
- [x] `input` emitted when modal state changes

# Methods
- [x] `show` opens modal
- [x] `hide` closes modal
- [x] `toggle` toggles modal state

Notice that or stateless modal these only emit @input, not change modal state. 

# Design
- [ ] Present to @xx13 after finishing.

# Notes
- [ ] Some framework recreate modal component by using `dialog` component (Quasar / Vuetify)
- [ ] Rename `actions` slot into `footer`

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/dialogs/)
* [Quasar](https://quasar.dev/vue-components/dialog)
* [Ant Design](https://vue.ant.design/components/modal/)
* [iView](http://iview.talkingdata.com/#/components/modal-en)

**Comment by igorprodev1** [comment]
After the investigation, we can conclude that the modal dialog is working correctly. And it covers the main use cases in comparison to other frameworks. After the investigation, I decided to close the ticket.
