### ISSUE TITLE
va-select has typing problem for :text-by and :value-by props

### ISSUE THREAD

**Issue by tassin-gauthier** [epicmaxco/vuestic-ui#3802]
**Vuestic-ui version:** 1.7.6

**Steps to reproduce**
```html
<va-select
  :options="countrySelectOptions"
  :text-by="(option: CountrySelect) => option.englishName"
  :value-by="(option: CountrySelect) => option.countryCode"
>
</va-select>
```

```ts
// props
const countrySelectOptions: CountrySelect[] = [];

type CountrySelect = {
  countryCode: string;
  englishName: string;
};
```

**What is the expected behavior?**

typescript typing should understand that when I use `text-by` and `value-by` props with a function, the function parameter is typed like my `options` list items (In this example, the `CountrySelect` type).

**What is the current behavior?**

Typescript show an error : `Argument of type ... is not assignable to parameter of type ....` The reason is because the `option` parameter is from type `export type SelectableOption = string | number | boolean | Record<string, any>;`.

**Other information**
I think the class should use something like a generic type `<T>` and use this type instead of `SelectableOption = string | number | boolean | Record<string, any>` which can be different from the `option`, but which is impossible.

**Comment by asvae** [comment]
Seems to be done.
