### ISSUE TITLE
Background issue (doesn't cover full screen)

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3805]
**Vuestic-ui version:** 1.7.6

<img width="1025" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/f8345318-6747-4d0b-abee-3cd8c533740e">

**Comment by aditii46** [comment]
Can I work on this, it will be great experience for me as it will be my first open source contribution.

**Comment by m0ksem** [comment]
> Can I work on this, it will be great experience for me as it will be my first open source contribution.

Hi. I think I fixed it already. We need to check it on dev. https://ui-develop.vuestic.dev/introduction/overview
