### ISSUE TITLE
We have a lot of warns in console for kitchensink page

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3809]
**Vuestic-ui version:** 1.7.6

https://ui-develop.vuestic.dev/getting-started/kitchensink
<img width="984" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/40458e04-c405-466f-8821-c55646c75845">

**Comment by m0ksem** [comment]
I don't have it. Maybe you had something cached.

**Comment by m0ksem** [comment]
Fixed here most of them:

https://github.com/epicmaxco/vuestic-ui/commit/56a28a4fe8bf5c7c8eb8633d5f17f90b919f6ee6

<img width="1458" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/ffbda3e3-944b-4e85-b602-b5f8438ccaed">
