### ISSUE TITLE
Nuxt install support

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#381]
When you install nuxt - you can select from a number of frameworks.
We want `Vuestic UI` to be in that list eventually.

![image](https://user-images.githubusercontent.com/5394573/87255845-e4252700-c496-11ea-8a01-5da5fa933b4f.png)

**Comment by m0ksem** [comment]
Let’s work on this task in scaffolding scope, since there is not next-create-app in nuxt3.

**Comment by aluarius** [comment]
This is Nuxt 2 installation interface (create-nuxt-app, https://github.com/nuxt/create-nuxt-app) on the screenshot (not supported by us). Nuxt 3 installer (npx nuxi init nuxt-app) doesn't support any selections during the installation - it's just copying common starter template (https://github.com/nuxt/starter).
