### ISSUE TITLE
VaBadge docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3813]
**Vuestic-ui version:** 1.7.6

<img width="533" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/2461de0b-6afc-44b1-bd84-bf415acc047b">

<img width="508" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/8003931a-f574-4fe8-8e3c-b05247d26102">

**Comment by m0ksem** [comment]
Let's use `grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4` classes on root element, so items render in column on mobile.
