### ISSUE TITLE
VaButton docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3814]
**Vuestic-ui version:** 1.7.6

Icons too close:
<img width="382" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/c54953ca-0f05-4549-b633-a62218b7d4b4">

Add some margin, check other examples
<img width="298" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/b91cf174-4254-4ccb-ab31-4591275ff247">

**Comment by m0ksem** [comment]
Let's use `grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4` class in this demo, so items have correct gap and render in column on mobile. Don't forget to remove existing paddings, because there is gap-4.
