### ISSUE TITLE
VaCarousel docs 

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3815]
**Vuestic-ui version:** 1.7.6

Let's use a bit different ratio to make it look better on mobile.
<img width="426" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/b485f8e7-1256-4d2c-b381-549876d2c183">

Let's use different text for slots, maybe something like [1]

**Comment by m0ksem** [comment]
Let's use different ration, so it is better visible on mobile. Like 16:10 or 16:12.
