### ISSUE TITLE
`VaInput` `border-color` adjusts to container  text `color`

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#3839]
**Vuestic-ui version:** 0.0.0-experimental-f060346c3-20230830

**Steps to reproduce**
- set the background and corresponding color for the `VaInput` parent  container

**What is the expected behavior?**
- input  text `color` and `border-color` adjust to container  text `color`

**What is the current behavior?**
- input `border-color` does not adjust to container text `color`

![image](https://github.com/epicmaxco/vuestic-ui/assets/55198465/6c3c57dd-5936-4e12-8878-977d36404f96)

**Comment by m0ksem** [comment]
We're not going to change component look depending on its background because it cost us a lot of performance issues.
You can probably wrap yellow block in `<VaConfig :colors="{ variables: { backgroundBorder: '#000000' } }" />` to make border color whatever you want.
