### ISSUE TITLE
`VaInput` `loading` prop issue

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#3841]
**Vuestic-ui version:** 0.0.0-experimental-f060346c3-20230830

**Steps to reproduce**
- `loading` prop

<img width="404" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/55198465/684c95f1-deaa-4fbd-aa7c-187776caf45d">

![chrome-capture-2023-8-8](https://github.com/epicmaxco/vuestic-ui/assets/55198465/5c5fb140-7d1e-4c51-a25f-f01cb89ca5ab)

**Comment by m0ksem** [comment]
Fixed here: https://github.com/epicmaxco/vuestic-ui/pull/3850
