### ISSUE TITLE
Add build plugin which converts lodash imports to direct file imports

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3847]
Sadly, `import { throttle } from 'lodash'` will produce commonjs import, which is wrong. We need to use `import throttle from 'lodash/throttle.js'` import, so we import only throttle function, not whole cjs module.

It also improves tree-shaking.

If you ask me WHY exactly `import { throttle } from 'lodash'` is incorrect - I DON'T KNOW. But it throws error, so we need to get rid of it.

Probably must be a feature in library builder.

**Comment by asvae** [comment]
But we're only using this syntax, no?

```
throttle from 'lodash/throttle.js'
```

**Comment by m0ksem** [comment]
> But we're only using this syntax, no?
> 
> ```
> throttle from 'lodash/throttle.js'
> ```

I'm always forgetting to use it. And new contributors can too.
