### ISSUE TITLE
va-select issue

### ISSUE THREAD

**Issue by xbgmsharp** [epicmaxco/vuestic-ui#3867]
**Vuestic-ui version:** 1.8.0

**Steps to reproduce**
After upgrading to 1.8.0 all the va-select now generate a vue warning.

**What is the expected behavior?**
No warning.

**What is the current behavior?**
```
[Vue warn]: Extraneous non-emits event listeners (click) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option. 
```
**Other information**
Adding the following does not change anything.
```
const emit = defineEmits(['update:modelValue')
```

**Comment by m0ksem** [comment]
It is an issue in our end.

**Comment by Muntari29** [comment]
I too am experiencing the same problem.
I hope a revised version comes out soon
thank you!!
