### ISSUE TITLE
va-select vue warning issue

### ISSUE THREAD

**Issue by xbgmsharp** [epicmaxco/vuestic-ui#3872]
**Vuestic-ui version:** 1.8.0

**Steps to reproduce**
Go to https://ui.vuestic.dev/ui-elements/select#objects-as-options
Click on `Open in codesandbox`
Open dev tools.
you see the vue warning for each select.

**What is the expected behavior?**

**What is the current behavior?**

**Other information**
![Screenshot 2023-09-14 at 16 21 59](https://github.com/epicmaxco/vuestic-ui/assets/1498985/ede5ecf9-5349-46c1-b076-2aaea38f6c12)

**Comment by m0ksem** [comment]
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/3867
