### ISSUE TITLE
Anchor overscrolls position

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3878]
**Vuestic-ui version:** 1.8.0

If you use [anchored link](https://ui.vuestic.dev/ui-elements/date-input#validation)

You see this:
<img width="1117" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/c073815d-bd14-4cd0-94bb-d2fc3681da1c">

Instead you should see this:
<img width="1012" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/463c325d-d390-4842-aced-dd62127665ea">

**Comment by ItsKDaniel** [comment]
@asvae I took the liberty to work on this issue. Kindly review the PR #3889
