### ISSUE TITLE
Where is the documentation for Vuestic-UI 1.7.6?

### ISSUE THREAD

**Issue by kakigorimochi** [epicmaxco/vuestic-ui#3887]
I do not want to update to the latest 1.8.0 version yet as I still have an ongoing app development using the 1.7.6 version of the framework. Please advise, thanks.

**Comment by asvae** [comment]
Hey, we don't host older versions of docs but you can spin it locally this way:

```bash
git clone https://github.com/epicmaxco/vuestic-ui.git
cd vuestic-ui
git checkout tags/v1.7.6
yarn install
yarn serve docs
```

That's fully functional docs (with search even). 

Hope that works for you 🤗.

**Comment by asvae** [comment]
Hey @kakigorimochi.

Do you have some issues with 1.7.6 you need fixed or what's your concern?

If docs are your concern - you can spin them locally this way:

```bash
git clone https://github.com/epicmaxco/vuestic-ui.git
cd vuestic-ui
git checkout tags/v1.7.6
yarn install
yarn serve docs
```

Apart from that - there is nothing limiting you from stayin on 1.7.6 as long as you want. :)

**Comment by m0ksem** [comment]
> Hey @kakigorimochi.
> 
> Do you have some issues with 1.7.6 you need fixed or what's your concern?
> 
> If docs are your concern - you can spin them locally this way:
> 
> ```shell
> git clone https://github.com/epicmaxco/vuestic-ui.git
> cd vuestic-ui
> git checkout tags/v1.7.6
> yarn install
> yarn serve docs
> ```
> 
> Apart from that - there is nothing limiting you from stayin on 1.7.6 as long as you want. :)

Maybe we can host 1.7.6 docs somewhere? It is just a static, gh-pages can be used for example.

**Comment by kakigorimochi** [comment]
Thank you for your reply, however, whenever I do `yarn serve docs` and access localhost:3000, I only get a blank page.

![image](https://github.com/epicmaxco/vuestic-ui/assets/16938949/3b4dbbc9-7978-4a69-b5b4-803bc38de6cc)


> Hey @kakigorimochi.
> 
> Do you have some issues with 1.7.6 you need fixed or what's your concern?
> 
> If docs are your concern - you can spin them locally this way:
> 
> ```shell
> git clone https://github.com/epicmaxco/vuestic-ui.git
> cd vuestic-ui
> git checkout tags/v1.7.6
> yarn install
> yarn serve docs
> ```
> 
> Apart from that - there is nothing limiting you from stayin on 1.7.6 as long as you want. :)

**Comment by kakigorimochi** [comment]
> > Thank you for your reply, however, whenever I do `yarn serve docs` and access localhost:3000, I only get a blank page.
> > ![image](https://user-images.githubusercontent.com/16938949/269144606-3b4dbbc9-7978-4a69-b5b4-803bc38de6cc.png)
> > > Hey @kakigorimochi.
> > > Do you have some issues with 1.7.6 you need fixed or what's your concern?
> > > If docs are your concern - you can spin them locally this way:
> > > ```shell
> > > git clone https://github.com/epicmaxco/vuestic-ui.git
> > > cd vuestic-ui
> > > git checkout tags/v1.7.6
> > > yarn install
> > > yarn serve docs
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Apart from that - there is nothing limiting you from stayin on 1.7.6 as long as you want. :)
> 
> It must be `yarn serve:docs`

Thank you for your help, I have hosted v1.7.6 docs on my vps: 

https://vuesticui176.futuregadget-apt.ph

**Comment by m0ksem** [comment]
```
yarn build:docs:ci
yarn start:docs:ci
```

We use it on our VM in case you want to host it manually.

**Comment by kakigorimochi** [comment]
Sadly it's hard to compile on a 1GB VPS server (it's the range I could only afford). 
I'll just run it locally, but it would be great if the team could offer a way to switch versions in the docs.
