### ISSUE TITLE
Feature Request: <Va-Info /> | ToolTip 

### ISSUE THREAD

**Issue by mrniamster** [epicmaxco/vuestic-ui#3893]
**Is your feature request related to a problem? Please describe.**
Hi Team, Would be great if we have Tooltip -> something like
```
 <Va-Info icon="info"  text="Describing the feature on hover" />
```
 

Currently, in my apps i would like my user to click on "Info" button  to show a tooltip describing the feature

**Describe the solution you'd like**
```
<Va-Info icon="info"  text="Describing the feature on hover" />
```

Possible Props :
Variant : Info,succes,error
Placement: L,R,T,B

**Describe alternatives you've considered**

**Additional context**

**Comment by m0ksem** [comment]
We have VaPopover

```html
<VaPopover message="Help is here">
   <Button preset="info-popover" />
</VaPopover>
```

**Comment by mrniamster** [comment]
Thanks @m0ksem  , my bad.

**Comment by beard7** [comment]
Ideally, it should be possible to add a tooltip to anything using a directive, such as v-tooltip rather than it being necessary to wrap things in another component.
