### ISSUE TITLE
Date Picker does not work properly

### ISSUE THREAD

**Issue by emiliorighi** [epicmaxco/vuestic-ui#3894]
**Vuestic-ui version:** 1.8.0

**Steps to reproduce**
 Hover the year of the arrows in the date picker component

**What is the expected behavior?**
 Shoul be able to interact with the component

**What is the current behavior?**
The year and the arrows disapper

**Other information**
![Screenshot from 2023-09-22 11-41-41](https://github.com/epicmaxco/vuestic-ui/assets/85154159/116de271-da0d-4f9f-8d13-c21da85ff11e)
![Screenshot from 2023-09-22 11-42-03](https://github.com/epicmaxco/vuestic-ui/assets/85154159/188f5f2e-8e53-4a7c-8319-2cba8875742d)

**Comment by asvae** [comment]
Hey, thanks for report.

Hey. That's already fixed and plannned for `1.8.1`.
