### ISSUE TITLE
Copyable changelog link

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3918]
I want to have a link to 1.8.0 changelog, but I'm unable to do so.

This is that only link I'm able to use.
https://ui.vuestic.dev/introduction/change-log

What I need is https://ui.vuestic.dev/introduction/change-log/1.7.0.

This link should open and scroll into view section for 1.7.0. All other sections should be closed.

I think we can just update url when user selects different changelog item (while closing the previously opened one. Then you would be able to just copy url.

**Comment by m0ksem** [comment]
Might be easier to add anchors and have links like https://ui.vuestic.dev/introduction/change-log#1.7.0

**Comment by xiongmao86** [comment]
Hi, @m0ksem, @asvae, simply add and `:id="version" to the h1 tag doesn't work. 

<img width="515" alt="屏幕截图 2023-11-07 221431" src="https://github.com/epicmaxco/vuestic-ui/assets/1770218/71213d63-5c90-407a-a73b-ed15a3a79883">

**Comment by m0ksem** [comment]
> Hi, @m0ksem, @asvae, simply add and `:id="version" to the h1 tag doesn't work. Can you give me some pointers?
> 
> <img width="515" alt="屏幕截图 2023-11-07 221431" src="https://github.com/epicmaxco/vuestic-ui/assets/1770218/71213d63-5c90-407a-a73b-ed15a3a79883">
> 

We have component called "anchor" from page config module. It must be available globally in nuxt docs.
