### ISSUE TITLE
Inconsistent behavior for VaTimeInput right icon

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3922]
**Vuestic-ui version:** 1.8.0

When you click on icon - dropdown doesn't close
When you click on input - dropdown closes

Icon should not have different behavior, it should behave as if it doesn't exist (I believe), and you only have input.

<img width="396" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/ab2b3c67-b18f-4daa-a0bd-4f34b08d0c11">

Compare to
https://www.naiveui.com/en-US/os-theme/components/time-picker

**Comment by Udaay** [comment]
@asvae  Picking this up

**Comment by Udaay** [comment]
Hi @asvae have gone through [naiveUI time picker]( https://www.naiveui.com/en-US/os-theme/components/time-picker ) component.
DropDown only closes when only on focusOut from InputBox.

Currently Implementing the same , dropdown will not close onclick on inputBox & Icon.

**Comment by Udaay** [comment]
#3933
