### ISSUE TITLE
VaDateInput bug

### ISSUE THREAD

**Issue by lashtun** [epicmaxco/vuestic-ui#3935]
**Vuestic-ui version:** 1.8.0

**Steps to reproduce**
After upgrading to 1.8.0 in the VaDateInput component, an error occurs when hovering over the year or arrows (left, right)

**What is the expected behavior?**
No error

**What is the current behavior?**
`Error: Color currentColor is not valid. Please, provide valid color.`

**Other information**
This error also occurs in the documentation for this component as well
<img width="815" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/15269313/2f27ff3f-da96-47d5-a4d0-8685debff692">

**Comment by m0ksem** [comment]
Fixed here https://github.com/epicmaxco/vuestic-ui/pull/3877 and will be available in 1.8.1.
