### ISSUE TITLE
Date picker default buttons throw error on hover

### ISSUE THREAD

**Issue by Jcjays** [epicmaxco/vuestic-ui#3941]
**Vuestic-ui version:** 1.8.0

**Steps to reproduce**

- use date picker
- hover on the prev | year | next buttons

**What is the expected behavior?**

- Change color

**What is the current behavior?**

- Missing 

**Other information**

![image](https://github.com/epicmaxco/vuestic-ui/assets/90882247/7c96459d-5a74-44ec-8134-1b26e0c3e7e9)
![image](https://github.com/epicmaxco/vuestic-ui/assets/90882247/c9435524-53c0-40da-b4ad-1e384e3e9a96)

**Comment by m0ksem** [comment]
Fixed in 1.8.1
