### ISSUE TITLE
the scrollbar in va-textarea is wrong（an arg should be provided to close the scrollbar inside va-textarea）

### ISSUE THREAD

**Issue by chenjie199234** [epicmaxco/vuestic-ui#3944]
**Vuestic-ui version:** 1.8.1

![捕获](https://github.com/epicmaxco/vuestic-ui/assets/29348971/aafc1084-4346-4671-a6b5-583531724dfa)

**Comment by m0ksem** [comment]
Hi, @chenjie199234. Can you make codesandbox reproduction or share some code examples? Not really sure where the problem is here.

**Comment by chenjie199234** [comment]
@m0ksem sorry,my mistake.I tested it again and it works fine.but how to close the scroll bar.i want to use the system's scrollbar
