### ISSUE TITLE
va-split dragger will cover the scrollbar（if use the vuestic's scrollbar,the scrollbar will be cover 100%）

### ISSUE THREAD

**Issue by chenjie199234** [epicmaxco/vuestic-ui#3947]
**Vuestic-ui version:** 1.8.3
![捕获](https://github.com/epicmaxco/vuestic-ui/assets/29348971/b264c2da-6c28-4702-941a-3679d7ef2e1f)

**Comment by m0ksem** [comment]
Hi @chenjie199234. Would you be able to make small reproduction in codesandbox or share code example of the case which causes this issue?

**Comment by chenjie199234** [comment]
@m0ksem the dragger in va-split cover the va-scroll-container's scroll bar,the scroll bar can't be selected by mouse
```
<script setup lang="ts">
	import {ref} from "vue"
	const list=ref<number[]>([0,1,2,3,4,5,6,7,8,9,10])
</script>

<template>
	<va-split style="width:100%;height:100%;display:flex" stateful :model-value='0' :limits="['300px',50]">
		<template #start>
			<va-scroll-container style="height:100px;overflow-y:auto">
				<va-list>
					<va-list-item v-for="item of list" :key="item">
						{{item}}
					</va-list-item>
				</va-list>
			</va-scroll-container>
		</template>
		<template #end>
			this is end
		</template>
	</va-split>
</template>
```
![1](https://github.com/epicmaxco/vuestic-ui/assets/29348971/304cfe82-9b47-4bee-a488-ececb6bd346b)
![2](https://github.com/epicmaxco/vuestic-ui/assets/29348971/f21be7d5-554e-446d-aa72-4453083f3542)
