### ISSUE TITLE
va-select - @change not working

### ISSUE THREAD

**Issue by sivasyams** [epicmaxco/vuestic-ui#3954]
**Vuestic-ui version:** 1.7.3

` <va-select label="Category Based" v-model="examDetail.sectionBasedEvaluation" :options="categoryBasedOptions" @change="onChange($event)"/>
`

In the above code, @change is not invoked upon changing the dropdown values. The v-model is getting updated. But it need to trigger an event as well.

**Comment by m0ksem** [comment]
Hi, @sivasyams.

What's payload will you expect from this event? 

We don't use native select and input accepts text as value, not actual value

```
<VaSelect :options="[{ text: 'One', value: 1 }]" @change="onChange($event)" />
```

Will you expect native event (will be input actually) or just `1` as emit payload?

Or something more complex like `{ option, value, text }`?

The downside of native event is obvious, event.target.value will show not actual value, but option text.

On the other side, if you need 1, you can listen for `@update:modelValue` or `watch` for `examDetail.sectionBasedEvaluation`.

**Comment by sivasyams** [comment]
Thanks @m0ksem, i actually wanted the value of the selection, which i have used @update:modelValue. This can be closed.
