### ISSUE TITLE
Components with render function only lost their styles

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3955]
When developing in 1.7.x, breadcrumbs were looking nice like this:
![image](https://github.com/epicmaxco/vuestic-ui/assets/40818011/1e52371e-605c-4591-84b3-90d848cac978)

But on upgrade 1.8.x they now look like this:
![image](https://github.com/epicmaxco/vuestic-ui/assets/40818011/6b972a4d-c320-49be-8aeb-ee3eecb958e8)

I thought installing Tailwind might help, but it doesn't. It seems the --va-breadcrumbs-separator-padding css variable doesn't get applied anywhere. I don't mind custom spacing or not, but need to improve the look of how these come out now. What am I missing?

_Originally posted by @brendanpetty in https://github.com/epicmaxco/vuestic-ui/discussions/3949_

**Comment by brendanpetty** [comment]
Thank you, looks great again!
