### ISSUE TITLE
VaModal size doesn't work

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3961]
**Vuestic-ui version:** 1.8.1

I set size to large, yet it seems fully dependent on content size. You can try to set other sizes - modal would still look the same.

```html
<va-modal
  :modelValue="true"
  title="123"
  message="123"
  size="large"
/>
```

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/a4c25090-e3bd-411d-a95d-f0107a9675f1)

## Other

We have [docs page where it looks ok](https://ui.vuestic.dev/ui-elements/modal#modal-sizing) for some reason. Not sure how this happened. Same for [story](https://ui-storybook.vuestic.dev/?path=/story/vamodal--default).

Could be some sort of confusion on what size means. I would expect modal to have constant size if I set it. But it seemingly behaves as if it's max-width.

**Comment by m0ksem** [comment]
We'll need to update sizesConfig and change how this whole thing works, because right now you're not able to set specific width for modal.
