### ISSUE TITLE
CSS is failing with the latest version of Vuestic UI

### ISSUE THREAD

**Issue by PavankalyanPayyavula** [epicmaxco/vuestic-ui#3967]
**Vuestic-ui version:** 1.8.2

**Steps to reproduce**
I am building an application from scratch, due to new release the css of the application is broken. when I download the new node-modules.
"vuestic-ui": "^1.8.0"

**What is the expected behavior?**
No Css Breakdown

**What is the current behavior?**
Entire screen is breaking down, CSS was reacting very oddly, Please check it immediately.

**Other information**
Again I have re-installed the "vuestic-ui": "1.8.0" nodemodules then It is working as expected.

Since i am working in a company, I am not posting the Screen shot if the Application.

**Comment by m0ksem** [comment]
Should be fixed in 1.8.3
