### ISSUE TITLE
Layout doesn't get absolute positioning

### ISSUE THREAD

**Issue by brendanpetty** [epicmaxco/vuestic-ui#3985]
**Vuestic-ui version:** 1.8.3

**Steps to reproduce** use the sample code from https://ui.vuestic.dev/ui-elements/layout#absolute (or mobile friendly, slightly further down the page)... and the absolute positioning never actually gets applied

**Other information**
I can't work out enough of how the internals of vuestic work to help find the solution, but from some css/devtools inspection it seems that the following CSS rule never actually gets applied, even though it seems the right elements and classes are present in the DOM:

```
.va-layout__absolute-area-wrapper .va-layout__area {
  position: absolute;
}
```

**Comment by m0ksem** [comment]
Probably related to my PR (https://github.com/epicmaxco/vuestic-ui/pull/3956)

**Comment by brendanpetty** [comment]
Thanks!
