### ISSUE TITLE
Modal closes when you finish the click outside of it

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3987]
**Vuestic-ui version:** 1.8.3

When you click and press on modal 
and hover mouse pointer out of modal, 
and release mouse button
then modal closes.

I would like to keep it open and only in this case close it if I start a click on background.

This is a problem for me because I like to select text with mouse drag. And when modal padding are small - it's very easy to miss - and modal closes. Sometimes I miss 2 or 3 times in a row.

This gets annoyance rating of 10 chili peppers out of 10 from me.

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/1986261b-83d6-4130-8bd4-495f4fdd18be)

**Comment by joshLumpkin** [comment]
Submitted a PR to fix this!

**Comment by joshLumpkin** [comment]
Submitted the correct PR
