### ISSUE TITLE
Inconsistent component naming in examples (va-component vs VaComponent)

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3989]
**Vuestic-ui version:** 1.8.3

Documentation has inconsistent caps for component names.
I found only one spot, but it's likely there are more.
We probably need a solution to prevent this from happening in the future (linter rule?).

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/f119f113-60ca-4d00-a586-aed8b058dfd5)

**Comment by xiongmao86** [comment]
Hi, @asvae, which case do you prefer? `PascalCase` or 'kebab-case'?

**Comment by xiongmao86** [comment]
I can see it's very sound code change here. Do I need to do any extra check? because I think reviewer is the last guard against the less worthy code, I need some suggestion on how to do it well.

**Comment by m0ksem** [comment]
I personally prefer PascalCase, so there is visually difference between VueComponent and nativeelement. Looks like the same approach is used in [vue docs examples](https://vuejs.org/guide/components/props.html#prop-passing-details).

Sad to see we have kebab-case in Vuestic Admin, @asvae!

**Comment by asvae** [comment]
I'd say pascal. The issue with kebab is that it's not universal, so you'll use kebab in template, but pascal in other places, which makes replacing tricky.

On the other hand, pascal we can use universally.

Even if we want to use kebab in template - I would rather go with some teplates conversion script to keep our codebase purely pascal.

> Sad to see we have kebab-case in Vuestic Admin, @asvae!

We don't have to! 😬
