### ISSUE TITLE
VaCounter: Readonly mustn't look like disabled

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#3999]
**Vuestic-ui version:** 1.8.3

**Steps to reproduce**
https://www.chromatic.com/test?appId=64d608ab34b67e621ab50cfd&id=65491aac0cb292254de33c55
**What is the expected behavior?**
<img width="169" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/495bf445-5352-41e8-b7f3-690a2f5cd463">

**What is the current behavior?**
<img width="161" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/5dc2e21f-849d-46eb-a83d-7ce4197e9efb">

**Other information**

**Comment by sfazli96** [comment]
Hi! If this is kind of like an CSS issue, I might give this a try. Let me know

**Comment by m0ksem** [comment]
Hi, @sfazli96. It is more script logic. Looks like we make buttons disabled when counter is read-only, but actually, we just need to ignore click events instead.

**Comment by sfazli96** [comment]
oh ok I see, I will still give this a try

**Comment by jose-fernandez** [comment]
Hi guys! I would like to work on this. I don't know if I have to say it before hand so it gets assigned, or I can directly create the PR.
