### ISSUE TITLE
VaBreadcrumbs: Active color

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4000]
**Vuestic-ui version:** 1.8.3

**Steps to reproduce**
https://www.chromatic.com/test?appId=64d608ab34b67e621ab50cfd&id=65491aac0cb292254de33c15
**What is the expected behavior?**
Only active breadcrumb must be danger color
**What is the current behavior?**
<img width="166" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/410a3cd7-394a-4e27-ab41-72ded9e850f9">

**Other information**

**Comment by emperorsegxy** [comment]
Hi, @m0ksem. I would like to pick this up, but I need to know what makes a breadcrumb active. 
The currently implemented condition just says - if a child node (VaBreadcrumbItem)
 is not the last child and it is not disabled.

![Screenshot 2023-11-11 004901](https://github.com/epicmaxco/vuestic-ui/assets/51512956/316d30bc-654f-4aa5-835b-258dc0397671)

**Comment by m0ksem** [comment]
> Hi, @m0ksem. I would like to pick this up, but I need to know what makes a breadcrumb active. The currently implemented condition just says - if a child node (VaBreadcrumbItem) is not the last child and it is not disabled.
> 
> ![Screenshot 2023-11-11 004901](https://user-images.githubusercontent.com/51512956/282200919-316d30bc-654f-4aa5-835b-258dc0397671.png)

I think we assume last item to be active. So `/users/Maksym/playlists` - `playlists` is gonna be the active element.
