### ISSUE TITLE
VaInnerLoading: add loading icon slot

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4003]
**Is your feature request related to a problem? Please describe.**

For innerLoading I wanted to make a timer from 3 to 1, but in VaInnerLoading it is impossible to provide custom slot and render numbers instead of spinner.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I can do it manually, but should I?

**Additional context**

This will allow users to use custom inner loading content, like cards or VaProgressBar instead of circle. 
(Make sure slot will not spin!)

**Comment by jose-fernandez** [comment]
@m0ksem Here is the PR. I added the slot and an example in storybook using `VaProgressBar`. I hope you did not mean literally to create the countdown timer xD

**Comment by emperorsegxy** [comment]
@m0ksem , @jose-fernandez , since this issue has been addressed, how do we close it?
