### ISSUE TITLE
VaCheckbox: move padding values from JS to CSS

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4011]
We will need to move these values to CSS variables under `_variables.scss`, so they can be configured.

_Originally posted by @m0ksem in https://github.com/epicmaxco/vuestic-ui/pull/4005#discussion_r1390609189_
            
            
Let's have something like `--va-checkbox-vertical-gap` and `--va-checkbox-horizontal-gap`

**Comment by Abhid1239** [comment]
Working on this

**Comment by Abhid1239** [comment]
@m0ksem can you check the PR and approve

**Comment by Abhid1239** [comment]
@m0ksem done required Changes please review.
Also, the branch didn't had a branch so created a branch and then created the PR

**Comment by Abhid1239** [comment]
@m0ksem can you check this?
