### ISSUE TITLE
VaModal sizes are off

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#4020]
**Vuestic-ui version:** 1.8.4

![image](https://github.com/epicmaxco/vuestic-ui/assets/5394573/d02c6b67-10bf-463c-add7-3dce5f07d873)

Regression seems to be introduced in this pr:
https://github.com/epicmaxco/vuestic-ui/pull/3970

**Comment by asvae** [comment]
I would recommend [reworking stories](https://github.com/epicmaxco/vuestic-ui/issues/3676) for va-modal, then following this up with a fix. So that we have visual tests.

**Comment by m0ksem** [comment]
I think we can fix it in scope of https://github.com/epicmaxco/vuestic-ui/issues/3333
