### ISSUE TITLE
VaPagination impossible to hide default pagination arrows

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4023]
I want to make my own buttons, place them tougher before pagination, but it is impossible to do, because Vuestic adds it's own buttons and they can not be hidden.

<img width="324" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/3c9865ef-6406-42ae-b368-a3f8a456ef85">

(My custom buttons are in red rect)

Should easy to fix, just add new prop and v-ifs on buttons.

**Comment by joshLumpkin** [comment]
I could be wrong, but isnt this already possible? The props for boundry-links and direction-links already exist, allowing you to pass in false, hiding them both.

If not the desired solution, i'd love to work on this.

**Comment by m0ksem** [comment]
> I could be wrong, but isnt this already possible? The props for boundry-links and direction-links already exist, allowing you to pass in false, hiding them both.
> 
> If not the desired solution, i'd love to work on this.

Yeah. It works! Thanks.
