### ISSUE TITLE
Let's add alias to useToast init function

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4024]
Name `init` looks too general. I'd prefer something like:

```ts
notify("User has been deleted!")
```

or

```ts
makeToast("User has been deleted!")
```

- [ ] Come up with new name which is super clear
- [ ] Add alias to useToast composable (init should stay, but you can mark it `@deprecated` using JSDocs
- [ ] Change `init` in docs to new method name.

https://ui.vuestic.dev/ui-elements/toast#toast

**Comment by joshLumpkin** [comment]
Just submitted PR!
