### ISSUE TITLE
VaButton icon sizes are broken (?)

### ISSUE THREAD

**Issue by codedealer** [epicmaxco/vuestic-ui#4036]
The icon size on buttons set via `icon` prop no longer changes with the change to the size of the button via `size` prop. E.g. the icon size on a large button is the same as on a small one. Is this the new intended behavior or a bug in a new 1.8.x version?

**Vuestic-ui version:** 1.8.4

**Steps to reproduce**
Change the `size` prop on a button and observe the icon's size.

**What is the expected behavior?**
![image](https://github.com/epicmaxco/vuestic-ui/assets/4258136/0b9cb995-6748-45f9-b83d-94679b4678be)

[Sandbox for v1.7.8](https://codesandbox.io/p/devbox/vbtn-184-forked-8d38p7)

**What is the current behavior?**
![image](https://github.com/epicmaxco/vuestic-ui/assets/4258136/d95a9961-dc3e-4074-9e89-4474e1eb96d2)

[Sandbox for v1.8.4](https://codesandbox.io/p/devbox/vbtn-184-smhzs8)

**Other information**
Currently I work around it by placing `VaIcon` inside the `VaButton` but I'd like some clarity on how buttons icons are treated from now on.

**Comment by m0ksem** [comment]
This must be considered here https://github.com/epicmaxco/vuestic-ui/issues/3333 later
