### ISSUE TITLE
Cursor pointer for switch

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#4054]
**Vuestic-ui version:** 1.8.5

[Vuestic UI - Switch](https://ui.vuestic.dev/ui-elements/switch) doesn't have cursor pointer, but it should.

**Comment by joshLumpkin** [comment]
I can knock this out!

**Comment by joshLumpkin** [comment]
@emperorsegxy Yes! Working on it today, If I can't finish it today I'll hand it over!

**Comment by joshLumpkin** [comment]
I can't get pointer-events: none to play nicely with cursor: pointer. removing pointer-events: none breaks the switch. Not sure where I am going wrong but will keep trying unless someone wants to takeover

**Comment by emperorsegxy** [comment]
@joshLumpkin , are you still on this? I am thinking of checking it out but want to be sure you are okay with that.
