### ISSUE TITLE
VaSidebar Menu Not Collapsing

### ISSUE THREAD

**Issue by Jcjays** [epicmaxco/vuestic-ui#4055]
**Vuestic-ui version:** 1.8.5

**Steps to reproduce**
Use VaSidebar

**What is the expected behavior?**
Should collapse on click.

**What is the current behavior?**
Not collapsing

**Other information**

**Comment by m0ksem** [comment]
I'm not seeing this issue in 1.8.6. https://ui.vuestic.dev/ui-elements/sidebar#default

Is this still relevant, @Jcjays?
