### ISSUE TITLE
VaSelect: max-visible-options prop must accept Number or String

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4066]
<img width="627" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/f039e034-049a-49ef-b0d8-8a731bf6c481">

Right now, it only may be number:
<img width="465" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/23530004/e2acc225-67b6-41b7-aa9f-7251617466cc">

**Comment by ishaanparlikar** [comment]
Can I pick it up?

**Comment by asvae** [comment]
I expanded this issue to cover other components - https://github.com/epicmaxco/vuestic-ui/issues/4071
