### ISSUE TITLE
VaForm: calling validate must mark form as dirty

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4075]
[Playground link](https://ui-experimental.vuestic.dev/play#eNp9kU9vEzEQxb/KyJdtpSZL1Vu0iaCoSOUAiCIumMOymWTd+h/2eIm03e/O2NuEglBv9szPb57fjOKN98shoViJJnZBeYKIlPxGWgBlvAsEIwTcwQS74AxUDFfS5nbnbCQwcQ/rTJxV1bm0TT3LsABfCI3XLWGRa/pL6HQb41qKoV30l1JsxrEITFNT95cz9bV954KBYRG1I0ZHGFqttqwCE7/ITKFurU/EmHFb1MyxjhSwCkljnvDtbDiH9QaGpUa7px428AoeH6EK+DOpgNvqO+P1k95J9ToROQuvO626h2J0ns2T79IPo6ipj9Bsl6/ZL1+a+tl3pRUXYg5wYVq/vI/OcshjfiOfGlGKFZRKrnGwkVS3SCqXpeiJfFzVdVILPHgMyqClVudtZW65xaE+vnGJatMqy2OkyIKTtBMboMhL2qn9P+M7Z7zSGD56UrzEv2y0Wrtf70uNQsKLY73rsXv4T/0+Hma/nwJGDAMndepRG/ZIc/vm7gMe+Hxq8t54VS82P2N0OmWPM3ad7JZtP+OK29uSprL7L/HmQGjj8VPZaEmj8CXity98/Y/dq+XVKcXpNygxCT0=)

Otherwise, no error messages are shown

**Comment by emperorsegxy** [comment]
I have picked this up.
