### ISSUE TITLE
VaInput: Not showing error state nor error messages

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#4104]
**Vuestic-ui version:** From version 1.8.5 and onwards, 1.8.4 does not have this issue

**Steps to reproduce**
Go to official documentation page, even examples are not working. 
https://ui.vuestic.dev/ui-elements/input

![image](https://github.com/epicmaxco/vuestic-ui/assets/46224115/2bf65399-9f47-4a32-961a-cfe7c4ba0f69)

**What is the expected behavior?**
Error state and messages should be shown

**What is the current behavior?**
They don't show even when they're set

**Comment by asbermudez** [comment]
Checking a bit the diff of version 1.8.4 to 1.8.5, I've see there were changes in the useForm, useFormParent and useValidation that they're probably the cause of the issue. My gut feeling tells me that probably the useValidation is overwriting the passed parameters to the VaInput component.

**Comment by m0ksem** [comment]
We added dirty state, so error isn't visible until you type something in input… In case you need to show error immediately, you can use `immediate-validation`.

We might need to add this prop to docs example.

**Comment by asbermudez** [comment]
@m0ksem yes would be nice. This was confusing as I wasn't able to see such a breaking change explicitly mentioned and obviously the examples in the documentation are broken.

**Comment by jonjakoblich** [comment]
> We added dirty state, so error isn't visible until you type something in input… In case you need to show error immediately, you can use `immediate-validation`.
> 
> We might need to add this prop to docs example.

+1 for adding it to the docs. The example is broken and it wasn't clear until I searched Github issues and found this. Thank you for all you do!
