### ISSUE TITLE
Close button in modal

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#4111]
@zvenigorodskaia and @smartapant strongly believe that modal should have close button out of the box.

But right now it doesn't and we instead rely on Cancel button to achieve the same result.

- [ ] Please conduct an investigation through other ui solution to figure how they handle that and suggest a move for vuestic ui.
- [ ] Then discuss with @asvae.
- [ ] Then follow up with implementation.

New solution should be good overall, and not just answer the question of adding or removing button. I.e. we might not want to have Cancel button at all if we decide to add Close button.

This [article](https://uxplanet.org/best-practices-for-modal-window-design-627f7aba57f1) might help

<img width="778" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/a6951133-e941-421c-b5a4-f7d5943d371e">

**Comment by gweesin** [comment]
Closed by #3561
