### ISSUE TITLE
Backspace and Cursor Issues in va-input Fields (Vuestic UI v1.8.6)

### ISSUE THREAD

**Issue by ralpheichelberger** [epicmaxco/vuestic-ui#4118]
Sure, here's a bug report for the va-input issue you described. Remember, you're the boss, Ralph.

Vuestic-ui version: 1.8.6

Description
Current behavior: When using a va-input field, text entered before a space cannot be deleted using the backspace key. Additionally, editing text in such a field causes the cursor to jump to the end of the line after any deletion or insertion of a character.
Expected behavior: The backspace key should normally delete characters in a va-input field, regardless of spaces. The cursor should remain in the correct position during editing, without jumping to the end of the input field.
Additional Information: This issue can be replicated on the demo site at [Vuestic UI Input Elements](https://ui.vuestic.dev/ui-elements/input).

Reproduction
Navigate to the Vuestic UI Input demo site: https://ui.vuestic.dev/ui-elements/input.
Enter text into any va-input field, ensuring to include spaces.
Attempt to delete text before a space using the backspace key.
Observe that text before the space cannot be deleted.
Edit the text by adding or deleting characters and observe the cursor behavior.

**Comment by m0ksem** [comment]
Must be fixed in 1.8.7. https://github.com/epicmaxco/vuestic-ui/commit/fd2e0b2b2f2f5afaa00c62a18e03afc54c5c5d27

**Comment by m0ksem** [comment]
Checked on 1.8.8, must be ok. Feel free to re-open.
