### ISSUE TITLE
VaSelect: Highlighted text and update-search emit trigger on first open when preselected option

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#4130]
**Vuestic-ui version:** 1.8.7

### Description

When we setup a VaSelect with a preselected option in model-value, on opening the dropdown, it shows the selected option with the highlight as if the select had the searchable option to true and the whole option text was set as value. If without touching anything you close and open again, it get cleared.
Also, at that moment the update-search emit is triggered with the whole text of the selected option.

### Reproduction
You can see it in the first example of the multiselect section on the documentation page of Vuestic

https://ui.vuestic.dev/ui-elements/select#multiple-select

First time:
![image](https://github.com/epicmaxco/vuestic-ui/assets/46224115/bf61bebe-042b-403c-8128-1f49b76786e3)

Second time:
![image](https://github.com/epicmaxco/vuestic-ui/assets/46224115/022d32e5-c182-405b-bd9a-8ab4c45052d0)

**Comment by m0ksem** [comment]
It must be fixed here... https://github.com/epicmaxco/vuestic-ui/commit/2be167f196b48637af47e35534b4b0fadac94e70
But we'll need to verify it and maybe make 1.8.8 before 1.9.0

**Comment by m0ksem** [comment]
Must be fixed in 1.8.8.
