### ISSUE TITLE
type: Number props must also be String

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4138]
> VaTextarea has issue with maxRows type. You can see it on the [playground for autosize from the docs](https://ui.vuestic.dev/play#eNp9UU1PAjEQ/StNL2gC7IF4QTRRw0EPaoR42kuzO0Cx2zbtdFkl+9+dbllEYzh1Pl7fvHmz53fWjusAfMpnCJVVAuE214zN3sUSGhQOREwZq0eVKUHd5LwWKkDOU1kENF5+Qcoq0Yyc2XlCXfUI4ixgY1QJjsoLokSGn1bqdUJkNG+WnQyn1BdOWqQYGmsIX8JKBIVsHz+UAsXFZYoZc4DB6T4jnVHdlA0Gw1Rpr+PbUhajWXak5kMuq8g+qoQdb73RZEJHkx8aPufTnpjWDuBRFqMgYznnG0Trp1kWZDQwtsYl1FkPMwGzSkhNzGnPlhTQTPSF0Su5/jOxMJWVCtyLRWn078lCKbN76mroAhwWoz8bKD7+qW99kyS+OvDgajrWsUf2rwFTe754phOfNOnCQRH6TPMNvFEhakyw+6BLkn2C69Q+dgbSjZd+3iBo3y8VhfYHObj6cGb1H7mT8eToYvsNpXzkYw==).
> Invalid prop: type check failed for prop "maxRows". Expected Number with value 5, got String with value "5".
 at <VaTextareamodelValue=""onUpdate:modelValue=fnautosize="" ...>
 at <Repl>
 
 We need all components with Number type to support String bind as well.

**Comment by m0ksem** [comment]
The idea of this issue is to go trought the packages/ui, find all `type: Number` props and convert them to `type: [Number, String]`. 

We want to allow user to set props as string `max="4"`, not only `:max="4"`. 

Everywhere changed prop is used it must be converted to number `Number(props.max)`.

**Comment by m0ksem** [comment]
Fixed for VaAspectRatio, VaButton and VaSidebar here: https://github.com/epicmaxco/vuestic-ui/commit/1791856cb476060e1a41cca2ef9dc4769963801d

**Comment by khurram-ansari** [comment]
Fixed for VaCounter at [5168331](https://github.com/epicmaxco/vuestic-ui/pull/4184/commits/51683318337ec7bf2f9711188d3f7ebf60eba8c3)
