### ISSUE TITLE
VaSwitch doesn't have cursor pointer on compiled version

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#4143]
**Vuestic-ui version:** 1.8.7

Confusing part is that on development server it works just fine.

<img width="879" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/2b50a31f-34ad-4363-829b-45684c6c29b0">

You can check there: https://admin-develop.vuestic.dev/settings

**Comment by m0ksem** [comment]
Looks like fixed.
