### ISSUE TITLE
VaInput component not displaying model-value on initial render (Nuxt)

### ISSUE THREAD

**Issue by bubu-bin** [epicmaxco/vuestic-ui#4150]
**Nuxt:** [3.5.3, 3.9.3]
**@vuestic/nuxt:** 1.0.18

#### Current behaviour
- In a project running Nuxt version 3.9.3 (also replicated in 3.5.3), and using @vuestic/nuxt version 1.0.18, I'm encountering a rendering issue with the Vuestic UI input component.
- The issue is that during the first render, the model-value of the input is not visible. The value becomes visible only upon focusing on the input field.
- This behavior is inconsistent and unexpected, causing confusion and potential usability issues.

#### Expected behaviour
- The expected behavior is that the value inside va-input should be visible on the first render, without needing to focus on the input field.

### Reproduction
[Issue demonstration on StackBlitz](https://stackblitz.com/edit/nuxt-starter-ewxveh?file=README.md)

**Comment by m0ksem** [comment]
As quick fix you can use experimental (basically 1.9.0 prerelease) version `vuestic-ui@0.0.0-experimental-b54792bd0-20240125` before we release 1.9.0 where this issue will be fixed.

https://stackblitz.com/edit/nuxt-starter-e4onl3?file=package.json

**Comment by bubu-bin** [comment]
Thank you very much for the quick response and the suggested workaround. Looking forward to the release of version 1.9.0 with this fix.
