### ISSUE TITLE
Date Input, Date picker | highlight-weekend prop works incorrectly with firstWeekday="monday"

### ISSUE THREAD

**Issue by bagrovYKT** [epicmaxco/vuestic-ui#4152]
**Vuestic-ui version:** 1.8.7

### Description

<VaDateInput
  weekends-color="primary"
  highlight-weekend
/>

this combination of props will highlight _Monday & Sunday_ instead of **Saturday & Sunday**

**Comment by abachant** [comment]
I was able to replicate this.
The problem was not that the combination of the two props, but that "monday" needs to be capitalized in order for it to work correctly.
![Screenshot 2024-02-14 at 7 14 02 PM](https://github.com/epicmaxco/vuestic-ui/assets/17188599/93845e22-8c67-4312-b131-7789e2c4f9e0)

Two questions to answer from here:
1. Should the props' capitalization be normalized (and be able to handle lower case "monday")?
2. Should there be a better way of handling improper prop value for this?

**Comment by m0ksem** [comment]
I think we gonna need to make a wrapper around defineProps to prevent this kind of issues globally.

```ts
defineProps({
   firstWeekday: { type: String, lowercase: true }, // Prop will be always normalized to lowercase
   weeksize: { type: Number, allowString: true }, // allow weeksize="4" (string) and :weeksize="4" (number)
})
```

Not sure how to do it the best way right now, so we'll come back to it later.

**Comment by bagrovYKT** [comment]
> I was able to replicate this. The problem was not that the combination of the two props, but that "monday" needs to be capitalized in order for it to work correctly. ![Screenshot 2024-02-14 at 7 14 02 PM](https://private-user-images.githubusercontent.com/17188599/304911933-93845e22-8c67-4312-b131-7789e2c4f9e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDYwMzgsIm5iZiI6MTcwODMwNTczOCwicGF0aCI6Ii8xNzE4ODU5OS8zMDQ5MTE5MzMtOTM4NDVlMjItOGM2Ny00MzEyLWIxMzEtNzc4OWUyYzRmOWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAxMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZmE5OGQxMTE1ODYwNmZlYWFhYWQ3YmJhZmMwY2ZiYzBiZTcxYjlmYTYxNDEzYmEwYjcyMTYwMzMwOTk2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XrY12NhF4VXYKibPwdYALVsohIL476Uo5zYZrJpVYJ0)
> 
> Two questions to answer from here:
> 
> 1. Should the props' capitalization be normalized (and be able to handle lower case "monday")?
> 2. Should there be a better way of handling improper prop value for this?

Thanks for advice, in this case props works correctly, but i still think that this behavior is unexpectable.
