### ISSUE TITLE
[VaVirtualScroller] Wrongly generated name in npm package causes issues

### ISSUE THREAD

**Issue by asbermudez** [epicmaxco/vuestic-ui#4156]
**Vuestic-ui version:** from 1.9.x

### Description

The final distribution file name of the VaVirtualScroller contains url-encoded values due (probably) to some misconfiguration which causes in some instances (eg. vitest) to fail when trying to import the file, as the url-encoded characters get decoded and the filename does not match.

So in this specific case, the script is in this file name:
`VaVirtualScroller.vue_vue_type_script_setup_true_generic_Item%20%3D%20unknown_lang.mjs`
vs a correct component
`VaViewer.vue_vue_type_script_setup_true_lang.mjs`

So in my scenario, the resolver is trying to import `VaVirtualScroller.vue_vue_type_script_setup_true_generic_Item = unknown_lang.mjs` and therefore fails.

![Screenshot 2024-02-23 at 11 30 16](https://github.com/epicmaxco/vuestic-ui/assets/46224115/6e7d5640-9ea9-428d-ab88-30495ba8e165)

### Reproduction
In my case I am using nuxt with @nuxt/test-utils, jsdom and vite. When I create a test that contains a vuestic component it crashes because of the faulty import:

![Screenshot 2024-02-23 at 11 32 17](https://github.com/epicmaxco/vuestic-ui/assets/46224115/2353b348-19ef-431a-97a4-f772b52064b7)

**Comment by asbermudez** [comment]
Digging a bit more, seems the issue comes from the generic in the definition of the virtual scroller:

https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/va-virtual-scroller/VaVirtualScroller.vue#L34C1-L34C50

Not sure why the generated file name does incorporate the generic definition though. Probably a good idea to remove the default, as it doesn't really seem to be necessary for it to work.

**Comment by m0ksem** [comment]
We'll need to make a vite plugin which fixes this = symbol in file names to prevent this issue in future.

1. find all files with `%20%3D%20` in file name, replace them with `_eq_`.
2. find all files that includes regex `/import(.*)%20%3D%20/` and replace it with `import$1_eq_`.

**Comment by asbermudez** [comment]
@m0ksem I would recommend to have a URLDecode and then just replace spaces with _ or similar. The issue is that if you do a regex like that one it might miss some characters (like a semicolon, which is not invalid in the definition)

**Comment by m0ksem** [comment]
I think it is fixed... Feel free to reopen.
