### ISSUE TITLE
Issue when loading components

### ISSUE THREAD

**Issue by sivasyams** [epicmaxco/vuestic-ui#4158]
**Vuestic-ui version:** 1.8.1

### Description
I have the following code, which renders the form based on an array

`<template v-for="examSectionData in examDetail.examSectionList">
  <va-card class="col-span-12" squared outlined>
      <va-card-title>{{ examSectionData.questionSection.name }}</va-card-title>
      <va-card-content>
          <div class="grid grid-cols-12 gap-6">
              <div class="flex md:col-span-4 col-span-12">
                  <va-input type="number" label="Pass Marks"
                      v-model="examSectionData.passMark" />
              </div>
              <div class="flex md:col-span-4 col-span-12">
                  <va-input type="number" label="Timing (Minutes)"
                      v-model="examSectionData.sectionTimingMins" />
              </div>
              <div class="flex md:col-span-4 col-span-12">
                  <va-input type="number" label="No: Of Questions"
                      v-model="examSectionData.noOfQuestions" />
              </div>
          </div>
      </va-card-content>
  </va-card>
</template>`

The form is properly rendered when editing, but the va-input are not populated based on specified v-model value. The va-input will populate only when we click that particular va-input. It is not populated when rendering.

**Comment by m0ksem** [comment]
Hi, @sivasyams. Please, upgrade your vuestic ui version to 1.9.2 where we fixed this issue. 
You can read changelog here: https://ui.vuestic.dev/introduction/change-log#change-log to prevent any unexpected changes in your project.

Or you can add this to GlobalConfig as temp workaround if you don't want to upgrade right now
```ts
components: {
  VaInput: {
    mask: { blocks: [99999] }
  }
},
```
