### ISSUE TITLE
docs: DataTable sorting section write about disableClientSideSorting prop

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#4166]
Q:
> When re-using the code from the data-table sorting section (https://ui.vuestic.dev/ui-elements/data-table#sorting) the columns are not sorting when I click on the column names. It works on the documentation example but doesn't work in my project. 

A:
> Try to set disableClientSideSorting to true.
> 
> We mimic server-side sorting in VuesticAdmin and globally disabled client-side sorting in 
> vuestic-admin/src/services/vuestic-ui/global-config.ts
> 
> In case you're going to use client-side sorting in you project, you can remove this prop or set it to false.

To prevent user confusion.

Simply add something like "Data table uses client-side sorting by default, to prevent re-ordering two times (after cleint sorting and after server sorting) you can use `disableClientSideSorting`." - this is awful explanation from me! Make it better :)

**Comment by khurram-ansari** [comment]
@m0ksem is this explanation good?

_"By default, the data table utilizes client-side sorting. However, when using server-side sorting use the `disableClientSideSorting` prop to prevent dual re-ordering."_

**Comment by m0ksem** [comment]
> @m0ksem is this explanation good?
> 
> _"By default, the data table utilizes client-side sorting. However, when using server-side sorting use the `disableClientSideSorting` prop to prevent dual re-ordering."_

Yeah. I think it is so much better.
