### ISSUE TITLE
Icon display in offline state

### ISSUE THREAD

**Issue by All-The-Best-for** [epicmaxco/vuestic-ui#4178]
**Icon display in offline state**

**Hello, I would like to inquire about how to solve the problem of basic icons not displaying properly when using Vuestic UI offline. For example, the expand icon on the<VaSelect>tag will only display text when offline**

![Snipaste_2024-03-07_21-40-51](https://github.com/epicmaxco/vuestic-ui/assets/76414672/4738638c-3704-4d61-9ddc-a6c96ed0fb00)

**Comment by m0ksem** [comment]
You can download Material Symbols instead of loading them from CDN from here:
https://github.com/marella/material-symbols/tree/main/material-symbols#readme

**Comment by All-The-Best-for** [comment]
Thank you very much for your reply. I have resolved the issue. Thank you!

**Comment by All-The-Best-for** [comment]
> You can download Material Symbols instead of loading them from CDN from here: https://github.com/marella/material-symbols/tree/main/material-symbols#readme

Thank you very much for your reply. I have resolved the issue. Thank you!
