### ISSUE TITLE
VaPopover CSS variables overriding not working

### ISSUE THREAD

**Issue by AlexFilipovici** [epicmaxco/vuestic-ui#4182]
**Vuestic-ui version:** 1.8.8

### Description

The VaPopover style is not overwritten by CSS variables.

### Reproduction
https://ui.vuestic.dev/play#eNp9Uk1P3DAQ/SupzziRyi1NkUqF1PbQohb15ItJhmDwlzzjdCna/45jr5ddhPYU5b15b97M+Jl98b5dIrCeDQTGa0lwIWzTDH/ltfNugdCMWiJ+Fsw8cV8gwRoDiHKGBNcygg0JlsVZfhmJnL34lkkDQ7eHsn/63Slrv8IetrvNSDK9AaQjg6E7SDsgPekSu30N2TyXKJwvsmJ8dJbAEr+V4+McXLRTgrQLfRNgaj4o410gaenTCe1d+nJU/6FvPgYwb1XbmqOkP4pRIO7lNCk7F30VDV0Zg52xYsiN9O0DOpuOk03EjkDB+morWLoekhp5VCss2D2Rx77roloPu1LtBEtXy1ykzkhlk7Ngu9bb1JMwzXen5jcdR2e80hB+eVLOHneWWrt/PzJGIcJZxcd7GB/fwR9wUyJeB0AICwi250iGGdL7WemrPz/zW9qTxk1Rp+oT5G9Ap+OasZRdptOm2Ad1Oe33vMC0+xu82qRrYh1qDZq3kevzVr+eGP017nl7vt/i9gV/Ih3y

**Comment by m0ksem** [comment]
It is not gonna work, because popover content is teleported into document.body. 
We'll need to add content-class, which will be applied to va-popover__content html element.

**Comment by gweesin** [comment]
> It is not gonna work, because popover content is teleported into document.body. We'll need to add content-class, which will be applied to va-popover__content html element.

But currently, we use a `color` prop to change the background color, the feature of the `content-class` prop will cause a breaking change, should we do this?
I'm glad to do it if you think it's necessary.

**Comment by m0ksem** [comment]
> > It is not gonna work, because popover content is teleported into document.body. We'll need to add content-class, which will be applied to va-popover__content html element.
> 
> But currently, we use a `color` prop to change the background color, the feature of the `content-class` prop will cause a breaking change, should we do this? I'm glad to do it if you think it's necessary.

Currently, `color` prop works as expected. We will not change it. The problem only with class and css variables.
