### ISSUE TITLE
Modal Form for Vuestic UI Landing page

### ISSUE THREAD

**Issue by zvenigorodskaia** [epicmaxco/vuestic-ui#4265]
Develop a modal form designed to collect emails from users interested in a free Vue.js code audit offered by the Vuestic Core Team. The form should engage users effectively, ensure user consent for data processing, and comply with best practices for user interaction.

Requirements:
- - only for https://ui.vuestic.dev/ (landing) not for docs
- Include a close button (X icon) at the top right of the modal.

- Content:
  -- Header: "Get a Free Vue.js Code Audit from Vuestic Core Team".
 -- Text: "Got a Vue.js project and want to make it better? Provide us with some details about your project, and we'll get back to you within 24 hours."
 -- Email input field
 -- CAPTCHA verification
 -- Submit button
 -- Text under the Submit button:
"Click 'Submit!' to consent to processing your data by Epicmax Georgia LLC for marketing purposes, including sending emails. For details, see our Privacy Policy."

Link for privacy: https://www.iubenda.com/privacy-policy/50799764

Functional Requirements:
The modal should not appear immediately upon page load. Implement a delay mechanism like:

<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.min.js"></script>
<script>
const delay = 5; // Pop-up delay in seconds
const popupId = "pop-up-wrapper"; // Pop-up ID name

$(document).ready(function() {
   if (!Cookies.get('alert')) {
     setTimeout(function() {
       document.getElementById(popupId). style.display = "flex";
       Cookies.set('alert', true, { expires: 1 });
     }, delay * 1000);
   }
});
</script>

Ensure the modal respects user privacy and cookie settings to prevent repeated displays to the same user within a given timeframe.

Example: 
![image](https://github.com/epicmaxco/vuestic-ui/assets/35342240/1621722d-d07d-4cdc-8f60-afd1f5e6ecfe)

Image for the right section here:
![Got a Vue js project and want to make it better Provide us with some details about your project, and we'll get back to you within 24 hours](https://github.com/epicmaxco/vuestic-ui/assets/35342240/0921fe66-b7f8-4b9d-b552-492856a9bae4)

**Comment by asvae** [comment]
Can we also limit this form to Europe and America?

Same for https://github.com/epicmaxco/vuestic-admin/issues/1037

I think the easiest approach would be to use some geolocation service, but up to you.
Maybe `Intl.DateTimeFormat().resolvedOptions().timeZone` will be good enough.

We also need to update webflow implementation to do the same. You can do it yourself or ping me and I'll do it.
