### ISSUE TITLE
file upload

### ISSUE THREAD

**Issue by All-The-Best-for** [epicmaxco/vuestic-ui#4282]
How can I modify the alarm information caused by type errors during file upload?
I want to customize these alarm messages
Thanks

![image](https://github.com/epicmaxco/vuestic-ui/assets/76414672/c67b3296-42c3-4a96-84f4-0792e5215596)

![image](https://github.com/epicmaxco/vuestic-ui/assets/76414672/afe188fb-e5ab-41c2-a5ac-bcb579c655ec)

**Comment by All-The-Best-for** [comment]
I also want to know how to control the number of uploaded files, for example, when only one file is required to be uploaded, if the user uploads a file, the upload function will be disabled unless the user deletes the uploaded file. But the existing disable props will also disable the delete button

**Comment by All-The-Best-for** [comment]
> I also want to know how to control the number of uploaded files, for example, when only one file is required to be uploaded, if the user uploads a file, the upload function will be disabled unless the user deletes the uploaded file. But the existing disable props will also disable the delete button

Suggest adding a 'limit' prop

**Comment by All-The-Best-for** [comment]
` <VaFileUpload
      v-model="cardLocal.file"
      dropzone
      file-types="txt"
      aria-label="upload"
      drop-zone-text="dropzone"
      undo="undo"
      undo-duration="1000"
      type="list"
      :file="cardLocal.oneFile"
      :files="cardLocal.fileData"
      @file-added="addFile"
    />`

After uploading a file in this component, I can only obtain partial information about the file, such as name, type, etc. However, how can I obtain the content or address of this file?

![image](https://github.com/epicmaxco/vuestic-ui/assets/76414672/c102f4d5-67bc-4bb2-8a6c-0e15236f766f)

**Comment by m0ksem** [comment]
> I also want to know how to control the number of uploaded files, for example, when only one file is required to be uploaded, if the user uploads a file, the upload function will be disabled unless the user deletes the uploaded file. But the existing disable props will also disable the delete button

There is no native way to control how many files can be selected (at least, I don't know about it). So you need to add validation yourself. You can use VaFormFiled to use FileUpload in pair with useForm if needed.

**Comment by m0ksem** [comment]
> ` <VaFileUpload v-model="cardLocal.file" dropzone file-types="txt" aria-label="upload" drop-zone-text="dropzone" undo="undo" undo-duration="1000" type="list" :file="cardLocal.oneFile" :files="cardLocal.fileData" @file-added="addFile" />`
> 
> After uploading a file in this component, I can only obtain partial information about the file, such as name, type, etc. However, how can I obtain the content or address of this file?
> 
> ![image](https://private-user-images.githubusercontent.com/76414672/332833576-c102f4d5-67bc-4bb2-8a6c-0e15236f766f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODgzNDIsIm5iZiI6MTcxNjQ4ODA0MiwicGF0aCI6Ii83NjQxNDY3Mi8zMzI4MzM1NzYtYzEwMmY0ZDUtNjdiYy00YmIyLThhNmMtMGUxNTIzNmY3NjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4MTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxOGRmY2JkNGQ4ZTZiYjM3NWJkOWIyNmM3Zjc4Y2RlMzNhZTY0Y2ViOGZhYjk1ZjE5Zjc0ZjA5YzBjMzNmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NlzdQcAkTvWiUVexgCxhAU7dI3GiPBI6Ym82QXloi9k)

You need to use something like FileReader browser API if you want to get file text content.

**Comment by m0ksem** [comment]
`fileIncorrectMessage` prop and `fileTypeIncorrect` i18n config key will be available in 1.9.11.

**Comment by EugenGedroyc** [comment]
I can not modify the alarm information: [example](https://ui.vuestic.dev/play#eNp9Us1OGzEQfhXLp1bKZg/c0rRSW1GpHKAqbS/dHtzdyeLgtS17HAIoEkLceAbeASFxQAKeYfNGjNfZ8CPEaWfmm/nmm299zD9bO5wF4CM+RmisEgifCs3Y+I/4JhX8tsqIKhYYm2WNqUB9LPh/4WVZ8FSunLFHRkPKJjSUSV0a56DErAHvRQ0001601+1Ve708ae+W5+0NW56195TctpfLU7a1u7PdE3YUeGjB09jU1gOr64TlJG2cP9FJqS+dtEgxzK1xyCqYiKCQHceBSqB49z7FjDnA4HSfMdadMWJ//w1SZfEhfheUxWicr6n5gMsmsmeNsMOpN5r86miKFeALPuqJC06GepRlFmQsF3wP0fpRngcZvY7QsIJZ3reZgHkjpCbmdOeCFNBO9KXRE1m/2FiaxpJFbseiNPr5ZqGUOdjqaugCrA6jmT0o91+pT/08SfzhwIObQcHXGApXAyZ4c3cb5hSvQXoKQVH3G+BP8EaFqDG1fQm6ItlP+jq13zsDpa5/+c05gvb9UVFo/0NWrn594/RHuRvDjbWLiwcqKP2h)
