### ISSUE TITLE
File upload - error when uploading images

### ISSUE THREAD

**Issue by dolmira** [epicmaxco/vuestic-ui#430]
* **What is the current behavior?**
<va-file-upload 
 type="gallery"
 dropzone
 v-model="advancedGallery"
 fileTypes=".png, .jpg, .jpeg, .gif"
/>
When I set fileTypes, I get an error "e.filter is not a function".

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
The error is reproduced on https://vuestic.epicmax.co/admin/ui/file-upload

![vuestic-upload-image](https://user-images.githubusercontent.com/46607568/94666970-d6a16f80-0316-11eb-82fc-75ab836ef5b8.png)

**Comment by asvae** [comment]
Doesn't reproduce on vuestic ui. So likely solved.
We'll update vuestic-admin with release.
