### ISSUE TITLE
Add ability to customize the color of "block-color"

### ISSUE THREAD

**Issue by pogrib0k** [epicmaxco/vuestic-ui#4308]
# Problem

In dark theme, I need to change one style, but I found that it can't be changed in vuestic config.

#### I want to change this element color:

![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/9f21a328-4bcc-4736-8e94-1a4e2ea988fe)

![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/49770d24-6839-4249-8557-85abf10df5a6)

# Desired solution

I need the ability in vuestic config to customize the color of `block-color`.

### Like this: 

![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/5462acad-5958-462d-a180-2f705dcd5049)

**Comment by Us3r-gitHub** [comment]
Have you tried this?

```ts
createVuesticEssential({
    config: {
      colors: {
        presets: {
          dark: {
            backgroundElement: "",
          },
        }
      }
    }
  })
```

According to the [docs](https://ui.vuestic.dev/ui-elements/card#css-variables)
Uses backgroundElement CSS Variable

**Comment by pogrib0k** [comment]
> Have you tried this?
> 
> ```ts
> createVuesticEssential({
>     config: {
>       colors: {
>         presets: {
>           dark: {
>             backgroundElement: "",
>           },
>         }
>       }
>     }
>   })
> ```
> 
> According to the [docs](https://ui.vuestic.dev/ui-elements/card#css-variables) Uses backgroundElement CSS Variable

Thank you. This solved my problem.
But this parameter also changed the background color of the switch, which is normal in my case, but perhaps it’s still worth adding the ability to specifically change the border color.

**Comment by Us3r-gitHub** [comment]
I think we can't change css variables for `block-border`, it used for default values

Maybe, we can apply [component preset config](https://ui.vuestic.dev/services/components-config#presets-config)
```TS
createVuesticEssential({
  config: {
    components: {
      presets: {
        VaCard: {
          outlinedBlack: {
            square: true,
            outlined: true,
            style: "border: 3px solid #000000",
          },
        },
      },
    },
  },
});
```

Component Usage
```Vue
<VaCard preset="outlinedBlack">
  <VaCardTitle>square and outlined</VaCardTitle>
  <VaCardContent>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  </VaCardContent>
</VaCard>
```

**Comment by Us3r-gitHub** [comment]
> I think we can't change css variables for `block-border`, it used for default values
> 
> Maybe, we can apply [component preset config](https://ui.vuestic.dev/services/components-config#presets-config)
> 
> ```ts
> createVuesticEssential({
>   config: {
>     components: {
>       presets: {
>         VaCard: {
>           outlinedBlack: {
>             square: true,
>             outlined: true,
>             style: "border: 3px solid #000000",
>           },
>         },
>       },
>     },
>   },
> });
> ```
> 
> Component Usage
> 
> ```
> <VaCard preset="outlinedBlack">
>   <VaCardTitle>square and outlined</VaCardTitle>
>   <VaCardContent>
>     Lorem ipsum dolor sit amet, consectetur adipiscing elit.
>   </VaCardContent>
> </VaCard>
> ```

But it cannot adjust to the theme currently applied (dark or light theme)

**Comment by m0ksem** [comment]
This CSS variable mustn't be hard coded. It must use CSS variable from colour scheme. Like `--va-block-color: var(--va-background-element)`.

**Comment by Us3r-gitHub** [comment]
I found CSS is hard coded like this `--va-block-border: thin solid rgba(52, 56, 85, 0.25);`
Can we change it to `--va-block-border: thin solid var(--va-background-border);`?

OR

According to [doc](https://ui.vuestic.dev/ui-elements/card#css-variables)
I think we can use `--va-background-border` for `--va-card-outlined-border`
Is there any reason to use the `--va-background-element` for this?

**Comment by Us3r-gitHub** [comment]
May i take this task?

**Comment by m0ksem** [comment]
> I found CSS is hard coded like this `--va-block-border: thin solid rgba(52, 56, 85, 0.25);` Can we change it to `--va-block-border: thin solid var(--va-background-border);`?
> 
> OR
> 
> According to [doc](https://ui.vuestic.dev/ui-elements/card#css-variables) I think we can use `--va-background-border` for `--va-card-outlined-border` Is there any reason to use the `--va-background-element` for this?

This must be definitely background-border.
