### ISSUE TITLE
Checkbox bug

### ISSUE THREAD

**Issue by igorprodev1** [epicmaxco/vuestic-ui#431]
* **What is the expected behavior?**
The checkbox remains in place

* **What is the current behavior?**
The checkbox jumps up after checking and jumps down after unchecking
![captured (1)](https://user-images.githubusercontent.com/55927944/94714720-328ae900-0355-11eb-8a9e-8c39ccfdcd1c.gif)

**Comment by Kushich** [comment]
@igorprodev1 Issue with [vue-book](https://github.com/epicmaxco/vuestic-ui/issues/360). This package uses vuestic components and rewrites styles

**Comment by asvae** [comment]
Worth noting it shouldn't be that fat.
