### ISSUE TITLE
Vuestic i18n has unnecessary console warning

### ISSUE THREAD

**Issue by pogrib0k** [epicmaxco/vuestic-ui#4326]
**Vuestic-ui version:** 1.9.11

### Description
I used "i18n" and started getting warnings in the console about the wrong configuration for "vuestic-i18n".

![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/b7916d9e-3522-4ea8-9ec0-1355a7553bf9)

To fix this, I need to add the i18n vuestic locale, which may be unnecessary.

Or, at least on the documentation page, provide an option to copy the required locales as an object. Now it looks like this:

![image](https://github.com/epicmaxco/vuestic-ui/assets/58943459/018acba7-9ef7-4e38-a89e-eac3f19aa106)

Otherwise, you have to use the chat-GPT to get it:
```
{
  "back": "Previous",
  "backToTop": "back to top",
  "breadcrumbs": "breadcrumbs",
  "cancel": "Cancel",
  "carousel": "carousel",
  "close": "close",
  "closeAlert": "close alert",
  "closeToast": "close toast",
  "color": "color",
  "colorName": "color {color}",
  "colorSelection": "color selection",
  "counterValue": "counter value",
  "currentRating": "current rating {value} of {max}",
  "decreaseCounter": "decrease counter",
  "dropzone": "Drop files here to upload",
  "fileDeleted": "File deleted",
  "fileTypeIncorrect": "File type is incorrect",
  "finish": "Finish",
  "goLastPage": "go last page",
  "goNextPage": "go next page",
  "goNextSlide": "go next slide",
  "goPreviousSlide": "go previous slide",
  "goSlide": "go slide {index}",
  "goToPreviousPage": "go to the previous page",
  "goToSpecificPage": "go to the {page} page",
  "goToSpecificPageInput": "enter the page number to go",
  "goToTheFirstPage": "go to the first page",
  "increaseCounter": "increase counter",
  "inputField": "Input field",
  "loading": "Loading",
  "movePaginationLeft": "move pagination left",
  "movePaginationRight": "move pagination right",
  "next": "Next",
  "nextPeriod": "next period",
  "noOptions": "Items not found",
  "noSelectedOption": "Option is not selected",
  "ok": "OK",
  "openColorPicker": "open color picker",
  "optionsFilter": "options filter",
  "pagination": "pagination",
  "previousPeriod": "previous period",
  "progress": "progress",
  "progressState": "progress state",
  "removeFile": "remove file",
  "reset": "reset",
  "resetDate": "reset date",
  "resetTime": "reset time",
  "search": "Search",
  "select": "Select an option",
  "selectAllRows": "select all rows",
  "selectedDate": "selected date",
  "selectedOption": "Selected option",
  "selectedTime": "selected time",
  "selectRowByIndex": "select row {index}",
  "slideOf": "slide {index} of {length}",
  "sliderValue": "Current slider value is {value}",
  "sortColumnBy": "sort column by {name}",
  "splitPanels": "split panels",
  "step": "step",
  "switch": "Switch",
  "switchView": "switch view",
  "toggleDropdown": "toggle dropdown",
  "undo": "Undo",
  "uploadFile": "Upload file",
  "voteRating": "vote rating {value} of {max}"
}

```

**Comment by m0ksem** [comment]
These warnings might be useful. If you use vue-i18n you must be forced to fill translations.

**Comment by dev-lep** [comment]
I'm not using i18n yet still get these warnings since the last update.
![image](https://github.com/epicmaxco/vuestic-ui/assets/96597209/082e767a-6330-4dc0-9749-0a5fd17e1112)
![image](https://github.com/epicmaxco/vuestic-ui/assets/96597209/ce9984cf-52cb-43a0-b42e-a20f24299919)
main.ts:20 is app.use(router) my Vue Router file

**Comment by m0ksem** [comment]
> I'm not using i18n yet still get these warnings since the last update. ![image](https://private-user-images.githubusercontent.com/96597209/342936417-082e767a-6330-4dc0-9749-0a5fd17e1112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTI2ODksIm5iZiI6MTcxOTM5MjM4OSwicGF0aCI6Ii85NjU5NzIwOS8zNDI5MzY0MTctMDgyZTc2N2EtNjMzMC00ZGMwLTk3NDktMGE1ZmQxN2UxMTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZThmZDc4YWIwZmNhYjJiNjMyODg5M2ZiYjhlYTA3OTAxYWJkOWRkOWE4MjIyZmI0YmZhZjQ2YzZmOTZmOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C-xo6tpA-B7ajQHq64y9l6YRPQM_0uCODQsku0DuwBQ) ![image](https://private-user-images.githubusercontent.com/96597209/342936476-ce9984cf-52cb-43a0-b42e-a20f24299919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTI2ODksIm5iZiI6MTcxOTM5MjM4OSwicGF0aCI6Ii85NjU5NzIwOS8zNDI5MzY0NzYtY2U5OTg0Y2YtNTJjYi00M2EwLWI0MmUtYTIwZjI0Mjk5OTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA4NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOWY1NTA3ZDFhN2IyODYyMzkyZmYwMzFlNDM2M2EwOGY1YWRmYTlkZTgwYzlmOWQ1YTljMjQ3OWY4YmU5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ZX_55GNf0UXx3EFdizc1G9QAIwrDiDwLNd_Pz9fauk) main.ts:20 is app.use(router) my Vue Router file

This one is fixed here: https://github.com/epicmaxco/vuestic-ui/commit/1cfac5601e2cd1fa1e330b768fe15f99784be8ba

I hope to build a new version today.
