### ISSUE TITLE
Things are too small on mobile

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#433]
Looks now:
![image](https://user-images.githubusercontent.com/5394573/94871179-17ea6a00-0452-11eb-8840-54bbb3b710a7.png)

Should look:
![image](https://user-images.githubusercontent.com/5394573/94871210-246ec280-0452-11eb-82fc-604a5a114086.png)

**Comment by Kushich** [comment]
I think  we need to finish [this](https://github.com/epicmaxco/vuestic-ui/issues/339) before refactoring the docs page

**Comment by asvae** [comment]
@Kushich Pretty sure that needs some small fix in header. So no relation to anything else.
