### ISSUE TITLE
va- prefix is not ideal

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#438]
Think of other prefixes. VA is not ideal as it has nothing to do with admin project.

**Comment by Kushich** [comment]
@asvae Maybe “vu” or “vs”? How many letters can we use?

**Comment by asvae** [comment]
Hmm. I was pretty sure `vu` was taken, but can't find anymore.

**Comment by kushich** [comment]
@asvae Still actual after release?

**Comment by m0ksem** [comment]
I think it's too late for this issue. 😁
@asvae

**Comment by haoyun** [comment]
`daisyui` allows users to specify the prefix: https://daisyui.com/docs/config/. It provides lots of flexibility.

**Comment by m0ksem** [comment]
> `daisyui` allows users to specify the prefix: [daisyui.com/docs/config](https://daisyui.com/docs/config/). It provides lots of flexibility.

Do you need this kind of feature? I don't think anyone would need Va prefix available.
