### ISSUE TITLE
Select updateSearch event ignores minSearchChars

### ISSUE THREAD

**Issue by beard7** [epicmaxco/vuestic-ui#4386]
**Vuestic-ui version:** 1.10.2

### Description

I'm hooking up a Select with a remote datasource and I need to implement remote searching. I'm using the updateSearch event to trigger remote filtering on the API, but the updateSearch event is triggered on the first character entered.

I know there's a simple workaround, but it shouldn't be necessary.

**Comment by m0ksem** [comment]
minSearchChars is used for client-side search.

update:search is used as v-model, therefore it will be always fire when search field is updated. It allows you to have search state controlled outside of VaSelect component.
