### ISSUE TITLE
VaTreeView disabled in checkbox changes the style but still able to uncheck and check

### ISSUE THREAD

**Issue by anviksuteiriy** [epicmaxco/vuestic-ui#4412]
![Screenshot from 2024-10-28 21-08-44](https://github.com/user-attachments/assets/b6a075bd-cac4-480b-bc64-42022ea1de34)

below unchecked the same disabled one 

![Screenshot from 2024-10-28 21-09-21](https://github.com/user-attachments/assets/07cff4c7-9fb9-413c-8369-7e85078a4139)

**Vuestic-ui version:** 1.10.3

**Comment by m0ksem** [comment]
closed here: https://github.com/epicmaxco/vuestic-ui/pull/4425

**Comment by anviksuteiriy** [comment]
hey @m0ksem is it released ?
