### ISSUE TITLE
Help me! Can't find where is filter in the context for select

### ISSUE THREAD

**Issue by 104260033** [epicmaxco/vuestic-ui#4416]
In below
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/d0877c65-8034-47be-9590-f5934976e841">

**Comment by m0ksem** [comment]
You may want to look into `searchFn`.

**Comment by 104260033** [comment]
I've found it ,but i didn't find it in the component's property

**Comment by m0ksem** [comment]
Let's move it to discord discussion.
