### ISSUE TITLE
[Vue warn]: Maximum recursive updates exceeded in component <VaDropdown>.

### ISSUE THREAD

**Issue by phamquangvinhfpt** [epicmaxco/vuestic-ui#4443]
### Description
When using dropdown components (VaDropdown, VaDateInput) in our mobile interface, i was encountering serious performance issues and UI freezing. Two main problems have been identified:

1. Maximum recursive updates error is consistently triggered:
2. Mobile-specific UI issues:
- Dropdowns don't properly disappear after selection
- UI becomes unresponsive
- Performance significantly degrades compared to desktop version
- Component states become "stuck"
### Example Code
```vue
<VaDropdown
  v-model="doShowDropdown"
  trigger="none"
  :offset="[13, 0]"
  stick-to-edges
>
  <template #anchor>
    <VaButton @click="doShowDropdown = !doShowDropdown">
      <!-- Content -->
    </VaButton>
  </template>
</VaDropdown>
<VaDateInput
          v-model="formData.birthDay"
          :rules="birthDayRules"
          class="w-full"
          :label="t('auth.birthDay')"
          clearable
        />

**Comment by phamquangvinhfpt** [comment]
So anyone get same like me? :(

**Comment by phamquangvinhfpt** [comment]
btw i am using vue 3.3.9

**Comment by m0ksem** [comment]
> btw i am using vue 3.3.9

Hi. Try upgrading your vue version. 

See: https://github.com/epicmaxco/vuestic-ui/issues/4339#issuecomment-2218058182
