### ISSUE TITLE
Nuxt tabs no active

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#449]
`va-tab--active` doesn't work for serverside rendering.
The problem is that for nuxt children could be compiled after parent, which is not the case for standard vue compilation. (not 100% sure I'm right)

We probably need a stricter way of registration. (i.e. see vuetify [registrable mixin](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/registrable/index.ts))

**Comment by asvae** [comment]
Low priority because vuestic ui won't support nuxt on 1.0.

**Comment by m0ksem** [comment]
Old task. It works with nuxt3 now.
