### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#45]
# Docs

- [ ] Do after [docs boilerplate](#17) is done.

### Props
- [x] `value: Number` - default: 0 - index of active slide
- [x] `autoplay: Boolean` - whether to scroll automatically
- [x] `autoplay-interval (*): Number` - default: 3000 - interval of the auto loop, in milliseconds
- [x] `loop: Boolean` - display the items in loop
- [ ] `height: String` - default: `auto` - the height of the carousel
- [x] `dots: Boolean` - show navigation dots
- [x] `arrows: Boolean` - show navigation arrow buttons
- [ ] `trigger (*): String` - default: 'click' - the way to activate the indicator. Optional value: click, hover.
- [ ] `effect: String` - default: `fade` - transition effect
- [ ] `vertical (*): Boolean` - whether to use a vertical display

### Slots
- [x] `default`
- [x] `control` - slot specific for carousel control

### Events
- [x] `input` - emitted when component's model changes

### Methods
- [x] `goTo` - go to specific panel
- [x] `next` - go to next panel
- [x] `prev` - go to previous panel

### Props
- [x] `name: String` - name of the item, can be used in goTo
- [x] `src: String`
- [x] #921

### Slots
- [x] `default`

# Design
- [ ] Present to @xx13 after finishing.

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/carousels)
* [Quasar](https://quasar.dev/vue-components/carousel)
* [Ant Design](https://vue.ant.design/components/carousel/)
* [iView](http://iview.talkingdata.com/#/components/carousel-en)
* [Element UI](https://element.eleme.io/#/en-US/component/carousel)

**Comment by asvae** [comment]
We need to figure out what's the status of this issue.

**Comment by m0ksem** [comment]
closed in  #1432
