### ISSUE TITLE
docs navigation text should keep size

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#453]
Make text keep size. (not jump around)

![2020-10-20_15-56-55](https://user-images.githubusercontent.com/5394573/96588983-f65ffe00-12ec-11eb-82ef-19228b0c2228.gif)

**Comment by Kushich** [comment]
In my case it works correctly
![ZnRDqDCXZd](https://user-images.githubusercontent.com/45711229/97398304-059e0780-18fc-11eb-9d17-352bc53db214.gif)
