### ISSUE TITLE
Compatibility with admin

### ISSUE THREAD

**Issue by Kushich** [epicmaxco/vuestic-ui#467]
There are issues that we must solve:
- [ ] Dropdown is broken
- [x] Button paddings
- [x] Inner Loading width (fit-content & 100%)
- [x] List structure
- [x] Card structure
- [x] Card strip & strip color must be one prop
- [x] Default icons config for components
- [x] Badge docs page
- [ ] Badge outline style
- [x] Rename va-tag to va-chip
- [x] Rename va-expand to va-collapse
- [x] Rename va-expand-group to va-accordion
- [x] Fix tree view state
- [x] Import va-spacer
- [x] Add default white color to card
- [x] Change default ColorMixin color
...

**Comment by m0ksem** [comment]
Subtask "Dropdown is broken" steps to reproduce,

![f8qeq5WTQz](https://user-images.githubusercontent.com/23530004/108089873-b9c9c680-7082-11eb-9f1d-e5e77220d8a6.gif)
