### ISSUE TITLE
Move docs to vue-cli temporarily

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#486]
Currently docs are using nuxt. And nuxt doesn't support vue 3 as of yet.
So we want to temporarily move documentation from nuxt to vue-cli.

- [x] Ideally keep nuxt stuff intact.
- [ ] Make documentation run on vue-cli with idea that it's going to be removed (and it's not public, so hacks are fine). Ideal solution would be if vue-cli stuff will be just located in separate folder

* Don't spend too much time on this to reach perfection. As long as it's working - it's fine.

**Comment by eqxs** [comment]
first version is ready #510, but need to do some improvements and fixes #512
