### ISSUE TITLE
Vue 3 plugin connection error

### ISSUE THREAD

**Issue by damirJa** [epicmaxco/vuestic-ui#491]
* **What is the expected behavior?**

I've been trying to connect and use plugin Vue3 version in the CodeSand box like this
```
import { createApp } from "vue";
import App from "./App.vue";
import { VuesticPlugin } from "vuestic-ui";

const app = createApp(App);
app.use(VuesticPlugin);
app.mount("#app");
```

* **What is the current behavior?**
I get the error
<img width="625" alt="Screen Shot 2021-01-18 at 12 30 42 PM" src="https://user-images.githubusercontent.com/10356386/104884933-fe314c00-5988-11eb-925c-a0b03349a8db.png">

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
You could check it here - https://codesandbox.io/s/dreamy-fermat-nkrej?file=/src/main.js

* **Other information**
Using Vue 3 and latest Vuestic build "1.0.0-alpha.11"

**Comment by asvae** [comment]
@m0ksem can you check if it's still relevant?

**Comment by m0ksem** [comment]
> 
> 
> @m0ksem can you check if it's still relevant?

Issue fixed.  Tested for `1.0.0-alpha.15`.
