### ISSUE TITLE
Config requires more comments

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#504]
You may want to comment pretty much every line.

https://github.com/epicmaxco/vuestic-ui/pull/495/files?file-filters%5B%5D=.hbs&file-filters%5B%5D=.html&file-filters%5B%5D=.ico&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.md&file-filters%5B%5D=.png&file-filters%5B%5D=.scss&file-filters%5B%5D=.ts&file-filters%5B%5D=.vue&file-filters%5B%5D=dotfile&hide-deleted-files=true#diff-e8960f75e553c83cf6d770c58e9bdff5967dfb1875cf65f17948363ecbdc8876

**Comment by Derranion** [comment]
Hey @asvae 

Could you tell - is this still relevant?

We have changed this logic here:
https://github.com/epicmaxco/vuestic-ui/pull/1634

Currently it consists mainly of 3 files:
https://github.com/epicmaxco/vuestic-ui/blob/release/v1.4.0/packages/ui/src/services/config-transport/createProxyComponent.ts
https://github.com/epicmaxco/vuestic-ui/blob/release/v1.4.0/packages/ui/src/services/config-transport/withConfigTransport.ts
https://github.com/epicmaxco/vuestic-ui/blob/release/v1.4.0/packages/ui/src/services/component-config/component-config.ts
(absolute path can be used if it was already merged)

I can do this if we need it.

**Comment by asvae** [comment]
Not relevant anymore :)
