### ISSUE TITLE
va-button doesn't use vue-router history mode as expected

### ISSUE THREAD

**Issue by eqxs** [epicmaxco/vuestic-ui#515]
* **What is the expected behavior?**
after clicking on the button, the location should be changed without reloading

* **What is the current behavior?**
after clicking on the button, the location changes with reloading

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
[codesandbox](https://codesandbox.io/s/qye05?file=/src/App.vue)
[website](https://vuestic-test.vercel.app)
play with buttons:
![image](https://user-images.githubusercontent.com/20516743/107748142-a4bf0180-6d29-11eb-9c7d-211d4ae8888e.png)

* **Other information**

**Comment by eqxs** [comment]
the same issue with `va-list-item`

**Comment by m0ksem** [comment]
The same issue with `va-card`, `va-chip`, `va-tab`. Maybe we need to make Readme.md file near RouteLinkMixin to prevent such issues.
