### ISSUE TITLE
VaButton slightly increases its size and moves other elements 

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#520]
## What is the expected behavior?
The button should be resizable only visually and should not affect siblings

## What is the current behavior?
During click button size increases by 1px 

## Steps to reproduce, ideally also a screenshot or gif if it's a style issue
![y2shDuUgLE](https://user-images.githubusercontent.com/23530004/108089051-d9142400-7081-11eb-9c1d-be20eec9624a.gif)

**Comment by asvae** [comment]
@m0ksem pretty sure that's because border is set to none somewere. Instead, border should be `transparent`, but keep size. That will prevent jumpy behavior.
