### ISSUE TITLE
Chat component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#53]
# Docs

- [ ] Do after [docs boilerplate](#17) is done.

# Props
- [ ] `sent: Boolean` - render as a sent message (so from current user, normally places on the right side)
- [ ] `text: Array` - array of strings that are the message body. Each string will be placed in new container.
- [ ] `name: String` - author's name
- [ ] `label: String` - renders a label header/section
- [ ] `color: String` - color (from theme plugin) for chat bubble background
- [ ] `text-color: String` - color (from the theme plugin) for chat bubble text
- [ ] `avatar: String` - url to the avatar image of the author
- [ ] `stamp: String` - creation timestamp

# Slots
- [ ] `default` - slot to define a custom message 
- [ ] `avatar` - slot for avatar

# Design
- [ ] Present to @xx13 after finishing.

# Refs
* [Quasar](https://quasar.dev/vue-components/chat)

**Comment by asvae** [comment]
Moved to vuestic-admin: https://github.com/epicmaxco/vuestic-admin/issues/834
