### ISSUE TITLE
Extract SCSS for components.

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#530]
3 ways here. 1st is better, but likely impossible. Spend an hour or so to ensure it's not doable.

* If we manage to extract SCSS from component without splitting it up - that's great.
* Use css variables only instead. Not really sure how flexible of a solution that is. Worth noting that we don't support ie11, so we don't need polyfills.
* If it's not possible - split component into 2 parts - scss and vue component.

**Comment by asvae** [comment]
2 ways here. 1st is better, but likely impossible. Spend an hour or so to ensure it's not doable.

* If we manage to extract SCSS from component without splitting it up - that's great.
* If it's not possible - split component into 2 parts - scss and vue component.

**Comment by untael** [comment]
Extracted as css variables.
