### ISSUE TITLE
VaInput uses the class twice

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#533]
* **What is the expected behavior?**
![изображение](https://user-images.githubusercontent.com/23530004/109024464-7ac0f400-76c6-11eb-95e9-a1f30ea217a5.png)
![изображение](https://user-images.githubusercontent.com/23530004/109024578-95936880-76c6-11eb-8887-590f4a699f41.png)

* **What is the current behavior?**

![изображение](https://user-images.githubusercontent.com/23530004/109024637-a0e69400-76c6-11eb-9a58-e6fff5643037.png)
![изображение](https://user-images.githubusercontent.com/23530004/109024828-d0959c00-76c6-11eb-9590-276680c70d60.png)

**Comment by asvae** [comment]
@m0ksem confirming that.

classes like 'mb-4' should *never* be used inside of component. Instead, scss variables or mixins should be a source of reuse.
