### ISSUE TITLE
VaTimeline throws error if RawSlots passed.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#534]
* **What is the expected behavior?**
```
  <va-timeline vertical>
    <va-timeline-item
      :active="false"
    >
      <template #before>
        <span
        class="va-timeline-item__text"
        :class="{ 'title': item, 'title title--gray': !item }"
        >
          Before text
        </span>
      </template>
      <template #after>
        <span
          class="va-timeline-item__text"
          :class="{ 'title': item, 'title title--gray': !item }"
        >
          After text
        </span>
      </template>
    </va-timeline-item>
    <va-timeline-item
      :active="false"
    >
      <template #before>
        <span
        class="va-timeline-item__text"
        :class="{ 'title': item, 'title title--gray': !item }"
        >
          Before text
        </span>
      </template>
      <template #after>
        <span
          class="va-timeline-item__text"
          :class="{ 'title': item, 'title title--gray': !item }"
        >
          After text
        </span>
      </template>
    </va-timeline-item>
  </va-timeline>
  ```
  
  Should compile without errors
* **What is the current behavior?**
![изображение](https://user-images.githubusercontent.com/23530004/109040601-c2e81280-76d6-11eb-864e-d8fb66aa4681.png)

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
This is becouse all demo has as `v-for`ed `va-timeline-item` as `$slots.default()` is equal to slot with type `Symbol(Fragment)`. If we will use raw slots without `v-for` all `va-timeline-item`s they will be childs of `$slots.default()`. 

* **Other information** 

We must check if `$slot.default()` is RawSlot or vue `Symbol(Fragment)`

**Comment by asvae** [comment]
@m0ksem can you disable this component right now?

It's not a priority to include it in current release.
