### ISSUE TITLE
Set va-icon class.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#538]
https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/vuestic-components/va-icon/IconMixin.ts
```js
const getClass = (iconConfig: any, font: string) => {
  let iconClass = ''
  if (isMaterialFont(font)) {
    iconClass = 'material-icons'
  } else if (isMaterialOutlinedFont(font)) {
    iconClass = 'material-icons-outlined'
  } else if (isFontAwesome4Font(font)) {
    iconClass = `fa fa-${iconConfig.code}`
  } else if (isFontAwesome5Font(font)) {
    iconClass = `${font} fa-${iconConfig.code} fa-fw`
  } else if (isIonicFont(font)) {
    iconClass = `icon ion-md-${iconConfig.code}`
  } else if (isIonicOutlineFont(font)) {
    iconClass = `icon ion-ios-${iconConfig.code}-outline`
  } else if (isWeLoveIconsFont(font)) {
    iconClass = `${font}-${iconConfig.code}`
  }

  return iconClass
}
````
The class is now empty.

I want to use icon in my config from scss file 
![изображение](https://user-images.githubusercontent.com/23530004/109494954-4323c480-7a97-11eb-8333-9ba2bcc57d15.png)
My icon class:
```scss
.vuestic-iconset-dashboard::before {
  content: '\0043';
}
```

but there is no option to set `iconClass`

I propose to use `iconConfig.code` as iconClass if it was not found or add `iconClass` property to config.
___

It would also be nice to make a mechanism so that any icons can be supported.

**Comment by asvae** [comment]
I'll provide architecture to make it doable.
