### ISSUE TITLE
Dispose of vuestic icons

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#540]
![image](https://user-images.githubusercontent.com/5394573/109636072-32895200-7b5c-11eb-87be-170199df46c7.png)

We have several icons that don't really make much sense given we use material design icons by default.

Check where these are being used (probably in vuestic-admin or docs) and move them there.

**Comment by m0ksem** [comment]
Fixed in https://github.com/epicmaxco/vuestic-ui/commit/8daf9680646ea0387e3fa9a0c19439dd21c48d78  https://github.com/epicmaxco/vuestic-ui/commit/89e182e335d08031cc843be903c2a6440a82cda4
