### ISSUE TITLE
Add icon config to documentation

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#563]
We want user to be able to connect different icon solution to their project.

Also see `src\services\icon-config\presets\fonts.ts` - it already contains presets. We do not want to expose these for users. Instead they should add them manually.

Icon item docs example:

### Font Awesome 4

```js
{
  name: /fa4-(.*)/,
  iconClass: code => `fa fa-${code}`,
}
```

**Comment by m0ksem** [comment]
Need advanced docs about icons config with regex examples.
