### ISSUE TITLE
It is impossible to build the project 

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#587]
* **What is the current behavior?**
![изображение](https://user-images.githubusercontent.com/23530004/113447446-8eb4ef80-9402-11eb-9769-4b22b910decc.png)

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
`yarn build` inside /packages/ui

----
This problem apear after adding workspaces.

Webpack use wrong types. There two of them: `n_m/webpack/types.d.ts` `n_m/@types/webpack`

**Comment by untael** [comment]
Solved with nohoist docs/old-docs by moving it into vue-cli-docs
