### ISSUE TITLE
va-file-upload area bug

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#61]
upload area more than upload button
example: 
![ezgif com-crop](https://user-images.githubusercontent.com/13301570/66193639-af7c7780-e69b-11e9-9063-c60f50a9f513.gif)

**Comment by asvae** [comment]
In most cases that's the desired behavior.

Please reopen if you disagree.

**Comment by Kreezag** [comment]
I can use drop-area like a button or dropzone
If I will use drop-area like a button, I expect that only clicking on the button itself will cause  behavior browser window
