### ISSUE TITLE
Weird VaButton icon implementation

### ISSUE THREAD

**Issue by untael** [epicmaxco/vuestic-ui#610]
If we want to set button as icon without any text we got that implementation:
![image](https://user-images.githubusercontent.com/11652328/114788835-d7699280-9d8a-11eb-9df8-a62904a9468a.png)
it looks weird, we should use simplier construction like
![image](https://user-images.githubusercontent.com/11652328/114790186-f9641480-9d8c-11eb-8f5a-55b70cd00b75.png)

**Comment by m0ksem** [comment]
I propose to use slots as API to pass icons to button.

We can declare default margin between button children

```css
.va-button__content {
  & > * {
     margin-right: 1rem;
     &:last-child {
        margin-right: 0;
     }
  }
}
```

In that case we can use

```vue
<va-button color="black"> Clear <va-icon name="clear" color="gray"/> </va-button>
```

Without `icon` prop user can define smth like that:
```vue
<va-button> Hello <va-icon name="hello-hand"/> Click me! </va-button>
```

For rounded buttons with icon. We can use prop "fab" or smth like that.

```vue
<va-button fab> <va-icon name="phone-call" color="blue"/> </va-button>
```
to get
![image](https://user-images.githubusercontent.com/23530004/114872496-13d8d500-9e03-11eb-87eb-fdc0ab6b69e5.png)

and without fab:
 ```vue
<va-button> <va-icon name="phone-call" color="blue"/> </va-button>
```
![image](https://user-images.githubusercontent.com/23530004/114872759-4a165480-9e03-11eb-94ef-6c57c7d648f6.png)
