### ISSUE TITLE
Redesign inputs and select

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#618]
![image](https://user-images.githubusercontent.com/5394573/114862327-0ddcf700-9df7-11eb-880e-21d1c3426b06.png)

**Comment by xx13** [comment]
[select inputs](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=12%3A137)
[dropdown select previews](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=123%3A483), ebmedded search and scroll view will be added
[inputs](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=125%3A7)
