### ISSUE TITLE
Redesign alerts

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#621]
![image](https://user-images.githubusercontent.com/5394573/114863585-94460880-9df8-11eb-80b4-9c8656c53cc8.png)
Current implementation https://vuestic.dev/en/ui-elements/alert

We played a bit with alert colors

Should look more vibrant, mb like above. See https://vuetifyjs.com/en/components/alerts/#prominent

**Comment by xx13** [comment]
https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=13%3A91

**Comment by untael** [comment]
Done [here](https://github.com/epicmaxco/vuestic-ui/commit/f97f540941a38c566cd7c9e195c865a48af9ad0b)
