### ISSUE TITLE
Revisit modals

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#624]
- [x] Paddings

![image](https://user-images.githubusercontent.com/5394573/114864546-ca37bc80-9df9-11eb-8279-e33ab6203f21.png)

- [x] Add text

![image](https://user-images.githubusercontent.com/5394573/114864579-d7ed4200-9df9-11eb-81dc-e12fdd1fadef.png)

- [x] Fullscreen modal is broken

![image](https://user-images.githubusercontent.com/5394573/114864666-f0f5f300-9df9-11eb-8bec-507af6f1cf27.png)

- [x] Modal should cover sidebar and header

![image](https://user-images.githubusercontent.com/5394573/114864739-04a15980-9dfa-11eb-9e83-d3f5c2897845.png)

- [ ] Check other places on page.

**Comment by m0ksem** [comment]
- [ ] No padding 

![image](https://user-images.githubusercontent.com/23530004/115631662-eadaa780-a30e-11eb-991e-3a519865c134.png)

![image](https://user-images.githubusercontent.com/23530004/115631684-f6c66980-a30e-11eb-9d69-e44bb5c66263.png)
