### ISSUE TITLE
Backtop doesn't have icon

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#625]
![image](https://user-images.githubusercontent.com/5394573/114865773-6910e880-9dfb-11eb-9a7a-6854649b09a5.png)

**Comment by m0ksem** [comment]
![image](https://user-images.githubusercontent.com/23530004/115083280-ca29e080-9f0f-11eb-8d1e-43dc1a4e1d36.png)

Blacktop is hiding behind the sidebar if the position set to the left.
