### ISSUE TITLE
No all.props.modelValue text

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#634]
API Table uses all.props.modelValue by default which does not exists
http://localhost:8080/en/ui-elements/sidebar#api

![image](https://user-images.githubusercontent.com/23530004/115217278-032fa400-a10e-11eb-82b4-2f4f0cd71d04.png)

**Comment by mxmvshnvsk** [comment]
It's dublicate of #885

**Comment by sergey-kravcov** [comment]
@mxmvshnvsk , I almost added all the missing text

**Comment by mxmvshnvsk** [comment]
@sergey-kravcov, ok. Please, notificate me, when you done it, because I want to implement it in russian locale. I started do it too with assigned issue #885.

**Comment by mxmvshnvsk** [comment]
Thx u.
