### ISSUE TITLE
Radio-button and input type radio does not look good

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#64]
Checkbox dot is crooked.
Need fix paddings
<img width="184" alt="Vue App 2019-10-04 12-14-34" src="https://user-images.githubusercontent.com/13301570/66196190-c7a2c580-e6a0-11e9-8766-d3eb8a1c169d.png">

**Comment by asvae** [comment]
Reimplementation is planned for radio button. We'll likely fix as a part.
