### ISSUE TITLE
Translations don't seem to work on vuestic.dev

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#645]
Not saying we should immediately have everything tranalsted, but UI shouldn't break that hard.

![image](https://user-images.githubusercontent.com/5394573/115717412-d33d0680-a382-11eb-874f-a593dbf52525.png)

One more thing:

![image](https://user-images.githubusercontent.com/5394573/115717860-42b2f600-a383-11eb-8a87-898839d4de5a.png)

**Comment by m0ksem** [comment]
Currently, we removed any translations, except English. 

Probably I have fixed that issue in https://github.com/epicmaxco/vuestic-ui/issues/643.

But also there is a problem with vue-lang-router.

According to docs https://github.com/adbrosaci/vue-lang-router we should simply use: 

```vue
<language-switcher v-slot="{ links }" tag="ul" active-class="my-custom-class">
  <li :class="link.activeClass" v-for="link in links" :key="link.langIndex">
    <a :href="link.url">{{ link.langIndex }}</a>
  </li>
</language-switcher>
```
But It's not working.

Also, hack with hash does not work with vue3 🤔.
