### ISSUE TITLE
Command to check for missing translations

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#647]
We need a command to check if some translation strings are not being used.

Note that translation strings are always used without variables. I.e. `offsets.sizes.xl` will never be used as `offsets.sizes.${size}`. If not - that's a mistake.

Command should just display a list of unused strings separated by line break. Should not attempt removing these strings.

**Comment by m0ksem** [comment]
I think we can close it since we use `vue18n-unused`.

**Comment by asvae** [comment]
Irrelevant because #3425
