### ISSUE TITLE
ability to sync docs translations

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#648]
Couple of problems we want to solve:

- [ ] Translations should be ordered alphabetically. On all nesting levels. Probably we want sorting for `en` to trigger on before commit.
- [ ] We need a way to sync other languages translations with `en` translation. Sync should also trigger sort.

**Comment by m0ksem** [comment]
Translations must be spliited away, so there is no need in ordering. By default, we have fallback to en lang, for separated translation this issue is not relevant
