### ISSUE TITLE
Move documentation to nuxt when it's ready for vue3

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#650]
We implemented nuxt docs before (see 87de7304be35def5cd60e96c5711dfa6ff75fa7b - `/packages/vue-cli-docs/old/nuxt-docs` ), but had to switch to vue-cli because it wasn't ready.

Ideally we still want to use nuxt for seo/speed reasons. It's also not that hard to implement.

- [ ] Implement documentation on nuxt. Don't leave vue-cli docs.
- [ ] Ensure things work: CI, navigation etc.
- [ ] Ensure there is no bugs (also check the leftovers in #1577)

See also https://github.com/epicmaxco/vuestic-ui/issues/1642

Nuxt docs were worked on, but removed in [this PR](https://github.com/epicmaxco/vuestic-ui/pull/2103), you can use these changes when you work on implementation.

The idea is that we want to only have one docs project in repo to avoid confusion.

We can also check https://github.com/epicmaxco/vuestic-ui/pull/1142 in context of this PR

**Comment by m0ksem** [comment]
We probably need to wait on nuxt release or move to pnpm from yarn.
