### ISSUE TITLE
On my tablet docs app is getting cut

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#653]
As you can see - page does not display fully (and I can't scroll anymore).

Managed to reproduce this only on my tablet (Lenovo P11 pro). 

While this could be a problem with that device, other web sites are not being cut, so likely problem with implementation.

![image](https://user-images.githubusercontent.com/5394573/115749921-43a65080-a3a0-11eb-906c-c90405f2f823.png)

**Comment by m0ksem** [comment]
![image](https://user-images.githubusercontent.com/23530004/116540560-fde30e00-a8f2-11eb-8152-607c27f084b5.png)

Remove unnecessary margin-top.
