### ISSUE TITLE
Some components still use SCSS variables.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#655]
We need to completely remove SCSS variables from components and CSS helpers (like typography, grid, etc.) too.

**Comment by asvae** [comment]
Would argue with "completely". Some styling abstractions can't be represented by css variables.

I.e. grids use lists and loops. Good luck achieving this with css variables.

**Comment by m0ksem** [comment]
> 
> 
> Would argue with "completely". Some styling abstractions can't be represented by css variables.
> 
> I.e. grids use lists and loops. Good luck achieving this with css variables.

I agree. But we can use CSS variables for grid padding etc.

Basically, I was talking about variables in mixins or components. For example, `va-button` mixin still use SCSS variables instead of CSS variables.
