### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#66]
## Gist
* We need to get interaction and scalability right. Singular features (like rotation, opacity etc) can wait.
* We want to support the following icon handling approaches: ligature font-icons, class font-icons, svg icons (component icons).

## High level plan
- [x] Implement icon service ([Example](https://vuetifyjs.com/en/customization/icons#using-custom-icons))
- [x] Implement icon component

## Icon service
- [x] We want to rely on context system. So, basically, we'll have global config, optional context-component in-between, then props. Context and props should function in a similar way as per usual.

## Icon component

**What is iconset**
Iconset is `Record<string, IconConfig>`. IconConfig is an object, that can be used to define an icon fully without any additional props.

**Why this config is important?**
* Allows us to define icon alias in service config, and the thing with icons is that in many cases in app you want to use the same icon. 
* Having config will allow us to fully support icon sets of any type.
* Makes icons testable and easier to reason about.

### Props
- [x] `tag: String` - default: 'i' - specifies a custom tag to be used
- [x] `size` -  use `sizeMixin`, also see [size docs](https://github.com/epicmaxco/vuestic-ui/blob/develop/docs/conventions.md#props).
- [x] `name: String` - name (alias) of icon. Not contextable
- [x] `iconSet: String` - name of icon set to be used to derive icon config from icon name (alias). Icon set itself should be defined in the context (only exception is material icons).
- [ ] 'config: IconConfig' - icon config should represent all relevant props. It's priority should be below props and above context. If both config and context are provided - component should disregard context while handling config, there should be no merge between the two. This prop is purely for testing, as we want to ensure config and props are working predictably in all cases.
- [x] `color` - use `ColorThemePlugin`
- [x] add other relevant props so that icon system supports all 3 types of icons.

### Slots
- [ ] `default` - this slot is fairly magical. We might leave it for later iterations. See vuetify example for things we might want from it.

### Events
- [x] All events are to be propagated. 

## Docs
- [ ] We need docs.

## Other
- [ ] Icon component should function without context, while using material design iconset.

## Low priority tasks
- [ ] Cover each icon solution with iconset. We might want these to be tree-shaked. It would make sense to split all other iconsets (apart from material icons) into different issue. Ensure iconsets are properly tested.
- [ ] We might want to support some of font-awesome features. Like animation, rotation and grouping.

# Refs
* [Vuetify](https://vuetifyjs.com/en/components/icons)
* [Quasar](https://quasar.dev/vue-components/icon)
* [Ant Design](https://vue.ant.design/components/icon/)
* [iView](http://iview.talkingdata.com/#/components/icon-en)
* [Element UI](https://element.eleme.io/#/en-US/component/icon)

**Comment by asvae** [comment]
> expected: svg template - the component used for the root node. This will override the `tag` property.

@AlexanderBoriskin can you describe what that means?

**Comment by Kreezag** [comment]
The implementation of the property `component` is being postponed. In the discussion, it turned out that she had a low priority

**Comment by asvae** [comment]
Component is already of decent quality, but not fully implemented.

Currently it works ok on low level, but we don't have user friendly high level config.

**Comment by m0ksem** [comment]
An old issue.
