### ISSUE TITLE
Button restyle

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#660]
- [x] Button: gradient - false by default
- [x] Use new design.

**Comment by untael** [comment]
partially implemented [here](https://github.com/epicmaxco/vuestic-ui/commit/8d058a8244aee8d6dde1f97acf61e3ce63ed990e)

@xx13 will check and we'll make the final corrections.

**Comment by untael** [comment]
Done [here](https://github.com/epicmaxco/vuestic-ui/commit/46b27ab38b446bbd45c0a2f3125a411b72a3fca7)
