### ISSUE TITLE
Tweak color selects for docs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#662]
- [ ] Remove dark and gray
- [x] Remove "Corporate" theme.

They should be assignable only via css variables.

![image](https://user-images.githubusercontent.com/5394573/116239010-cf3a2b80-a76a-11eb-8566-2889ce90cfc8.png)

**Comment by m0ksem** [comment]
Do this after https://github.com/epicmaxco/vuestic-ui/issues/618. Currently, dark and gray used in inputs.

**Comment by m0ksem** [comment]
We just hid this dropdown

**Comment by m0ksem** [comment]
Not relevant anymore.
