### ISSUE TITLE
Markup table component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-ui#67]
# Docs

- [ ] Do after [docs boilerplate](#17) is done.

# Props
- [ ] `separator: String` - default: 'horizontal', accepted values: 'horizontal', 'vertical', 'cell', 'none'  - use a separator/border between rows, columns or all cells
- [ ] `flat: Boolean` - applies no default shadow view.
- [ ] `square: Boolean` - removes border-radius from table

# Refs
* [Quasar](https://quasar.dev/vue-components/markup-table)

**Comment by asvae** [comment]
Covered by [content](https://github.com/epicmaxco/vuestic-ui/issues/70).

**Comment by asvae** [comment]
I'm not seeing this being of particular use given we already have `content` class that does the same.
Props are also not that useful (if at all).
