### ISSUE TITLE
Deploy docs CI task fails sometimes.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#676]
https://app.circleci.com/pipelines/github/epicmaxco/vuestic-ui/648/workflows/f733a3ef-429c-44cc-8307-8ae8d565af0d/jobs/1379

`deploy-docs` CI task fails sometimes.

**Comment by asvae** [comment]
Reopen if still fails

**Comment by asvae** [comment]
Added another fix on centry side. Please reopen if still repeats.
