### ISSUE TITLE
Checkbox box-shadow

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#692]
![image](https://user-images.githubusercontent.com/23530004/117039593-9fae9480-ad11-11eb-91fc-e540db029765.png)

Unexpected box-shadow after alt + tab in Firefox.

**Comment by m0ksem** [comment]
I realized that this shadow is part of the focus style.

Also, a checkbox is changing its own value only if you click "enter". If you want to press space - the value will be changed then changed back again.

**Comment by zvenigorodskaia** [comment]
@m0ksem not reproduced =(
