### ISSUE TITLE
Remove <template> and <script> from show code view

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#698]
These don't play much of a role

![image](https://user-images.githubusercontent.com/5394573/117402744-a145ab80-af0f-11eb-9940-ced6502113aa.png)

**Comment by asvae** [comment]
Not really sure we want that.

**Comment by m0ksem** [comment]
![image](https://user-images.githubusercontent.com/23530004/162320008-0f4035bb-bca2-4243-bc0c-361975f110f3.png)

Also, we don't need a root div anymore in vue3.

**Comment by m0ksem** [comment]
I personally prefer copying script and template tags. It is easier to reproduce demo in project. Let's make this task about removing root div for code examples (comment above).

**Comment by asvae** [comment]
Agreed 👍. Moved your suggestion to another issue.
