### ISSUE TITLE
Checkbox visual update

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#715]
- [x] Change padding between a checkbox and a label from `4px` to `8px`
- [x] `Mixed` option was added with a minus icon
- [x] Default font style should match `regular medium` style which is `15/20`
- [x] #2092
- [x] Set border-radius to 0 (0.125 rem according to the figma)
- [x] Change `display` to `inline-block`
- [x] Remove horizontal paddings

The reset items are for 1.5.0.

[Visual references](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=188%3A0)

**Comment by m0ksem** [comment]
We also need to remove extra paddings
![image](https://user-images.githubusercontent.com/23530004/178080482-c0ef6d8c-ae8e-44c2-8c7e-e029ca5a932f.png)

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2346
