### ISSUE TITLE
Radio button default behavior update

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#716]
By default a checked radio button shouldn't have a semi-transparent background.

**Comment by m0ksem** [comment]
@xx13, can you provide a screenshot, or correct reference, please.

**Comment by xx13** [comment]
@m0ksem no semi-transparent. the first image is correct, the second one shows the wrong style

 ![65A36C5A-E53F-49D9-865A-F442ED0182D7](https://user-images.githubusercontent.com/22664941/118098448-36dfb000-b3d4-11eb-9ef7-e06249c70503.jpeg)
![7F7B98BD-B96B-4D36-ABD6-78A9E19BBDAB](https://user-images.githubusercontent.com/22664941/118098434-33e4bf80-b3d4-11eb-9bf7-2e84dd23f7bc.jpeg)

**Comment by m0ksem** [comment]
It's a focus state after a click. I think we could make correct keyboard navigation and focus state for the radio button as I did for selects.

For now, after clicking on the radio button it's became focused. Sounds correct, but not convenient.

**Comment by asvae** [comment]
@m0ksem can we mark this as ready for implementation? I'm not clear on status of this issue, nor its description.

**Comment by m0ksem** [comment]
@aluarius, let's remove this semi bg and add focus outline (yellow colors same as we have on button)

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2347
