### ISSUE TITLE
On this screen size - sidebar should be handled the same as for mobile (should stay closed).

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#725]
- [ ] Investigate other docs and figure out the correct solution. Pretty sure there is a standard one.

![image](https://user-images.githubusercontent.com/5394573/117686388-7da88c80-b1bf-11eb-81f0-eee2adcdb652.png)

**Comment by m0ksem** [comment]
Looks like it fixed.

![image](https://user-images.githubusercontent.com/23530004/147552905-396849e1-ead3-4591-8bf9-bbf7253c8ec7.png)
