### ISSUE TITLE
Add scss files to dist

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#727]
We have resources, such as va-scroll, etc. As a user, I would like to use them in my project as part of the framework.

**Comment by asvae** [comment]
@m0ksem still relevant or will you say it makes more sense to move to css variables + css overrides?

**Comment by m0ksem** [comment]
@asvae, this issue could be close.

I have added SCSS file to final dist.

For example, `va-scroll` mixin can be found here `dist/styles/resources/index.scss`.

But, there are no docs about this feature. Also, I think there are a lot of outdated mixins.
