### ISSUE TITLE
Actions slot on card component

### ISSUE THREAD

**Issue by ssemenkoff** [epicmaxco/vuestic-ui#729]
It might be really helpful to have a dedicated slot for buttons at the bottom of the card component like vuetify does:
<img width="564" alt="Screenshot 2021-05-12 at 13 40 38" src="https://user-images.githubusercontent.com/10769790/117962746-3ee21600-b328-11eb-86db-459eef80d6e5.png">

**Comment by alygee** [comment]
Done in this pr https://github.com/epicmaxco/vuestic-ui/pull/987
