### ISSUE TITLE
Test select

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#736]
- [x] There are multiple issues which we want to test and fix.

-----------------
Unsorted:

- [x] Searchable - сёрчбар должен оставаться на месте и не скроллится
- [x] Клики на селект листают элементы вниз
- [x] Нажатие ↑ закрывает селект
- [ ] Неправильный вид курсора

But should be more

**Comment by Derranion** [comment]
Most of these issues should be fixed by https://github.com/epicmaxco/vuestic-ui/pull/861,

Though we close select by Esc instead of ↑

Also not sure about wrong cursor, feel free to ping me if it was not solved yet.

I've linked it pull request.
