### ISSUE TITLE
On mobile version margin is too big

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#739]
- [ ] We want to show more content as mobile device doesn't have that much space.

Probably this should be applied on layout.

![image](https://user-images.githubusercontent.com/5394573/118128246-50e4b700-b403-11eb-9185-0506e4cb939a.png)

**Comment by m0ksem** [comment]
Also, need to align version text and language dropdown.

**Comment by NikhilSharma03** [comment]
Can you please assign this issue to me?

**Comment by asvae** [comment]
@NikhilSharma03 done :).

**Comment by NikhilSharma03** [comment]
Ok Thankyou .
