### ISSUE TITLE
Select internal logic is off

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#740]
Currently `hoveredOption` is used to represent both mouse hover and keyboard navigation. This is not ideal.

- [ ] add `selectedOption` to track keyboard navigation.
- [ ] use `hoveredOption` solely for mouse hover (if it's not possible to do with css even),

**Comment by Derranion** [comment]
Probably worth doing after this pull request https://github.com/epicmaxco/vuestic-ui/pull/861
