### ISSUE TITLE
Popover component is disabled

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#769]
We have popover, but it's not enabled (docs are hidden)

- [ ] We want to investigate if this component is needed (it probably is, as VaDropdown is too low level).
- [ ] If it is - fix docs to reflect this component reason to exist + fix translations.

![image](https://user-images.githubusercontent.com/5394573/118374306-06f6ff00-b5c4-11eb-8b0c-b9cbc3313c67.png)

**Comment by kushich** [comment]
Fixed
