### ISSUE TITLE
va-input has incorrect styles

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#77]
va-input has an incorrect left border-radius.

Need to add a case to demo input with the left icon (MB need fix it)
example:
<img width="580" alt="va-input-incorrect-design" src="https://user-images.githubusercontent.com/13301570/66377988-45294700-e9bb-11e9-9158-e5978b44f110.png">

**Comment by asvae** [comment]
That seems to be fixed already.
