### ISSUE TITLE
The gutter should change on a smaller screen

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#774]
The gutter should change on a smaller screen with some breakpoints. For now, gutter--lg is too big on mobile.

![image](https://user-images.githubusercontent.com/23530004/118496155-8a336480-b72c-11eb-9799-8a9023a3f30d.png)

**Comment by asvae** [comment]
Probably not much do discuss here. Seems pretty useful to me out of the box.

But we can talk whether to support sidebar or make this configurable.

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2189
