### ISSUE TITLE
SITE: Customize everything section

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#777]
- Tabs should be centered. Currently they are aligned to the left.
- Currently tab labels don't make much sense ('large modern', 'style', and 'multiple themes'). Originally the idea was to show the same components but in different styles so that you can copy & paste it into your project.

<img width="1156" alt="centered-tabs" src="https://user-images.githubusercontent.com/22664941/118506076-4ab94800-b72d-11eb-8199-52138fdfea67.png">

**Comment by asvae** [comment]
There are multiple problems with tabs.

If you remove 'grow' prop from tab - it becomes properly centered o.o.
But then part of the text is getting cut off.

![image](https://user-images.githubusercontent.com/5394573/118522071-56fccf80-b744-11eb-8189-c6b94dcd74d2.png)

**Comment by xx13** [comment]
@asvae it shouldn't be the case for 2 tabs, right?

**Comment by xx13** [comment]
- Center the tabs
- Rename to `Form elements` , `Table`, `Misc`
