### ISSUE TITLE
Top nav github margin

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#778]
- Margin is missing between the language select and the github button.

<img width="238" alt="top-nav-github-margin" src="https://user-images.githubusercontent.com/22664941/118506936-0b3f2b80-b72e-11eb-9508-44e7c543daa1.png">

**Comment by asvae** [comment]
![image](https://user-images.githubusercontent.com/5394573/118522908-43059d80-b745-11eb-9b72-65262ede34a9.png)
