### ISSUE TITLE
SITE: Top menu (not required)

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#779]
- Let's have menu items as links, not ghost buttons
- On hover let's change the colour to `dark`
- No bg should appear

<img width="1293" alt="top-menu-update" src="https://user-images.githubusercontent.com/22664941/118507251-5a855c00-b72e-11eb-9e5a-a62d92e7f24a.png">

**Comment by asvae** [comment]
Could be just switched to plain preset.

**Comment by xx13** [comment]
- On hover change the colour to `dark`, as the active element should also
- Language label, like `English` should have the same font style as other menu items
- Fix the layout when selecting a language
<img width="576" alt="image" src="https://user-images.githubusercontent.com/22664941/192266253-77a400ea-4a6e-477a-997d-526f400d6fa4.png">
