### ISSUE TITLE
Rating > Custom icons

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-ui#781]
- Custom icons in Rating have weird behaviour.

<img width="1131" alt="rating-custom-icons" src="https://user-images.githubusercontent.com/22664941/118508320-5f96db00-b72f-11eb-949c-9fbdcad9e309.png">

**Comment by asvae** [comment]
Not bad o.o.

**Comment by asvae** [comment]
![image](https://user-images.githubusercontent.com/5394573/118520260-99bda800-b742-11eb-965d-8e81ae8f67a9.png)
