### ISSUE TITLE
Sidebar has empty space on mobile

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#782]
![image](https://user-images.githubusercontent.com/5394573/118513020-f8cbee80-b73b-11eb-850a-022bbdcb7dd8.png)

**Comment by sergey-kravcov** [comment]
It looks like this bug has already been fixed. I tested it on my phone and using browser tools.
<img width="376" alt="first_image" src="https://user-images.githubusercontent.com/20461547/123109397-e1230c80-d443-11eb-8834-b09d7dda082d.png">
