### ISSUE TITLE
Visual bugs - Customize Everything

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#783]
![image](https://user-images.githubusercontent.com/5394573/118521129-64658a00-b743-11eb-8bfb-6507f3fe1eac.png)

- [ ] Alers should look like alert (move to separate line etc)
- [ ] toggle should not overlap with button group.

**Comment by sergey-kravcov** [comment]
It looks like this bug has already been fixed.
<img width="853" alt="Снимок экрана 2021-06-25 в 13 09 54" src="https://user-images.githubusercontent.com/20461547/123409816-4f3c1080-d5b7-11eb-81f1-c3ab29f9cba7.png">
