### ISSUE TITLE
2 font declarations

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#784]
We have font declared 2 times.

![image](https://user-images.githubusercontent.com/5394573/118528542-25d3cd80-b74b-11eb-9fcb-3253bc5fe381.png)

But if you remove second declaration - here's how it looks (fonts are off).

![image](https://user-images.githubusercontent.com/5394573/118528590-3126f900-b74b-11eb-8f62-fefd24ab4349.png)

This line was removed:
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400">
```

**Comment by sergey-kravcov** [comment]
here declarations two different fonts: 'Source Sans Pro' and 'Source Code Pro'. Both fonts use in projects.
Exemple:
'Source Code Pro' use for code of  api docs table.
'Source Sans Pro' use in th tags of api docs table.
