### ISSUE TITLE
Tables not vertically scrollable on mobile

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#787]
![image](https://user-images.githubusercontent.com/5394573/118569274-42d7c300-b782-11eb-960f-e6ff1f91a6be.png)

**Comment by smellyshovel** [comment]
Guess you meant "not **horizontally* scrollable"?

**Comment by smellyshovel** [comment]
So basically in such cases in general it's usually completely enough just to add `overflow: auto` css property to the parent element. So I don't think we should fix it on the `.va-table` class. If the problem is specifically docs-related, we should change the docs' markup instead.

**Comment by smellyshovel** [comment]
The PR above allows for any non-fitting content to use horizontal scroll (when needed only).
