### ISSUE TITLE
va-tabs incorrectly show part of their content

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#79]
tabs hide part of the content or add scroll
Examples:
Hide content:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13301570/66497331-fff13c00-eac4-11e9-9791-5ac083c2579e.gif)
Add scroll:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/13301570/66497263-e5b75e00-eac4-11e9-88fc-7adaf8d19a56.gif)

**Comment by asvae** [comment]
Tabs are being remade
