### ISSUE TITLE
Weird element on app-bar

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#795]
![image](https://user-images.githubusercontent.com/5394573/118648706-5ff4ac00-b7eb-11eb-9013-e3ab9d6c640b.png)

**Comment by ritik-vashist** [comment]
I want to work on this issue.

**Comment by asvae** [comment]
@ritik-vashist sure, would be great :).
Assigned you.

**Comment by m0ksem** [comment]
@ritik-vashist, tip for you: the issue caused because there is no icon aliases "battery" and "ellipses".
