### ISSUE TITLE
Miss `:active` state

### ISSUE THREAD

**Issue by cawa-93** [epicmaxco/vuestic-ui#809]
* **What is the expected behavior?**
`<va-button>` must have visual changes for [`:active`](https://developer.mozilla.org/docs/Web/CSS/:active) state. 
* **What is the current behavior?**
`<va-button>` have only `:hover`, `:focus` and `:disabled` states. 

It also reelvant for other interactive elements, like Pagination, Sidebar item, Clickable list etc

**Comment by aluarius** [comment]
Closed via https://github.com/epicmaxco/vuestic-ui/pull/1945
