### ISSUE TITLE
va-chart does not consider "options" prop

### ISSUE THREAD

**Issue by luuuke** [epicmaxco/vuestic-ui#81]
I understood the options prop of va-chart to be additional Chart.js configuration, which will be passed to the Chart.js instance. But for me it seems like it isn't even considered, as it never gets merged with the default config. 

My options object looks like this: `{
                    legend: {
                        display: false,
                        labels: {
                            padding: 0
                        }
                    }
                }`, such that the legend should be hidden, but it isn't.

**Comment by asvae** [comment]
Thanks for pointing that out.
