### ISSUE TITLE
Version changelog

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#820]
We want a way to quickly compile a release.

Should include:
* Top level log (might be written by hand).
* All fixed issues (with)

**Comment by asvae** [comment]
Try to use native github release log.

**Comment by Derranion** [comment]
> Try to use native github release log.

This refers to this button in the `Release` tab:

![autoGeneratedReleaseNotes](https://user-images.githubusercontent.com/7745899/169260243-5c197fef-4076-4a5b-879e-0bb6dfa5859d.jpg)

**Comment by asvae** [comment]
Closing for now. Github releases are good enough. Also #1988.
