### ISSUE TITLE
[BUG] Endless Builds with Vite and Complaining about Eval

### ISSUE THREAD

**Issue by Dan6erbond** [epicmaxco/vuestic-ui#821]
* **What is the expected behavior?**

As I'm using Vite, I expect a fast build with Vue 3 and Typescript.

* **What is the current behavior?**

When I run the build, it seems to be running endlessly, and my terminal is spammed with the following output: 

```bash
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
```

Right before that, I get this output from Vite, which looks proper, but no `dist/` folder is generated and instead the above occurs:

```node
yarn run v1.22.5
warning package.json: No license field
$ vue-tsc --noEmit && vite build
vite v2.3.4 building for production...
transforming (18) node_modules\vuestic-ui\dist\vuestic-ui.cssUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
```

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**

1. Scaffold a Vue 3 project with Typescript and Vite using `npx init @vitejs/app` or `yarn create @vitejs/app`.
2. Add Vuestic UI.
3. Run build.

[Demo repository](https://github.com/Dan6erbond/qv-checker) (see `vuestic-ui/` directory).

* **Other information** 

Testing a very similar setup with Equal Vue yields no results, which seems to point to this being an issue with Vuestic UI's compatability with Rollup and Vite, and not necessarily any of the other tools involved in the setup.

**Comment by Dan6erbond** [comment]
@m0ksem I wanted to provide some extra information so I attached a custom logger to Rollup, and printed the location of the warning alongside the actual message. My guess is that you guys don't even use `eval()`, but Webpack's build is outputting it given what I've found:

```node
{
  column: 248121,
  file: 'C:/<anonymous>/qv-checker/vite/node_modules/vuestic-ui/dist/vuestic-ui.js',
  line: 2
} Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
{
  column: 259719,
  file: 'C:/<anonymous>/qv-checker/vite/node_modules/vuestic-ui/dist/vuestic-ui.js',
  line: 2
} Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
{
  column: 261007,
  file: 'C:/<anonymous>/qv-checker/vite/node_modules/vuestic-ui/dist/vuestic-ui.js',
  line: 2
} Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
```

Those are just some examples. Let me know if you need more context!

**Comment by odanado** [comment]
I got same issue.
ref: https://github.com/odan-sandbox/vite-vuestic-sandbox
