### ISSUE TITLE
When i use chrome, the display area of Input's label  is too small when the language of label is chinese.

### ISSUE THREAD

**Issue by xdbytes** [epicmaxco/vuestic-ui#837]
* **What is the expected behavior?**
Complete display of Chinese characters in Input's label
* **What is the current behavior?**
When I use chrome, Chinese characters cannot be displayed completely; Firefox and Safari is Ok.
* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
1. chrome
![FireShot Capture 003 - Vuestic Admin - localhost](https://user-images.githubusercontent.com/77269893/120917811-d9453780-c6e3-11eb-8a43-e8f2945a781f.png)
2. Firefox is Ok
![WechatIMG68](https://user-images.githubusercontent.com/77269893/120917925-5bcdf700-c6e4-11eb-875a-904ad03aa5c3.jpeg)

* **Other information**

**Comment by smellyshovel** [comment]
Can you attach these characters here as a plain text?

**Comment by xdbytes** [comment]
电子邮箱
密码

**Comment by xdbytes** [comment]
@smellyshovel 
电子邮箱
密码

**Comment by smellyshovel** [comment]
@xdbytes I can't reproduce the issue using Chrome 90.0.4430.212 with noto-fonts-cjk:

![Screenshot_20210606_130103](https://user-images.githubusercontent.com/9782236/120920407-41d1eb80-c6c7-11eb-90dc-d22c301ffc44.png)

**Comment by smellyshovel** [comment]
https://vuestic.dev/en/styles/css-variables#overriding

Try to override `.va-input__label`'s `overflow` css property with visible. I believe this may help.

**Comment by xdbytes** [comment]
@smellyshovel Thank you very much! May you be happy every day!

**Comment by xdbytes** [comment]
works!
