### ISSUE TITLE
Move vue to peer dependencies

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#838]
We want to add vue as peer dependency. That prevents conflicts when different version is being used in app.

See implementations from other frameworks:
* [vuetify](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/package.json)
* [element-plus](https://github.com/element-plus/element-plus/blob/dev/package.json)

**Comment by sergey-kravcov** [comment]
The issue was resolved in pull request #852.
