### ISSUE TITLE
Slot data bind for VaDropdown

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#849]
```vue
<va-dropdown>
  <template #anchor="{ isContentShown, anchorWidth }">
    <va-button :icon="isContentShown ? 'opened': 'closed'" />
  </template>
</va-dropdown>
```

There is can be more slot data. 

----

Pass some data in slots, so we can check if content shown in template, for example if component is stateful

**Comment by m0ksem** [comment]
The same thing can be applied to VaAccordion.

**Comment by sergey-kravcov** [comment]
Could you please add more information about the issue.

**Comment by asvae** [comment]
Removed discussion label as I didn't see the point. Readd if I'm wrong :).
