### ISSUE TITLE
Use much complex solution for Modals, Dropdowns, Popovers 

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#850]
Use much complex solution for Modals, Dropdowns, Popovers to prevent bugs with overflow: hidden.

We need to make a fixed dropdown, that can be shown outside overflow-hidden card and divs.

There is some example: https://codepen.io/agop/pen/itbew

**Comment by m0ksem** [comment]
We have `boundaryBody` prop, that fixed dropdowns and popovers - need to check it. Maybe we should make it true by default?

Modals should be fixed here https://github.com/epicmaxco/vuestic-ui/issues/817

**Comment by DieselTripleX** [comment]
Can you assign me, please?)
