### ISSUE TITLE
Button Multiline Text Issue

### ISSUE THREAD

**Issue by alexanderrudnik** [epicmaxco/vuestic-ui#862]
* **What is the expected behavior?**
Badges should support multiline text with no UI issues.

* **What is the current behavior?**
Badges don't support multiline text.

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
![image](https://user-images.githubusercontent.com/9514327/122378502-ae25d800-cf6e-11eb-9fbb-0abb1e98b208.png)

* **Other information**

**Comment by sergey-kravcov** [comment]
Assign me, please

**Comment by m0ksem** [comment]
This is not a badge, it's a button. 

A badge doesn't support multi-line at all:
![image](https://user-images.githubusercontent.com/23530004/122895678-0551f100-d351-11eb-8ac0-e2e43a9ef591.png)
Looks like we need to remove some white-space CSS rule.

This issue should fix badge and button issues as well.

**Comment by sergey-kravcov** [comment]
A badge support multi-line if you specify `multi-line` prop.
Something like that:
`<va-badge
                multi-line
                text="Lorem Ipsum is simply dummy text of the printing and typesetting industry. />`

**Comment by asvae** [comment]
@sergey-kravcov please check references if multi line badges is a thing.

**Comment by sergey-kravcov** [comment]
This is how the button looks now with multi line text.
![Снимок экрана 2021-06-29 в 13 34 57](https://user-images.githubusercontent.com/20461547/123784161-d2bf6f80-d8df-11eb-83f8-b1f9351b9afa.png)

**Comment by sergey-kravcov** [comment]
@asvae This is how badges look with multi line prop.
![Снимок экрана 2021-06-29 в 13 38 03](https://user-images.githubusercontent.com/20461547/123784420-1619de00-d8e0-11eb-8889-0d021a690b04.png)
![Снимок экрана 2021-06-29 в 13 37 45](https://user-images.githubusercontent.com/20461547/123784438-1b772880-d8e0-11eb-990b-862ad0914c85.png)

**Comment by asvae** [comment]
ok, so what multiline prop is even doing for badge given multilime text is shown properly on badge?

**Comment by sergey-kravcov** [comment]
@asvae multi line prop needs for auto separate a long text. Examples in the demo were incorrect, I changed it.
<img width="408" alt="Снимок экрана 2021-06-30 в 10 26 57" src="https://user-images.githubusercontent.com/20461547/123920982-35bc0f80-d98f-11eb-950a-416fbfb99338.png">
