### ISSUE TITLE
Dev Tools freeze on the docs page.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#869]
Lags on Firefox and Chrome.

**Comment by DieselTripleX** [comment]
I would like to figure it out!)

**Comment by m0ksem** [comment]
Check how it's working with a new project created with vue cli. Does it freeze?

**Comment by asvae** [comment]
A lot of css variable rewrites might be an issue actually >.>.

**Comment by m0ksem** [comment]
Looks like fixed.
