### ISSUE TITLE
Docs. Languages table bind with languages.ts

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#877]
![image](https://user-images.githubusercontent.com/23530004/123077793-0c493400-d423-11eb-8ea9-efaa94877667.png)

We can bind this table with languages.ts file 
![image](https://user-images.githubusercontent.com/23530004/123077852-1a975000-d423-11eb-9a83-d76d0725f01a.png)

Example
```ts
export const languages = [
  {
    code: 'en',
    name: 'English',
    status: '*',
  },
  {
    code: 'es',
    name: 'Español',
    status: 'partial',
  },
  {
  	code: 'ru',
  	name: 'Russian',
  	status: 'work in progress',
  }
  // GENERATOR_ADD - language
]

```

**Comment by mxmvshnvsk** [comment]
Assign me, please. I'll implement this feature after ru locale.
