### ISSUE TITLE
Close Dropdown on window blur

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#890]
Reason: 
When a user clicks on the iframe no window click event does not emit. Instead, there is a focus on iframe and blur for a window. Also, if we can we need to check if the new focus target is an iframe. Because blur emits when you can click on the Windows Task bar. 

It's not important but will be nice to have.

**Comment by DieselTripleX** [comment]
I could do it :)

**Comment by asvae** [comment]
Sounds reasonable!
