### ISSUE TITLE
Docs in dev mode is showing warnings about reactive components.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#898]
TODO: provide a screenshot.

For now, you can open any docs page and see a lot of warnings.

**Comment by sergey-kravcov** [comment]
<img width="1202" alt="Снимок экрана 2021-06-30 в 15 49 36" src="https://user-images.githubusercontent.com/20461547/123963307-002d1b80-d9bb-11eb-82ac-0a14ff50f251.png">

**Comment by sergey-kravcov** [comment]
<img width="1202" alt="Снимок экрана 2021-06-30 в 15 49 36" src="https://user-images.githubusercontent.com/20461547/123963307-002d1b80-d9bb-11eb-82ac-0a14ff50f251.png">
