### ISSUE TITLE
Make FormComponentMixin composable 

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#910]
I want to have the option to use FormComponentMixin as a composable function e.g. useForm or useFormComponent.

File structure (cFormComponent.ts):
```ts
export const FormComponentProps = { ... }
export const useFormComponent(...) => ... 
```

You can also decompose the `useFocus` hook and use it useFormComponent.

```ts
import { useFocus } from '../../composables/useFocus'

export const FormComponentProps = { ... }

export const useFormComponent(...) => { ...useFocus, ... } 
```

See a small example here: packages/ui/src/components/vuestic-mixins/StatefulMixin/cStatefulMixin.ts

**Comment by asvae** [comment]
We want to get rid of all mixins eventually.

**Comment by Derranion** [comment]
I added `useFormComponent` by this pull request:
[Composition API Select, refactor & new composable files](https://github.com/epicmaxco/vuestic-ui/pull/935)
