### ISSUE TITLE
Translation for language and translation status

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#911]
Would be great to have translation for these fields as well (language and translation status):

![addTranslation](https://user-images.githubusercontent.com/7745899/124124551-3b921d80-da81-11eb-9f28-2c4211499243.jpg)

**Comment by mxmvshnvsk** [comment]
Yes, it's good idea, assign me please.

**Comment by mxmvshnvsk** [comment]
Yes, that's a good idea. Assign me please.

**Comment by mxmvshnvsk** [comment]
@Derranion Yes, that's a good idea. Assign me please.
