### ISSUE TITLE
<va-sizebar-item> got  Cannot read property 'href' of undefined

### ISSUE THREAD

**Issue by lanshuofeng** [epicmaxco/vuestic-ui#915]
![image](https://user-images.githubusercontent.com/15353624/124223234-e9f79a80-db35-11eb-9288-72f76c1096de.png)

codesandbox: https://codesandbox.io/s/71xsr?file=/src/App.vue
doc link: https://vuestic.dev/en/ui-elements/sidebar-item
![image](https://user-images.githubusercontent.com/15353624/124223364-27f4be80-db36-11eb-8553-cbb3e0dedc68.png)

**Comment by DieselTripleX** [comment]
I will fix this)

**Comment by m0ksem** [comment]
We don't have `vue-router` installed on code sandbox. Need to use router-link only if vue-router exists.

You can use RouterLinkMixin: packages/ui/src/components/vuestic-mixins/RouterLinkMixin/RouterLinkMixin.ts

You can modify this Mixin if needed.
