### ISSUE TITLE
The error appears after clicking the Copy code button

### ISSUE THREAD

**Issue by sergey-kravcov** [epicmaxco/vuestic-ui#919]
* **What is the expected behavior?**
The code should be copied.

* **What is the current behavior?**
The error appears after clicking the Copy code button and code do not copy.

![Снимок экрана 2021-07-05 в 11 03 04](https://user-images.githubusercontent.com/20461547/124438930-78139100-dd81-11eb-9f7f-d9c14573c043.png)

Tested in google chrome

**Comment by DieselTripleX** [comment]
Assign me, please) @m0ksem
