### ISSUE TITLE
No components names in devtools

### ISSUE THREAD

**Issue by mxmvshnvsk** [epicmaxco/vuestic-ui#923]
Now all components in devtools are anonymous:

![image](https://user-images.githubusercontent.com/25287077/124487370-ae700100-ddbf-11eb-97cd-f153840dd4a3.png)

One solution is to add `name` option in components, for example `~/page/contribution/translation.vue`:

```javascript
@Options({
  name: 'DocsTranslation',
  components: {
    DocsContent,
  },
})
```
After we'll have named component in devtools components tree:

![image](https://user-images.githubusercontent.com/25287077/124487792-2ccca300-ddc0-11eb-9e0a-324d9f761dbc.png)

**Comment by DieselTripleX** [comment]
I can fix this) Assign me, please! @m0ksem

**Comment by mxmvshnvsk** [comment]
@DieselTripleX, hi, did you implement this?
