### ISSUE TITLE
Invalid va-slider behavior

### ISSUE THREAD

**Issue by sergey-kravcov** [epicmaxco/vuestic-ui#927]
* **What is the expected behavior?**
- [x]  Change order of icons in vertical slider.
- [x]  Fix append and prepend slots.
- [x]  The slot label should have a color as `label-color`.
- [x]  Hide tags of label section when invert-label is true and label is not present.

* **What is the current behavior?**
- Wrong order of icons in vertical slider.
![Снимок экрана 2021-07-06 в 14 26 22](https://user-images.githubusercontent.com/20461547/124592474-301a6a00-de66-11eb-9c79-cad328099047.png)
- Missing content of append and prepend slots when displayed vertically.
![Снимок экрана 2021-07-06 в 12 23 30](https://user-images.githubusercontent.com/20461547/124590187-8639de00-de63-11eb-91fa-d1aa8e1107ea.png)
- The slot label misses a label color.
![Снимок экрана 2021-07-06 в 12 22 39](https://user-images.githubusercontent.com/20461547/124590525-e761b180-de63-11eb-9021-4ac9de5c2ff4.png)
- Some tags is visible if invert-label is true but label is not present.
![Снимок экрана 2021-07-06 в 11 46 35](https://user-images.githubusercontent.com/20461547/124590576-f5173700-de63-11eb-8424-0f0dec439757.png)

**Comment by asvae** [comment]
Nice catch! Thanks.
