### ISSUE TITLE
Need to remove specific defaults component props

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-ui#93]
For support task (#80) 
If some parts of component were designed with specific defaults in mind - these have to go away. I.e. small as Boolean assumes default side is "medium", but that could be not the case if config was applied. So it makes more sense to have size: 'small' | 'medium' | 'large' and no Boolean props.
For example:
```<va-button small>button</va-button>```
need change to 
```<va-button size="small">button</va-button>```

**Comment by asvae** [comment]
Small is already implemented properly everywhere.
Booleans, such as outline or flat are fine the way they are currently.
