### ISSUE TITLE
Standardize emits, slot binds etc.

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#940]
I think we need to allow users to use as many binds for the slot, as possible.

```vue
<slot name="save-button" v-bind="{ onClick, fileName, fileSize }">
	{{ fileName }} <va-button @click="onClick" icon="save" />
</slot>

//then

<template #save-button="{ onClick, fileSize }">
	{{ fileSize }} <va-chip @click="onClick" />
</template>
```

For emits, for now there is two ways:

```vue
emit('update:text', text, format)
emit('update:text', { text, format })

// or

emit('update:text', text)
emit('update:text', { text })
```

Which one should I use? It would be nice to have some style guide about it.

Maybe there are some others things that we should discuss.

- [ ] Improve docs to support slots documentation.
- [ ] standardise slots (we want to have consistent logic across all of them).
- [ ] Add docs for existing slots.

**Comment by asvae** [comment]
@m0ksem do we have a lot of cases where emits send multiple values?

I would actually prefer to split these into separate emits if that makes sense.

**Comment by m0ksem** [comment]
> @m0ksem do we have a lot of cases where emits send multiple values?
> 
> I would actually prefer to split these into separate emits if that makes sense.

Few of them. I think arguments is enough.

Before thinking about standardising slot binds we need to add them to docs.

**Comment by m0ksem** [comment]
Not relevant.
