### ISSUE TITLE
Make CSS Variables docs more readable

### ISSUE THREAD

**Issue by sergey-kravcov** [epicmaxco/vuestic-ui#949]
* **What is the expected behavior?**
Words in plain text should not be syntactically highlighted.

* **What is the current behavior?**
The words operators change a color.
![Снимок экрана 2021-07-12 в 15 26 30](https://user-images.githubusercontent.com/20461547/125288035-5d638e00-e326-11eb-93fe-bd5a55e23153.png)

**Comment by m0ksem** [comment]
Maybe you want here to pass specific language to the Vue Prism component (If there such option, of course). 

But, I think you need to write this code block in a human familiar style. E.g. using lists, paragraphs, code blocks.
