### ISSUE TITLE
Styles from _typography.scss, included twice in Docs

### ISSUE THREAD

**Issue by sergey-kravcov** [epicmaxco/vuestic-ui#950]
![Снимок экрана 2021-07-12 в 15 37 50](https://user-images.githubusercontent.com/20461547/125289190-a0723100-e327-11eb-8996-1f158747bacd.png)

**Comment by asvae** [comment]
@zvenigorodskaia can you check if that's relevant still? If not - you can close an issue.

**Comment by zvenigorodskaia** [comment]
> @zvenigorodskaia can you check if that's relevant still? If not - you can close an issue.

@asvae yes, still relevant 
![image](https://user-images.githubusercontent.com/35342240/136333965-fdec1689-6cca-4d62-8daf-d56f556cc685.png)
