### ISSUE TITLE
Add the ability to localize examples in the docs

### ISSUE THREAD

**Issue by sergey-kravcov** [epicmaxco/vuestic-ui#951]
It would be nice to be able to pass text to examples, it would help with localization.
![Снимок экрана 2021-07-12 в 15 46 26](https://user-images.githubusercontent.com/20461547/125290014-884ee180-e328-11eb-971a-6087f095bdc5.png)
It should be taken into account that the examples should remain adequate and the text localization code should not be very conspicuous in these examples.

**Comment by asvae** [comment]
Here's a good case for this feature: https://vuestic.dev/ru/ui-elements/alert

**Comment by mxmvshnvsk** [comment]
@asvae If no one is involved in this task, I can implement this.
