### ISSUE TITLE
Do you need help to provide a Chinese translation document?

### ISSUE THREAD

**Issue by Zenquan** [epicmaxco/vuestic-ui#963]
First of all, I think this is a pretty good Vue3 component library, but the catch is that there is no Chinese document, which cannot make it more convenient for Chinese developers and users.

**Comment by asvae** [comment]
Absolutely!
If you can provide some feedback on how easy are things to translate - that would also be great.
We added a couple of tools to simplify language sync recently.

**Comment by Zenquan** [comment]
So please tell me what should I do now?

**Comment by m0ksem** [comment]
@Zenquan, Hi there. 

We have a small guide [here](https://vuestic.dev/en/contribution/translation).

You need to make fork & PR.

You can start using a generate command:
```bash
yarn workspace docs generate:translation
```
Then you will be able to edit the JSON translation file.

[Here is an example of a Russian translation PR](https://github.com/epicmaxco/vuestic-ui/pull/895)

----

Feel free to ask any questions in [Discord](https://discord.com/invite/u7fQdqQt8c)

**Comment by Zenquan** [comment]
> @Zenquan, Hi there.
> 
> We have a small guide [here](https://vuestic.dev/en/contribution/translation).
> 
> You need to make fork & PR.
> 
> You can start using a generate command:
> 
> ```shell
> yarn workspace docs generate:translation
> ```
> 
> Then you will be able to edit the JSON translation file.
> 
> [Here is an example of a Russian translation PR](https://github.com/epicmaxco/vuestic-ui/pull/895)
> 
> Feel free to ask any questions in [Discord](https://discord.com/invite/u7fQdqQt8c)

Ok, good guide！

**Comment by smartapant** [comment]
Hi @Zenquan, are you still willing to help with Chinese docs? :)

**Comment by Zenquan** [comment]
Yes, but I need some time, and the English language documentation is not perfect.

**Comment by smellyshovel** [comment]
@Zenquan https://github.com/epicmaxco/vuestic-ui/pull/1004

I've made some updates to the english translation, now waiting for it to be reviewed. Please, notify me if something still soesn't look right.

**Comment by Zenquan** [comment]
ok, that's great!

**Comment by asvae** [comment]
@Zenquan would you be willing to take a go at translation? :)
English translation should be good enough. We also got decent tooling.

**Comment by asvae** [comment]
https://localizejs.com/ - could work.
Not sure how applicable is google translate and other autotranslate approaches.

**Comment by Zenquan** [comment]
> @Zenquan would you be willing to take a go at translation? :)
> English translation should be good enough. We also got decent tooling.


Sorry, due to busy work, I cannot provide help for the Chinese translation document, good luck!
