### ISSUE TITLE
Some components are missing properties in the docs.

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#969]
There are some properties missing in a props lists of our docs for some of the components.

I think it could miss properties imported by Mixins.

Looks like an automatic generation of properties description works only for explicitly declared props inside a component.

For example I've found it in VaForm:

![vaFormNoPropsDescription](https://user-images.githubusercontent.com/7745899/126652859-bb476bf0-f25f-406f-8b72-fc87a0444860.jpg)

There are only two properties in the description while in reality VaForm imports FormComponentMixin that has 10 more props.

Most likely there are more components with this issue.

**Comment by asvae** [comment]
Nice catch!

**Comment by Derranion** [comment]
Update:
Our current solution is to move to Composition API - this way we will have `Composable functions` instead of `Mixins` which will resolve this issue.

But right now less than half of the Components are using it that's why issue is still relevant.

**Comment by m0ksem** [comment]
Looks like it can be closed.
