### ISSUE TITLE
Add Composition API usage description to docs.

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#985]
Right now we are moving our components to Composition API.

That's why it could be wise to add description of how we want it to be implemented and some key tips for contributors to make it easier and more consistent.

**Comment by Derranion** [comment]
We can just shortly describe it and add a link to already existing great Composition API example:
[VaSelect](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/va-select/VaSelect.vue) component that uses most of new syntax features and a lot of composable functions inside as well.

**Comment by asvae** [comment]
TL;DR: Use it for good, don't use it for bad! 😼
